### ISSUE TITLE
Schematica printer doesn't work without using /sit command

### ISSUE THREAD

**Issue by StKillReal** [GrimAnticheat/Grim#1001]
### Describe the false positive and how to replicate it

I want to allow players use Printer to build arts, but permissions doesn't help. Now they can build using printer only when they sit using Gsit plugin. Grim ac works better then all anticheats I used before, but only with grim I can't just disable some checks for players.
1) Try to build something using SchematicaPriner
![image](https://user-images.githubusercontent.com/60330193/226828736-d777e0b1-ec18-4563-a1fe-1b8337113f61.png)
![2023-03-22_10 16 42](https://user-images.githubusercontent.com/60330193/226828833-bb5d3ab5-4163-4b42-a488-26dd720b47c0.png)

### Grim version

2.3.39

### Server version

![image](https://user-images.githubusercontent.com/60330193/226828943-dac68566-23b8-4eb7-a2cc-7a101a30d2d1.png)

### Plugins

![image](https://user-images.githubusercontent.com/60330193/226829002-c4e8c0ed-56b8-4154-859a-68c56e5911bc.png)

**Comment by MWHunter** [comment]
schematica printer is a cheat though.

**Comment by MWHunter** [comment]
remove Post from punishments.yml to disable the check

**Comment by MWHunter** [comment]
Closing due to schematica printer being a cheat
