### ISSUE TITLE
1.20 datapack on 1.19.4 + console spam

### ISSUE THREAD

**Issue by StKillReal** [GrimAnticheat/Grim#1004]
### Describe the false positive and how to replicate it

Is there a way to add new blocks from 1.20, or give me simething like instruction how to do it manual? Now grim adon't know about them and if u try to stand on bamboo block or any block added on 1.20 DP, anticheat will drop u on the ground.
![image](https://user-images.githubusercontent.com/60330193/227720123-ad518775-c42a-42da-89ae-068cac05ee05.png)
(Sometimes it says Simulations)
1) Install last build of grim on the 1.19.4
2) Enable 1.20 datapack in the world
3) Try to stand on new blocks without any grim permissions

Issue number 2 - console spam:
![image](https://user-images.githubusercontent.com/60330193/227721621-b1c074de-ebc3-46c4-a4f7-6e4323cfdee4.png)

### Grim version

The last build
![image](https://user-images.githubusercontent.com/60330193/227720300-450028df-a4d2-4982-b8d3-46f77850cef8.png)

### Server version

![image](https://user-images.githubusercontent.com/60330193/227720072-51e39dcd-d33d-49d9-9091-d5a76a062e1b.png)

### Plugins

![image](https://user-images.githubusercontent.com/60330193/227720091-0542884c-5406-4c55-af16-f18b90b681b0.png)

**Comment by MachineBreaker** [comment]
Send the entire stacktrace in a pastebin

**Comment by StKillReal** [comment]
> Send the entire stacktrace in a pastebin

do u mean this?
https://pastebin.com/iZPrR17x

**Comment by MWHunter** [comment]
Grim doesn't support this experimental datapack.

**Comment by StKillReal** [comment]
> Grim doesn't support this experimental datapack.

Okay, but on 1.19.3 grim didn't spam into console even with 1.20 datapack

**Comment by MWHunter** [comment]
root cause is probably that EntityTypes in packetevents doesn't have all the 1.20 experimental entities.

**Comment by StKillReal** [comment]
> root cause is probably that EntityTypes in packetevents doesn't have all the 1.20 experimental entities.

Oh, damn, you're righ, it's because of sniffers
