### ISSUE TITLE
Swift Sneak falses simulation

### ISSUE THREAD

**Issue by Weigurde** [GrimAnticheat/Grim#1005]
### Describe the false positive and how to replicate it

1. Wear leggings enchanted with Swift Sneak
2. Sneak
3. Move
4. Cry
https://paste.grim.ac/097U2

### Grim version

2.3.35

### Server version

git-Purpur-1924, 1.19.3

### Plugins

Plugins (43): AdvancedAntiVPN, BetterCommandSpy, BetterRTP, ClearLag, CMILib, ConsoleSpamFix, CoreProtect, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit, floodgate, Geyser-Spigot, GeyserSkinManager, GriefPrevention, GrimAC, GSit, LiteBans, LuckPerms, mcMMO, NetheriteSMPCore, OpenInv, PlaceholderAPI, PlayerVaults, PlugManX, PremiumVanish, ProtocolLib, PvPManager, SilkSpawners_v2, spark, TerraformGenerator, TrollBoss, UltimateAntiBot, UltimateTimber, Vault, VeinMiner, ViaBackwards, ViaRewind, ViaVersion, ViaVersionStatus, WorldGuard, XCatch

**Comment by MWHunter** [comment]
Please include real reproduction steps.
