### ISSUE TITLE
How can i add punishments

### ISSUE THREAD

**Issue by Dryixz** [GrimAnticheat/Grim#1007]
I added punishments in the punishments config but it errors, always says expected a block end and Grim auto shuts off and wont activate, how do i do it properly (sorry for being an idiot if i did something wrong i followed the exact thing in the wiki)

**Comment by c0dingnoobi** [comment]
provide the stacktrace and your config next time 
feel free to pm me throu discord (noobi#3073) so we can avoid filling issues with support
