### ISSUE TITLE
GrimAC WARN spam a few minutes after startup

### ISSUE THREAD

**Issue by blek-id** [GrimAnticheat/Grim#1017]
### Stack trace

https://paste.gg/p/anonymous/3f7565900e654b0384e9e602d17c8169

### How to replicate it if known

1. Start server up

### Grim version

grimac-2.3.39.jar

### Server version

Paper 474 
1.19.4

### Plugins

Bukkit Plugins:
BattlePass, BungeeGuard, Chunky, Citizens, CMI, CMILib, CoreProtect, CrateReloaded, DeluxeMenus, DeluxeTags
Denizen, Depenizen, DisableMending, DisableShulkerFarm, Elevator, EntityDetection, ezAuctions, FarmControl, FastAsyncWorldEdit, GCore
GrimAC, Guilds, HeadDatabase, HolographicDisplays, IllegalStack, JPremium, LuckPerms, LWC, MMOCore, MMOItems
MobsToEggs, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, MythicLib, NoBreaks, *NoDrops, Oraxen, OverleveledEnchanter, PinataParty
PlaceholderAPI, PlayerParticles, PlayerVaults, ProtocolLib, QuickShop-Hikari, Residence, Shopkeepers, spark, TradeSystem, Vault
ViaBackwards, ViaVersion, VotingPlugin, WorldGuard, WorldGuardExtraFlags

**Comment by MWHunter** [comment]
packetevents issue, will be fixed in next release
