### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1018]
### Stack trace

https://mclo.gs/n1AJHfK

### How to replicate it if known

Step 1. Put the plugin in plugin folder
Step 2. Start

### Grim version

GrimAC v2.3.39

### Server version

[08:47:24 INFO]: Checking version, please wait...
[08:47:24 INFO]: This server is running Paper version git-Paper-481 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: cbcdfd0)
You are 3 version(s) behind
Download the new version at: https://papermc.io/downloads

### Plugins

Only GrimAC since it is a test server and wanted to try the plugin for the first time

**Comment by MWHunter** [comment]
caused by acf

**Comment by MachineBreaker** [comment]
Not a error but warning

**Comment by ghost** [comment]
Technically both 😅

**Comment by MWHunter** [comment]
https://github.com/GrimAnticheat/Grim/commit/c1188f476591f60366fed65583f51b5c8df9faaf
