### ISSUE TITLE
Lava swim false positive

### ISSUE THREAD

**Issue by shaqupl** [GrimAnticheat/Grim#1019]
### Describe the false positive and how to replicate it

1. Jump into lava pool
2. Try to swim up
3. You cant
4. False AntiKnockBack check
![2023-04-02_13 05 48](https://user-images.githubusercontent.com/68109218/229349434-ae3d767f-ed5c-4bc0-aabe-21bfe62bc469.png)

### Grim version

grimac-2.3.38

### Server version

git-Purpur-1926 (MC: 1.19.3)*

### Plugins

  - AltDetector, AntiLavaCast, antiRedstoneClock, Aqua, AuxProtect, *BCommons, BossShopPro, CasinoCrash, ChatManager, ChestSort
  Chunky, Citizens, CommandWhitelist, ConsoleSpamFix, CoreProtect, CoreProtectTNT, CustomCrafting, CustomNetheriteSmithing, DeathCoordinates, DecentHolograms
  DeluxeMenus, DriveBackupV2, *EasyWhitelist, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, EvenMoreFish, EvoDragons, ExcellentCrates
ExcellentShop, ExtraContexts, EZColors, FastAsyncWorldEdit, freeplugins-fishing, GrimAC, GSit, HeadDB, *HideAchievements, HomeGUI
 ikVote, InfiniteJump, InventoryRollbackPlus, *IPLock, LibsDisguises, LimitCreative, LiteBans, LuckPerms, *McListpl, MessageOverHead
 MeteoritesPro, MinecraftListaPlugin, MoneyHunters, Multiverse-Core, NexEngine, NoChatReports, *OldEnchant, OpenAFK, OpenInv, PermissionPortals
 PlaceholderAPI, Plan, PlayerKits, PlayerPoints, PlayerStats, *Playtimes, PlugManX, *PortalTrapRescue, ProtectionStones, ProtocolLib
 PvPManager, *q1zZ-DiscordRewards, Quests, RHLeafDecay, SafeNET, SharpSK, Shopkeepers, ShulkerPacks, SimpleRTP, SimpleScore
 SkBee, skDragon, Skellett, SkinsRestorer, Skript, *SkStuff, *skUtilities, *SM-Votifier, SmoothTimber, spark
 Spectator, *SpectatorRotator, StreakRewards, Stress, TAB, *TaskScheduler, TimedRewards, TimeIsMoney, TimeVote, TradeSystem
  UltraCosmetics, *UltraParkour, Vault, VeinMiner, ViaBackwards, ViaVersion, ViewDistanceTweaks, VillagerTradeLimiter, WitherSpawn, WolfyUtilities
 WorldGuard, WorldGuardExtraFlags, *ZCtiktok

**Comment by MWHunter** [comment]
https://github.com/GrimAnticheat/Grim/issues/678
