### ISSUE TITLE
False triggers

### ISSUE THREAD

**Issue by AfraidDaniPlay** [GrimAnticheat/Grim#1024]
Ive had over 50+ false triggers for reach without using any mdos other than optifine and with 30-40 ping constantly
possible issue with reach check

**Comment by c0dingnoobi** [comment]
provide steps to reproduce 
useful would be a video which shows how u false it 
if we dont know what u did to "trigger" those falses we cant figure out the reason
it would also be useful to know what server and client version has been used

**Comment by MWHunter** [comment]
How do you know the player isn't cheating

**Comment by MWHunter** [comment]
oh, do you use forge?

**Comment by AfraidDaniPlay** [comment]
I use forge optifine, I have no clue how to reproduce it and videos dont really help either, i have one where it looks like i hit 3.7 blocks and i believe this one triggered the anticheat too
I believe the client couldnt affect it but i use multimc

![Screenshot_20230327-120234_Discord](https://user-images.githubusercontent.com/86973908/230579414-ec3453dd-0304-463b-a73e-5ff4740fe00b.jpg)
LOUD NOISES
https://medal.tv/games/minecraft/clips/1153VsMPczmsyS/znnBIUvxgpEf?invite=cr-MSxpenMsMTQ1MDIzNzc1LA

**Comment by SamB440** [comment]
What version are you on?

Forge 1.18.2+ is a cheat and has extended reach with right click and left click. See https://github.com/MinecraftForge/MinecraftForge/issues/9309

Latest versions of Forge 1.19.4 supposedly fix the issue, but apparently there are still issues with sweeping and large entity hitboxes. Haven't tested the fix fully yet.

**Comment by AfraidDaniPlay** [comment]
I use 1.19.2

**Comment by MWHunter** [comment]
Forge 1.19.2 has accidentally included cheats within the game.  This is not a false with grim but rather the Forge devs fucked up their reach code so that the player has reach.

There's nothing I can do to about this.  You just have to update your forge client.
