### ISSUE TITLE
[Feature request]more hacking=more punishment

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1025]
### Feature description

like this it works first time you get banned for 1day using a plugin then when you keep hacking you can set like then it bans you for 1week them 1mon ETC i dont know does this aleredy exsits tell me if it and tell me how

**Comment by MachineBreaker** [comment]
Use the Grim API, save existing player punishments in a file or database, if a entry exists, then implement a longer ban.

This feature is not gonna be added at all to Grim, there's a reason why API exists

**Comment by ghost** [comment]
bruh

**Comment by MachineBreaker** [comment]
Can you close this if resolved?

**Comment by MWHunter** [comment]
this isn't the job of an anticheat, use a plugin like LibertyBans that would support this
