### ISSUE TITLE
WARNING error when a player logs on to the server.

### ISSUE THREAD

**Issue by sm1leclock** [GrimAnticheat/Grim#1027]
### Stack trace

https://pastebin.com/JjSVqwYP

### How to replicate it if known

Error when entering the player

### Grim version

Grim Anticheat 2.3.40 hotfix 1

### Server version

This server is running GuardSpigot 1.16.5 version git-Airplane-"1bfa658" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1 SNAPSHOT)

### Plugins

Citizens, CMI, CMILib, DeluxeMenus, EnchantableBlocks, ExecutableItems, GrimAC, LuckPerms, MineableSpawners, MoneyFromMobs, NBTAPI, PlaceholderAPI, PlayerKits, PlayerPoints, ProtocolLib, SCore, UltimateClans, Vault, WokaScheduledTrader, WorldEdit, WorldGuard

**Comment by SamB440** [comment]
#911
