### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by molor** [GrimAnticheat/Grim#1028]
### Stack trace

https://paste.gg/p/anonymous/61b7dd7fcc204205bb5f4e5398faab7a

### How to replicate it if known

```
summon minecraft:item_display ~ ~1 ~ {item:{id:"golden_pickaxe",Count:1b}}
data merge entity @e[type=minecraft:item_display,sort=nearest,limit=1] {Rotation:[180.0f,0.0f]}
data merge entity @e[type=minecraft:item_display,sort=nearest,limit=1] {transformation:{scale:[2.0f,2.0f,2.0f]}}
```

### Grim version

See stack trace

### Server version

git-Paper-499 (MC: 1.19.4)

### Plugins

ProtocolLib, LuckPerms, Essentials, MobArena, GrimAC, WorldEdit, WorldGuard, Vault, OpenInv, dynmap, Chunky

**Comment by MWHunter** [comment]
make a packetevents issue, not a grim error
