### ISSUE TITLE
Add a way to disable Protocolib integration

### ISSUE THREAD

**Issue by sk8ba** [GrimAnticheat/Grim#1032]
### Feature description

If there would be a way to add Protocolib-integration : false/true option in grim that would make cool cuz im using protocolib 4.8.0 and I have bugs but i don't wanna to update protocolib cuz other plugin will break so if that would be possible i would be thankful.

-Waiting for response

**Comment by MWHunter** [comment]
this is technically impossible.

Grim doesn't use protocollib, it just breaks due to protocollib 4 doing stupid stuff to the netty pipeline
