### ISSUE TITLE
Globally linked geyser accounts are no longer exempt

### ISSUE THREAD

**Issue by SykoUSS** [GrimAnticheat/Grim#1035]
### Describe the bug and how to replicate it

Step 1. Globally link your bedrock and Java account with link.geysermc.org
Step 2. Join a server with your bedrock account
Step 3. You will be unable to move and be flagged by GrimAC

### Grim version

grimac-2.3.36

### Server version

This server is running Paper version git-Paper-448 (MC: 1.19.3)

### Plugins

"plugins": [
  "ViaVersion v4.6.0",
  "LuckPerms v5.4.65",
  "Vault v1.7.3-b131",
  "FastAsyncWorldEdit v2.5.3-SNAPSHOT-381;bfd919b",
  "WorldGuard v7.0.8-SNAPSHOT+2208-cb100bb",
  "ProtocolLib v5.0.0-SNAPSHOT-b608",
  "PlaceholderAPI v2.11.2",
  "mcMMO v2.1.217",
  "Citizens v2.0.30-SNAPSHOT (build 2972)",
  "CoreProtect v21.3",
  "WildStacker v2022.6-b418",
  "Multiverse-Core v4.3.1-b861",
  "LibsDisguises v10.0.32-SNAPSHOT",
  "floodgate v2.2.2-SNAPSHOT (b77-089b9a7)",
  "MythicMobs v5.2.1-fd1d0777",
  "Sentinel v2.6.5-SNAPSHOT (build 478)",
  "BlueMap v3.7",
  "DecentHolograms v2.8.0",
  "Lands v6.28.18",
  "Essentials v2.20.0-dev+44-43d84de",
  "SCore v3.9.48",
  "EssentialsChat v2.20.0-dev+44-43d84de",
  "DiscordSRV v1.27.0-SNAPSHOT",
  "WolfyUtilities v4.16.9.4",
  "LevelledMobs v3.9.4 b740",
  "UltimateTimber v2.3.5",
  "WorldGuardExtraFlags v4.2.1",
  "Votifier v2.7.3",
  "AdvancedRegionMarket v3.3.7",
  "ViaBackwards v4.6.0",
  "ModelEngine vR3.1.2",
  "InteractiveChat v4.2.5.7",
  "CustomCrafting v4.16.3.2",
  "BountyHunters v2.5",
  "BeautyQuests v0.20.1_BUILD348",
  "MobArena v0.107",
  "CrazyCrates v1.11.14.2",
  "AdvancedEnchantments v9.0.0b77",
  "zVoteParty v1.0.2.0",
  "WildLoaders v2022.7-b70",
  "WildChests v2022.7-b91",
  "UNBMB v1.0-SNAPSHOT",
  "UltraCosmetics v2.9.2-RELEASE",
  "TigerReports v5.1.4",
  "TAB-Bridge v2.0.11",
  "SpawnerMeta v18.5",
  "ServerSigns v4.8.0",
  "QuickShop v5.1.1.2",
  "pvparena v1.15.2",
  "PlayerAuctions v1.21.2",
  "MythicDungeons v1.1.1F",
  "Multiverse-Portals v4.2.1-b834",
  "Multiverse-Inventories v4.2.3-b523",
  "MoneyFromMobs v4.6",
  "MiniMOTD v2.0.8",
  "MCPets v3.0.2",
  "InteractiveChatDiscordSrvAddon v4.2.5.7",
  "GrimAC v2.3.36",
  "ExtraContexts v2.0-SNAPSHOT",
  "ExecutableItems v5.9.48",
  "EssentialsSpawn v2.20.0-dev+44-43d84de",
  "Duels v3.5.2",
  "DualWield v3.0",
  "dtlTraders v6.4.16",
  "CraftingStore v2.9.0",
  "CommandPanels v3.18.6.0",
  "BlueMapFloodgate v1.5.0",
  "BlueMap-Essentials v1.1.0",
  "BlueBorder v1.1.0",
  "BetterKeepInventory v1.4-BETA1",
  "BeautyQuestsAddon v1.6",
  "BattlePass v3.11.3",
  "AntiPopup v5.4",
  "ajLeaderboards v2.6.8",
  "AdminAnything v2.4.12",
  "DungeonParties v1.0-SNAPSHOT"

**Comment by MWHunter** [comment]
grim uses floodgate api: https://github.com/GrimAnticheat/Grim/blob/2.0/src/main/java/ac/grim/grimac/utils/floodgate/FloodgateUtil.java


Something is wrong with your config and you will have to be the one to debug it as the code is simply calling floodgate's api to detect a geyser player.
