### ISSUE TITLE
False negativetimer flag

### ISSUE THREAD

**Issue by craciu25yt** [GrimAnticheat/Grim#1036]
### Describe the false positive and how to replicate it

1. Just pvp or hit someone and eventually it will flag Negative Timer

### Grim version

 2.3.40 hotfix 1

### Server version

PufferFish 1.19.4 b778163

### Plugins

Grim, LuckPerms, ViaVersion and ViaBackwards

**Comment by MWHunter** [comment]
not enough info

**Comment by craciu25yt** [comment]
what other info do you need. Just ask for it before closing lol. And I just told that to get that false flag you need to hit someone and anything else. Idk what other info is required
