### ISSUE TITLE
Replacing chestplate with elytra via RMB on 1.19.4 falses Simulation

### ISSUE THREAD

**Issue by VidTu** [GrimAnticheat/Grim#1037]
### Describe the false positive and how to replicate it

1. Join the 1.19.4 server with 1.19.4 vanilla client.
2. Equip any chestplate through inventory.
3. Equip elytra with RMB. (New 1.19.4 feature)
4. Try to glide.
5. Simulation falses.

https://youtu.be/1E0sL7e6yMY
https://paste.grim.ac/A5FId

### Grim version

af14800

### Server version

```
Current: git-Purpur-1962 (MC: 1.19.4)*
* You are running the latest version
```

### Plugins

```
Bukkit Plugins: (2):
 - GrimAC, spark
```

**Comment by MWHunter** [comment]
was fixed at some point in the past
