### ISSUE TITLE
Two new exceptions

### ISSUE THREAD

**Issue by molor** [GrimAnticheat/Grim#1038]
### Stack trace

Not sure it's caused by Grim or again PacketEvents (developer of which probably forgot about GitHub :/)

https://paste.gg/p/anonymous/14a63976b8a54bca998039c48cf71991
https://paste.gg/p/anonymous/a0cfe0ad9fbe4198ad761844acc9369e

### Grim version

See stack traces

### Server version

git-Paper-499 (MC: 1.19.4)

### Plugins

ProtocolLib, LuckPerms, Essentials, MobArena, GrimAC, WorldEdit, WorldGuard, Vault, OpenInv, dynmap, Chunky

**Comment by MWHunter** [comment]
Your server is sending invalid packets.
