### ISSUE TITLE
1.19.3 Reach Magma Slime False Positive

### ISSUE THREAD

**Issue by adabugra** [GrimAnticheat/Grim#1039]
### Describe the false positive and how to replicate it

Step 1: Hit a magma or slime
and get flagged with Reach Missed Hitbox

### Grim version

2.3.40

### Server version

Pufferfish 1.19.3

### Plugins

Towny, Siegewar, mcMmo, Grim, FAWE, WorldGuard, CombatLogX, Itemsadder

**Comment by MWHunter** [comment]
is this the minimal reproduction?
