### ISSUE TITLE
NegativeTimer bypass

### ISSUE THREAD

**Issue by z7087** [GrimAnticheat/Grim#1051]
### Describe the bypass and how to replicate it

Step 1. Use a 1.12.2 hacked client, stop moving and sending move packets
Step 2. Wait a while and stop doing that, send a CPacketPlayer.Rotation packet(add 360 for yaw to bypass AimDuplicateLook) before next move packet
Step 3. Grim don't flag NegativeTimer for me

Simulation doesnt appear to flag players sending c05 over the air, BadPacketsE is too forgiving

### Grim version

2.3.40

### Server version

Paper 1.8.9

### Plugins

GrimAC 2.3.40, ViaBackwards 4.5.2, ViaVersion 4.5.2

**Comment by MWHunter** [comment]
I don't care.

**Comment by c0dingnoobi** [comment]
> Step 3. Grim don't flag NegativeTimer for me

negative timer mostly is a "misc" check, u dont rlly gain advantage by using it
considering the current state of grim this "bypass" isnt rlly worth looking at
