### ISSUE TITLE
A false positive of ice blocks

### ISSUE THREAD

**Issue by IllIIIlIllllII** [GrimAnticheat/Grim#1053]
### Describe the false positive and how to replicate it

(I am using a translator because I am not good at English. I'm sorry)

1. Place the ice block
1-1. Place slab on top of the ice block
2. Walk on the block

1.19.4
https://github.com/GrimAnticheat/Grim/assets/108587375/1f1a6255-6bd3-4d9c-8314-72ea7df2d936

1.20.1
https://github.com/GrimAnticheat/Grim/assets/108587375/59076b98-87e7-492b-a687-33a1545d6b27

(It's my personal feeling) it seems to be happening more setbacks in 1.19.4. (and slime block)

===
I wanted to upload the log, but I don't think it's possible because my laptop's internet is not connected. I'm sorry

### Grim version

2.3.42 (grim.ac Discord community version)

### Server version

Paper 1.19.4 550

### Plugins

Viaversion and GrimAC

**Comment by alec-jensen** [comment]
This is because grim does not account for [bug #1127](https://bugs.mojang.com/browse/MC-1127)
Probably a result of the new system for getting the block the player is standing on.

**Comment by MWHunter** [comment]
Yes this would have been introduced with the new 1.20 changes

**Comment by MWHunter** [comment]
fixed by https://github.com/GrimAnticheat/Grim/commit/fd69b9c2fb6663442077074a098f104206fdaaa8
