### ISSUE TITLE
Race condition involving velocity

### ISSUE THREAD

**Issue by ItsClairton** [GrimAnticheat/Grim#1055]
### Describe the false positive and how to replicate it

If you get knocked back and block on your foot disappears (or appears)
at the same time, you will get a simulation flag and the knockback will be cancelled.

This doesn't happen as often in paper 1.8.8.

But in spigots that perform knockback outside the tickloop (ImanitySpigot, PandaSpigot, or any other pvp focused spigot) it happens frequently.

Step 1: Download this testing plugin: https://cdn.discordapp.com/attachments/909679630611513364/1119342813256097792/proof-1.0-SNAPSHOT.jar
Step 2: Make a bridge, and run /proof

https://paste.grim.ac/YUeBq
https://streamable.com/9tb74t

You can see that the knockback works without the block disappearing by writing /proof a.

Proof code:

```java
        User user = PacketEvents.getAPI().getPlayerManager().getUser(player);

        WrapperPlayServerEntityVelocity velocity = new WrapperPlayServerEntityVelocity(user.getEntityId(),
                new Vector3d(1, 1, 1));

        Block block = player.getLocation().clone().add(0, -1, 0).getBlock();
        block.setType(Material.AIR);
        user.sendPacket(velocity);
```

### Grim version

2.3.43

### Server version

git-PaperSpigot-445 1.8.8

### Plugins

GrimAC, Proof

Sorry for bad English.

**Comment by MWHunter** [comment]
issue with point three detector eating knockbacks when checking for between tick velocity application from a changing world that results in a tick skip but the next tick has a different world state and therefore the player can't skip ticks which is what this code is trying to fix, on 1.9+ clients, and not a race condition.  root cause is always mojang being idiots :)

Likely duplicate #719 but this is a good minimal reproduction

**Comment by MWHunter** [comment]
if anyone does want to fix this, it would be making a method so. https://github.com/GrimAnticheat/Grim/blob/258c1adc24dad10820ea9d6cf383acce63ae3d39/src/main/java/ac/grim/grimac/predictionengine/PointThreeEstimator.java#L154 can poll velocity without eating it

**Comment by MachineBreaker** [comment]
> if anyone does want to fix this, it would be making a method so.
> 
> https://github.com/GrimAnticheat/Grim/blob/258c1adc24dad10820ea9d6cf383acce63ae3d39/src/main/java/ac/grim/grimac/predictionengine/PointThreeEstimator.java#L154
> 
> can poll velocity without eating it

what if i still want to eat my bread

**Comment by MWHunter** [comment]
no eating first or second bread

**Comment by MWHunter** [comment]
After three months of giving the fix and no one pull requesting a fix, this issue is likely fixed because someone made a bypass out of it so I finally decided to fix it.
