### ISSUE TITLE
0% Velocity

### ISSUE THREAD

**Issue by DasCanard** [GrimAnticheat/Grim#1056]
### Describe the bypass and how to replicate it

1. Use FDPClient
2. Set Velocity mode to Grim
3. done (see video)

https://github.com/GrimAnticheat/Grim/assets/17070204/3c65af94-c841-4416-8a66-2de160f6612e

### Grim version

258c1adc24dad10820ea9d6cf383acce63ae3d39

### Server version

Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)

### Plugins

GrimAC, ProtocolLib, ViaBackwards, ViaRewind, ViaVersion

**Comment by MWHunter** [comment]
is this just increasing your ping so you never receive knockback?

**Comment by DaddyAlmunther** [comment]
https://github.com/SkidderMC/FDPClient/blob/6499c82e7e85fec3ec228bfdb8771b13275f1339/src/main/java/net/ccbluex/liquidbounce/features/module/modules/combat/velocitys/other/GrimVelocity.kt

that is the client

**Comment by MWHunter** [comment]
oh, so it's holding onto the first of the breads for five ticks or so

**Comment by MWHunter** [comment]
tell me if https://github.com/GrimAnticheat/Grim/commit/1bed34d73c477861694ef5244aba8715944cd059 fixes it.  don't feel like launching a minecraft client since I'm a literal god and this probably is the issue

**Comment by c0dingnoobi** [comment]
well a simple check would be checking for transactions order since its cancelling send transactions which vanilla will never be able to do 
karhu also has a simple order check which flags this

**Comment by MWHunter** [comment]
it should be parched by the commit i linked

**Comment by DasCanard** [comment]
> tell me if [1bed34d](https://github.com/GrimAnticheat/Grim/commit/1bed34d73c477861694ef5244aba8715944cd059) fixes it. don't feel like launching a minecraft client since I'm a literal god and this probably is the issue

this fixed the issue
I'm getting flagged with the following
![image](https://github.com/GrimAnticheat/Grim/assets/17070204/21d8a5c5-4601-4f5b-a812-6a3f763c8bab)
