### ISSUE TITLE
Camel, Horse, Strider

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [GrimAnticheat/Grim#1059]
### Describe the false positive and how to replicate it

1.Sit on a camel.
2. Try to jump on it
3. You will be pushed off the camel

Same with horse (rare) and Strider (especially outside lava)

### Grim version

2.3.43

### Server version

PaperMC 1.20.1 Build # 39

### Plugins

GrimAC

**Comment by welove69** [comment]
1.20.1，BUG，Camels cannot sprint

**Comment by CatTeaA** [comment]
I also encountered this situation
1.20.1，Camels cannot sprint

**Comment by maglink** [comment]
Mee too

**Comment by MWHunter** [comment]
https://gist.github.com/MWHunter/f6096b05dd665d98a034ef1d005adc4a

The jumping code for horses would have to be switched to this for camels

Stepping height must also be set to 1.5 for camels

If the camel refuses to move the camel's horizontal velocity would be set to 0

If you want to support camels, I would suggest decompiling MCP-Reborn to get the 1.20 code to port it over to grim

**Comment by welove69** [comment]
> https://gist.github.com/MWHunter/f6096b05dd665d98a034ef1d005adc4a
> 
> The jumping code for horses would have to be switched to this for camels
> 
> Stepping height must also be set to 1.5 for camels
> 
> If the camel refuses to move the camel's horizontal velocity would be set to 0
> 
> If you want to support camels, I would suggest decompiling MCP-Reborn to get the 1.20 code to port it over to grim

It's a pity I won't decompile, sorry

**Comment by MachineBreaker** [comment]
Working on this

**Comment by StKillReal** [comment]
> Working on this

any news?

**Comment by Envel-Nikita-Gutsenkov** [comment]
> > Working on this
> 
> any news?

I have no idea how to fix this. After experimenting with horses as well, I saw that GRIM sometimes expects Y = 0 from a jump. As for camels, the mojang code is terrible. In my case I just ignore offset if it is less than 2.5 on horses and camels. this is a dumb solution, but it's temporary (see https://github.com/OpenCommunity-Original/Grim/commit/dc68105e0d26766488b98939f0699ca9939353f7).

**Comment by molor** [comment]
Still a issue in Paper 1.20.1 :(

**Comment by 7hatGuyAJ** [comment]
> > > Working on this
> > 
> > 
> > any news?
> 
> I have no idea how to fix this. After experimenting with horses as well, I saw that GRIM sometimes expects Y = 0 from a jump. As for camels, the mojang code is terrible. In my case I just ignore offset if it is less than 2.5 on horses and camels. this is a dumb solution, but it's temporary (see [OpenCommunity-Original@dc68105](https://github.com/OpenCommunity-Original/Grim/commit/dc68105e0d26766488b98939f0699ca9939353f7)).

When will you be pushing these changes and in the mean time is there a way I can disable these checks?

**Comment by CatTeaA** [comment]
Is there any progress? Looking forward to it

**Comment by itsTyrion** [comment]
Can confirm that the [OpenCommunity-Original fork](https://github.com/OpenCommunity-Original/Grim) fork works for me.

**Comment by molor** [comment]
Still a issue in Paper 1.20.4 :(

**Comment by Folas1337** [comment]
Definitely also still happening on 1.21.1

**Comment by SamB440** [comment]
https://github.com/GrimAnticheat/Grim/commit/eb72a7c86df73a1f2abc131c55d82a9c74a77ce8
