### ISSUE TITLE
Simulation Fail when player walks up stairs that have ice under them

### ISSUE THREAD

**Issue by Andrei1744** [GrimAnticheat/Grim#1060]
### Describe the false positive and how to replicate it

Step 1: Craft cobblestone stairs
Step 2: Put them over ice blocks. 
Step 3: Run over them
Step 4: Boom! False positive

### Grim version

2.4.0

### Server version

 Folia version git-Folia-"7c6e251" (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 7c6e251)

### Plugins

Backuper, GrimAC, EpicHomes

**Comment by MWHunter** [comment]
2.4.0 isn't a version, invalid bug report

**Comment by Andrei1744** [comment]
> 2.4.0 isn't a version, invalid bug report

It is. It's available on hangar.papermc.io.
Here's a link: https://hangar.papermc.io/Envel_Go/Grim-Anticheat-by-GoodMC

**Comment by MWHunter** [comment]
I have nothing to do with that version

**Comment by Andrei1744** [comment]
> I have nothing to do with that version

How come? Aren't these the same plugins?

**Comment by Andrei1744** [comment]
> I have nothing to do with that version

NVM, I saw that the one that I was having errors with was a fork. Sorry!
