### ISSUE TITLE
Unloaded chunks / teleport

### ISSUE THREAD

**Issue by DaddyAlmunther** [GrimAnticheat/Grim#1061]
### Describe the false positive and how to replicate it

Step 1. Just get a teleport
NOTE: Maybe because of the unloaded chunks? idk

https://github.com/GrimAnticheat/Grim/assets/119123238/f4edaabf-9e70-495d-a48b-f49330067ec4

### Grim version

Latest 1bed34d73c477861694ef5244aba8715944cd059

### Server version

This Server is currently running ImanitySpigot3 Premium
Version: 2023.03.1 BUILD 3

(iSpigot)

### Plugins

Citizens
FastAsyncWorldEdit
GrimAC
Core(Custom Plugin)
Game(Custom Plugin)
spark

**Comment by MWHunter** [comment]
no grim log, invalid bug report
