### ISSUE TITLE
Unloaded chunks / teleport

### ISSUE THREAD

**Issue by DaddyAlmunther** [GrimAnticheat/Grim#1062]
### Describe the false positive and how to replicate it

Step 1. Just get a teleport
NOTE: Maybe because of the unloaded chunks? idk

https://github.com/GrimAnticheat/Grim/assets/119123238/791d1128-396a-4b13-b8a1-b8114485249b

Logs:
 - https://paste.grim.ac/0NwBy
 - https://paste.grim.ac/GdM8t

### Grim version

Latest 1bed34d73c477861694ef5244aba8715944cd059

### Server version

This Server is currently running ImanitySpigot3 Premium
Version: 2023.03.1 BUILD 3

(iSpigot)

### Plugins

Citizens
FastAsyncWorldEdit
GrimAC
Core(Custom Plugin)
Game(Custom Plugin)
spark

**Comment by EternalHuman** [comment]
Can be fixed with:

> boolean check = TimeUtil.hasExpired(player.lastRespawn, 1) && !player.packetStateData.lastPacketWasTeleport;
>         // Short circuit out flag call
>         if ((offset >= getThreshold() || offset >= immediateSetbackThreshold) && check && flag()) {

In Simulation check.

**Comment by MachineBreaker** [comment]
That's a workaround, but should work for the moment

**Comment by DaddyAlmunther** [comment]
still falses
the player falses in the next 5-3 ticks after the teleport

**Comment by EternalHuman** [comment]
Use asyncTeleport

**Comment by DaddyAlmunther** [comment]
what do you mean by asyncTeleport? loading chunks before teleporting?

**Comment by EternalHuman** [comment]
> what do you mean by asyncTeleport? loading chunks before teleporting?

From Essentials. On new versions u can use just entity.teleportAsync(Location)
```java
 public static CompletableFuture<Boolean> teleportAsync(final Entity entity, final Location location, final PlayerTeleportEvent.TeleportCause cause) {
        final int x = location.getBlockX() >> 4;
        final int z = location.getBlockZ() >> 4;

        return getChunkAtAsync(location.getWorld(), x, z, true, true).thenApply(chunk -> entity.teleport(location, cause));
    }

    public static CompletableFuture<Chunk> getChunkAtAsync(final World world, final int x, final int z, final boolean gen, final boolean isUrgent) {
        final CompletableFuture<Chunk> future = new CompletableFuture<>();
        Objects.requireNonNull(future);
        final World.ChunkLoadCallback chunkLoadCallback = future::complete;
        world.getChunkAtAsync(x, z, chunkLoadCallback);
        return future;
    }
```

**Comment by SamB440** [comment]
Fixed by https://github.com/GrimAnticheat/Grim/pull/1494
