### ISSUE TITLE
ProtocolSupport is incompatibility and can't moving

### ISSUE THREAD

**Issue by SunshroomChan** [GrimAnticheat/Grim#1063]
### Describe the bug and how to replicate it

Step 1. I install ProtocolSupport and some addon for older client
Step 2. Install latest GrimAC

### Grim version

2.3.43

### Server version

This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Plugins

Plugins (41): ajLeaderboards, BedWars1058, Bedwars1058-AdminAddon, BedWars1058-AdventureMode*, BedWars1058-ArenaSetup, BedWars1058-Compass, BedWars1058-PopUpTowers*, BedWars1058-Sponge, BedWars1058-TeamSelector, BedWars1058-WinStreak, BedWars1058-XpBar*, BW1058-Cosmetics*, Citizens, ClearLag, CrossplatForms, DecentHolograms, DeliveryMan*, DeluxeMenus, Essentials, floodgate, GadgetsMenu, GlobalGamerules, GoldenGG*, LiteBans, LuckPerms, Matrix, Multiverse-Core, NBTAPI, ntdLuckyBlock, OldCombatMechanics, PlaceholderAPI, ProtocolLib, ProtocolSupport, ProtocolSupportPotions, SkinsRestorer, Vault, ViaVersion, VisibilityToggle, WG-GUI, WorldEdit, WorldGuard

**Comment by MWHunter** [comment]
what client version?

**Comment by SunshroomChan** [comment]
> what client version?

Im using 1.8 client and i can't move

**Comment by SunshroomChan** [comment]
Nevermind i should not use this anymore because ProtocolSupport is old and buggy, thanks
