### ISSUE TITLE
Bamboo Mosaic Stairs (need additional bugfixes with block 1.20)

### ISSUE THREAD

**Issue by Incluuu** [GrimAnticheat/Grim#1067]
### Describe the false positive and how to replicate it

1. Bamboo Mosaic Stairs
2. Move on bamboo mosaic stairs
3. backs up and can't walk

### Grim version

Grim Anticheat 2.3.43

### Server version

Current: git-Purpur-2004 (MC: 1.20.1)*

### Plugins

GrimAC and Protocollib

**Comment by MWHunter** [comment]
sounds like packetevents doesn't have this in their blocktags for stairs

**Comment by SamB440** [comment]
I already fixed it, needs recompilation with latest PE

**Comment by molor** [comment]
> needs recompilation with latest PE

Hello @SamB440! How did you do it? Just follow the instructions from the Grim's README "Compiling through terminal" or do I need to do something extra?

**Comment by SamB440** [comment]
> > needs recompilation with latest PE
> 
> Hello @SamB440! How did you do it? Just follow the instructions from the Grim's README "Compiling through terminal" or do I need to do something extra?

Yes, probably with `./gradlew build --refresh-dependencies`. But the latest CI jar should be fine as well since retrooper merged my stairs fix a few days ago.
