### ISSUE TITLE
Velocity Bypass

### ISSUE THREAD

**Issue by SkyplayYT** [GrimAnticheat/Grim#1068]
### Describe the bypass and how to replicate it

https://streamable.com/s4o672

### Grim version

grimac-2.3.43

### Server version

![image](https://github.com/GrimAnticheat/Grim/assets/103359249/9f899d6c-62c3-4757-98c8-19b973c925c0)

### Plugins

Protocollib, LuckPerms, WorldGuard, GrimAC, WorldEdit, NCP

**Comment by DasCanard** [comment]
try out the artifact of this commit 1bed34d73c477861694ef5244aba8715944cd059

**Comment by SkyplayYT** [comment]
It works. But there is a little problem. The Velocity Hack only works semi-good now. Sometimes the Knockback correction works and sometimes not.

**Comment by DasCanard** [comment]
@MWHunter

**Comment by MWHunter** [comment]
this seems fixed?

**Comment by SkyplayYT** [comment]
Can't tell you. Lost access to the Client. I only know that it had 2 Velocity Bypasses. One Blocked Knockback completely and the other one is a reduce Velocity without a swing. Maybe they changed that but I can't tell you :)
