### ISSUE TITLE
Spam of warns using Java 8 + 1.8.8

### ISSUE THREAD

**Issue by Fredh1000** [GrimAnticheat/Grim#1075]
### Stack trace

Inexistent

### How to replicate it if known

1) Install Grim on 1.8.8 server and running it with Java 8
2) Join in the server without * or op perms.
3) The console will spam these warns:
![Screenshot (387)](https://github.com/GrimAnticheat/Grim/assets/82319919/30dde849-4909-4fde-aadf-dc0b93c35abc)

### Grim version

2.3.43

### Server version

GuardSpigot 1.8.8

### Plugins

![Screenshot (388)](https://github.com/GrimAnticheat/Grim/assets/82319919/e7dd2bc5-3efc-4b3b-ac13-e2cdffae1745)

**Comment by MachineBreaker** [comment]
> ### Stack trace
> Inexistent
> 
> ### How to replicate it if known
> 1. Install Grim on 1.8.8 server and running it with Java 8
> 2. Join in the server without * or op perms.
> 3. The console will spam these warns:
>    ![Screenshot (387)](https://user-images.githubusercontent.com/82319919/250894012-30dde849-4909-4fde-aadf-dc0b93c35abc.png)
> 
> ### Grim version
> 2.3.43
> 
> ### Server version
> GuardSpigot 1.8.8
> 
> ### Plugins
> ![Screenshot (388)](https://user-images.githubusercontent.com/82319919/250894514-e7dd2bc5-3efc-4b3b-ac13-e2cdffae1745.png)

Did you tested without GuardSpigot?

**Comment by c0dingnoobi** [comment]
Seems to be an issue on your side, works fine for me with vanilla 1.8 and grim latest with java 8 
Try to narrow down to cause by removing plugins and testing it
