### ISSUE TITLE
False positives when using portals

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [GrimAnticheat/Grim#1086]
### Describe the false positive and how to replicate it

I could not understand the nature of the problem, when entering and exiting the portal to nether (we can do this very quickly), grim starts to totally incorrectly predict movements and completely stops the player. To reproduce the problem, it is often necessary to jump / run from the portal and into the portal for a long time.

### Grim version

c97da23

### Server version

PaperMC 1.20.1 # 67

### Plugins

Grim

**Comment by c0dingnoobi** [comment]
Sounds to be https://github.com/GrimAnticheat/Grim/issues/1062 in combination of https://github.com/GrimAnticheat/Grim/issues/787

**Comment by SamB440** [comment]
Fixed by #1494
