### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by Gray-Falcon** [GrimAnticheat/Grim#1088]
### Feature description

Hello, this is the best anti-cheat i have tested so far, (Tested Negativity v2, Spartan and Grimm). I wonder if i there is Discord server or some form of communication/support.

**Comment by Gray-Falcon** [comment]
If you as a developer dont have time to setup a discord, i would be happy to help in this way and do it, i would transfer ownership to you then

**Comment by c0dingnoobi** [comment]
there is a [dc](https://discord.gg/5s6VqBVY) but its mainly used for anouncements and not for communication/support

**Comment by Gray-Falcon** [comment]
Thanks for invite
