### ISSUE TITLE
Is it possible to publish plugins that have been successfully builds here

### ISSUE THREAD

**Issue by CatTeaA** [GrimAnticheat/Grim#1093]
### Feature description

It can be downloaded directly here

**Comment by c0dingnoobi** [comment]
unsure what is meant
but if you mean grim builds then https://github.com/GrimAnticheat/Grim/actions u can download them here

**Comment by CatTeaA** [comment]
> 不确定是什么意思，但如果您的意思是严峻的构建，那么 https://github.com/GrimAnticheat/Grim/actions 您可以在此处下载它们

Sorry, what I'm trying to express is, posting in this place, the jar that has been built has been completed
I'm using translation software, I'm sorry
Like this, you can download and use it directly
https://www.spigotmc.org/resources/grim-anticheat.99923/

**Comment by c0dingnoobi** [comment]
> but if you mean grim builds then https://github.com/GrimAnticheat/Grim/actions u can download them here

they get built and uploaded automatically as by github actions
see [the latest build by latest commit](https://github.com/GrimAnticheat/Grim/suites/14086253235/artifacts/787633128)

**Comment by welove69** [comment]
> > but if you mean grim builds then https://github.com/GrimAnticheat/Grim/actions u can download them here
> 
> they get built and uploaded automatically as by github actions see [the latest build by latest commit](https://github.com/GrimAnticheat/Grim/suites/14086253235/artifacts/787633128)

I know, but there are still many who won't build jar yet
