### ISSUE TITLE
Being in lava = antikb falses

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1094]
### Describe the false positive and how to replicate it

Being in lava = antikb falses o: 0.01960
Being in lava = antikb falses o: 0.01960
Being in lava = antikb falses o: 0.01960
Being in lava = antikb falses o: 0.01960
just putting this here incase it affects 3.0 aswell

### Grim version

grimac-2.3.43

### Server version

1.20.1 paper

### Plugins

amogus

**Comment by raffel080108** [comment]
Can confirm, has been replicated on my server by several players including myself

**Comment by raffel080108** [comment]
I had this issue aswell, I fixed it by changing the antikb threshold in the config (config.yml -> knockback -> threshold [line 94]) (I set it to 0.1)

**Comment by itsTyrion** [comment]
0.1 is pretty high, I have never seen it false higher than 0.0196. 0.02 seems to be enough

**Comment by raffel080108** [comment]
The default value is even higher than 1.0, I don‘t remember the exact… it might be good to change it

**Comment by itsTyrion** [comment]
the default is 1e-5 (0.00001)

**Comment by raffel080108** [comment]
Oh, ok - It‘s possible I simply misremembered that

**Comment by cn-cn-cn** [comment]
I can't reproduce this.

**Comment by raffel080108** [comment]
It only happens when the anti kb filter is set very high, as was described - This isn‘t really a bug at all and I think this should be closed

**Comment by itsTyrion** [comment]
@notcancername try swimming straight upwards in lava without fire resistance so you have damage tick

@raffel080108 I disagree. Having to set the knockback check very lenient to not get dragged drown when trying to escape lava is a bug in my eyes. 

I made a temp. workaround plugin for this btw, source and jar on my GH
