### ISSUE TITLE
fast fly

### ISSUE THREAD

**Issue by baldballs** [GrimAnticheat/Grim#1097]
### Describe the bypass and how to replicate it

hello i am a developer and i found months ago this fly that abuses any type of velocity using server tp, basically i tp 1000 blocks forward everytick and if i take velocity while doing it grim will calculate wrongly my motion and it will apply infinitly the kb i was getting, flagless as u can see in the clip 
https://streamable.com/kac762
(i want it to get patched bc someone packetlogged me and now a skidded client have it so patch it pls) 

### Grim version

works on any version

### Server version

1.8 but works on every vers 

### Plugins

i have no idea and idc

**Comment by c0dingnoobi** [comment]
[lpx](https://pastebin.com/gL6nR0Rp) flags this (ytnoos is fine with this being public)

**Comment by ytnoos** [comment]
that moment when you accidentally patch things

**Comment by c0dingnoobi** [comment]
> @c0dingnoobi ik but not every server has lpx

was meant to show how it would be flagable dummy

**Comment by baldballs** [comment]
@c0dingnoobi dumbass theyre crash a check could check that by just lowering the hard coded border

**Comment by ItsClairton** [comment]
I think this is the bypass that the Augustus Client is using.

https://youtu.be/HeWGg0TKyno
https://youtu.be/yjgNKe1C8rk

**Comment by baldballs** [comment]
@ItsClairton ye they stole mine cus someone gave it to the dev ( @c0dingnoobi )

**Comment by c0dingnoobi** [comment]
> @ItsClairton ye they stole mine cus someone gave it to the dev ( @c0dingnoobi )

https://prnt.sc/BnDavQldEmKk 
idiotic reasoning

**Comment by MachineBreaker** [comment]
Keep this respectfully please

**Comment by Euro-pol** [comment]
h

**Comment by AoElite** [comment]
This is already fixed in grim 3.0, but we'll probably make a fix for 2.0 since this does seem like a critical issue.

**Comment by Euro-pol** [comment]
what is grim 3.0 bro

**Comment by AoElite** [comment]
> what is grim 3.0 bro

It's the next version of grim. Not sure when it's going to be released. It's private at the moment.

**Comment by MWHunter** [comment]
"flagless"

as you are getting violations in the video.

**Comment by AoElite** [comment]
Pushed a fix

**Comment by baldballs** [comment]
@MWHunter https://streamable.com/ywrqrf
https://streamable.com/pnsdem
https://streamable.com/gd9n5h
get a brain kiddo ur ac is ass

**Comment by baldballs** [comment]
i could open other 30 + tabs with bypasses for this ac like kid i litterally flagged one time simulation that falses a shit ton @MWHunter and u are soo stupid u give out bypasses for ur ass anticheat in yt comments get a brain

**Comment by Euro-pol** [comment]
GrimAnticheat blocked baldballs
