### ISSUE TITLE
Chests disappearing

### ISSUE THREAD

**Issue by Saidas25** [GrimAnticheat/Grim#1103]
### Describe the bug and how to replicate it

Step 1. have a 1.19.4 papermc minecraft server with grim
Step 2. Have a double chest
Step 3. look away from the double chest for 10seconds, shoot with your bow, break blocks anything
Step 4. turn around and the double chest has disappeared
Step 5. Right clicking where the chest was suposed to be brings it back
Deleting grim fixed the issue

### Grim version

latest

### Server version

This server is running Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)
You are running the latest version

### Plugins

![image](https://github.com/GrimAnticheat/Grim/assets/91024239/06574c15-a638-4750-944c-2c3cdc7921c2)

**Comment by AoElite** [comment]
@Saidas25 Update to the latest commit of Grim. There was a issue in PacketEvents that caused chests to disappear. You can find the download in the discord.
