### ISSUE TITLE
Kicked while harvesting

### ISSUE THREAD

**Issue by ch4ika** [GrimAnticheat/Grim#1106]
### Describe the false positive and how to replicate it

When larger fields are harvested, you sometimes get kicked.
You are sending too many packets.

Maybe it has nothing to do with the harvest. But with the click.
Is there any other setting or something that I can do about it?

### Grim version

grimac-2.3.44

### Server version

This server is running Paper version git-Paper-95 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: aa93dcf)
You are 3 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Purpur-2016 (MC: 1.20.1)

### Plugins

PlotSquared, Fawe

**Comment by c0dingnoobi** [comment]
> You are sending too many packets.

Why do you think that this is grim related? Grim never kicks for that reason sounds like its paper 
also you didnt list grim as plugin in ur list
do you even run grim
