### ISSUE TITLE
Placing Sponges

### ISSUE THREAD

**Issue by dicepvp** [GrimAnticheat/Grim#1110]
### Describe the false positive and how to replicate it

go into deep water and stand where the sponge will absorb water. while you are in the air after placing the sponge it spams for simulation.
https://paste.grim.ac/Lon8N

in this example dev checks are on but the false exists in either way

### Grim version

GrimAC version 2.3.43 Libre simulation anticheat designed for 1.19 with 1.8-1.19 support, powered by PacketEvents 2.0. Author: GrimAC

### Server version

Current: git-Purpur-2025 (MC: 1.20.1)*
Previous: git-Purpur-2023 (MC: 1.20.1)

### Plugins

AdvancedReplay, Amend, AntiCheatReplay, BanFromClaim, BetterRTP, BlueSlimeCore, Chunky, ChunkyBorder, CMI, CMILib:  CombatLogX, CoreProtect, DiscordSRV, FastAsyncWorldEdit, FileGUI, floodgate, GDHooks, Geyser-Spigot, GriefDefender, GrimAC  IllegalStack, InsaneShops, Jobs, KauriVPN, LiteBans, LuckPerms, Orebfuscator, Pl3xMap, Pl3xMap-Claims, PlaceholderAPI Plan, ProtocolLib, PurpurExtras, RoyaleEconomy, ServerBackup, ServerBackup, SmoothTimber, spark, SpectatorMode, SpigotWeb StaffPlusPlus, UltimateAutoRestart, UltraCustomizer, UnstripLog, Vault, Votifier

**Comment by MWHunter** [comment]
Then don't place sponges underwater
