### ISSUE TITLE
stricter Timer check?

### ISSUE THREAD

**Issue by z7087** [GrimAnticheat/Grim#1115]
### Feature description

vanilla client seems runs up to 10 ticks once after its lag (on 1.8.8/1.12/1.19.2 client), adding check of this may prevent some client like Liquidbounce from using blink

**Comment by MWHunter** [comment]
Vanilla client can run up to 30 seconds due to latency variation.

**Comment by z7087** [comment]
I apologize for any confusion caused by the previous translations. To clarify, this stuttering issue is unrelated to network connectivity and will result in a lower frame rate for the client, leading to a less smooth visual experience.

**Comment by MWHunter** [comment]
the behaviour is the same for a timer check.  A player whose network times out for two seconds will send 40 movements all at once.  Blink is vanilla.

**Comment by z7087** [comment]
i think it should only be vanilla when the client delays all packets, however, Blink on a Liquidbounce client does not delay transaction packets. It also does not send rotation packets, this will flag simulation

**Comment by xuenailuodaskidder** [comment]
So what you mean is that "vanilla" will delay sending all packets when lag, while "LiquidBounce"'s blink module will not do that. Therefore, this is judgment is not "vanilla" but a way for cheating clients to deceive Grimac？

**Comment by z7087** [comment]
idk i think it can be, for example if i use blink to walk 100 blocks, the vanilla client will not send all transaction packets at the beginning of the journey

**Comment by z7087** [comment]
if it does, it should be detected by timer check

**Comment by MWHunter** [comment]
The vanilla client would send all transactions at the end of the journey if both inbound and outbound had a lag spike.  Sending all in the beginning would flag timer.  There are no gameplay rules broken by this type of timer.
