### ISSUE TITLE
irremovability

### ISSUE THREAD

**Issue by MILK2679** [GrimAnticheat/Grim#1116]
### Describe the bug and how to replicate it

I am the owner of a mod server, after installing the plugin, when standing on any mod block it will trigger detection and cause me to be unable to act on it

### Grim version

。

### Server version

arclight-1.16.5-1.0.24-551ec3ff (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Plugins

AFKKick, Dirtywordsshielding, ErrorFixer, GiveItem, NoChunkLag, PlaceholderAPI, NetworkUtil, JoinMessagePlus, Boom, PvPToggle, JoinWithCommand, BanItem, EntitySearch, NoSay, GSit, QiMengBugFix, Transfer, ScreenshotPlugin, ChatManager, CoreProtect, LockServer, ClearEntity, LuckPerms, ControlPlayer, KingCrimson, VillagerOptimiser, CMILib, NametagHide, Broadcast, MessageRecorder, ProtocolLib, AutoUnloadChunk, RecordPlayerCoordinate, AntiModifySpawner, LimitPillagers, yuanluAntiSpam, AntiUpdateSkipper, HECore, ShieldPlayer, Vault, JoinCommands, MiaoChat, ResourceWorld, SaveItems, NoPlugins, MobFarmManager, PlayerTitle, HECob, RandomTeleport, PacketLimiter, GrimAC, HeadDatabase, XConomy, TabooLib5, TrMenu, Citizens, ScriptBlockPlus, SuperVanish, HuskHomes, TransferTip

**Comment by MILK2679** [comment]
Grim version

**Comment by MILK2679** [comment]
grimac-2.3.43

**Comment by MachineBreaker** [comment]
Grim doesn't support modded servers

**Comment by MWHunter** [comment]
Grim will never support mods, it depends on PacketEvents which I designed for only vanilla blocks
