### ISSUE TITLE
Banned from Discord (absolute no reason) Grim 2.0 is Abandoned

### ISSUE THREAD

**Issue by Hwaanx** [GrimAnticheat/Grim#1117]
AoeLite Decided to Ban me.

The only issue i will open on grim 2.0.

I got banned from 3 different accounts i tried to join ask why would he ban me and he banned me again.

I support Grim i think there should be more anticheats like this with simulation and more anticheats that are this good.

I don't like how a mod responds to everything by open an issue on github.

I decided to say "No, I refuse to open a issue on github." He instantly banned me.
This is not a reason for a ban but i won't argue if the rules are -mods can do whatever they want.-

You are only creating hate. You can instead say something else or don't ban me.
You really got far with banning all of my accounts even i haven't said something.

I don't care about 2.0 anymore that 3.0 is announced because as far as i know Define gave up on 2.0 
Grim 2.0 is Abandoned there is no one looking after it i will wait until some news.

**Comment by Hwaanx** [comment]
why am i writing this: i have no accounts to join on grim discord.

**Comment by MWHunter** [comment]
A mod banning you for DM'ing is fair, use the issue tracker.

**Comment by Hwaanx** [comment]
> A mod banning you for DM'ing is fair, use the issue tracker.

What is DM'ing you mean direct messaging? I did not direct message anyone

**Comment by Hwaanx** [comment]
I don't know what is fair or not but i wouldn't like to be banned, if you can please open my ban on discord i did nothing wrong and i don't think i deserve a ban.
