### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1118]
### Stack trace

https://paste.gg/p/anonymous/9ba92d959fb345549f1c7bd70c5fd8da

### How to replicate it if known

1. Add grim to your server
2. Start your server
3. Join your server

### Grim version

GrimAC version 2.3.43

### Server version

Current: git-Purpur-2030 (MC: 1.20.1)*

### Plugins

floodgate, Geyser-Spigot, GrimAC, LuckPerms, nAntiBot, ProtocolLib, spark, Vault, ViaBackwards, ViaVersion

**Comment by ghost** [comment]
PS - This causes every single person to get disconnected and not be able to join the server
https://cdn.discordapp.com/attachments/1142206137719066665/1142206434373795971/rn_image_picker_lib_temp_6d7ff2ca-ab6b-47dc-9acf-a7fa3284e7a0.jpg
https://cdn.discordapp.com/attachments/1141407018402459769/1141426085783941180/image.png

**Comment by c0dingnoobi** [comment]
try using latest commit 
ur on outdated version

**Comment by ghost** [comment]
Oh ok, I just downloaded this one from spigotmc. I'll try latest commit thx

**Comment by ghost** [comment]
Still occurring on latest build

**Comment by ghost** [comment]
https://paste.walshy.dev/NO8yNgny0I7v

New paste

**Comment by ghost** [comment]
It appears to be more frequent in the dev build. Is it safe to downgrade?

**Comment by MWHunter** [comment]
Report on the PacketEvents repo, not a grim issue
