### ISSUE TITLE
Camel,Try to jump on it,You will be pushed off the camel

### ISSUE THREAD

**Issue by CatTeaA** [GrimAnticheat/Grim#1121]
### Describe the false positive and how to replicate it

Riding a camel cannot accelerate and jump
https://github.com/GrimAnticheat/Grim/issues/1059

### Grim version

grimac 2.3.44

### Server version

1.20.1

### Plugins

grimac

**Comment by MWHunter** [comment]
What was the point of reporting this issue if you knew it was a duplicate?
