### ISSUE TITLE
duplicate 1.17 packets abuse

### ISSUE THREAD

**Issue by z7087** [GrimAnticheat/Grim#1122]
### Describe the bypass and how to replicate it

grim does not check for 1.17 duplicate packets, but vanilla still handles it normally, this can be used in 1.17+ client as some timer bypass or other

### Grim version

grim-2.3.44.jar

### Server version

Spigot 1.19.2

### Plugins

ViaVersion, ViaBackwards, ViaRewind, GrimAC

**Comment by MWHunter** [comment]
How do these packets help?

**Comment by z7087** [comment]
~~For example, if I send 40 of this packets while eating food, I can eat it instantly~~ I tested this in a paper 1.8.8 server
Or I use packets like this to move around the air, send a normal c04 after the move is over, and grim will setback me to where I started, and soon vanilla will teleport me to where the move over

**Comment by ytnoos** [comment]
I can confirm this.

**Comment by ballddddddddinggg** [comment]
the explanation is really wrong fly doesnt really work like that but okkkk

**Comment by MWHunter** [comment]
Eating food is 1.8 server specific.

**Comment by z7087** [comment]
> the explanation is really wrong fly doesnt really work like that but okkkk

mine works like that and im struggling with being kicked by sending too much packets

**Comment by MWHunter** [comment]
Fine, I'll move stupidity on stupidity (stupidity packet on 0.03 stupidity) after the stupidity check

https://github.com/GrimAnticheat/Grim/commit/4dcdc784623ce9c1a45ac1f86617417bc8050eb3

**Comment by z7087** [comment]
Is it necessary to add a check to prevent 1.17+ clients from using fastuse on 1.8 servers?

**Comment by MWHunter** [comment]
Yes, but 1.8 servers are on their own for this.  I'm not planning to fix this as I don't really care about 9 year old versions of the game paired with modern clients, stuff like this can happen.

**Comment by kulovplayz** [comment]
why tf did u patch it bruh
