### ISSUE TITLE
Camel issues

### ISSUE THREAD

**Issue by DasCanard** [GrimAnticheat/Grim#1130]
### Describe the false positive and how to replicate it

1. Spawn Camel
2. Put saddle on it
3. Ride -> fp (https://paste.grim.ac/th8EW)

https://share.richy.sh/23/08/YqTih4.mp4

### Grim version

4dcdc784623ce9c1a45ac1f86617417bc8050eb3

### Server version

This server is running Paper version git-Paper-164 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 6813244)
You are 5 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-128 (MC: 1.20.1)

### Plugins

![image](https://github.com/GrimAnticheat/Grim/assets/17070204/be8b7173-d451-48f8-9d22-7ab18e1766bb)

_Hint: also happening without AnticheatAdditon_

**Comment by CatTeaA** [comment]
https://github.com/GrimAnticheat/Grim/issues/1059

**Comment by MWHunter** [comment]
stop reporting this duplicate issue

If you want it fixed, I've given the NMS code and the place that it goes
