### ISSUE TITLE
Fly bypass

### ISSUE THREAD

**Issue by rejomy** [GrimAnticheat/Grim#1132]
### Describe the bypass and how to replicate it

https://www.youtube.com/watch?v=dd1Wt0IJ3K8
https://www.youtube.com/watch?v=DAhlG6fAHdc

### Grim version

idk

### Server version

idk

### Plugins

idk

**Comment by ytnoos** [comment]
wait it's my server

**Comment by MWHunter** [comment]
It's likely patched if you update to the latest git.
