### ISSUE TITLE
FastMath Simulation False

### ISSUE THREAD

**Issue by Hwaanx** [GrimAnticheat/Grim#1137]
### Describe the false positive and how to replicate it

Just Fighting with FastMath on

### Grim version

99b272d

### Server version

Paper 1.19.4

### Plugins

GrimAC, LuckPerms, SkinsRestorer, Spark, ViaVersion, Viabackwards

**Comment by furyzen** [comment]
can you provide additional informations about you and the opponent ? 

do you both have fastmath on ? or only you or the opponent, what is the opponent's and your version ? are you both in vanilla ?

**Comment by Hwaanx** [comment]
I am in Lunar Client Sodium 1.19.2 he is on Optifine 1.19.4

**Comment by Hwaanx** [comment]
![image](https://github.com/GrimAnticheat/Grim/assets/112027449/5d71aa68-71cc-4c4c-8998-040c5df324a3)
I did this to add a little bit of lag so server lag + fastmath could be the issue i don't know

**Comment by Hwaanx** [comment]
also there is a negative timer false so how can i disable/prevent it?

**Comment by MWHunter** [comment]
invalid bug report

**Comment by Hwaanx** [comment]
> 

so is it from server lag?

**Comment by MWHunter** [comment]
You have to give a more detailed bug report, such as using grim logs for the simulation flag

**Comment by Hwaanx** [comment]
![265747158-886d639a-b9cd-436e-b332-dcc67f4bffa2](https://github.com/GrimAnticheat/Grim/assets/112027449/9ff898d6-6c99-4c52-b4bf-e94a0a602a6a)

I only have this screenshot i'll try recreating it if i am not lazy
