### ISSUE TITLE
Invincibility

### ISSUE THREAD

**Issue by Hwaanx** [GrimAnticheat/Grim#1139]
### Describe the bug and how to replicate it

GrimAC causes players to be invincible when the match starts

1. Use the sword to get into a match
2. Sometimes one player is invincible and other player automatically wins because of it

### Grim version

99b272d

### Server version

1.19.4 Pufferfish

### Plugins

ajLeaderboards, AnimatedScoreboard, Authme, Chatcontrol, Citizens, DeluxeMenus, Essentials, EssentialsSpawn, FAWE, GrimAC, LiteBans, LPC, LPX, Multiverse-Core, MyCommand, PlaceHolder-API, Playtime, PlugManX, ProtocolLib, Ranks, SkinsRestorer, Spleef, StrikePractice, TAB, TntRun_Reloaded, Vault, ViaVersion, VoidSpawn, Vulcan, WebSender, WorldGuard

**Comment by MWHunter** [comment]
Invalid bug report, you need more information than just that the player is invincible.

**Comment by MWHunter** [comment]
The burden of proof on a bug for free software is on you - prove that the bug exists and find a way to reproduce it or at least show the issue is with grim.  I can't spend hours trying to debug your setup.

**Comment by Hwaanx** [comment]
> The burden of proof on a bug for free software is on you - prove that the bug exists and find a way to reproduce it or at least show the issue is with grim. I can't spend hours trying to debug your setup.

you are very right, i didn't think that way i'll find a way to reproduce it but the bug is very rare my current thinking it could be an issue with strikepractice or vulcan.

**Comment by ytnoos** [comment]
It's happening also to me but on a bedwars server (not sure it's Grim). When a player respawns and gets teleported on his island, if he doesn't move at all he cannot be attacked. In fact people who crash and stay in the server for a few seconds are impossible to kill

**Comment by MWHunter** [comment]
fine, it's plausible if Ytnoos says it happens - will try the minimal reproduction of simply respawning and not moving.

**Comment by Hwaanx** [comment]
> fine, it's plausible if Ytnoos says it happens - will try the minimal reproduction of simply respawning and not moving.

you can move in my condition.

**Comment by Finoway** [comment]
> > fine, it's plausible if Ytnoos says it happens - will try the minimal reproduction of simply respawning and not moving.
> 
> you can move in my condition.

It's just a suggestion, but from what I remember the Essentials plugin has an option to prevent damage after a teleport for 5 seconds. So if the player has been teleported by grimac (or another plugin) because of a detection, this could be the cause of the problem? or even the problem? I remember a similar problem several years ago when I was using essentials, but I haven't tested my hypothesis yet.

**Comment by Hwaanx** [comment]
It's not for five seconds its forever but you can use projectiles to deal the player damage you just can't hit him.

**Comment by MWHunter** [comment]
that means that the reach check doesn't see the other player, possibly due to a race condition with world switching or something else

**Comment by Hwaanx** [comment]
> that means that the reach check doesn't see the other player, possibly due to a race condition with world switching or something else

yes players switch worlds when they queue we use multiverse for strikepractice

**Comment by Hwaanx** [comment]
BIG UPDATE! Watch This Video https://paste.grim.ac/7m9lV
https://youtu.be/Y0SPQmVzfBo

**Comment by MWHunter** [comment]
https://github.com/GrimAnticheat/Grim/blob/16f2e5427c2044a0cc616334f46a8b345e03f36e/src/main/java/ac/grim/grimac/events/packets/PacketPlayerRespawn.java#L113C2-L113C2

Could you try compiling with this line set to
if (respawn.getDimension().getId() != player.dimension.getId()) {

This follows minecraft source code better.  It shouldn't matter, but I don't know what else it could be.

**Comment by Hwaanx** [comment]
Sadly it doesn't fix it.

**Comment by MWHunter** [comment]
Are you using async entity tracking?

**Comment by Hwaanx** [comment]
I am using pufferfish and i checked the config file, its not there. Im pretty sure async entity tracker is only available in pufferfish+

**Comment by Hwaanx** [comment]
i am thinking of closing this since i cannot confirm %100 that this happens because of grim @ytnoos you guys switched to polar did this issue got fixed when you did so?

**Comment by ytnoos** [comment]
It was a very rare issue, until now no one reported anything

**Comment by Hwaanx** [comment]
> It was a very rare issue, until now no one reported anything

Okay then i think i can close this until i get new information
