### ISSUE TITLE
Slime Elevation False Flag (Updated)

### ISSUE THREAD

**Issue by Hwaanx** [GrimAnticheat/Grim#1141]
### Describe the false positive and how to replicate it

https://youtu.be/MQkEi46r004

It also works on other blocks that works as a step.

the video is recorded with 1.19.2 client version but i also can recreate it on 1.19.4

### Grim version

latest

### Server version

1.19.4 Paper 550

### Plugins

![image](https://github.com/GrimAnticheat/Grim/assets/112027449/9c9af7ad-200c-4ba8-8108-e0549b0f9614)

**Comment by Hwaanx** [comment]
New Video

**Comment by c0dingnoobi** [comment]
might be related to #974 which is in relation to #760

**Comment by Hwaanx** [comment]
closed due to duplicate
