### ISSUE TITLE
Future Beta Velocity Bypass

### ISSUE THREAD

**Issue by Th3L1nk** [GrimAnticheat/Grim#1149]
### Describe the bypass and how to replicate it

I have no idea how it works, I dont have future beta, but I fight people who do and they take no knockback and have stated openly that future beta has a bypass.
           
### Grim version

2.3.45

### Server version

1.19

### Plugins

whatever plugins 2b2t runs

**Comment by outlineutils** [comment]
malding

**Comment by oragejuice** [comment]
I think they're using this, I tested it on 2b and seems to work the same. The bypass part from the velocity module is:
```java
            if (event.getPacket() instanceof EntityVelocityUpdateS2CPacket ) {
                EntityVelocityUpdateS2CPacket  var4 = event.getPacket();
                if (var4.getId() == mc.player.getId()) {
                    event.cancel();
                    grimTicks = 6;
                }
            }
            if (event.getPacket() instanceof PlayPingS2CPacket && grimTicks > 0) {
                event.cancel();
                grimTicks--;
            }```

**Comment by Th3L1nk** [comment]
Thank you for adding this oragejuice. Velocity is ultimately the biggest hindrance to the current meta, and it's unfortunately very tricky to patch.

**Comment by c0dingnoobi** [comment]
https://github.com/GrimAnticheat/Grim/pull/1057 
pls merge this..

this check would successfully flag any transaction/ping packet cancellings to bypass velocity without falses.
i rlly can not understand why this pr is still open

**Comment by 0-x-2-2** [comment]
> #1057 pls merge this..
> 
> this check would successfully flag any transaction/ping packet cancellings to bypass velocity without falses. i rlly can not udnerstand why this pr is still open

Transactions do get dropped in some situations but I don't think the velocity posted here actually works on modern grim and seems to only work on old grim. One of the biggest problems is viaversion/viabackwards emulating the transaction packets.

**Comment by Th3L1nk** [comment]
if thats the case then why does future betas velo still seem to work on 2b

**Comment by 0-x-2-2** [comment]
2b2t runs an older version of Grim as far as I know.

**Comment by Th3L1nk** [comment]
I believe that they updated it yesterday no?

**Comment by c0dingnoobi** [comment]
> Transactions do get dropped in some situations

as mentioned in the pr that check is valid, and is used by multiple servers (1.8 1.20 1.19 since months (and multiversions))
checking transaction order is a valid approach 
karhu/polar even do it too

> 2b2t runs an older version of Grim as far as I know.

i dont know about 2b2ts current situation of what version they run
im just saying, using that check we could avoid further "bypasses"

**Comment by FluorideHistorian** [comment]
> I think they're using this, I tested it on 2b and seems to work the same. The bypass part from the velocity module is:
> 
> ```java
>             if (event.getPacket() instanceof EntityVelocityUpdateS2CPacket ) {
>                 EntityVelocityUpdateS2CPacket  var4 = event.getPacket();
>                 if (var4.getId() == mc.player.getId()) {
>                     event.cancel();
>                     grimTicks = 6;
>                 }
>             }
>             if (event.getPacket() instanceof PlayPingS2CPacket && grimTicks > 0) {
>                 event.cancel();
>                 grimTicks--;
>             }```
> ```

this was patched a long time ago

**Comment by c0dingnoobi** [comment]
just checked again and yes its patched by https://github.com/GrimAnticheat/Grim/commit/1bed34d73c477861694ef5244aba8715944cd059 

we either have to assume that 2b2t uses an old version which i doubt since that commit is from june 
or future does something else than the shown snippet

**Comment by FluorideHistorian** [comment]
> just checked again and yes its patched by [1bed34d](https://github.com/GrimAnticheat/Grim/commit/1bed34d73c477861694ef5244aba8715944cd059)
> 
> we either have to assume that 2b2t uses an old version which i doubt since that commit is from june or future does something else than the shown snippet

2b2t is on the latest version

there are multiple velocity bypasses in grim rn

**Comment by c0dingnoobi** [comment]
> this was patched a long time ago

still confused  when [he](https://github.com/GrimAnticheat/Grim/issues/1149#issuecomment-1719987941) said ` I tested it on 2b and seems to work the same`

**Comment by FluorideHistorian** [comment]
> > this was patched a long time ago
> 
> still confused when [he](https://github.com/GrimAnticheat/Grim/issues/1149#issuecomment-1719987941) said ` I tested it on 2b and seems to work the same`

grim allows you to flag for awhile, he didnt test for long enough

**Comment by c0dingnoobi** [comment]
doesnt since https://github.com/GrimAnticheat/Grim/commit/1391fc554961e7d4a49feb08e55fd20dc75a7190
well 2b2t might not be on that ver yet

**Comment by flufferyomada** [comment]
From my knowledge
Their Version is atleast from august

**Comment by master7720** [comment]
#Free0x22

**Comment by AoElite** [comment]
I've tested Future Beta & it doesn't appear to bypass grim. Maybe 2b2t has configured grim wrong.

**Comment by Th3L1nk** [comment]
what version were you testing and what configs

**Comment by skdii** [comment]
wdym future doesnt have working velocity nor does beta build. It only works on 2b2t since its very old version but it doesnt work so idk what u yappin about

**Comment by skdii** [comment]
> ture Beta & it doesn't appear to bypass grim. Maybe 2b2t has configured grim wrong.

bro you do not have future beta stop lyin 😭 💀

**Comment by AoElite** [comment]
> > ture Beta & it doesn't appear to bypass grim. Maybe 2b2t has configured grim wrong.
> 
> bro you do not have future beta stop lyin 😭 💀

I don't have future beta and never claimed I did, but I know someone who does & did test it. However I don't know if they were using the latest version of it and I haven't tested it since. There could have been updates made after. I also tested it on the very latest grim at the time & not on 2b2t.

**Comment by skdii** [comment]
> 
"Ive tested" , Wild aswell you were probably testing the public release, I doubt any beta user would help develop a patch

**Comment by SamB440** [comment]
This does not bypass or it was fixed

**Comment by flufferyomada** [comment]
> This does not bypass or it was fixed

future doesn't bypass but rusherhack does

https://video.omada.cafe/w/a1QgvhmyonYdriSSb5dgvz

**Comment by SuicidalEeper** [comment]
> > This does not bypass or it was fixed
> 
> future doesn't bypass but rusherhack does
> 
> https://video.omada.cafe/w/a1QgvhmyonYdriSSb5dgvz

Does it work with normal velocity? (Not 0 hit delay)

**Comment by SamB440** [comment]
Don’t use anticheat test server and enable experimental checks
