### ISSUE TITLE
False alarms about Camel

### ISSUE THREAD

**Issue by Linwendong83** [GrimAnticheat/Grim#1157]
### Describe the false positive and how to replicate it

False alarms are generated when the player is riding on a camel，when the player sprints（English is not my first language. This is machine translation）

### Grim version

2.3.45

### Server version

Current: git-Purpur-2062 (MC: 1.20.1)

### Plugins

CommandWhitelist, CoreProtect, deathpunishment, Essentials, EssentialsChat, LuckPerms, PlaceholderAPI, ProtocolLib, Sieg
eWar, spark
[21:00:24 INFO]:  TAB, Towny, TownyChat, Vault, xptomoney

**Comment by Souipi** [comment]
What's alarms ?

**Comment by Linwendong83** [comment]
![QQ截图20230924121330](https://github.com/GrimAnticheat/Grim/assets/93021538/69bbc612-edf8-45be-a81f-5fbc88a1efea)

**Comment by Hwaanx** [comment]
> ![QQ截图20230924121330](https://user-images.githubusercontent.com/93021538/270144295-69bbc612-edf8-45be-a81f-5fbc88a1efea.png)

Can you provide a video it would be better for explanation

**Comment by Linwendong83** [comment]
https://github.com/GrimAnticheat/Grim/assets/93021538/c818ba69-d842-4d5a-b372-fbc60745ba1d

Look out the "ctrl"

**Comment by Linwendong83** [comment]
> > ![QQ截图20230924121330](https://user-images.githubusercontent.com/93021538/270144295-69bbc612-edf8-45be-a81f-5fbc88a1efea.png)
> 
> Can you provide a video it would be better for explanation


https://github.com/GrimAnticheat/Grim/assets/93021538/a051d4d4-686e-44b2-8a03-748fb7a5f763

**Comment by Souipi** [comment]
Oh okay i see that is bcs grim aren't really updated for 1.20. But that can be patch easily.

**Comment by c0dingnoobi** [comment]
seems to be related to #1059

**Comment by Souipi** [comment]
> seems to be related to #1059

Yup

**Comment by SamB440** [comment]
https://github.com/GrimAnticheat/Grim/commit/eb72a7c86df73a1f2abc131c55d82a9c74a77ce8
