### ISSUE TITLE
PrimAC prevents user from joining after packetevents encounters an decode exeption.

### ISSUE THREAD

**Issue by nicolube** [GrimAnticheat/Grim#1159]
### Describe the bug and how to replicate it

Just install GrimAC and wait.

For additional information see:
https://github.com/retrooper/packetevents/issues/609

### Grim version

2.3.43

### Server version

Current: git-Purpur-2050 (MC: 1.20.1)*
Previous: git-Purpur-2023 (MC: 1.20.1)
* You are 12 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Plugins

ArmorStandTools, ChestShop, Citizens, FastAsyncWorldEdit, floodgate, GrimAC, HuskSync, Images, LuckPerms, PlotSquared, PrimeBooster, PrimeClans, PrimeCore, PrimeCrates, PrimeEssentials, PrimeField, PrimeHomes, PrimeJobs, PrimePerks, PrimePlotAdditions PrimeQuests, PrimeSettings, PrimeTitles, PrometheusExporter, ProtocolLib, spark, Vault

The Prime - plugins can be ignored, the PrimeCore sends fake list packets via ProtocolLib (But they do not contain a displayname)

**Comment by MWHunter** [comment]
PacketEvents issue, not a grim issue
