### ISSUE TITLE
Hitting forward + backwards movement at the same time on a boat.

### ISSUE THREAD

**Issue by 0-x-2-2** [GrimAnticheat/Grim#1166]
### Describe the false positive and how to replicate it

Get in a boat in liquid.
Hold forward and backward movement keys at the same time.
Simulation flag+dismount.

Grim log:
https://paste.grim.ac/Dwpaq

### Grim version

https://github.com/GrimAnticheat/Grim/tree/16f2e5427c2044a0cc616334f46a8b345e03f36e

### Server version

```
This server is running Paper version git-Paper-477 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 5c78e77)
```

### Plugins

```
Server Plugins (3):
Bukkit Plugins:
 - GrimAC, ViaVersion, WorldEdit
 ```

**Comment by 0-x-2-2** [comment]
The client version in the log is 1.20.2 but the same issue happens with any 1.20.x client in my testing and should be identical.

**Comment by 0-x-2-2** [comment]
Related?: https://github.com/GrimAnticheat/Grim/issues/981

**Comment by FirephoenixX02** [comment]
> Related?: https://github.com/GrimAnticheat/Grim/issues/981

Both issues share the same problem. Yours is just without ice, original issue states that the flags are not related to ice and it also flags in water. So your issue is likely just a duplicate.

**Comment by c0dingnoobi** [comment]
> So your issue is likely just a duplicate.

exactly,
this issue should be sage to close too

**Comment by 0-x-2-2** [comment]
See https://github.com/GrimAnticheat/Grim/issues/981
