### ISSUE TITLE
Hoverable Alerts

### ISSUE THREAD

**Issue by Hwaanx** [GrimAnticheat/Grim#1169]
### Feature description

This should definitely be included atleast in grim 3.0. Add extra information and also a click to tp button when you hover on alerts

**Comment by c0dingnoobi** [comment]
op is quite rough about the idea of the implementation
i would suggest:
- a hoverable chat component on the whole line
- a click command as op mentioned to use grim spectate (defaultly) to tp to that player (maybe a config option called 'override-spectate-command' which will let users use their own command from f.e vanish plugins)
- a layout config option to define the layout of that chatcomponent with color code and internal placeholder support
- an option within checks too add infos to that hover message which will get cleared on each check run 

just in case, if a pr is done, this list should give the person a clearer vision on how it should look like

**Comment by ghost** [comment]
> a click command as op mentioned to use grim spectate (defaultly) to tp to that player (maybe a config option called 'override-spectate-command' which will let users use their own command from f.e vanish plugins)

It'd be actually very useful. 
2 options; or grim implements an atual vanish method to the grim spectate command or the command executed should be configurable.

**Comment by FrancyPro** [comment]
Hi, these days I make the pull request, since I created them on my private fork of grim.

**Comment by FrancyPro** [comment]
Hi, I created the pull request with the new hover messages: https://github.com/GrimAnticheat/Grim/pull/1184

> > a click command as op mentioned to use grim spectate (defaultly) to tp to that player (maybe a config option called 'override-spectate-command' which will let users use their own command from f.e vanish plugins)
> 
> It'd be actually very useful. 2 options; or grim implements an atual vanish method to the grim spectate command or the command executed should be configurable.
