### ISSUE TITLE
1.20.2

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1170]
### Feature description

Yes very nice!

**Comment by c0dingnoobi** [comment]
before grim gets updated packetevents needs to so we gotta wait

**Comment by 0-x-2-2** [comment]
1.20.2 seems to work just as well as the other 1.20.x versions from my initial testing, grim just doesn't seem to recognize the version. https://github.com/retrooper/packetevents/pull/607

**Comment by ghost** [comment]
> 1.20.2 seems to work just as well as the other 1.20.x versions from my initial testing, grim just doesn't seem to recognize the version. [retrooper/packetevents#607](https://github.com/retrooper/packetevents/pull/607)

Try to login with 1.20.2 to a server running grim, it blows up, as packet events needs to be updated to 1.20.2, there were alot of under the hood changes.

**Comment by ghost** [comment]
Hey, any updates?

**Comment by c0dingnoobi** [comment]
> Hey, any updates?

well either way before we can update we need to wait until pe merges that pr

**Comment by ghost** [comment]
> > Hey, any updates?
> 
> well either way before we can update we need to wait until pe merges that pr

go time 😸

**Comment by Xylzlol** [comment]
soo when 1.20.2 support?

**Comment by Xylzlol** [comment]
anytime soon?

**Comment by AoElite** [comment]
Added initial 1.20.2 support (updated packetevents & ACF)
