### ISSUE TITLE
grim 100%Velocity

### ISSUE THREAD

**Issue by 26692** [GrimAnticheat/Grim#1172]

**Comment by Souipi** [comment]
Mhhhh we need more information i think.... ?

**Comment by c0dingnoobi** [comment]
> Mhhhh we need more information i think.... ?

got deleted to prevent ppl using it 
saved the code snippets so we can patch them (well edit histories exist too)

**Comment by z7087** [comment]
#1133

**Comment by c0dingnoobi** [comment]
yea currently waiting for him to test it using defines suggestion

**Comment by 0-x-2-2** [comment]
using latest version is enough for this

**Comment by Aspect-404** [comment]
> > Mhhhh we need more information i think.... ?
> 
> got deleted to prevent ppl using it saved the code snippets so we can patch them (well edit histories exist too)

uh I got news buddy...
![image](https://github.com/GrimAnticheat/Grim/assets/90273544/2030e364-00e5-4921-a958-cf3b726448eb)
have fun patching though!
