### ISSUE TITLE
grim Disabler

### ISSUE THREAD

**Issue by 26692** [GrimAnticheat/Grim#1173]

**Comment by z7087** [comment]
why they dont block you

**Comment by c0dingnoobi** [comment]
managed to make him delete these lol
working on patching them now

**Comment by Souipi** [comment]
Wtf is these issue ?

**Comment by 0-x-2-2** [comment]
this doesn't exactly look very special

**Comment by ghost** [comment]
> managed to make him delete these lol working on patching them now

it not really helpful disabler. And also how you guys suppose to patch it? Even if you guys patch it prob gonna flag legit sometimes.

**Comment by FluorideHistorian** [comment]
this doesn't really do much, you can already just write hacks to get around the post check anyways
