### ISSUE TITLE
Grim Noslow

### ISSUE THREAD

**Issue by 26692** [GrimAnticheat/Grim#1174]
### Describe the bypass and how to replicate it

            "grim" -> {
                    if (event.eventState == EventState.PRE) {
                        if (isUsingFood()) {
                            return
                        }
                    }
                    if (event.eventState == EventState.PRE && classProvider.isItemSword(mc.thePlayer!!.heldItem!!.item)) {
                        mc.netHandler.addToSendQueue(
                            classProvider.createCPacketPlayerDigging(
                                ICPacketPlayerDigging.WAction.RELEASE_USE_ITEM,
                                WBlockPos.ORIGIN, classProvider.getEnumFacing(EnumFacingType.DOWN)
                            )
                        )

                    }

                }

### Grim version

1.12.2

### Server version

1.12.2

### Plugins

grim

**Comment by ghost** [comment]
Same logic used here [1160](https://github.com/GrimAnticheat/Grim/issues/1160)

**Comment by MarkGG8181** [comment]
this is patched, there is a new method but I won't leak it since it is private
