### ISSUE TITLE
GrimAC Disable vertical boatFly check if two players sit in the boat

### ISSUE THREAD

**Issue by RpMGrut** [GrimAnticheat/Grim#1178]
### Describe the bypass and how to replicate it

GrimAC Disable vertical boatFly check if two players sit in the boat

![2023-10-01_22 36 48](https://github.com/GrimAnticheat/Grim/assets/128047676/1a5f893a-9d91-44cc-852c-9b20843efa6f)

### Grim version

last

### Server version

This server is running SSSpigot version SSSpigot2-1.16.5-20221115-b878191 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Plugins

Works independently of plugins

**Comment by Delyfsss** [comment]
works

**Comment by SamB440** [comment]
I can't reproduce this. Please try this on the latest commit, if it still works, provide better replication steps and client + server versions.
