### ISSUE TITLE
FastBreak-False Positive 1.20.1

### ISSUE THREAD

**Issue by Huge-mistake** [GrimAnticheat/Grim#1193]
### Describe the false positive and how to replicate it

When a player has Haste II and uses an Efficiency V netherite pickaxe, and stands on top of the stone while mining downwards, it triggers Grimac detaction.  FastBreak

### Grim version

2.3.46

### Server version

1.20.1     purpur-1.20.1-2062

### Plugins

Grimac,FastAsyncWorldEdit

**Comment by Huge-mistake** [comment]
When a player has Haste II and uses an Efficiency V Netherite Pickaxe, and stands on top of the stone while mining downwards, it triggers Grimac detaction.

**Comment by Huge-mistake** [comment]
When a player has Haste II and uses an Efficiency V netherite pickaxe, and stands on top of the stone while mining downwards, it triggers Grimac detaction. FastBreak
![{2D28D53F-EAFE-457a-B654-75FA1064B4A9}](https://github.com/GrimAnticheat/Grim/assets/137968615/92b07bd1-f0eb-4ace-91e4-54f18efa931d)
![{C21417D4-0BC7-45f4-938B-852852C4855E}](https://github.com/GrimAnticheat/Grim/assets/137968615/0c5484e3-8171-4d4d-bdb0-9839639d51ed)

**Comment by Huge-mistake** [comment]
![{4724A038-7D52-426e-882B-B6C2C917D3AF}](https://github.com/GrimAnticheat/Grim/assets/137968615/7bd7a227-7399-4a8d-9a26-d96f52adfb8f)
![{F380A641-AAE5-42a3-B642-FA51DB911DDE}](https://github.com/GrimAnticheat/Grim/assets/137968615/455a7d20-e0df-4aaa-a2e6-0960fab75269)
![f2e1746308cd9d83de1cc71fc8c98c6f](https://github.com/GrimAnticheat/Grim/assets/137968615/cfe1791c-965c-403c-9423-31a5795b966d)

**Comment by CatTeaA** [comment]
Can be confirmed

**Comment by Souipi** [comment]
I can confirm the false flag, i think it's because of the netherite pickaxe

**Comment by Souipi** [comment]
I tested on paper paper-1.20.1-196 with grim ( lastest action ) and spark.

**Comment by Huge-mistake** [comment]
Can someone fix this false positive?😭

**Comment by Huge-mistake** [comment]
@c0dingnoobi 
Can you help with this analysis?❤️

**Comment by c0dingnoobi** [comment]
investigating
