### ISSUE TITLE
NoSlow Bypass (duplicate)

### ISSUE THREAD

**Issue by ManInMyVan** [GrimAnticheat/Grim#1198]
### Describe the bypass and how to replicate it

*This does flag post but does not set you back*
*this is different than switchitem noslow (#1091)*

1. Install [NightX client](https://github.com/Aspw-w/NightX-Client)
2. Join a 1.8.8 (idk if this works on other versions) grim server (I used eu.loyisa.cn)
3. Set NoSlow's mode to "ValidSpoof"
4. Enable NoSlow
5. Use an item and walk around

### Grim version

2.3.46

### Server version

Tested on eu.loyisa.cn

### Plugins

Tested on eu.loyisa.cn

**Comment by z7087** [comment]
![image](https://github.com/GrimAnticheat/Grim/assets/75190047/6c2af908-a546-4b88-8776-2f9ba331531b)
why dont just use ncp mode

**Comment by c0dingnoobi** [comment]
switch item, dup #1091 (check if ur issue exists before opening a new one)

**Comment by ManInMyVan** [comment]
> why dont just use ncp mode

Didn't know it worked

> switch item, dup #1091

I thought it was different (~~the mentioned mode in 1091 doesn't seem to reuse the use in hand after switching (I could be wrong), because eu.loyisa.cn's scoreboard says I'm not blocking. With ValidSpoof it does say I'm blocking~~ I was wrong)

> check if ur issue exists before opening a new one

1091 was mentioned in the post but ok

**Comment by c0dingnoobi** [comment]
> 1091 was mentioned in the post but ok

oh, my apologies lmao. didnt see that one sorry
