### ISSUE TITLE
Riding a camel throws simulation check

### ISSUE THREAD

**Issue by RealDestroy** [GrimAnticheat/Grim#1203]
### Describe the false positive and how to replicate it

Player riding camel throws a simulation check

### Grim version

2.3.46

### Server version

paper 1.20.2 (git-paper-248)

### Plugins

Lots of custom plugins, one that summons a camel with a saddle which may be relavant?

**Comment by RealDestroy** [comment]
just walking is fine, the sprinting is what flags

**Comment by c0dingnoobi** [comment]
dup #1157 & #1165 adressed in #1165 
werent able to work on it the past few weeks, will try to finish in the upcoming days

**Comment by RealDestroy** [comment]
awesome ty

**Comment by RealDestroy** [comment]
Duplicate issue addressed in https://github.com/GrimAnticheat/Grim/pull/1165
