### ISSUE TITLE
Use the API instead of reflection

### ISSUE THREAD

**Issue by ZyloqX** [GrimAnticheat/Grim#1206]
### Stack trace

Bukkit will attempt to fix it this time for you, but may not be able to do this every time.
If you see this message after typing a command from a plugin, please report this to the plugin developer, they should use the api instead of relying on reflection (and doing it the wrong way).
[16:06:14 WARN]: Found inconsistent skull meta, this should normally not happen and is not a Bukkit / Spigot issue, but one from a plugin you are using.

### Grim version

2.3.46

### Server version

1.20.2

### Plugins

ajLeaderboards, ajParkour, CataMines, Citizens, *ClearAll, CombatPlus, CommandPanels, DailyRewards, DecentHolograms, DeluxeMenus
Duels, Essentials, EzSpawn, FastAsyncWorldEdit, floodgate, GadgetsMenu, Geyser-Spigot, GrimAC, *HealOnKill, LoginSecurity
LPC, LuckPerms, Multiverse-Core, Multiverse-Inventories, nAntiBot, PlaceholderAPI, PlayerKits, PlayerPoints, SkinsRestorer, TAB
 ViaBackwards, ViaVersion, WorldGuard

**Comment by SamB440** [comment]
This doesn't seem related to Grim, feel free to open a new issue with more detail if you can reproduce this on the latest version.
