### ISSUE TITLE
troubles with russian language

### ISSUE THREAD

**Issue by Cazawaka** [GrimAnticheat/Grim#1210]
### Describe the bug and how to replicate it

when im trying to check the alerts of anticheat im see this 
![cmd_nqHfYvnw2m](https://github.com/GrimAnticheat/Grim/assets/88434607/5af3cd85-8e7c-48d4-a1c4-076a15711976)
this trouble in game too

### Grim version

2.3.46

### Server version

CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### Plugins

GrimAC

**Comment by MWHunter** [comment]
Find the command line argument for 1.8 to use UTF-8.

**Comment by Cazawaka** [comment]
> Найдите аргумент командной строки для версии 1.8, чтобы использовать UTF-8.

But what about minecraft? And how to change language of AC in the game?

**Comment by MWHunter** [comment]
Add -Dfile.encoding=UTF8 as a startup flag for the server

**Comment by Cazawaka** [comment]
> Add -Dfile.encoding=UTF8 as a startup flag for the server

I wanna change language of AntiCheat in minecraft (russian ---> english)

**Comment by Cazawaka** [comment]
How to do this?
