### ISSUE TITLE
Transmission across worlds during sprints, simulation false positives

### ISSUE THREAD

**Issue by Huge-mistake** [GrimAnticheat/Grim#1211]
### Describe the false positive and how to replicate it

Transmission across worlds during sprints, simulation false positives

https://github.com/GrimAnticheat/Grim/assets/137968615/f4958477-e0b1-4eee-a078-c9a52c8afe44

### Grim version

grimac2.3.46

### Server version

Current: git-Purpur-2062 (MC: 1.20.1)*
* You are running the latest version

### Plugins

Grimac, AncientGates, LuckPerms

**Comment by Huge-mistake** [comment]
Can this false positive be fixed？😊
I'm not sure if it's the same issue
https://github.com/GrimAnticheat/Grim/issues/1086

**Comment by ManInMyVan** [comment]
Looks like #379

**Comment by SamB440** [comment]
Try https://github.com/SamB440/Grim/actions/runs/9259165691 (on a modern client at least, but welcome to test other versions)

Edit: wait, working on other versions

Edit 2: done

**Comment by CatTeaA** [comment]
> Try https://github.com/SamB440/Grim/actions/runs/9258547099 (on a modern client at least, but welcome to test other versions)
> 
> Edit: wait, working on other versions

I used this beta version for 1.20.1 and 1.20.4 and it worked
Grim 2.3.64 on 1.20.4 does not reproduce sprint stuttering
Grim 2.3.64 is on 1.20.1, which can reproduce sprint stuttering
Grim 2.3.62, on 1.20.4 and 1.20.1, it is possible to reproduce the cross-world sprint stutter
This beta version of yours, I used it on 1.20.4 and 1.20.1, and I couldn't reproduce the cross-world sprint stutter
effective
