### ISSUE TITLE
Flight bypass

### ISSUE THREAD

**Issue by Baxs1337** [GrimAnticheat/Grim#1229]
### Describe the bypass and how to replicate it

Enabled blink on Vape V4
Turn FakeLag on Dynamic ( max settings )
Bind fakelag, blink and flight to the same
Start flying

### Grim version

2.3.46

### Server version

Paper 1.8.9

### Plugins

Essentials, Grim, ( its an anticheat test server )

**Comment by MWHunter** [comment]
Banned for trolling.
