### ISSUE TITLE
Vpae Client Bypassing Grim reach check

### ISSUE THREAD

**Issue by fodded** [GrimAnticheat/Grim#1231]
### Describe the bypass and how to replicate it

Vape client using function BackTrack is bypassing Grim. It doesn't detect this at all. BackTrack is basically reach

### Grim version

The latest from the github

### Server version

1.8.8 paper

### Plugins

My custom + grimac

**Comment by Souipi** [comment]
i don't think BackTrack can't be detected. And imo that not a real " reach "

**Comment by overkidding** [comment]
> ### Describe the bypass and how to replicate it
> Vape client using function BackTrack is bypassing Grim. It doesn't detect this at all. BackTrack is basically reach
> 
> ### Grim version
> The latest from the github
> 
> ### Server version
> 1.8.8 paper
> 
> ### Plugins
> My custom + grimac

Settings of vape backtrack

**Comment by c0dingnoobi** [comment]
(vapes backtrack is invalid and flags reach)

**Comment by CuteistCat** [comment]
Backtrack is emulated lag so i dont think it can be patched without a lot of faslo positives. But im not a ac dev so im not sure

**Comment by ManInMyVan** [comment]
duplicate of #545
