### ISSUE TITLE
An error has occurred when running transactions for player

### ISSUE THREAD

**Issue by JuliCarles** [GrimAnticheat/Grim#1233]
### Stack trace

The error is displayed randomly on certain players of the server.
Stacktrace can be found at: [https://pastebin.com/J6TLJpuJ](https://pastebin.com/J6TLJpuJ)
This error isn't present in Grim 2.3.46.

### How to replicate it if known

Happens at random moments for certain players only, there are no specific steps to replicate.

### Grim version

Grim version 2.3.48

### Server version

Paper 1.8.8

### Plugins

Grim, ViaVersion, ProtocolLib.

**Comment by SamB440** [comment]
Well, it's related to my commit, but...

49 is not a valid slot in the player's inventory?

Probably easy enough to just add a check to see if the set slot is within bounds, but the server shouldn't be sending this as far as I can tell. I would like to see proper reproduction steps for this - I've ran my changes for over a month and never seen it.

Also examplePlayer1 seems odd?
