### ISSUE TITLE
Can I ask what version of Grimac supports protocollib version 4.8.0?

### ISSUE THREAD

**Issue by quocn9043** [GrimAnticheat/Grim#1235]
### Stack trace

https://paste.gg/ask

### Grim version

?

### Server version

?

### Plugins

?

**Comment by SamB440** [comment]
Why 4.8.0 specifically? The latest plib is 5.1.0 and works with 1.8+, just use that. Anyway I don't think there are any issues with Grim and plib, if you are experiencing errors you should fill out the bug report form properly.

**Comment by MWHunter** [comment]
GrimAC has never worked with ProtocolLib 4.8.0 due to ProtocolLib's injection being incompatible with PacketEvents 2.0's injection.

0.X supports ProtocolLib 4.8.0 - but these builds were never really used by anyone due to instability.
