### ISSUE TITLE
Timer disalber

### ISSUE THREAD

**Issue by MIYU5200** [GrimAnticheat/Grim#1241]
### Describe the bypass and how to replicate it
Use Rise Disalber
https://www.youtube.com/watch?v=qPAk1vUfs14

### Grim version

The latest from the github

### Server version

1.8.8

### Plugins

GrimAC

**Comment by SamB440** [comment]
Looks like a duplicate of #1105

**Comment by Hwaanx** [comment]
> Looks like a duplicate of #1105

#1105 is probably balance abuse but its fixed.

**Comment by SamB440** [comment]
It's basically the same though, all this does is massively delay transaction packets increasing the balance. Easy way to reproduce is just ping spoof transactions to 10000ms standing still for a while then turn on timer. 

This is a serious issue that needs fixing though. I was able to use 5x timer for 3-5s, you can use 2x for 10s+. However I am not sure how this can be fixed without flagging people who legitimately lag.

**Comment by z7087** [comment]
Is it feasible to reduce the value of max-transaction-time in the config.yml? Grim will kick out players who have timed out, but will not flag them.

**Comment by SamB440** [comment]
> Is it feasible to reduce the value of max-transaction-time in the config.yml? Grim will kick out players who have timed out, but will not flag them.

There are a lot of players with poor connections that will easily go above 10k ms during the join process, or at random points, but then go back to something like 500ms stable (crazy I know). So this won't really work for a lot of servers.

**Comment by SamB440** [comment]
I did some quick testing, it might be possible to use transaction ping to limit the balance.

Try changing:
https://github.com/GrimAnticheat/Grim/blob/2a534bfed442770731b1f8f80b55369d91c332ec/src/main/java/ac/grim/grimac/checks/impl/movement/TimerCheck.java#L74-L76

to:
```java
    public void doCheck(final PacketReceiveEvent event) {
        final double transactionPing = player.getTransactionPing() * 1e6;
        // Limit using transaction ping if over 1000ms
        double adjustedBalance = player.getTransactionPing() < 1000 
                ? timerBalanceRealTime 
                : timerBalanceRealTime + (transactionPing - clockDrift - 50e6);
        if (adjustedBalance > System.nanoTime()) {
            if (flag()) {
```

Tested with clumsy at 1000-2000ms and throttle 150ms 80% though I claim no responsibility if you experience issues because I've only looked at this for a few hours... at least this way it would only false for player's over 1k ping

**Comment by MWHunter** [comment]
The reason the check is programmed like this is mojang's code.  If the player's FPS lag spikes, they will process all transactions, then send 10 movements all at once.

**Comment by SamB440** [comment]
Should be mitigated by https://github.com/GrimAnticheat/Grim/commit/5fd8230884db404b4cebd6b6bd6c1e8bbbc3734b in my testing
