### ISSUE TITLE
NoSlowA by Riptide

### ISSUE THREAD

**Issue by GetSlained** [GrimAnticheat/Grim#1242]
A player complained about getting stuck while using the enchant riptide in water. 

The console told me this:

10.12 12:11:14 [Server] Server thread/[INFO] Grim » SusCat_ failed NoSlowA (Prediction) (x10) 
10.12 12:11:28 [Server] Server thread/[INFO] Grim » SusCat_ failed NoSlowA (Prediction) (x15) 
10.12 12:11:31 [Server] Server thread/[INFO] Grim » SusCat_ failed NoSlowA (Prediction) (x20) 
10.12 12:11:34 [Server] Server thread/[INFO] Grim » SusCat_ failed NoSlowA (Prediction) (x25) 
10.12 12:11:39 [Server] Server thread/[INFO] Grim » SusCat_ failed NoSlowA (Prediction) (x30) 

i have had a similar issue with NoKB getting activated when a player took damage in lava. I fixed the issue by changing the threshold to 0.1 . Didnt work with NoSlowA.

What do i do?

**Comment by SamB440** [comment]
Please fill out the false positive form next time, also try updating to the latest commit, there were fixes for lava movement that the Spigot version doesn't have.

**Comment by GetSlained** [comment]
lava movement isnt the issue.

The issue is when a player uses a trident with riptide in water.

**Comment by c0dingnoobi** [comment]
invalid issue, impossible to work on with these informations
we neither do know client version nor server version nor grim version 
i would suggest close this one and create a new issue with proper following of the issue preset

**Comment by SamB440** [comment]
NoSlow handling changed a lot recently. Feel free to open a new issue following the template if this still happens on the latest Grim.
