### ISSUE TITLE
trapdoor + blocks

### ISSUE THREAD

**Issue by ManInMyVan** [GrimAnticheat/Grim#1243]
### Describe the false positive and how to replicate it

1. build the following or similar setup (you can also do this with them placed on the top of the block)
![image](https://github.com/GrimAnticheat/Grim/assets/113963219/73fa9818-a75d-41e2-8173-3a1ca55f995f)
2. get blocks and jump onto the trapdoors while holding right click

https://paste.grim.ac/JkJZX

### Grim version

27397f9

### Server version

git-PaperSpigot-445

### Plugins

- grimac 2.3.48
- EssentialsX 2.20.1
- LuckPerms 5.4.108

**Comment by z7087** [comment]
1.20 clients can place block without sneaking on a iron trapdoor, and 1.12 clients seems cant

**Comment by ManInMyVan** [comment]
Also applies to cauldrons
