### ISSUE TITLE
bed false [duplicate]

### ISSUE THREAD

**Issue by ManInMyVan** [GrimAnticheat/Grim#1244]
### Describe the false positive and how to replicate it

Setup:
![setup](https://github.com/GrimAnticheat/Grim/assets/113963219/2110e1cf-ee58-4355-a001-ba41bd06fe06)
1. walk back into the iron bars so you are positioned like this:
![image](https://github.com/GrimAnticheat/Grim/assets/113963219/8da82d3f-bfda-4389-ba7a-182584b0e6bb)
2. sprint and then jump immediately after

https://paste.grim.ac/tWw2h

### Grim version

27397f9

### Server version

git-PaperSpigot-445

### Plugins

- grimac 2.3.48
- EssentialsX 2.20.1
- LuckPerms 5.4.108

**Comment by z7087** [comment]
Looks like a duplicate of https://github.com/GrimAnticheat/Grim/issues/760
