### ISSUE TITLE
water + jumping

### ISSUE THREAD

**Issue by ManInMyVan** [GrimAnticheat/Grim#1245]
### Describe the false positive and how to replicate it

Just holding right click holding a water bucket and holding jump

https://paste.grim.ac/kmF1X

### Grim version

27397f9

### Server version

git-PaperSpigot-445

### Plugins

- grimac 2.3.48
- EssentialsX 2.20.1
- LuckPerms 5.4.108

**Comment by c0dingnoobi** [comment]
dup #578

**Comment by ManInMyVan** [comment]
> dup #578

I have build perms (no worldguard)

**Comment by c0dingnoobi** [comment]
reproduceable with and without build perms (as you did yourself)
root of problem is jumping on water while removing it (or being removed by server when no build perm)
