### ISSUE TITLE
NoSlowB lags back when it shouldn't

### ISSUE THREAD

**Issue by ManInMyVan** [GrimAnticheat/Grim#1246]
When a player has `grim.nosetback`, the player will still get lagged back when flagging NoSlowB.

Server version: git-PaperSpigot-445
Grim version: 27397f9
Plugins:
- grimac 2.3.48
- EssentialsX 2.20.1
- LuckPerms 5.4.108

**Comment by SamB440** [comment]
This looks intentional because it cancels the movement packet

**Comment by c0dingnoobi** [comment]
working on making this (cancelling move packets) affected by grim.nosetback permission
