### ISSUE TITLE
failed BadPacketsE

### ISSUE THREAD

**Issue by gptlang** [GrimAnticheat/Grim#1247]
### Describe the false positive and how to replicate it

1. Run server with PaperMC 
2. Join with vanilla client on

### Grim version

grimac-2.3.46

### Server version

1.20.4

### Plugins

- AuthMe
- ProtocolLib
- Grim

**Comment by c0dingnoobi** [comment]
grim not comaptible yet for versions such as .3 and .4

**Comment by SamB440** [comment]
Feel free to open a new issue with proper reproduction steps if you can reproduce this on the latest Grim.
