### ISSUE TITLE
Regen bypass

### ISSUE THREAD

**Issue by KeppLex** [GrimAnticheat/Grim#1248]
### Describe the bypass and how to replicate it

I have no specific steps on reproducing this bypass.
It consists in using 1.17+ versions to bypass Regen sending packets and somehow abusing 1.17 extra packets.
This bypass is present in Exire client and was tested by myself, it can also be seen in videos [here](https://www.youtube.com/watch?v=FebS8UnfKHk)
Thank you.

### Grim version

Grim version 2.3.48 and latest [27397f9](https://github.com/GrimAnticheat/Grim/commit/27397f95e840e89141f5051038af95fad70377d2)

### Server version

Paper 1.8.8

### Plugins

Grim, ProtocolLib

**Comment by c0dingnoobi** [comment]
being worked on (might pr once i know how its done and how its preventable), seems like this is even an issue on vulcan

**Comment by 0-x-2-2** [comment]
The best way to fix this is to transform the 1.8 server but the second-best is to just not send the duplicate full move packets to the server in the first place if the server is 1.8. Vulcan does have more checks against this compared to Grim as far as I know.

**Comment by nullablepointer** [comment]
Grim does not support 1.8, as stated in #1122

**Comment by ManInMyVan** [comment]
> Grim does not support 1.8

"1.8-1.19" - repository description
