### ISSUE TITLE
NoSlowBypass

### ISSUE THREAD

**Issue by Cool114** [GrimAnticheat/Grim#1250]

**Comment by SamB440** [comment]
Update, you are on an outdated version even compared to the Spigot one, use the latest commit instead.

Looks like the same/similar as other issues already open as well.

**Comment by Yedeting** [comment]
> 更新，即使与 Spigot 版本相比，您也使用过时的版本，请改用最新的提交。
> 
> 看起来和其他已经悬而未决的问题相同/相似。

The latest version also has this issue. I only tested it in version 2.3.45

**Comment by Margele** [comment]
genshin impact

**Comment by Cool114** [comment]
> Update, you are on an outdated version even compared to the Spigot one, use the latest commit instead.
> 
> Looks like the same/similar as other issues already open as well.

The latest version and 2.3.45 both have these vulnerabilities, and I only tested them on 2.3.45
