### ISSUE TITLE
Negative Timer Falses

### ISSUE THREAD

**Issue by optimize-2** [GrimAnticheat/Grim#1251]
### Describe the false positive and how to replicate it

The negative timer check falses when players dragging their window or changing resource packs
Personally think the check makes no sense
Hackers can't gain advantages through a negative timer while other players may false this

### Grim version

latest

### Server version

1.8.8

### Plugins

Grim

**Comment by optimize-2** [comment]
scaling windows will also false negative timer

**Comment by SamB440** [comment]
I doubt negative timer will get "fixed" at least anytime soon, you should disable it if you don't like it, see https://github.com/GrimAnticheat/Grim/issues/1205#issuecomment-1793677921

**Comment by optimize-2** [comment]
Agree but I'm not the server owner.
The maintainers of the server I'm playing lack experience in anti-cheat configuration.
Let's keep this issue open as a false-positive though.

**Comment by AoElite** [comment]
I've made NegativeTimer experimental for now
