### ISSUE TITLE
Grimac 2.3.49,False positive FastBreak"axe"

### ISSUE THREAD

**Issue by CatTeaA** [GrimAnticheat/Grim#1253]
### Describe the false positive and how to replicate it

GRIMAC2.3.49 Use axe to chop down trees
2.3.48 does not have this problem

### Grim version

Grimac 2.3.49

### Server version

paper 1.20.1

### Plugins

Grimac 2.3.49

**Comment by CatTeaA** [comment]
I'm rolling back 2.3.48 for the time being, waiting for a fix

**Comment by SamB440** [comment]
Seems to be a PacketEvents issue with `MINEABLE_WITH_AXE` block tag, I will try and get this fixed.

Edit: Problem has been found, working on a PE fix

**Comment by SamB440** [comment]
Fixed as per https://github.com/retrooper/packetevents/pull/626, PE will need to put a new build out though I think before Grim can update to it.

**Comment by okunamayanad** [comment]
Geyser (2.2.0-SNAPSHOT, git-master-3292718) on a Velocity (3.2.0-SNAPSHOT, git-8dcc7ee3-b294) proxy with Floodgate installed on both proxy and backend servers, GrimAC v2.3.49 works fine on Purpur (MC: 1.20.2, git-Purpur-2092 ) for only Bedrock clients

**Comment by SamB440** [comment]
Fixed in 2.3.52, please try that

**Comment by CatTeaA** [comment]
> Fixed in 2.3.52, please try that

Tested, fixed😊

**Comment by CatTeaA** [comment]
Reappearing this issue in grimac-2.3.53 and 2.3.54,
I found that only the latest version on spigot is normal，https://www.spigotmc.org/resources/grim-anticheat.99923/

**Comment by SamB440** [comment]
The CI builds are not using the latest packetevents, it needs to be manually compiled (I am not sure how to make it use the latest commit myself).
