### ISSUE TITLE
Server crashes when I try to join, using 1.8.9 client.

### ISSUE THREAD

**Issue by Nihilanthyc** [GrimAnticheat/Grim#1256]
### Stack trace

https://mclo.gs/Uo95zZo#L572

### How to replicate it if known

Install the plugin
Try to join the server
Get the "Internal server error"
Server crashes.
![imagem_2023-12-17_200914887](https://github.com/GrimAnticheat/Grim/assets/89376030/e6dc0b75-da7c-40bc-9b5f-7a18bf5f6945)

### Grim version

2.3.49

### Server version

This server is running CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Error obtaining version information

### Plugins

VoidGen, nAntiBot, PlaceholderAPI, PerWorldPlugins, ServersNPC, Multiverse-Core, MVdWPlaceholderAPI, FastAsyncWorldEdit, Multiverse-Inventories, ViaVersion, JH_Shop, ViaBackwards, AntiUserSteal, ViaRewind, LuckPerms, WorldEdit, ProtocolLib, WorldGuard, SkinsRestorer, TAB, ServerListPlus, Vault, WorldGuardExtraFlags, WorldEditSelectionVisualizer, nLogin, SimpleScore, Skript, JH_Economy, VoidTeleportPlus, GrimAC, System, ArmorStandTools, Animatronics, HeadDatabase, aEventos, AtlasMaquinas, DecentHolograms

**Comment by Souipi** [comment]
And without grim you don't have the problem ?

**Comment by AoElite** [comment]
Not a grim issue
