### ISSUE TITLE
Error on 3000+ lines

### ISSUE THREAD

**Issue by StKillReal** [GrimAnticheat/Grim#1262]
### Stack trace

https://pastebin.com/3D5wPdeT

### How to replicate it if known

Start the server with the latest grim verstion

### Grim version

latest from spigot

### Server version

![image](https://github.com/GrimAnticheat/Grim/assets/60330193/3b25b9c7-7ea6-4db6-8f8b-65a36507271c)

### Plugins

![image](https://github.com/GrimAnticheat/Grim/assets/60330193/8193c765-d05b-4157-9beb-5eb29088f097)

**Comment by SamB440** [comment]
Seems like a plugin sending something dodgy with entity metadata, but either way this is a packetevents issue

**Comment by StKillReal** [comment]
Can resource pack create this issue?

**Comment by SamB440** [comment]
There is nothing related to resource packs in there. Something sent a weird text component part (probably display name?) in the metadata of an entity.

But you should make an issue on the packetevents repo instead, since it's not Grim's fault.

**Comment by StKillReal** [comment]
god damn, 340k lines of this error
![image](https://github.com/GrimAnticheat/Grim/assets/60330193/ce38bf3c-f81e-4cae-b7c4-1a57d0a0e3db)

**Comment by StKillReal** [comment]
is spigot version contains all this actions?

![image](https://github.com/GrimAnticheat/Grim/assets/60330193/bb6ef449-b943-4030-832f-4fd44a58e478)
![image](https://github.com/GrimAnticheat/Grim/assets/60330193/21c8bee2-5312-4ca5-8ed4-16fae37f19bb)

**Comment by SamB440** [comment]
It seems it does, yes.

But the update notes are wrong because packetevents hasn't published a new version yet, that version still has the fastbreak issue

**Comment by SamB440** [comment]
Should have been fixed by PacketEvents.
