### ISSUE TITLE
Failed to map the Packet ID 36 to a PacketType constant. Bound: CLIENT, Connection state: CONFIGURATION, Server version: 1.20.2

### ISSUE THREAD

**Issue by czychuuu** [GrimAnticheat/Grim#1263]
### Stack trace

https://pastebin.com/F7ku6bh6

### How to replicate it if known

join 1.20.2 server on 1.20.2 client

### Grim version

2.3.46

### Server version

Current: git-Purpur-2095 (MC: 1.20.2)*
* You are running the latest version

### Plugins

![image](https://github.com/GrimAnticheat/Grim/assets/60987404/61dd30ba-d1ce-4df4-abb0-83d555c5c977)

**Comment by SamB440** [comment]
Feel free to open a new issue if you can reproduce this on the latest Grim.
