### ISSUE TITLE
How to disable alerts in configs

### ISSUE THREAD

**Issue by DimaSergeew** [GrimAnticheat/Grim#1269]
### Feature description

I completely disabled alerts in the plugin configs, but continue to receive a message in the game chat, and I every time I have to go to the server to write the command /grim alerts, which is terribly uncomfortable
<img width="593" alt="image" src="https://github.com/GrimAnticheat/Grim/assets/75163645/c0481ded-cdea-4e3b-b72d-2332af87b7b8">

**Comment by ManInMyVan** [comment]
If you have luckperms you can set `grim.alerts.enable-on-join` to false
