### ISSUE TITLE
1.17+ nofall

### ISSUE THREAD

**Issue by z7087** [GrimAnticheat/Grim#1275]
### Describe the bypass and how to replicate it

```java
package cally72jhb.addon.modules.misc;

import meteordevelopment.meteorclient.events.world.TickEvent;
import meteordevelopment.meteorclient.systems.modules.Categories;
import meteordevelopment.meteorclient.systems.modules.Module;
import meteordevelopment.orbit.EventHandler;
import net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket;

// https://bugs.mojang.com/browse/MC-171969
// need 1.17+ client and 1.15-pre5+ server

public class GrimNoFall extends Module {

    public GrimNoFall() {
        super(Categories.Misc, "grim-nofall", "Disable fall damage on Grim servers.");
    }

    @EventHandler
    private void onPreTick(TickEvent.Pre event) {
        if (!mc.player.isOnGround() && mc.player.fallDistance > 1f) {
            mc.getNetworkHandler().sendPacket(new PlayerMoveC2SPacket.Full(mc.player.getX(), mc.player.getY() + 0.000000001, mc.player.getZ(), mc.player.getYaw(), mc.player.getPitch(), false));
            mc.player.onLanding();
        }
    }

}
```
Is there a way to check if the 1.17 duplicate packet is at a possible location?

### Grim version

2.3.48

### Server version

spigot 1.19.2

### Plugins

Grim, ViaVersion, ViaBackwards

**Comment by SamB440** [comment]
https://github.com/SamB440/Grim/commit/c57e4f17784d3f82a0e3b912b87aa28b3fddb4c6

Try this.

Edit: I think it can be changed to then send a USE_ITEM anyway, but I'll see if I can improve it further

**Comment by z7087** [comment]
I didn't test them, but they should work
```java
package cally72jhb.addon.modules.misc;

import meteordevelopment.meteorclient.events.world.TickEvent;
import meteordevelopment.meteorclient.systems.modules.Categories;
import meteordevelopment.meteorclient.systems.modules.Module;
import meteordevelopment.orbit.EventHandler;
import net.minecraft.item.ItemStack;
import net.minecraft.network.packet.c2s.play.HandSwingC2SPacket;
import net.minecraft.util.Hand;
import net.minecraft.util.math.Vec3d;

// https://bugs.mojang.com/browse/MC-171969
// need 1.17+ client and 1.15-pre5+ server

public class GrimNoFall extends Module {

    public GrimNoFall() {
        super(Categories.Misc, "grim-nofall", "Disable fall damage on Grim servers.");
    }

    @EventHandler
    private void onPreTick(TickEvent.Pre event) {
        if (mc.player != null && !mc.player.isOnGround() && mc.player.fallDistance > 2f) {
            for (Hand hand : Hand.values()) {
                ItemStack stack = mc.player.getStackInHand(hand);
                if (!stack.isEmpty()) {
                    if (mc.player.isUsingItem()) {
                        mc.interactionManager.stopUsingItem(mc.player);
                    }
                    Vec3d originVec = mc.player.getPos();
                    mc.player.setPosition(originVec.add(0.0, 1.0E-9, 0.0));
                    if (mc.interactionManager.interactItem(mc.player, hand).shouldSwingHand()) {
                        mc.getNetworkHandler().sendPacket(new HandSwingC2SPacket(hand));
                    }
                    if (mc.player.isUsingItem()) {
                        mc.interactionManager.stopUsingItem(mc.player);
                    }
                    mc.player.setPosition(originVec);
                    mc.player.onLanding();
                    break;
                }
            }
        }
    }

}
```

**Comment by SamB440** [comment]
https://github.com/SamB440/Grim/commit/d92ebb1ac65aefcc445ca64c0345d372025e1d4f

Make sure to try position change above 1e-7

**Comment by z7087** [comment]
https://github.com/SamB440/Grim/blob/feat/enforce-stupidity-use/src/main/java/ac/grim/grimac/events/packets/CheckManagerListener.java#L360 maybe can use it fly
a 1.17 duplicate packet with same position but different look is useful in using bucket

Can we get all possible velocities and deny impossible 1.17 duplicate packet? Like clientVelocity = 0,-1,0 then the player can't move up

**Comment by SamB440** [comment]
I don't see how you could use it to fly, I considered the possibility but as soon as you've gone more than 0.03 or 0.0002 blocks (1.18.2+) it's going to check you. If you illegally added velocity in the stupidity packet, you will be flagged.

Although it should probably use `lastClaimedPosition` to determine the velocity instead.

> Can we get all possible velocities and deny impossible 1.17 duplicate packet? Like clientVelocity = 0,-1,0 then the player can't move up

The problem is the player can move anywhere within the movement threshold with the stupidity packet, moving up is a possibility and legitimate.

**Comment by z7087** [comment]
> The problem is the player can move anywhere within the movement threshold with the stupidity packet, moving up is a possibility and legitimate.

I don't understand but ok...

My idea is when the player sends two different 1.17 packets in a row, do a move check with the rotation of the previous one and the position of the next one, and if those are same, deny the next one
if the player sends a normal flying packet and a 1.17 packet and their position is different, do a move check with the 1.17 packet's position and last rotation

**Comment by SamB440** [comment]
> I don't understand but ok...

When you move less than 0.03 (0.0002 on 1.18.2+) blocks a movement packet won't be sent to the server. But you can right click to send a duplicate packet which will update the current position on the server when it wouldn't usually be. You can move up within this threshold (though it is probably rare).

> My idea is when the player sends two different 1.17 packets in a row, do a move check with the rotation of the previous one and the position of the next one, and if those are same, deny the next one

The player can send infinite duplicate packets with the same rotation and position, you'd be punishing legitimate players by the sounds of it.

> if the player sends a normal flying packet and a 1.17 packet and their position is different, do a move check with the 1.17 packet's position and last rotation

The player can legitimately have a different position on the two packets, I think this will cause falses

Do you have a Discord? Since it's easier to discuss on there. Mine is cotander.

**Comment by z7087** [comment]
> The player can send infinite duplicate packets with the same rotation and position, you'd be punishing legitimate players by the sounds of it.

I think something might not happen to Vanilla when it receives duplicate duplicate packets...

> The player can legitimately have a different position on the two packets, I think this will cause falses

Then do another check and use the flagless one?

> Do you have a Discord? Since it's easier to discuss on there. Mine is cotander.

Mine is 7087z, I sent a request but my wifi bad

**Comment by MWHunter** [comment]
You can edit inbound packets to force stupidity to use the previous position.

The stupidity packet has the last tick position and the current tick look.  You can't prediction engine it.

**Comment by z7087** [comment]
If the player sends 2 stupidity packet(if their location are different) or sends a normal flying packet and a stupidity packet(if their position are different and no teleports between them), the player must ran 1+ tick and skipped it, so can we run checks on it with last rotation and next position after server can confirm the next one is a stupidity packet? (use https://github.com/SamB440/Grim/blob/feat/enforce-stupidity-use/src/main/java/ac/grim/grimac/events/packets/patch/EnforceUseItemStupidity.java to comfirm it)

**Comment by SamB440** [comment]
> You can edit inbound packets to force stupidity to use the previous position.
> 
> The stupidity packet has the last tick position and the current tick look. You can't prediction engine it.

Isn't that the equivalent to cancelling the packet though?

I know the packet was introduced to fix a "bucket desync" but does that require the position or just the player sending a move packet?

**Comment by MWHunter** [comment]
The new look is required to partially fix the bucket desync - but the position is useless.

**Comment by ghost** [comment]
> [SamB440@c57e4f1](https://github.com/SamB440/Grim/commit/c57e4f17784d3f82a0e3b912b87aa28b3fddb4c6)
> 
> Try this.
> 
> Edit: I think it can be changed to then send a USE_ITEM anyway, but I'll see if I can improve it further

Correct me if I'm wrong, but this will be easy bypass if I just send one fake pong packet right? I mean it the same thing with the old post disabler.

**Comment by SamB440** [comment]
I and z7087 are working on stupidity improvements. If you want to fix this simply, do what mw said. However it is quite difficult to enforce stupidity because of viaversion.

**Comment by ghost** [comment]
> 

> I and z7087 are working on stupidity improvements. If you want to fix this simply, do what mw said. However it is quite difficult to enforce stupidity because of viaversion.

good luck I guess. looking at the current one there is plenty of ways I can bypass it so u prob have to find a better solution to it.

**Comment by z7087** [comment]
you can try bypass this on 1.9+ server and client (with stupidity), i didnt make check for 1.8- server cause viaversion eats use_item packet
https://github.com/z7087/Grim/actions/runs/7421142414

**Comment by ghost** [comment]
Sure I will give it a try then
