### ISSUE TITLE
warns if player tp very fast (between worlds)

### ISSUE THREAD

**Issue by SL-69** [GrimAnticheat/Grim#1276]
### Stack trace

https://logpaste.com/CPUkfJvF

### How to replicate it if known

1. server paper 1.12.2 
2. 1 account enter in worlds (world, nether, end) and write  "/tphere"  for 2 account
3. warns if actions very fast

### Grim version

2.3.49 (i download latest version)

### Server version

[21:20:50 INFO]: This server is running Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[21:20:50 INFO]: Unknown version

### Plugins

AdvancedBan, ajLeaderboards, ajParkour, AntiChatManager, antiRedstoneClock, ArmorStandTools, BannerMaker, BKCommonLib, Chatty, ChestCommands, ClearLag, CombatTagPlus, CrazyAuctions, DecentHolograms, DiscordSRV, EasySetSpawn, Essentials, FastAsyncWorldEdit, FunctionalClans, GrimAC, IllegalStack, InteractiveChat, InteractiveChatDiscordSrvAddon, IRandomTeleport, LightCleaner, Log4jFix, LoginSecurity, LuckPerms, MoneyFromMobs, NBTAPI, Orebfuscator, PlaceholderAPI, PlayerReport, PlugMan, PlugManX, ProtectionStones, ProtocolLib, SimplePortals, SimpleRename, SkinsRestorer, TAB, UltimateServerProtector, Vault, WorldEdit, WorldGuard, ZNPCsPlus

**Comment by SamB440** [comment]
Your paste seems to have expired. Feel free to open a new issue if you can reproduce this on the latest Grim.
