### ISSUE TITLE
Server Panel Error 

### ISSUE THREAD

**Issue by xPoyraz** [GrimAnticheat/Grim#1277]
### Stack trace

https://paste.gg/p/anonymous/c321a2c48b6143c2af5816a677009609

### Grim version

2.3.50

### Server version

Purpur 2111 - 1.20.4

### Plugins

None

**Comment by SamB440** [comment]
https://github.com/retrooper/packetevents/issues/637

Downgrade your server build version until a build with a packetevents fix is published

**Comment by SamB440** [comment]
Fixed in 2.3.52, please try that
