### ISSUE TITLE
Entity push speed/strafe in 1.8 server

### ISSUE THREAD

**Issue by z7087** [GrimAnticheat/Grim#1278]
### Describe the bypass and how to replicate it

Place many boats on ground and use strafe on them, you will get less flags

1.11+ vanilla clients in 1.8 server do not appear to be subject to collisions from other entities

Can we disable entity push handler when the maxEntityCramming gamerule = 0? Players won't get push by other player in this context.

### Grim version

2.3.48

### Server version

Paper 1.8.8

### Plugins

eu.loyisa.cn

**Comment by SWIMHUBISWIMMING** [comment]
KILL YOURSELFF!!!!!!

**Comment by z7087** [comment]
you can still use it in 1.11+ server and why you dont kill everyone working in anticheat

**Comment by z7087** [comment]
I didn't find how server controls client's entity collision, but I can't get push in 1.8 server with any client

**Comment by z7087** [comment]
https://github.com/z7087/Grim/tree/pushspeed
should patched it on <=1.8 servers with >=1.9 clients
