### ISSUE TITLE
Reappearing this issue in grimac-2.3.53 and 2.3.54, False positive FastBreak"axe"

### ISSUE THREAD

**Issue by CatTeaA** [GrimAnticheat/Grim#1290]
Reappearing this issue in grimac-2.3.53 and 2.3.54,
I found that only the latest version on spigot is normal，https://www.spigotmc.org/resources/grim-anticheat.99923/

_Originally posted by @BangXi in https://github.com/GrimAnticheat/Grim/issues/1253#issuecomment-1879784633_

**Comment by AoElite** [comment]
@BangXi Ensure you are using latest packetevents when compiling or use the latest from here https://hangar.papermc.io/GrimAnticheat/GrimAnticheat/versions
