### ISSUE TITLE
incompatibility with skinrestorer

### ISSUE THREAD

**Issue by Sneyzi** [GrimAnticheat/Grim#1294]
### Describe the bug and how to replicate it

Bug when player change skin /skin [name] on spawn (island several blocks high)

https://youtu.be/vSfi2A5nBHw
![2024-01-09_22 37 51](https://github.com/GrimAnticheat/Grim/assets/30902875/875bef09-ce09-4f45-baea-6379385d03b7)

### Grim version

2.3.54

### Server version

paper 1.12.2

### Plugins

SkinsRestorer (bungee) 15.0.4
Grim

**Comment by SamB440** [comment]
It is very likely this is caused by SR being on the proxy and sending packets that Grim can't see. Feel free to reopen a new issue if this is not the case with reproduction steps on the latest version.
