### ISSUE TITLE
Noslow 1.16.5 bypass (block, eat, bow)

### ISSUE THREAD

**Issue by DanilGnedin** [GrimAnticheat/Grim#1302]
### Describe the bypass and how to replicate it

1.Use bypass client.
2.set version 1.15+ and this noslow bypass grim.
Fix this noslow please.
Video:
https://www.youtube.com/watch?v=9HpBCtfYbJM

### Grim version

grim version: 2.3.54

### Server version

This server is running Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Previous version: git-Paper-245 (MC: 1.14.4)
Unknown version

### Plugins

Plugins (4): GrimAC, LuckPerms, ProtocolLib, ViaVersion

**Comment by ManInMyVan** [comment]
are you able to replicate this on #1623? ([pre-built jar](https://github.com/ManInMyVan/Grim/actions/runs/10153397633/artifacts/1753208952))

**Comment by DanilGnedin** [comment]
um i test last version grim but item can unsync of server( if you eat second and next (no every) item).And i testing noslows and for some 1 vl flag. And at first (unsync) related to packet events PacketType.Play.Client.USE_ITEM because its not always sent.for example sometimes send PacketType.Play.Client.PLAYER_BLOCK_PLACEMENT but there are times when the grim cannot do analyze or there are no incoming packets.
