### ISSUE TITLE
Invincibility issue

### ISSUE THREAD

**Issue by JuliCarles** [GrimAnticheat/Grim#1306]
### Describe the bug and how to replicate it

Related to #1139 which was closed due to lack of information.

Sometimes one player is invincible to hand-on-hand pvp (excluding arrows) and the other player automatically wins because of it. The problem can be resolved by teleporting the player to spawn, as the affected player becomes untracked by others.

Upon analyzing the `PlayInUseEntity` packet, we found out that Grim cancels the packet, leading to damage cancellation. The suspected cause is the Reach check in Grim at:
https://github.com/GrimAnticheat/Grim/blob/0a36d3e92ebfe9a6cc6f28e003b8d9787df16f9c/src/main/java/ac/grim/grimac/checks/impl/combat/Reach.java#L75

This indicates that the packet is being canceled because Grim removes the entity from the `player.compensatedEntities.entityMap` but not from the `player.compensatedEntities.serverPositionsMap`. If the player has the entity removed from the `serverPositionsMap` then the problem doesn't happen at all.

Some observations:

- This issue only happens in fast-paced game modes with quick teleports between worlds and distant chunks, leading to rapid player tracking changes.
- The `serverPositionsMap` is not removed in the real tick, unlike the `entityMap`, potentially contributing to the bug's occurrence. Although I'm not so sure about the exact role of the `serverPositionsMap`.
- When changing worlds, the `serverPositionsMap` is not cleared according to Grim's source, though it's also unclear if this is the root cause.

To address this, we implemented a temporary solution, we manually remove the entity from `serverPositionsMap` if it exists in `serverPositionsMap` but not in `entityMap`. However, we acknowledge that this might not be the most elegant fix, so we wonder if there's a better solution on Grim's end.

### Grim version

[0a36d3e](https://github.com/GrimAnticheat/Grim/commit/0a36d3e92ebfe9a6cc6f28e003b8d9787df16f9c)

### Server version

Spigot 1.8.8

### Plugins

Grim
ProtocolLib
ViaVersion
Custom Core

**Comment by z7087** [comment]
Does your server or plugins send custom ping or window-confirmation packets?
https://github.com/GrimAnticheat/Grim/blob/0a36d3e92ebfe9a6cc6f28e003b8d9787df16f9c/src/main/java/ac/grim/grimac/events/packets/PacketEntityReplication.java#L78-L80
Seems PacketEntityReplication doesn't check if that packet was send by Grim
Not sure if that causes by this, but atleast a problem
If client and server version <=1.16.5, player can click an inventory to make server send a transaction
and if the server sends packet like this the entity can be removed in entityMap wrongly: despawn entity -> transaction that not sent by Grim -> spawn that entity

**Comment by JuliCarles** [comment]
> Does your server or plugins send custom ping or window-confirmation packets?

Nope

**Comment by MWHunter** [comment]
I would blame
https://github.com/GrimAnticheat/Grim/blob/0a36d3e92ebfe9a6cc6f28e003b8d9787df16f9c/src/main/java/ac/grim/grimac/utils/latency/LatencyUtils.java#L20

for weird race conditions like this.  This method runs the task sometime in the player's channel later.  This later may be processed AFTER an incoming ping packet, for example.  This idea is supported by poking around for a few minutes in the sources though, not by any real testing.

edit: The fix is only running this method if we aren't on the player's netty thread... otherwise just run the runnable immediately.

**Comment by AoElite** [comment]
@JuliCarles Check if commit d13351f7c097035626fee96c9efa669032a7bd2b fixes your issue.

**Comment by JuliCarles** [comment]
> Check if commit [d13351f](https://github.com/GrimAnticheat/Grim/commit/d13351f7c097035626fee96c9efa669032a7bd2b) fixes your issue.

Unfortunately, it doesn't, the `serverPositionsMap` still has the entity in it (and the `entityMap` doesn't) even after the latest commit, which causes the damage to get canceled.

**Comment by AoElite** [comment]
@JuliCarles Try commit 70f6ea08064e50db799548e11f49830259966b1e

**Comment by JuliCarles** [comment]
> Try commit [70f6ea0](https://github.com/GrimAnticheat/Grim/commit/70f6ea08064e50db799548e11f49830259966b1e)

The issue continues. Take into account that this doesn't exclusively happen on world change, it can happen in mid-match with just teleports.

**Comment by AoElite** [comment]
@JuliCarles I'm not sure how that's happening. https://github.com/GrimAnticheat/Grim/blob/70f6ea08064e50db799548e11f49830259966b1e/src/main/java/ac/grim/grimac/events/packets/PacketEntityReplication.java#L295
The handling looks like it's implemented correctly. I'll have to look into it a bit more.

**Comment by AoElite** [comment]
@JuliCarles You can try 60cc4d7faab0a460caa4eac6ab772a4f9276c6d7. This might not fix the issue but worth a try. If that doesn't resolve it then try modifying https://github.com/GrimAnticheat/Grim/blob/60cc4d7faab0a460caa4eac6ab772a4f9276c6d7/src/main/java/ac/grim/grimac/events/packets/PacketEntityReplication.java#L429 to `player.latencyUtils.addRealTimeTask(player.lastTransactionSent.get() + 1` and see if that fixes it.

**Comment by ghost** [comment]
@AoElite hes the owner of universocraft and he doesnt even know what a transaction is, universocraft is using ncp + vulcan + grim, probbly this is the issue.

**Comment by AoElite** [comment]
The last commit I made may fix it. Vulcan sends its own transactions that could interfere with Grim's handling of entities but I resolved that in the last commit.

**Comment by ghost** [comment]
> The last commit I made may fix it. Vulcan sends its own transactions that could interfere with Grim's handling of entities but I resolved that in the last commit.

![image](https://github.com/GrimAnticheat/Grim/assets/143160235/1612f010-f57c-4d70-9ba5-66f800e7a787)
probbly is one of this plugins but anyways the "invincibility" i think he mean regen

**Comment by JuliCarles** [comment]
> is using ncp + vulcan + grim.

Not for the sake of this test, although you are clearly just trolling.

> i think he mean regen

Also no.

> You can try [60cc4d7](https://github.com/GrimAnticheat/Grim/commit/60cc4d7faab0a460caa4eac6ab772a4f9276c6d7).

That seems to have resolved the issue. I wonder if this has something to do with LPX sending custom ping or window confirmation packets? Anyway, cheers @AoElite, thanks.

**Comment by AoElite** [comment]
Yes, other plugins transactions could interfer with the entity handling. So now it ensures it's grim that sent the transaction.

**Comment by ghost** [comment]
> > is using ncp + vulcan + grim.
> 
> Not for the sake of this test, although you are clearly just trolling.
> 
> > i think he mean regen
> 
> Also no.
> 
> > You can try [60cc4d7](https://github.com/GrimAnticheat/Grim/commit/60cc4d7faab0a460caa4eac6ab772a4f9276c6d7).
> 
> That seems to have resolved the issue. I wonder if this has something to do with LPX sending custom ping or window confirmation packets? Anyway, cheers @AoElite, thanks.

sir you can see the cap with all the universo sk plugins same with bw. The pluginfinder doest lie!

**Comment by z7087** [comment]
> > Does your server or plugins send custom ping or window-confirmation packets?
> 
> Nope

:?

**Comment by ghost** [comment]
> > > Does your server or plugins send custom ping or window-confirmation packets?
> > 
> > 
> > Nope
> 
> :?

he doesnt know anything abt window-confirmation and related things also tells me "I am trolling" when i send a pic with all the plugins they use

**Comment by AoElite** [comment]
I don't see how this is relevant here. Talk about this somewhere else.
