### ISSUE TITLE
0Vl Ground Rotation

### ISSUE THREAD

**Issue by LangYa466** [GrimAnticheat/Grim#1307]
### Describe the bypass and how to replicate it

Describe the bypass and how to replicate it
`    public static float[] getGrimRotations(EntityLivingBase target) {
        if (target == null) {
            return null;
        }

        Minecraft mc = Minecraft.getMinecraft();
        AxisAlignedBB bb = target.getEntityBoundingBox();
        double x = MathHelper.clamp(mc.player.posX, bb.minX, bb.maxX) + new java.util.Random().nextDouble() * 0.4 - 0.2;
        double y = MathHelper.clamp(mc.player.posY + mc.player.getEyeHeight(), bb.minY, bb.maxY) +  new java.util.Random().nextDouble() * 0.4 - 0.2;
        double z = MathHelper.clamp(mc.player.posZ, bb.minZ, bb.maxZ) + new java.util.Random().nextDouble() * 0.4 - 0.2;
        double xSize = x - mc.player.posX;
        double ySize = y - (mc.player.posY + mc.player.getEyeHeight());
        double zSize = z - mc.player.posZ;
        double theta = MathHelper.sqrt(xSize * xSize + zSize * zSize);
        float yaw = (float) ((Math.atan2(zSize, xSize) * 180 / Math.PI) - 90);
        float pitch = (float) (-(Math.atan2(ySize, theta) * 180 / Math.PI));
        return new float[]{mc.player.rotationYaw + MathHelper.wrapDegrees(yaw - mc.player.rotationYaw), mc.player.rotationPitch + MathHelper.wrapDegrees(pitch - mc.player.rotationPitch)};
    }`

### Grim version

eu.loyisa.cn

### Server version

eu.loyisa.cn

### Plugins

eu.loyisa.cn

**Comment by z7087** [comment]
?

**Comment by SamB440** [comment]
What does this even do?
