### ISSUE TITLE
NoSlow

### ISSUE THREAD

**Issue by LangYa466** [GrimAnticheat/Grim#1312]
### Describe the bypass and how to replicate it

There is no slowdown, just send 2 C09 SwitchItems in the MotionPre Event, and then send a TryUseItem in the MotionPost time to use the item to bypass

### Grim version

eu.loyisa.cn

### Server version

eu.loyisa.cn

### Plugins

eu.loyisa.cn

**Comment by ManInMyVan** [comment]
Duplicate of #1091
