### ISSUE TITLE
Grim Telly

### ISSUE THREAD

**Issue by LangYa466** [GrimAnticheat/Grim#1314]
### Describe the bypass and how to replicate it

https://github.com/CCBlueX/LiquidBounce/blob/nextgen/src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/world/scaffold/ModuleScaffold.kt

Here's Liquidbounce's code for his Scaffold Mode Telly to bypass New Grim

### Grim version

eu.loyisa.cn

### Server version

eu.loyisa.cn

### Plugins

eu.loyisa.cn

**Comment by ManInMyVan** [comment]
Unlikely to be patched, see https://github.com/GrimAnticheat/Grim/issues/877#issuecomment-1732335335
