### ISSUE TITLE
1.20.4 InstantEat

### ISSUE THREAD

**Issue by LangYa466** [GrimAnticheat/Grim#1315]
### Describe the bypass and how to replicate it

https://github.com/CCBlueX/LiquidBounce/blob/nextgen/src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/player/ModuleFastUse.kt
Here's Liquidbounce's code for his InstantEat to bypass New Grim

### Grim version

eu.loyisa.cn

### Server version

eu.loyisa.cn

### Plugins

eu.loyisa.cn

**Comment by z7087** [comment]
https://github.com/GrimAnticheat/Grim/pull/1303
