### ISSUE TITLE
Grim 1.20.4 Full Velocity

### ISSUE THREAD

**Issue by LangYa466** [GrimAnticheat/Grim#1316]
### Describe the bypass and how to replicate it

https://github.com/CCBlueX/LiquidBounce/blob/nextgen/src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/combat/ModuleVelocity.kt
Here's Liquidbounce's code for his Velocity Mode Grim to bypass New Grim

### Grim version

eu.loyisa.cn

### Server version

eu.loyisa.cn

### Plugins

eu.loyisa.cn

**Comment by z7087** [comment]
https://github.com/GrimAnticheat/Grim/pull/1303

**Comment by ManInMyVan** [comment]
dupe #1133, mentioned on [L276](https://github.com/CCBlueX/LiquidBounce/blob/nextgen/src%2Fmain%2Fkotlin%2Fnet%2Fccbluex%2Fliquidbounce%2Ffeatures%2Fmodule%2Fmodules%2Fcombat%2FModuleVelocity.kt#L276)
