### ISSUE TITLE
Imitation of Legit Player Landing Water Nofall

### ISSUE THREAD

**Issue by LangYa466** [GrimAnticheat/Grim#1318]
### Describe the bypass and how to replicate it

https://github.com/CCBlueX/LiquidBounce/blob/nextgen/src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/player/nofall/modes/MLG.kt
Imitation of Legit Player Landing Water Nofall
Here's Liquidbounce's code for his Nofall Mode MLG to bypass New Grim

### Grim version

eu.loyisa.cn

### Server version

eu.loyisa.cn

### Plugins

eu.loyisa.cn

**Comment by ManInMyVan** [comment]
Unlikely to be patched, see https://github.com/GrimAnticheat/Grim/issues/877#issuecomment-1732335335
