### ISSUE TITLE
Aimbot

### ISSUE THREAD

**Issue by LangYa466** [GrimAnticheat/Grim#1319]
### Describe the bypass and how to replicate it

HackAimbot that mimics Legit Player Aim
https://github.com/CCBlueX/LiquidBounce/blob/3b6f8c1068255efc795f1dac32265c4e2b5ff42e/src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/combat/ModuleAimbot.kt
Here's the code for Liquidbounce

### Grim version

eu.loyisa.cn

### Server version

eu.loyisa.cn

### Plugins

eu.loyisa.cn

**Comment by ManInMyVan** [comment]
Duplicate of #1236
