### ISSUE TITLE
ESP bypass

### ISSUE THREAD

**Issue by Legit6034** [GrimAnticheat/Grim#1325]
### Describe the bypass and how to replicate it

New Grim ESP Bypass,here are codehttps://github.com/CCBlueX/LiquidBounce/blob/nextgen/src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/render/ModuleESP.kt

### Grim version

loyisa.cn

### Server version

loyisa.cn

### Plugins

GrimAC

**Comment by Nel1yMinecraft** [comment]
Fxxk you monther

**Comment by LangYa466** [comment]
fxxk you mom

**Comment by LangYa466** [comment]
Because I shared my issues in a Chinese chat on Tencent QQ, they all came to scold me

**Comment by Zamx114514** [comment]
sb

**Comment by ManInMyVan** [comment]
Impossible to detect, see https://github.com/GrimAnticheat/Grim/issues/1298#issuecomment-1890837160

**Comment by Zamx114514** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月20日(星期六) 下午3:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [GrimAnticheat/Grim] ESP bypass (Issue #1325)





 
Impossible to detect, see #1298 (comment)
