### ISSUE TITLE
Derp Bypass

### ISSUE THREAD

**Issue by Legit6034** [GrimAnticheat/Grim#1326]
### Describe the bypass and how to replicate it

Liquidbounce Derp bypass Grimac

https://github.com/CCBlueX/LiquidBounce/blob/nextgen/src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/fun/ModuleDerp.kt

### Grim version

loyisa

### Server version

loyisa

### Plugins

Grimac

**Comment by LangYa466** [comment]
This one has long been fixed
