### ISSUE TITLE
Bamboo farm hoppers ghost items and won't let them to be taken out; Grim » aquatuba failed CrashD (x20) clickType=0 button=0

### ISSUE THREAD

**Issue by lethargistic** [GrimAnticheat/Grim#1334]
### Describe the false positive and how to replicate it

Step 1: Make a big bamboo farm from a Shulkercraft tutorial, the hoppers are constantly full.
Step 2: After trying to take something from the hoppers themselves (not the chests) items appear in my inventory until I close it
and this are the logs:
Grim » aquatuba failed CrashD (x20) clickType=0 button=0

Both the player and I are using fabric with no hacks so this is definitely a false positive. I imagine it might be bad for some uses where you have to take out the items from the hoppers not just chests although they retain their function so low prio.

### Grim version

grimac-2.3.52.jar

### Server version

git-Purpur-2119 (MC-1.20.4)

### Plugins

AdvancedBan, Authy, BlueMap, CoreProtect, DiscordSRV, GrimAC, floodgate, Geyser, LuckPerms, SkinsRestorer, spark, UltimateAutoRestart, WorldEdit

**Comment by SamB440** [comment]
Update to 2.3.54.

**Comment by AoElite** [comment]
Update grim
