### ISSUE TITLE
gribac boguses the console

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1337]
### Stack trace

https://paste.gg/p/threefusii/fc0ab34de8d243818dabbaf87a4df23f (two attached files - two different errors)

### How to replicate it if known

- download latest (1.20.4-b393) paper and latest (60cc4d7) grim
- join it with 1.20.4 client
- grimac spams the console

if it doesn't spam restart the server and try again, two or three restarts is enough

### Grim version

60cc4d7

### Server version

paper 1.20.4-b393

### Plugins

grim only

**Comment by Alluseri** [comment]
congratulations on issue 1337

**Comment by AoElite** [comment]
PacketEvents issue, can be fixed by recompiling with latest PacketEvents or you can wait for the next build.
