### ISSUE TITLE
PositionPlace triggering for "fire" block

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1338]
### Describe the false positive and how to replicate it

I think this is caused by 70005cfb0229e0954fd9925192a5ff9902172fea, since this has only come up since updating. Seeing alot of positionplace flags for weird stuff like "fire" and "stone_button". I could be wrong though.

### Grim version

2024c11d16429a20faebef5a54e461cb11a37db6

### Server version

paper 1.20.4

### Plugins

grimAC

**Comment by AoElite** [comment]
@ThrowerWay yea you're probably right, will be fixed next build

**Comment by z7087** [comment]
button false exists before that commit and now can trigger with empty hands https://github.com/GrimAnticheat/Grim/issues/1090

**Comment by z7087** [comment]
What is your client version? I can't replicate false on fire on Spigot 1.20.2 and 1.20.2 client

**Comment by SamB440** [comment]
Buttons probably false due to lack of hitbox data, I did implement button hitbox in #1238

Edit: Fire doesn't have it either

**Comment by SamB440** [comment]
Fixed I think, fire hitbox was added.
