### ISSUE TITLE
Kill Aura while shield is up (no flags)

### ISSUE THREAD

**Issue by RealDestroy** [GrimAnticheat/Grim#1340]
### Describe the bypass and how to replicate it

Enable kill aura, without rotation, also know as triggerbot
Make it hit through your shield so that you can block and hit at the same time

### Grim version

2.3.55

### Server version

latest paper build, I tested on most paper builds 1.20.2 to 1.20.4, have not tested earlier builds

### Plugins

not relevant, works regardless of plugins

**Comment by z7087** [comment]
https://github.com/GrimAnticheat/Grim/issues/1160

**Comment by SamB440** [comment]
Fixed by #1436
