### ISSUE TITLE
Configuration for setbackvl is not working

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1345]
### Stack trace

.

### How to replicate it if known

TimerA:
  setbackvl: 100
 If I use the timer, I get an instant teleport  with x1 instead x100

### Grim version

grimac-2.3.55.jar

### Server version

Dionysus 1.12.2

### Plugins

[10:24:31 INFO]: Plugins (2): GrimAC, LuckPerms

**Comment by AoElite** [comment]
Fixed by 107942dc7f7ea8c52a581a4b5117397bfac24431
