### ISSUE TITLE
player triggered BadPacketsN

### ISSUE THREAD

**Issue by hseermc** [GrimAnticheat/Grim#1346]
### Describe the false positive and how to replicate it

1.Use MCC(minecraft console client) to enter a server with Grim Anticheat
2.An alert appears
But when I got into the server I didn't do anything,I don't know if it's because of mcc or Grim Anticheat.
(You can search "MCCTeam/Minecraft-Console-Client" on github to learn more)

### Grim version

grim version 2.3.55

### Server version

This server is running Leaves version git-Leaves-"f010a0c" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: f010a0c)

### Plugins

 Bukkit Plugins:
  - BetterReactor, BetterRTP, *ChineseName, Citizens, CMILib, CrazyAuctionsPlus, CrossplatForms, CrystamaeHistoria, DeluxeMenus, DynaTech
 eco, EcoEnchants, EcoPower, ElectricSpawners, ElementManipulation, Essentials, EssentialsSpawn, ExoticGarden, ExtraGear, FastMachines
 floodgate, Floodgate-Skript, FluffyMachines, FNAmplifications, Galactifun, Gastronomicon, GeneticChickengineering, Geyser-Spigot, GlobalWarming, GrimAC
 GroupManager, GSit, GuizhanLibPlugin, InfiniteScoreboard, InfinityExpansion, InteractionVisualizer, LegendaryGuild, libreforge, LiteAnnouncer, LiteItemShow
  LiteSignIn, LobbyGames, mcMMO, MiniMOTD, Multiverse-Core, Multiverse-NetherPortals, NekoMaid, Networks, PlaceholderAPI, PlayerTitle
 PrivateStorage, ProtocolLib, QuickShop, QuickShopForm, Residence, ResidenceForm, *SGLogin, SimpleTpa, SimpleUtils, SkinsRestorer
 Skript, Slimefun, SlimeGlue, SlimeTinker, SoulJars, *SpawnPlugin, Supreme, Tpa, TranscEndence, TrChat
 UltimateGenerators, UltraSetHome, Uniporter, Vault, ViaBackwards, ViaVersion, XConomy, ZMusic

**Comment by SamB440** [comment]
Works as intended... the client (MCC) is not following vanilla rules.
