### ISSUE TITLE
Conflict with Cosmin

### ISSUE THREAD

**Issue by sachingorkar102** [GrimAnticheat/Grim#1349]
### Describe the bug and how to replicate it

hey there author of cosmin here, when grimac is installed, the cosmetics/fake armor from [cosmin](https://www.spigotmc.org/resources/cosmin-cosmetic-armor-sets-hats-auto-resource-pack-generator-1-16-1-20.92427/) does not seem to work

this is probably caused by SET_SLOT packet used by both plugins at same time, (i tried setting the [ListernerPriority](https://aadnk.github.io/ProtocolLib/Javadoc/com/comphenix/protocol/events/ListenerPriority.html) to HIGHEST on my side but its still causing the same issue)

**with grimac**

https://github.com/GrimAnticheat/Grim/assets/74291008/20fb300b-a156-4985-ab65-7d291ac666b0

**without grimac**

https://github.com/GrimAnticheat/Grim/assets/74291008/55869be1-ae0a-4331-816f-7ffea5466946

### Grim version

2.3.56

### Server version

paper 1.20.4

### Plugins

grimAC, Cosmin

**Comment by ManInMyVan** [comment]
> i tried setting the ListernerPriority to HIGHEST on my side but its still causing the same issue

Changing anything with protocollib won't change anything, as grim uses packetevents, which has nothing to do with protocollib

**Comment by 0-x-2-2** [comment]
grim has code for detecting inventory desync it is possible that is what is happening here.

**Comment by sachingorkar102** [comment]
> > i tried setting the ListernerPriority to HIGHEST on my side but its still causing the same issue
> 
> Changing anything with protocollib won't change anything, as grim uses packetevents, which has nothing to do with protocollib

uhm you [sure](https://github.com/GrimAnticheat/Grim/blob/60f503da01c50da3815d3c6dcab7d990da7dbea9/src/main/java/ac/grim/grimac/utils/latency/CompensatedInventory.java#L436) ?

and protocollib HAS packetevents which grim and cosmin use as far as i am aware lol

**Comment by ManInMyVan** [comment]
> uhm you [sure](https://github.com/GrimAnticheat/Grim/blob/60f503da01c50da3815d3c6dcab7d990da7dbea9/src/main/java/ac/grim/grimac/utils/latency/CompensatedInventory.java#L436) ?

Didn't say anything about setslot

> and protocollib HAS packetevents

No it doesn't? There's 0 references to packetevents in src.

> which grim and cosmin use

This is either supposed to mean grim uses protocollib, which isn't true, or cosmin uses packetevents, which in that case, why is protocollib a dependency?

**Comment by sachingorkar102** [comment]
> > uhm you [sure](https://github.com/GrimAnticheat/Grim/blob/60f503da01c50da3815d3c6dcab7d990da7dbea9/src/main/java/ac/grim/grimac/utils/latency/CompensatedInventory.java#L436) ?
> 
> Didn't say anything about setslot
> 
> > and protocollib HAS packetevents
> 
> No it doesn't? There's 0 references to packetevents in src.
> 
> > which grim and cosmin use
> 
> This is either supposed to mean grim uses protocollib, which isn't true, or cosmin uses packetevents, which in that case, why is protocollib a dependency?

i apologize, i got somethings confused and didn't realize that grimac uses PacketEvents lib as dependency instead of protocollib, and yes cosmin uses protocolib

resolved the issue, since both use different libs for packetevents, i am now using packetevents listener for some methods on my side

thank you for the help
