### ISSUE TITLE
Sprint Scaffold 

### ISSUE THREAD

**Issue by ManInMyVan** [GrimAnticheat/Grim#1357]
### Describe the bypass and how to replicate it

Set pitch to 100ish to look at the block without changing yaw to allow for sprinting

Solutions:
a) don't allow places if the player's pitch is out of bounds (or cap pitch in rotationplace)
b) setback if the player's pitch is out of bounds

### Grim version

3fa22a1

### Server version

paper 1.8.8 (1.8.9 client)

### Plugins

LuckPerms 5.4.116
EssentialsX 2.20.1
ViaVersion 4.9.2
WorldEdit 6.1.9
WorldGuard 6.2

**Comment by z7087** [comment]
Try ban the player if it flags BadPacketsD once

**Comment by SamB440** [comment]
I think the point is most servers don't have checks like that set up to autoban/kick, and most server admins don't know what flagging "BadPackets D" means and just assume Grim will block it.

**Comment by z7087** [comment]
```java
    @Override
    public void onPacketReceive(PacketReceiveEvent event) {
        //if (player.packetStateData.lastPacketWasTeleport) return;

        if (WrapperPlayClientPlayerFlying.isFlying(event.getPacketType())) {
            if (player.yRot > 90 || player.yRot < -90) {
                player.getSetbackTeleportUtil().executeViolationSetback();
                event.setCancelled(true);
                player.onPacketCancel();
                flagAndAlert();
            }
        }
    }
```
should work but idk why exempts teleports

**Comment by ManInMyVan** [comment]
> ```java
>     @Override
>     public void onPacketReceive(PacketReceiveEvent event) {
>         //if (player.packetStateData.lastPacketWasTeleport) return;
> 
>         if (WrapperPlayClientPlayerFlying.isFlying(event.getPacketType())) {
>             if (player.yRot > 90 || player.yRot < -90) {
>                 player.getSetbackTeleportUtil().executeViolationSetback();
>                 event.setCancelled(true);
>                 player.onPacketCancel();
>                 flagAndAlert();
>             }
>         }
>     }
> ```
> should work but idk why exempts teleports

Sends you flying down (potential speed?) in my testing.

**Comment by z7087** [comment]
try move badpacketsd to prepredictionchecks and change player.yrot to packet.getlocation().getpitch()

**Comment by matsu1213** [comment]
> ```java
>     @Override
>     public void onPacketReceive(PacketReceiveEvent event) {
>         //if (player.packetStateData.lastPacketWasTeleport) return;
> 
>         if (WrapperPlayClientPlayerFlying.isFlying(event.getPacketType())) {
>             if (player.yRot > 90 || player.yRot < -90) {
>                 player.getSetbackTeleportUtil().executeViolationSetback();
>                 event.setCancelled(true);
>                 player.onPacketCancel();
>                 flagAndAlert();
>             }
>         }
>     }
> ```
> 
> should work but idk why exempts teleports

vanilla client can send invaild pitches after relative teleports
https://bugs.mojang.com/browse/MC-259376

**Comment by z7087** [comment]
```java
    @Override
    public void onPacketSend(PacketSendEvent event) {
        if (event.getPacketType(PacketType.Play.Server.PLAYER_POSITION_AND_LOOK) && player.getClientVersion().isNewerThanOrEquals(ClientVersion.V_1_19_3)) {
            WrapperPlayServerPlayerPositionAndLook teleport = new WrapperPlayServerPlayerPositionAndLook(event);
            if (teleport.isRelativeFlag(RelativeFlag.PITCH)) {
                if (teleport.getPitch() != 0)
                    d = true;
            } else {
                if (teleport.getPitch() > 90 || teleport.getPitch() < -90)
                    d = true;
            }
        }
    }
    @Override
    public void onPacketReceive(PacketReceiveEvent event) {
        // there is a rotation desync with a teleport
        // client yaw0 pitch90  server yaw0 pitch90
        // client gets a teleport: yaw0 pitch91  server yaw0 pitch91
        // client changes rotation and runs a tick: yaw0 pitch 90  server yaw0 pitch91
        // maybe should do something
        if (event.getPacketType() == PacketType.Play.Client.PLAYER_ROTATION || event.getPacketType() == PacketType.Play.Client.PLAYER_POSITION_AND_ROTATION) {
            WrapperPlayClientPlayerFlying packet = new WrapperPlayClientPlayerFlying(event);
            if (packet.getLocation().getPitch() > 90 || packet.getLocation().getPitch() < -90) {
                if (player.getClientVersion().isNewerThanOrEquals(ClientVersion.V_1_19_3) && player.packetStateData.lastPacketWasTeleport && d) {
                    exemptVec = new Vector3f(packet.getLocation().getYaw(), packet.getLocation().getPitch(), 0);
                    return;
                }
                if (exemptVec == null || exemptVec.getX() != packet.getLocation().getYaw() || exemptVec.getY() != packet.getLocation().getPitch()) {
                    exemptVec = null;
                    flagAndAlert(); // Ban.
                }
            } else {
                exemptVec = null;
            }
        }
    }
```

**Comment by ManInMyVan** [comment]
> ```java
>     @Override
>     public void onPacketSend(PacketSendEvent event) {
>         if (event.getPacketType(PacketType.Play.Server.PLAYER_POSITION_AND_LOOK) && player.getClientVersion().isNewerThanOrEquals(ClientVersion.V_1_19_3)) {
>             WrapperPlayServerPlayerPositionAndLook teleport = new WrapperPlayServerPlayerPositionAndLook(event);
>             if (teleport.isRelativeFlag(RelativeFlag.PITCH)) {
>                 if (teleport.getPitch() != 0)
>                     d = true;
>             } else {
>                 if (teleport.getPitch() > 90 || teleport.getPitch() < -90)
>                     d = true;
>             }
>         }
>     }
>     @Override
>     public void onPacketReceive(PacketReceiveEvent event) {
>         // there is a rotation desync with a teleport
>         // client yaw0 pitch90  server yaw0 pitch90
>         // client gets a teleport: yaw0 pitch91  server yaw0 pitch91
>         // client changes rotation and runs a tick: yaw0 pitch 90  server yaw0 pitch91
>         // maybe should do something
>         if (event.getPacketType() == PacketType.Play.Client.PLAYER_ROTATION || event.getPacketType() == PacketType.Play.Client.PLAYER_POSITION_AND_ROTATION) {
>             WrapperPlayClientPlayerFlying packet = new WrapperPlayClientPlayerFlying(event);
>             if (packet.getLocation().getPitch() > 90 || packet.getLocation().getPitch() < -90) {
>                 if (player.getClientVersion().isNewerThanOrEquals(ClientVersion.V_1_19_3) && player.packetStateData.lastPacketWasTeleport && d) {
>                     exemptVec = new Vector3f(packet.getLocation().getYaw(), packet.getLocation().getPitch(), 0);
>                     return;
>                 }
>                 if (exemptVec == null || exemptVec.getX() != packet.getLocation().getYaw() || exemptVec.getY() != packet.getLocation().getPitch()) {
>                     exemptVec = null;
>                     flagAndAlert(); // Ban.
>                 }
>             } else {
>                 exemptVec = null;
>             }
>         }
>     }
> ```

This no longer solves the original issue

**Comment by z7087** [comment]
try https://github.com/z7087/Grim/actions/runs/7967328768

**Comment by ManInMyVan** [comment]
> try https://github.com/z7087/Grim/actions/runs/7967328768

Doesn't fix it

**Comment by z7087** [comment]
work for me, what is your client/server version?

**Comment by ManInMyVan** [comment]
> work for me, what is your client/server version?

1.8.9/1.8.8, as stated in the original issue

**Comment by z7087** [comment]
https://github.com/z7087/Grim/actions/runs/7974183147
I don't know what can I do if unfair pitch is vanilla
