### ISSUE TITLE
Hitting while eating gapple/blocking with shield

### ISSUE THREAD

**Issue by NuggetRider** [GrimAnticheat/Grim#1360]
### Describe the bypass and how to replicate it

Step 1. open minecraft with meteor
Step 2. take a sword
Step 3. take a golden apple or shield
Step 4. open killaura with only on look mode (with legit settings)
Step 5. then attack someone, you can eat golden apple while attacking.

### Grim version

2.3.58

### Server version

1.20.1

### Plugins

![image](https://github.com/GrimAnticheat/Grim/assets/130094236/cc980ef6-d7b8-4830-9188-0ea60d9dfc30)
a little bit :):):)):

**Comment by ManInMyVan** [comment]
duplicate of multiple open issues, #881, #1160, #1195, #1340
