### ISSUE TITLE
Console Spammer

### ISSUE THREAD

**Issue by z7087** [GrimAnticheat/Grim#1367]
### Describe the bypass and how to replicate it

[NettyPacketEncoder.zip](https://github.com/GrimAnticheat/Grim/files/14386909/NettyPacketEncoder.zip)

### Grim version

2.3.58

### Server version

spigot 1.8.8

### Plugins

ViaVersion 4.9.2, ViaBackwards 4.9.1, ViaRewind 3.0.5, Grim

**Comment by mazioot** [comment]
Does this exclusively work on 1.8.8?
Or does it also work on the latest versions eg 1.20.4 paper

**Comment by z7087** [comment]
tested and work on spigot 1.8.8 1.12.2 1.20.2 and paper 1.20.4

**Comment by ghost** [comment]
Fix this fast! https://www.youtube.com/watch?v=mQM2y82k9bI

**Comment by MachineBreaker** [comment]
Working on this.

**Comment by MachineBreaker** [comment]
Fixed by https://github.com/retrooper/packetevents/pull/687, should be merged soon after i finish some requested changes
