### ISSUE TITLE
GrimAC "packetevents bug"

### ISSUE THREAD

**Issue by AstonicPI** [GrimAnticheat/Grim#1373]
### Describe the bug and how to replicate it

No replication, I just uploaded the plugin and it started happening

### Grim version

Grim version 2.3.58

### Server version

CarbonSpigot version 1.8.8

### Plugins

No other plugin is interfering with this, also I cant show all the plugins.

**Comment by MachineBreaker** [comment]
Invalid issue, you didnt even wrote what the issue is?
