### ISSUE TITLE
You forgot to include cave air in none collision blocks

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1374]
### Describe the false positive and how to replicate it

Cave air falses grim because you forgot it

CollisionData.java should have:

NONE(NoCollisionBox.INSTANCE, StateTypes.AIR, StateTypes.CAVE_AIR, StateTypes.LIGHT),

but only has

NONE(NoCollisionBox.INSTANCE, StateTypes.AIR, StateTypes.LIGHT),

### Grim version

N/A

### Server version

N/A

### Plugins

N/A

**Comment by SamB440** [comment]
It also needs void air, I did fix this in my hitting through walls pr, or maybe I forgot to port it
