### ISSUE TITLE
Place Disabler on 1.8- servers

### ISSUE THREAD

**Issue by z7087** [GrimAnticheat/Grim#1375]
### Describe the bypass and how to replicate it

[NettyPacketEncoder.zip](https://github.com/GrimAnticheat/Grim/files/14417874/NettyPacketEncoder.zip)
https://github.com/GrimAnticheat/Grim/pull/1368 can patch it?

### Grim version

2.3.58

### Server version

spigot 1.8.8

### Plugins

ViaVersion 4.9.2, ViaBackwards 4.9.1, ViaRewind 3.0.5, Grim

**Comment by mazioot** [comment]
may I ask what this does?

**Comment by z7087** [comment]
it makes grim(packetevents) think this is a use item packet
and it wont be reencode from packet wrapper cause [PacketSetWrapperNull](https://github.com/GrimAnticheat/Grim/blob/2.0/src/main/java/ac/grim/grimac/events/packets/PacketSetWrapperNull.java)
basically useless with high ping

**Comment by z7087** [comment]
https://github.com/z7087/packetevents/tree/patch-1

**Comment by mazioot** [comment]
I got that from the code, but I still don't really get what this could be used for?

**Comment by z7087** [comment]
useless

**Comment by z7087** [comment]
https://www.bilibili.com/video/BV1nU411F7Ci
https://www.bilibili.com/video/BV1dF4m1G7s8
skidders here

**Comment by ManInMyVan** [comment]
> #1368 can patch it?

It seems to (unless placed at -1, -1, -1 @ 0.0, 0.0, 0.0), but this is more of a PE issue

**Comment by z7087** [comment]
why this still alive

**Comment by ManInMyVan** [comment]
> why this still alive

This is a full place disabler, and allows for down/sprint/expand/rotationless scaffold on all versions
