### ISSUE TITLE
you forgot to update packet events in d60c5577

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1378]
https://github.com/GrimAnticheat/Grim/commit/d60c5577ebc36108f052f46dd7882eeec2e3fdfe

you bumped grim version and added:  .kickOnPacketException(true) but didn't bump packet events version, do i need to modify build.gradle to use latest dev packet events maybe?

error: cannot find symbol
                .fullStackTrace(true)
                ^

**Comment by AoElite** [comment]
There was packetevent changes but not a version bump. So there is nothing to update in gradle.

**Comment by SamB440** [comment]
@ThrowerWay make sure you clear your gradle cache, you can use the inbuilt intellij refresh dependencies, make sure your .m2 folder doesn't have packetevents as well
