### ISSUE TITLE
It's fake?

### ISSUE THREAD

**Issue by rejomy** [GrimAnticheat/Grim#1379]
### Describe the bypass and how to replicate it

https://youtu.be/msajNTp0kM8?si=JNu26yzs8iyBuJPB

https://youtu.be/fisy2KXinfU?si=xqI8Oq53myyzg0IG

### Grim version

D

### Server version

W

### Plugins

2

**Comment by z7087** [comment]
I think the previous one has been patched 2 days ago

**Comment by SamB440** [comment]
Both of these are patched, 2nd one has been patched for a long time

**Comment by z7087** [comment]
> 2nd one has been patched for a long time

Is that been patched?

**Comment by SamB440** [comment]
Oh I was looking at a different video, probably autoplay from when I clicked the 1st.

I'm pretty certain the 2nd one is patched, or never existed. Herobrine.org is known for having a very poor Grim config.

It seems to be using ghost blocks (which was patched) and also timer abuse (which was patched).

Can be fixed by enabling ghost block mitigation in the config.

**Comment by nullablepointer** [comment]
> Oh I was looking at a different video, probably autoplay from when I clicked the 1st.
> 
> I'm pretty certain the 2nd one is patched, or never existed. Herobrine.org is known for having a very poor Grim config.
> 
> It seems to be using ghost blocks (which was patched) and also timer abuse (which was patched).
> 
> Can be fixed by enabling ghost block mitigation in the config.

timer abuse hasnt been patched but yes ghost blocks work weirdly

**Comment by SamB440** [comment]
> > Oh I was looking at a different video, probably autoplay from when I clicked the 1st.
> > I'm pretty certain the 2nd one is patched, or never existed. Herobrine.org is known for having a very poor Grim config.
> > It seems to be using ghost blocks (which was patched) and also timer abuse (which was patched).
> > Can be fixed by enabling ghost block mitigation in the config.
> 
> timer abuse hasnt been patched but yes ghost blocks work weirdly

The timer abuse should be patched via mitigation, but the current implementation is flawed, I'm working on a fix

**Comment by ghost** [comment]
Second one looks to be ghost block abuse.
