### ISSUE TITLE
More inventory out of bounds errors

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1383]
### Stack trace

https://pastebin.com/u1PyxYwb

### How to replicate it if known

Grim always has had out of bounds inventory problems, random stacktraces for index out of bounds, using latest version its still a problem.

### Grim version

latest commit 57b4f3a724c24e0124892b955e6a733642634374

### Server version

This server is running Paper version git-Paper-"850b736" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 850b736)
You are 10 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-"9e171ef" (MC: 1.20.4)

### Plugins

Grim

**Comment by SamB440** [comment]
Doesn't seem like the latest commit to me, `(CompensatedInventory.java:481)`

That's a higher line than exists

**Comment by SamB440** [comment]
Would also need reproduction steps for this, without any other plugins installed, Grim has never had such issues for me, generally stuff like this is caused by bad plugins

**Comment by z7087** [comment]
![图片](https://github.com/GrimAnticheat/Grim/assets/75190047/a4e203f4-e139-4948-92d8-2017c009db4b)
![图片](https://github.com/GrimAnticheat/Grim/assets/75190047/9a8f1a71-883c-45f8-96ab-344b40ffb1e0)
![图片](https://github.com/GrimAnticheat/Grim/assets/75190047/92e6b5b2-73cb-452b-a1a4-2ace763d613a)

**Comment by ghost** [comment]
Yes i am using a fork, but all it adds to compensatedinventory is a util method,  and other plugins are irrelevant

i will post the compensated line number eventually, idk, i need to use my fork for production, it has many fixes and improvements.
