### ISSUE TITLE
Scaffold Expand Bypass

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1384]
### Describe the bypass and how to replicate it

Hello Writing the following code into LiquidBounce can bypass Scaffold's Expand. I am Japanese and my expression is not good

`package net.ccbluex.liquidbounce.injection.forge.mixins.packets;

import net.minecraft.network.Packet;
import net.minecraft.network.PacketBuffer;
import net.minecraft.network.play.INetHandlerPlayServer;
import net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock;
import net.minecraft.util.EnumFacing;
import net.minecraft.util.EnumHand;
import net.minecraft.util.math.BlockPos;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Overwrite;
import org.spongepowered.asm.mixin.Shadow;

import java.io.IOException;

@Mixin(CPacketPlayerTryUseItemOnBlock.class)
public class MixinCPacketPlayerTryUseItemOnBlock {
@Shadow
    private BlockPos position;
@Shadow
    private EnumFacing placedBlockDirection;
@Shadow
    private EnumHand hand;
@Shadow
    private float facingX;
@Shadow
    private float facingY;
@Shadow
    private float facingZ;

    /**
     * &#064;authorsfgfadg  吸尘器没电了
     * &#064;reasonasfre  皇帝帮忙插上了
     * @author
     * @reason
     */
    @Overwrite
    public void writePacketData(PacketBuffer p_writePacketData_1_) throws IOException {
        p_writePacketData_1_.writeBlockPos(this.position);
        p_writePacketData_1_.writeVarInt(6 + (this.placedBlockDirection.ordinal() * 7));
        p_writePacketData_1_.writeEnumValue(this.hand);
        p_writePacketData_1_.writeFloat(this.facingX);
        p_writePacketData_1_.writeFloat(this.facingY);
        p_writePacketData_1_.writeFloat(this.facingZ);
    }
}
`

### Grim version

Grim Anticheat 2.3.59

### Server version

1.12.2

### Plugins

GrimAC, ViaVersion

**Comment by z7087** [comment]
你们没有一点自己的东西吗

**Comment by mazioot** [comment]
Perhaps it would be more useful to showcase this bypass on a more modern version of Liquidbounce? Eg something like Liquidbounce Nextgen

**Comment by ghost** [comment]
I use LiquidBounce B73

**Comment by mazioot** [comment]
> I use LiquidBounce B73

That's a very very very old version of Liquidbounce. Please write this on Liquidbounce Nextgen, as it's easier to see whats happening.

**Comment by ManInMyVan** [comment]
Duplicate of #1375

**Comment by EzDiaoL** [comment]
別人發過了。

**Comment by devrgu** [comment]
> I use LiquidBounce B

> I use LiquidBounce B73

now try to report bypass without looking codes.

**Comment by ManInMyVan** [comment]
This is fixed

**Comment by SamB440** [comment]
Fixed by https://github.com/retrooper/packetevents/pull/704
