### ISSUE TITLE
RotationPlace

### ISSUE THREAD

**Issue by z7087** [GrimAnticheat/Grim#1387]
### Describe the false positive and how to replicate it

use a modified version of mcp 1.12.2 client to control mouse input
![图片](https://github.com/GrimAnticheat/Grim/assets/75190047/913f5586-a641-4ecf-a6cd-5a9787337810)
press left mouse button and next key G
https://streamable.com/b09wag

### Grim version

2.3.58

### Server version

Paper 1.8.8

### Plugins

ViaVersion, AntiSwitchItem, ViaBackwards, ViaRewind, GrimAC

**Comment by 0-x-2-2** [comment]
Did you flag the check once? The check will use the last tick rotations if you flag the check once.

**Comment by z7087** [comment]
I think if I did then the check will flag pre-flying

**Comment by z7087** [comment]
I used a modified version of grim to prevent being affected by this https://github.com/GrimAnticheat/Grim/blob/57b4f3a724c24e0124892b955e6a733642634374/src/main/java/ac/grim/grimac/events/packets/CheckManagerListener.java#L192
and it is reproducible on latest grim too (post-flying)

**Comment by 0-x-2-2** [comment]
interesting

**Comment by z7087** [comment]
https://github.com/z7087/Grim/tree/c09
