### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1393]
### Stack trace

 https://paste.md-5.net/ejunenugop.md

### How to replicate it if known

i don't know

### Grim version

 grimac-2.3.55.jar

### Server version

[12:55:50 INFO]: This server is running PandaSpigot version git-PandaSpigot-116 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) (Git: 4d92553)

### Plugins

 Plugins (17): PuniX, AWD, PlaceholderAPI, DeluxeMenus, BuildTrain, Lobby, ViaVersion, WorldTablist, Multiverse-Core, ProtocolLib, LuckPerms, Citizens, Vulcan, DecentHolograms, GrimAC, TAB, TntTag

**Comment by rejomy** [comment]
true.
