### ISSUE TITLE
You broke baritone check

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1401]
### Describe the false positive and how to replicate it

https://github.com/GrimAnticheat/Grim/commit/284ee973efb9069cedfe25c3eab132bb57d7d4b7

baritone is flagging legit players now

### Grim version

Latet commit https://github.com/GrimAnticheat/Grim/commit/284ee973efb9069cedfe25c3eab132bb57d7d4b7

### Server version

1.20.4 latest paper

### Plugins

N/A

**Comment by ghost** [comment]
wtf how

**Comment by Souipi** [comment]
Can you explain me when it false flag you ?

**Comment by ghost** [comment]
multiple legit players are flagging since updating from https://github.com/GrimAnticheat/Grim/commit/57b4f3a724c24e0124892b955e6a733642634374

Divisor -0.33333332505491076

only thing that changed that touches baritone check is https://github.com/GrimAnticheat/Grim/commit/284ee973efb9069cedfe25c3eab132bb57d7d4b7

but changing order of yaw and pitch shouldn't affect anything? weird, also why was it even changed.

**Comment by Souipi** [comment]
Man can you explain me how do you false it ?

**Comment by ghost** [comment]
> Man can you explain me how do you false it ?

Multiple players in production started flagging it randomly out of nowhere since updating to that commit, after noone flagging it for over 1 year.

**Comment by Souipi** [comment]
Mhhhh okay but actually i can't help you if i don't know how to replicate that exactly

**Comment by z7087** [comment]
did the baritone check work before?

**Comment by ghost** [comment]
> did the baritone check work before?

Yes

**Comment by 0-x-2-2** [comment]
that change has no functional changes

**Comment by 0-x-2-2** [comment]
most likely these players have invalid gcd or something?

**Comment by VenixPLL** [comment]
![image](https://github.com/GrimAnticheat/Grim/assets/32221428/31a846ca-0424-4b08-a94b-65f134225812)
![image](https://github.com/GrimAnticheat/Grim/assets/32221428/01314d4e-79d2-4d5d-9c03-124d61026c34)
![image](https://github.com/GrimAnticheat/Grim/assets/32221428/1da510fa-bdda-44aa-990f-014ab8af71ab)
![image](https://github.com/GrimAnticheat/Grim/assets/32221428/be5018b5-5b82-410d-bf82-ae92754e3320)



Still falses on grim 2.3.61, always the same divisor

**Comment by ManInMyVan** [comment]
~~could have been the change in constructor order but no changes in usages~~ checked and it looks right

**Comment by TypicalModMaker** [comment]
still happens
