### ISSUE TITLE
How to disable fastbreak check since it keeps breaking my box world?

### ISSUE THREAD

**Issue by Talcility** [GrimAnticheat/Grim#1404]
### Describe the false positive and how to replicate it

Title.

### Grim version

2.3.60 (From Spigot)

### Server version

1.20.1

### Plugins

EconomyShopGUI
ApeCombatLog, AuctionMaster, CraftingStore, DamageIndicator, Dupe, Essentials, HolographicDisplays, Lifesteal, LPC, LuckPerms
MinehutCosmetics, MinehutPlugin, MineResetLite, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, PerWorldCommands(Deleting in a few minutes, not related), PerWorldPlugins, PlaceholderAPI, RandomTP
ServersNPC, Shopkeepers, SimpleScore, Skript, Spawntp, StaffPlusPlus, TAB, TradeSystem, Vault, ViaBackwards
ViaRewind, ViaVersion, WorldEdit, WorldGuard

**Comment by ManInMyVan** [comment]
Steps to replicate?
