### ISSUE TITLE
NegativeTimer does not appear to work

### ISSUE THREAD

**Issue by Symmettry** [GrimAnticheat/Grim#1406]
### Describe the bypass and how to replicate it

step 1. set timer to like 0.2 or anything
step 2. negativetimer doesn't appear to flag ever. even with verbose on & drift at 0 in config

### Grim version

2.3.60

### Server version

git-Purpur-2155 (MC: 1.20.4)*

### Plugins

- Chunky, CoreProtect, DangerLevel, DiscordSRV, Factions, GraveStonesPlus, GrimAC, InventoryRollbackPlus, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, LiteBans, LuckPerms, mcMMO, Movecraft, *ObsidianDestroyer, SkBee, Skript, skript-reflect, spark, TwerkGrowth, VanishNoPacket, Vault, VeinMiner, ViaBackwards, ViaVersion, Vulcan, WorldEdit

**Comment by SamB440** [comment]
Negative timer is marked as experimental. Do you have experimental checks enabled?

**Comment by Symmettry** [comment]
oh lmao
