### ISSUE TITLE
Criticals bypass

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1416]
### Describe the bypass and how to replicate it

    @EventTarget
    fun onAttack(event: AttackEvent) {
                    val blink = Arctic.moduleManager[Blink::class.java] as Blink
                    if(!blink.state && blinktick<=0) {
                        if (thePlayer.onGround && jump > 10 && airtick == 0 && !dotimercri && mc2.player.hurtTime == 0) {
                            //thePlayer.motionY =0.41999998688698
                            mc2.gameSettings.keyBindJump.pressed = true
                            jump = 0
                            airtick = 0
                            dotimercri = true
                            mc.timer.timerSpeed = 2f - timervalue.get() //speed up
                        }
                    }else{
                        if(thePlayer.onGround && jump >10) {
                            thePlayer.motionY =0.41999998688698
                            jump = 0
                        }
                    }
}

### Grim version

grimac-2.3.61.jar

### Server version

1.8.8

### Plugins

ViaVersion-4.9.2.jar grimac-2.3.61.jar

**Comment by yusuf1746** [comment]
can you explain what all the variables stand for?

**Comment by SamB440** [comment]
This is not a bypass, it’s just jumping
