### ISSUE TITLE
Ghostblock Fly

### ISSUE THREAD

**Issue by z7087** [GrimAnticheat/Grim#1420]
### Describe the bypass and how to replicate it

https://github.com/GrimAnticheat/Grim/pull/1270
[the patch](https://github.com/GrimAnticheat/Grim/commit/10a99fd67bcf98417b200289161dafbb4d454f77) doesnt even work at all and i have use it for at least 3 months and nobody noticed

### Grim version

2.3.61

### Server version

Paper 1.20.4

### Plugins

grim and via

**Comment by Symmettry** [comment]
Doesn't the ghost block system only allow 3 blocks or so? I used this fly like a year ago and the ghost block limiter blocked it.

**Comment by ManInMyVan** [comment]
I'll look into this later

> Doesn't the ghost block system only allow 3 blocks or so? I used this fly like a year ago and the ghost block limiter blocked it.

Not what he's talking about

**Comment by z7087** [comment]
i didnt find the ghost block system but im sure that the current ghostblock patch is not safe

**Comment by ManInMyVan** [comment]
> [the patch](https://github.com/GrimAnticheat/Grim/commit/10a99fd67bcf98417b200289161dafbb4d454f77) doesnt even work at all

Does your original one work?

**Comment by z7087** [comment]
> Does your original one work?

i forgot that but i think change to the original one is safe now

**Comment by Symmettry** [comment]
> I'll look into this later
> 
> > Doesn't the ghost block system only allow 3 blocks or so? I used this fly like a year ago and the ghost block limiter blocked it.
> 
> Not what he's talking about

You sure? It's literally titled "Ghostblock fly" and that's the ghost block fly that got patched.

**Comment by z7087** [comment]
then nocom will work

**Comment by ManInMyVan** [comment]
PacketEvents says the packet's cursor is 0.0, 0.0, 0.0 (using a 1.8.9 client), but my client says NaN, NaN, NaN.

**Comment by z7087** [comment]
use 1.11+ client and server

**Comment by ManInMyVan** [comment]
> use 1.11+ client and server

FabricatedPlace & InvalidPlace flag, still can't replicate.

c1.20.4, s1.16.5 & s1.12.2
```kt
val packet = event.packet
if (packet is PlayerInteractBlockC2SPacket) {
    packet.blockHitResult.pos.x = Double.NaN
    packet.blockHitResult.pos.y = Double.NaN
    packet.blockHitResult.pos.z = Double.NaN
}
```

**Comment by z7087** [comment]
then it must been patched :D

**Comment by ManInMyVan** [comment]
> > use 1.11+ client and server
> 
> FabricatedPlace & InvalidPlace flag, still can't replicate.
> 
> c1.20.4, s1.16.5 & s1.12.2
> ```kt
> val packet = event.packet
> if (packet is PlayerInteractBlockC2SPacket) {
>     packet.blockHitResult.pos.x = Double.NaN
>     packet.blockHitResult.pos.y = Double.NaN
>     packet.blockHitResult.pos.z = Double.NaN
> }
> ```

nvm I was using a fixed version, I'll pr it
