### ISSUE TITLE
false bow reach alerts

### ISSUE THREAD

**Issue by xemuain1** [GrimAnticheat/Grim#1422]
### Describe the false positive and how to replicate it

just false reach alerts for bow

### Grim version

.

### Server version

.

### Plugins

.

**Comment by SamB440** [comment]
Considering the effort it takes for someone to fix issues, you could at least put the effort in and give proper reproduction steps and info about your client and server

**Comment by Symmettry** [comment]
No idea what this is meant to mean. Doesn't appear to flag me when Im using a bow / swapping to swords.

**Comment by SamB440** [comment]
Please open a new issue with better reproduction steps.
