### ISSUE TITLE
fly (up only?)

### ISSUE THREAD

**Issue by ManInMyVan** [GrimAnticheat/Grim#1424]
### Describe the bypass and how to replicate it

https://github.com/CCBlueX/LiquidBounce/blob/nextgen/src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/movement/fly/modes/grim/FlyGrim2859V.kt

### Grim version

2fda5b4

### Server version

1.12.2 paper

### Plugins

Via*

**Comment by 9x00** [comment]
this is alr patched

**Comment by ManInMyVan** [comment]
> this is alr patched

then the patch didn't work

**Comment by ghost** [comment]
not even worth patching, it literally just makes you float up and down, and you cant move in that state

**Comment by ManInMyVan** [comment]
> not even worth patching, it literally just makes you float up and down, and you cant move in that state
> 

It's a slow spider/step

**Comment by Symmettry** [comment]
> not even worth patching, it literally just makes you float up and down, and you cant move in that state

Yeah, that's still a cheat. I can think of many use cases for it. It's not vanilla behavior, so grim should patch it.

**Comment by ghost** [comment]
> Yeah, that's still a cheat. I can think

please tell me the use cases for it 🙏

**Comment by Symmettry** [comment]
> > Yeah, that's still a cheat. I can think
> 
> please tell me the use cases for it 🙏

Escaping people by flying upwards, jumping over things you're not able to in non-survival servers (stuff with walls that don't have barriers on top, because you can't get over in vanilla), and i'm sure you can easily think of many cases where you can break maps with it

**Comment by djw27921** [comment]
fly dis
[GrimFlyDisabler.zip](https://github.com/GrimAnticheat/Grim/files/15111042/GrimFlyDisabler.zip)

**Comment by ManInMyVan** [comment]
> fly dis
> [GrimFlyDisabler.zip](https://github.com/GrimAnticheat/Grim/files/15111042/GrimFlyDisabler.zip)
> 

Spectator disabler?
