### ISSUE TITLE
False Killaura & Aim Checks

### ISSUE THREAD

**Issue by x2loreeh** [GrimAnticheat/Grim#1429]
If I hit some mob doing strange rotations with the head in Minecraft Vanilla 1.8.8, it flags with Aim and Killaura, sometimes also cirticals if i jump

**Comment by Souipi** [comment]
Hum that not possible to false Killaura check because grim DON'T HAVE one...

**Comment by jonesdevelopment** [comment]
Grim doesn't have Killaura and Criticals checks.
