### ISSUE TITLE
Baritone check does not work at all

### ISSUE THREAD

**Issue by VenixPLL** [GrimAnticheat/Grim#1432]
### Describe the bug and how to replicate it

Also i observed a false flagging issue in grimac regarding Baritone check as seen in the issue below
The bug in this issue seems like a floating point calculation error to me.
https://github.com/GrimAnticheat/Grim/issues/1401

Baritone version: [v1.10.2](https://github.com/cabaletta/baritone/releases/tag/v1.10.2)

Step 1. Download baritone and run baritone task
Step 2. Enable grim verbose
Step 3. Observe that there is no alerts being thrown by grimac regarding baritone.

Video of the process: (Check is not working on official release, im using modified release with additonal checks)
https://streamable.com/f3xbs5

### Grim version

GrimAC 2.3.61

### Server version

PaperSpigot 1.20.4 (git-Paper-423)

### Plugins

GrimAC. Spark, Skript, Terra. ViaVersion, ViaBackwards, WorldBorder, FAWE, InvSeePlusPlus

**Comment by SamB440** [comment]
From what I remember, baritone fixed the detection method, MW made a new detection method but wasn't willing to publish it, so the current check is useless

Edit: https://github.com/GrimAnticheat/Grim/issues/813#issuecomment-1324310020

**Comment by VenixPLL** [comment]
> From what I remember, baritone fixed the detection method, MW made a new detection method but wasn't willing to publish it, so the current check is useless
> 
> Edit: [#813 (comment)](https://github.com/GrimAnticheat/Grim/issues/813#issuecomment-1324310020)

Okay that's fair, What about that false flags i mentioned at the top of the issue? that is very strange and i can't reproduce that ;/

**Comment by SamB440** [comment]
I bet it's Optifine cinematic camera / fastmath

**Comment by VenixPLL** [comment]
> I bet it's Optifine cinematic camera / fastmath

I tried debugging the check and found that unlikely that so many checks will be thrown at once, i tried optifine fastmath and cinematic camera that is the only way i found triggering it, but at most 1 check is thrown and its very hard to do, sensitivity yawn and cinematic camera spam.

I would assume that this baritone check is triggered by some aim cheats, but i don't even have a clue on what, i tried screensharing those players and they were clear, versions all around 1.18.2-1.20.4

**Comment by VenixPLL** [comment]
I would suggest marking baritone check as deprecated, or refactor that check as invalid aim gcd. (Moving mouse too slow)

**Comment by SamB440** [comment]
What are these players using though?? I can't false this no matter how hard I try

**Comment by SamB440** [comment]
Okay I can only false this when using cinematic camera + yawn sensitivity. I got 49 violations.

Are all these players using yawn sensitivity and cinematic camera or what??

**Comment by VenixPLL** [comment]
> Okay I can only false this when using cinematic camera + yawn sensitivity. I got 49 violations.
> 
> Are all these players using yawn sensitivity and cinematic camera or what??

Nope, grim profile shows sensitivity in ranges from 30% to 80%

![image](https://github.com/GrimAnticheat/Grim/assets/32221428/6fa63392-810a-4e8d-ba5e-8e6630e9eaa6)
![image](https://github.com/GrimAnticheat/Grim/assets/32221428/4fe6394e-fb5d-4fb8-8104-4e0e015f9732)
![image](https://github.com/GrimAnticheat/Grim/assets/32221428/b26f967e-537b-435c-a965-3ec78075a622)
