### ISSUE TITLE
NoSlow bypass

### ISSUE THREAD

**Issue by Dbbtop** [GrimAnticheat/Grim#1444]
### Describe the bypass and how to replicate it

import net.minecraft.item.Items;
import net.minecraft.network.packet.c2s.play.PlayerActionC2SPacket;
import net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket;
import net.minecraft.network.packet.c2s.play.PlayerInteractItemC2SPacket;
import net.minecraft.network.packet.c2s.play.UpdateSelectedSlotC2SPacket;
import net.minecraft.util.Hand;
import net.minecraft.util.hit.BlockHitResult;
import net.minecraft.util.math.Direction;

if (mc.player.isUsingItem() && !mc.player.isRiding() && !mc.player.isFallFlying()) {
            switch (mode.getValue()) {
case GrimNew -> {
                    if (mc.player.getActiveHand() == Hand.OFF_HAND) {
                        sendPacket(new UpdateSelectedSlotC2SPacket(mc.player.getInventory().selectedSlot % 8 + 1));
                        sendPacket(new UpdateSelectedSlotC2SPacket(mc.player.getInventory().selectedSlot));
                    } else if (mainHand.getValue() && (mc.player.getItemUseTime() <= 3 || mc.player.age % 2 == 0)) {
                        sendSequencedPacket(id -> new PlayerInteractItemC2SPacket(Hand.OFF_HAND, id));
                    }
                }
}

### Grim version

latest

### Server version

purpur 1.17.1

### Plugins

grim, protocolLib

**Comment by ManInMyVan** [comment]
Could be patched by #1445

**Comment by Dbbtop** [comment]
> Could be patched by #1445

in main hand not fixed

**Comment by ManInMyVan** [comment]
We could patch this by setting the server using state to false before handling a use packet
