### ISSUE TITLE
Flagged on toggle flight when on grounding

### ISSUE THREAD

**Issue by Currypan1229** [GrimAnticheat/Grim#1447]
### Describe the false positive and how to replicate it

https://github.com/GrimAnticheat/Grim/assets/67533379/8f08b728-3ff2-472d-b92e-e5a3c9c023b7

1. set gamemode to creative
2. enable fly
3. disable fly
4. enable fly when u on ground

### Grim version

fa77a80ae161fbd9d7f130329800dfe05971e9eb
2.3.62

### Server version

1.20.4

### Plugins

GrimAC

**Comment by SamB440** [comment]
Duplicate. See https://github.com/GrimAnticheat/Grim/issues/1441#issuecomment-2075177794

**Comment by bbb908** [comment]
yeah this has been a thing for ages
