### ISSUE TITLE
1.20.5

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1448]
### Feature description

🙏

**Comment by ghost** [comment]
once packet events is released ofc, could work with this fork which is about to be merged for 1.20.5 support https://github.com/booky10/packetevents/tree/dev/1.20.5
https://github.com/retrooper/packetevents/pull/658

**Comment by SamB440** [comment]
I already started work on this in #1439

**Comment by Symmettry** [comment]
I think this is implemented by #1439 so should it be closed or is there any other 1.20.5 thing needing fix?

**Comment by SamB440** [comment]
I'm considering this complete, as we are also approaching 1.21 now, any further problems should get their own issue.
