### ISSUE TITLE
False Positive Detection with Aquatic Helmet in Grim Anticheat

### ISSUE THREAD

**Issue by DimaSergeew** [GrimAnticheat/Grim#1453]
### Describe the false positive and how to replicate it

I encountered a false positive detection issue with the Grim Anticheat, version 2.3.62, on my Purpur server (version 1.20.4). The problem arises when a player equips a helmet enchanted with Aqua Affinity III. Specifically, when the player who is wearing this helmet starts moving underwater, the anti-cheat system erroneously flags and blocks them for a "simulation violation". This issue can be consistently replicated by following these steps:
Ensure Grim Anticheat 2.3.62 is installed and active on a server running Purpur 1.20.4.
Equip a helmet with the Aqua Affinity III enchantment.
Enter any body of water and start moving underwater.
Observe the anti-cheat alerts for a simulation violation concerning the player's movement.

### Grim version

2.3.62

### Server version

Purpur 1.20.4

### Plugins

-

**Comment by SamB440** [comment]
Aqua Affinity doesn't affect movement, this issue doesn't make sense

**Comment by Symmettry** [comment]
Just tested and I can confirm that... you're bullshitting. Aqua affinity does not flag. Neither does depth strider or any other underwater enchant.
