### ISSUE TITLE
Non Bukkit server support

### ISSUE THREAD

**Issue by MelonHell** [GrimAnticheat/Grim#1471]
### Feature description

I took a quick look at the sources and see that BukkitAPI is almost never used. Our server is written in Minestom and we would really like to use this anti-cheat. As I understand it, anti-cheat works as an intermediary between packets, and in this case it would be convenient to install anti-cheat on Velocity

**Comment by SamB440** [comment]
This isn't going to happen without a significant rewrite. Bukkit is still fundamentally used in the plugin. I myself am working on a multiplatform ac but it is not publicly available yet.

I imagine if someone were to attempt this it would be better to wait for Grim 3.0

However, you are talking about minestom, and unfortunately, **Minestom is not supported by packetevents** at this time, so that would need to be done too. Also proxy wouldn't work, Grim uses some server events like piston pushing.

**Comment by vytskalt** [comment]
> I imagine if someone were to attempt this it would be better to wait for Grim 3.0

AFAIK 3.0 isn't going to be open source

**Comment by AoElite** [comment]
No plans are to be made to support minestorm

**Comment by MelonHell** [comment]
> No plans are to be made to support minestorm

This is not about supporting Minestom, but about separating from Bukkit so that third-party developers can write platform implementations

**Comment by MelonHell** [comment]
It seems to me that it would be an excellent solution to transfer grim to a proxy, this will allow it to support any platforms

**Comment by AoElite** [comment]
There's issues running it solely on proxies. Like not being able to retrieve the server's state.

**Comment by MelonHell** [comment]
In any case, the server sends all information in packets. Using a proxy will allow you to connect anti-cheat to any servers, even those not written in java

**Comment by MelonHell** [comment]
Personally, I would generally make anti-cheat as a separate service. For example, the connection will look like this: 
`Velocity/Bungee -> AntiCheat -> Minestom/Bukkit/Fabric/Sponge/Vanilla`

**Comment by AoElite** [comment]
Feel free to fork if you desire.

**Comment by MelonHell** [comment]
Maybe I'll try it when I have free time

**Comment by Danieljunek17** [comment]
is there any progress made on this since I would like to use it on minestom and I was thinking about forking it but if you think you can make your concept work without significantly adding ping or performance penalties @MelonHell I Whould really like to see something like that.
