### ISSUE TITLE
baritone

### ISSUE THREAD

**Issue by A4Jirka** [GrimAnticheat/Grim#1473]
### Describe the false positive and how to replicate it

when you have optifine on your client and you zoom the anticheat will give you so many warns that it autobans you

### Grim version

2.3.6.5

### Server version

git-Paper-550 (MC: 1.19.4),    git-Paper-496 (MC: 1.20.4)

### Plugins

Server Plugins (48):
Bukkit Plugins:
 - ajLeaderboards, AntiCrasher, ArmorStandTools, BetterShulkerBoxes, CataMines, Citizens, ClearLag, CMI, CMILib, CoreProtect
DecentHolograms, DeluxeCombat, *DeluxeCombatFlags, DeluxeMenus, Duels, eShulkerBox, ExcellentCrates, FastAsyncWorldEdit, GrimAC, HeadDB
InventoryRollbackPlus, ItemEdit, JPremium, LibsDisguises, LiteBans, LuckPerms, MineBlocks, Multiverse-Core, nightcore, NoteBlockAPI
PlaceholderAPI, *PlayTime, PlugManX, PremiumVanish, ProtocolLib, Shopkeepers, SkinsRestorer, SuperbVote, TAB, Tebex
ToastedAFK, TradeSystem, ViaBackwards, ViaVersion, VoidGen, VoteParty, Votifier, WorldGuard

**Comment by Anthony01M** [comment]
FP of Baritone mentioned in #1432  
I recommend disabling Baritone fully.
