### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 1hendex** [GrimAnticheat/Grim#1483]
### Stack trace

https://pastes.dev/w0hYz1OQge

### How to replicate it if known

1. Join to server

### Grim version

lastest (2.3.64)

### Server version

Dionusys 1.12.2 (17 Java)

### Plugins

GrimAC

**Comment by SamB440** [comment]
This doesn't seem possible unless your server is sending an attribute that doesn't exist, or there is a packetevents bug

**Comment by 1hendex** [comment]
This was not the case in the previous version

**Comment by envizar** [comment]
Similar error
https://hastebin.com/share/ukubufaziw.php

**Comment by SamB440** [comment]
Fixed in aa6d7c22b87e852d1a9724a70f9a2049102fe5d5
