### ISSUE TITLE
Many false positives in the version 2.3.64

### ISSUE THREAD

**Issue by ChrisTVH** [GrimAnticheat/Grim#1484]
### Describe the false positive and how to replicate it

Usually something like this happens, which leaves my players blocked and others take advantage to kill them by being left like this.
![sshot-047](https://github.com/GrimAnticheat/Grim/assets/58376852/30844fc7-8f72-4fd4-adb9-39ab55c61bcb)

This happens regardless of whether they use vanilla, badlion or fabric etc. clients.
Your version, they are all usually on 1.20.3/1.20.4?

### Grim version

First of all, I don't know if the version is misspelled spigot or hangar, but that's the one I use.
![image](https://github.com/GrimAnticheat/Grim/assets/58376852/bcad1b70-0a74-4b23-987b-f74ef34ec28e)
![image](https://github.com/GrimAnticheat/Grim/assets/58376852/d5df8d67-1897-49fb-b844-c172287ac668)

### Server version

Since I upgraded grimac to this version it is full of too many false positives, this is the version of my server.
![image](https://github.com/GrimAnticheat/Grim/assets/58376852/9c111e52-695e-47a5-8126-5431f042ee55)

### Plugins

And these are my plugins, in case something conflicts.
![image](https://github.com/GrimAnticheat/Grim/assets/58376852/01b361c2-3c91-422d-b865-8ecd00164211)

**Comment by ChrisTVH** [comment]
Here is a collection of the most recent false positives.
![image](https://github.com/GrimAnticheat/Grim/assets/58376852/baf49614-9d2c-4a85-8afb-cc0a6584a7cf)
![image](https://github.com/GrimAnticheat/Grim/assets/58376852/fadd0997-cb1b-44e2-b801-b169f3760ebd)
![image](https://github.com/GrimAnticheat/Grim/assets/58376852/d7425e74-61ca-47c7-be61-8d0012eb4546)
![image](https://github.com/GrimAnticheat/Grim/assets/58376852/b5183fa5-506f-40e9-91c5-3d5962cbe49b)
![image](https://github.com/GrimAnticheat/Grim/assets/58376852/ec61f738-3052-4cda-9c3a-0d5945077c12)
![image](https://github.com/GrimAnticheat/Grim/assets/58376852/23779733-39fb-442a-9ef1-64a8904ab027)
![image](https://github.com/GrimAnticheat/Grim/assets/58376852/e5d8a8a8-9040-45c1-8273-c12659b85789)
![image](https://github.com/GrimAnticheat/Grim/assets/58376852/104fa0ae-af00-447e-80b9-5304d5f50f6d)
![image](https://github.com/GrimAnticheat/Grim/assets/58376852/2dba1090-1fb0-461b-ac7a-dc44e7647dee)
![image](https://github.com/GrimAnticheat/Grim/assets/58376852/a9f6ef6c-1d4e-408c-90e3-b08dbb3689c2)
![image](https://github.com/GrimAnticheat/Grim/assets/58376852/05af4e63-6b85-4212-b361-14b2e938e808)

**Comment by ChrisTVH** [comment]
And there are many more besides those.

**Comment by SamB440** [comment]
Need more info such as when this happens, have you tried without plugins, as this can't be reproduced.

**Comment by ChrisTVH** [comment]
> Need more info such as when this happens, have you tried without plugins, as this can't be reproduced.

It just happens, the player is walking normally and at a random moment he freezes.
For now I have reverted to an earlier version of anticheat, version 2.3.62, where it works fine.

**Right now I have a suspicion with ItemEditor objects, specifically objects that modify the player's speed or give other certain effects.**

**Comment by SamB440** [comment]
I would be surprised if movement speed attributes were broken considering that specific part of the code hasn't been touched

**Comment by ChrisTVH** [comment]
> I would be surprised if movement speed attributes were broken considering that specific part of the code hasn't been touched

Is there a way to have more detailed records that are not individual per player?

**Comment by SamB440** [comment]
No, I really don't see anything in the changelog that could cause this.

Can you try two commits?

https://github.com/GrimAnticheat/Grim/actions/runs/9047426271
https://github.com/GrimAnticheat/Grim/actions/runs/8978196965

And tell me if the issue occurs on them

**Comment by ChrisTVH** [comment]
> No, I really don't see anything in the changelog that could cause this.
> 
> Can you try two commits?
> 
> https://github.com/GrimAnticheat/Grim/actions/runs/9047426271 https://github.com/GrimAnticheat/Grim/actions/runs/8978196965
> 
> And tell me if the issue occurs on them

I've been testing with this commit and it's working fine so far, I've been checking for more than 1 hour.
https://github.com/GrimAnticheat/Grim/actions/runs/9047426271

**Comment by SamB440** [comment]
Don't bother with the other commit then, the issue isn't with my 1.20.5 pr or packetevents

**Comment by ChrisTVH** [comment]
> Don't bother with the other commit then, the issue isn't with my 1.20.5 pr or packetevents

Okay, so that rules out a few things.

**Comment by SamB440** [comment]
Try https://github.com/GrimAnticheat/Grim/actions/runs/9210861271

**Comment by envizar** [comment]
Same issue
grim 3.3.64, paper 1.20.6

**Comment by SamB440** [comment]
> Same issue grim 3.3.64, paper 1.20.6

This doesn't help, check if you have anything in common such as plugins or when it happens

**Comment by envizar** [comment]
> > Same issue grim 3.3.64, paper 1.20.6
> 
> This doesn't help, check if you have anything in common such as plugins or when it happens

I have CMI, FancyNPCs, FAWE, LuckPerms, ProtocolLib, Vault, PlaceholderAPI
Maybe CMI or FancyNPCs causing this

**Comment by ChrisTVH** [comment]
> Try https://github.com/GrimAnticheat/Grim/actions/runs/9210861271

I've been testing it for quite a few hours now and yes, there are problems with that commit, lots of false positives.
On top of that it even gets buggy when my players get tp.
also tell me what happened in the previous one you gave me to test.

**Comment by SamB440** [comment]
Do you have a plugin respawning players a lot? My guess is sprinting becomes desynced due to an oversight I made. But if the player just toggles sprint then it should be fine...?

Try https://github.com/SamB440/Grim/actions/runs/9245737334

> also tell me what happened in the previous one you gave me to test.

Unsure what you are referring to

**Comment by ChrisTVH** [comment]
> Do you have a plugin respawning players a lot? My guess is sprinting becomes desynced due to an oversight I made. But if the player just toggles sprint then it should be fine...?
> 
> Try https://github.com/SamB440/Grim/actions/runs/9245737334
> 
> > also tell me what happened in the previous one you gave me to test.
> 
> Unsure what you are referring to

You mean reappear a lot by dying and reviving?

**Comment by ChrisTVH** [comment]
This says one of my players:

When you put any tp command, either home, ps home or warp.
I can't move
And the camera starts to bug too
Having to go to the lobby and back

**Comment by ChrisTVH** [comment]
I'll be checking how the build you gave me works, I'll let you know how it goes.

**Comment by ChrisTVH** [comment]
It seems that now after the change you made it is going well, now the false positives are more real, as I have only seen false positives with people who have real lagg.

For now I'm told it's going well, with more than 40 active users, anything else I'll let you know here.

**Comment by SamB440** [comment]
Fixed by #1494 and #1488
