### ISSUE TITLE
BadPacketsW EnderDragon entity false

### ISSUE THREAD

**Issue by Ayouuuu** [GrimAnticheat/Grim#1496]
### Describe the false positive and how to replicate it

1. Summon ender dragon
2. Hit it

 Because grim player [CompensatedEntities](https://github.com/GrimAnticheat/Grim/blob/2.0/src/main/java/ac/grim/grimac/utils/latency/CompensatedEntities.java#L28-#L29) can't get entity by id that dragon body,wings,head. see [Interact Packet](https://wiki.vg/Protocol#Interact) 

### Grim version

2.3.64

### Server version

1.20.1 Paper

### Plugins

None

**Comment by jonesdevelopment** [comment]
Can confirm (1.20.4 Paper server)

**Comment by SamB440** [comment]
There's no clean way to fix this, I think the only way is to keep a list of ender dragons (looping through the entire entity list every hit would be bad for performance) and check if the entity id is within range of any of those dragon ids.

Or maybe we can populate the entity list with fake dragon parts? I don't think the server should ever send an entity id within the 8 ids if we did that, right?
