### ISSUE TITLE
Alert of minerals that players break

### ISSUE THREAD

**Issue by ChrisTVH** [GrimAnticheat/Grim#1499]
### Feature description

I wonder if they could add an alert that can be turned on or off and have a whitelist on which worlds it should work plus a command to use it individually with each play and also to turn the alert on or off.

One of my moderators has been screaming to me that we should have something like this, it would be great if it came implemented with the anticheat.

In short, an alert notifying which ores are being mined by players.

**Comment by ManInMyVan** [comment]
Something like [ajAntiXray](https://www.spigotmc.org/resources/ajantixray.68409/) would probably be fine

**Comment by ChrisTVH** [comment]
> Something like [ajAntiXray](https://www.spigotmc.org/resources/ajantixray.68409/) would probably be fine

Yes, I think that's just what I need, thank you.
Sorry for the inconvenience.

**Comment by ManInMyVan** [comment]
> Yes, I think that's just what I need, thank you.

Can you close this then?
