### ISSUE TITLE
GroundSpoof & BadPacketsN false

### ISSUE THREAD

**Issue by matsu1213** [GrimAnticheat/Grim#1501]
### Describe the false positive and how to replicate it

Step 1. Relative teleport(shooting a  gun)
Step 2. Sometimes GroundSpoof false(, then BadPacketsN false on 1.12.2)
Step 3. To make matters worse, this causes a chunk rendering bug on 1.12.2
https://youtu.be/kczgM99qLbc?si=VUXLjtkXps59o4pK&t=66

![2024-05-29_19 56 15](https://github.com/GrimAnticheat/Grim/assets/85377530/3d986fa6-dfd0-4f42-8ba3-5e18eb430c61)

Also confirmed on 1.16.5, 1.18.2(But no false for BadPacketsN)
https://paste.grim.ac/dj44ir3

### Grim version

grim 2.3.62

### Server version

git-Paper-1620 1.12.2

### Plugins

AdvancedScope, Crackshot, CrackShotPlus, DiscordSRV, GrimAC, LuckPerms, Multiverse-Core, MythicMobs, PlugMan, Protocollib, Vault, Viaversion, Votifer, WorldEdit, WorldGuard

**Comment by SamB440** [comment]
Make sure you don't have via* installed on the proxy

**Comment by Dg32z** [comment]
> 确保您没有在代理上安装 via*

![QQ截图20240529222752](https://github.com/GrimAnticheat/Grim/assets/100349169/44c1d9b6-cfa8-4d25-a6be-35420121360e)

**Comment by matsu1213** [comment]
> Make sure you don't have via* installed on the proxy

no

**Comment by matsu1213** [comment]
~~My guess is that this occurs when the client's performance decreases.~~ The more players there are, the more frequently it happens. Some players experience this issue frequently, while others do not experience it at all.

**Comment by matsu1213** [comment]
I need an option to disable BadPacketsN.

**Comment by SamB440** [comment]
Performance does not affect this check. You don't want to disable BadPacketsN, that's an instant disabler.

**Comment by matsu1213** [comment]
more info (1.12.2)
![image](https://github.com/GrimAnticheat/Grim/assets/85377530/bae49083-6b5a-4a1e-8a1d-f451b81b2b07)
https://paste.grim.ac/y71hnve (/gl 130)

**Comment by matsu1213** [comment]
![image](https://github.com/GrimAnticheat/Grim/assets/85377530/e009af3f-c028-415c-9f88-bc65ccf50940)

**Comment by SamB440** [comment]
I'm using `/tp ~ ~ ~1` (with various values) for relative teleport and I can't reproduce this with Grim + latest via from https://ci.viaversion.com/job/ViaVersion-DEV/ on a 1.12.2 server with 1.20.6, 1.16.5, 1.12.2 client

**Comment by SamB440** [comment]
Should be fixed by 9be1688af0a751cb81935d20f76bd2b8a0cf954d, although you probably need #1483 to be able to update.

**Comment by SamB440** [comment]
You should be able to use the latest commit.

**Comment by matsu1213** [comment]
![2024-07-09_17 36 02](https://github.com/GrimAnticheat/Grim/assets/85377530/db9a0542-abdf-42fa-b9fc-e7640e037672)

This still false on latest commit. (I added some debug info)
