### ISSUE TITLE
Severe false positive with Breeze wind cause trial dungeon is not playable

### ISSUE THREAD

**Issue by KujouMolean** [GrimAnticheat/Grim#1503]
### Describe the false positive and how to replicate it

1.start a brand new server, edit server.properties, set initial-enabled-packs=vanilla,update_1_21 and delete all world(regen)
2.summon a Breeze 
3.toggle survival mode
4.attacked by Breeze, then player can't move for several seconds

### Grim version

2.3.64

### Server version

This server is running Folia version 1.20.6-DEV-dev/1.20.6@78f49e0 (2024-05-20T08:29:50Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version
Previous version: git-Folia-"e97b1ee" (MC: 1.20.4)

### Plugins

only GrimAC

**Comment by SamB440** [comment]
Should be fixed by 7d287686630ae0ade924b8d2ba67c441b3c42881
