### ISSUE TITLE
Simulation&GroundSpoof False Flag

### ISSUE THREAD

**Issue by Dg32z** [GrimAnticheat/Grim#1507]
### Describe the false positive and how to replicate it

Logs: https://paste.grim.ac/7kdmhgb

### Grim version

grimac-2.3.64

### Server version

>ver
[13:20:25 INFO]: This server is running CraftBukkit version git-PaperSpigot-f6fba00-9935adc (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### Plugins

Plugins (8): PlugMan, ViaVersion, PlugManX, LiteBans, PlaceholderAPI, ProtocolLib, LuckPerms, GrimAC

ViaVersion : 4.9.3
ProtocolLib: 5.1.0

**Comment by SamB440** [comment]
Simulation falses must include a grim log. Your video doesn't seem to work, either.

**Comment by Dg32z** [comment]
> 模拟假字必须包含严峻的日志。您的视频似乎也不起作用。

https://paste.grim.ac/7kdmhgb
