### ISSUE TITLE
BadPacketsX and AirLiquidPlace false flag

### ISSUE THREAD

**Issue by cubk1** [GrimAnticheat/Grim#1508]
### Describe the false positive and how to replicate it

Video: https://www.youtube.com/watch?v=ybu9m79lSfw

replicated on vanilla/forge without mods 1.18.1 and 1.20.4

### Grim version

2.3.64

### Server version

1.8.8 (mc.loyisa.cn)

### Plugins

ViaVersion 4.10.2

**Comment by SamB440** [comment]
#1472
