### ISSUE TITLE
Simulation&GroundSpoof False Flag

### ISSUE THREAD

**Issue by Dg32z** [GrimAnticheat/Grim#1509]
### Describe the false positive and how to replicate it

https://github.com/GrimAnticheat/Grim/assets/100349169/520c50f1-31f2-45f2-8c4c-e03058efe241

SimulationLogs: https://paste.grim.ac/7kdmhgb

### Grim version

grimac-2.3.64

### Server version

ver
[13:20:25 INFO]: This server is running CraftBukkit version git-PaperSpigot-f6fba00-9935adc (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### Plugins

Plugins (8): PlugMan, ViaVersion, PlugManX, LiteBans, PlaceholderAPI, ProtocolLib, LuckPerms, GrimAC

ViaVersion : 4.9.3
ProtocolLib: 5.1.0

**Comment by SamB440** [comment]
For some reason Firefox doesn't work with your video, but anyway, don't expect this to be fixed any time soon as this is a fence connection desync caused by legacy versions

**Comment by xEcho1337** [comment]
> For some reason Firefox doesn't work with your video, but anyway, don't expect this to be fixed any time soon as this is a fence connection desync caused by legacy versions

I fixed this issue on my private fork, the client never connects a fence with a farmland
