### ISSUE TITLE
Speed bypass

### ISSUE THREAD

**Issue by Dbbtop** [GrimAnticheat/Grim#1511]
### Describe the bypass and how to replicate it

if ((mode.is(Mode.GrimEntity2)|| mode.is(Mode.GrimCombo)) && MovementUtility.isMoving()) {
            int collisions = 0;
            for (Entity ent : mc.world.getEntities())
                if (ent != mc.player && (ent instanceof LivingEntity || ent instanceof BoatEntity) && mc.player.getBoundingBox().expand(1.0).intersects(ent.getBoundingBox()))
                    collisions++;

            double[] motion = MovementUtility.forward(0.08 * collisions);
            mc.player.addVelocity(motion[0], 0.0, motion[1]);
        }

### Grim version

2.3.64

### Server version

1.17.1

### Plugins

GrimAC PacketEvents

**Comment by overkidding** [comment]
https://github.com/SamB440/Grim/commit/564df0af7a87f7b11a5f264044a93755c4bd5b45

this should fix it

(probably its still experimental)

**Comment by SamB440** [comment]
It's not possible to fix without falses during tick skipping because of missing idle packet, if this were to be fixed people would have to accept it can false in certain scenarios

**Comment by SamB440** [comment]
I will try to calculate the theoretical maximum velocity the player could achieve whilst being pushed, although I haven't had much success with that before

**Comment by overkidding** [comment]
> It's not possible to fix without falses during tick skipping because of missing idle packet, if this were to be fixed people would have to accept it can false in certain scenarios

i think a fix that falses a little is better than a bypass that gives advantages
