### ISSUE TITLE
False positive: mcMMO - BadPacketsZ

### ISSUE THREAD

**Issue by jonesdevelopment** [GrimAnticheat/Grim#1512]
### Describe the false positive and how to replicate it

1. Use the Super Breaker ability in mcMMO

Would there be the possibility for Grim to support mcMMO abilities?
We temporarily fixed this issue by disabling BadPacketsZ.

![image](https://github.com/GrimAnticheat/Grim/assets/73846784/ba4592e6-f96f-4efe-887b-88ea65559c80)

### Grim version

Grim 2.3.65

### Server version

```
Current: git-Purpur-2176 (MC: 1.20.4)*
Previous: git-Purpur-2169 (MC: 1.20.4)
* You are running the latest version
```

### Plugins

![image](https://github.com/GrimAnticheat/Grim/assets/73846784/468c01c4-b0ad-49fa-a5f7-d1c7b9bb953c)

**Comment by ManInMyVan** [comment]
does this fix it? https://github.com/ManInMyVan/Grim/tree/test/bpZ

**Comment by Dynamic-Gravity** [comment]
I just compiled the jar and uploaded it to my server to test. I'll let you know by tomorrow afternoon.

**Comment by jonesdevelopment** [comment]
> does this fix it? https://github.com/ManInMyVan/Grim/tree/test/bpZ

It seems like the Super Breaker issue is fixed with your custom version, however, I randomly flagged it while I was mining:

![image](https://github.com/GrimAnticheat/Grim/assets/73846784/3d385933-716f-4682-bb7b-e287e1033051)

I was just mining a stone block in front of me while walking forward. It flags when it sometimes teleports me back when I mine the block.

**Comment by SamB440** [comment]
I haven't followed the logic of the check entirely, but, flagging for start digging seems dubious considering the client can fail to send a packet to signify digging stopped.

**Comment by ManInMyVan** [comment]
> It seems like the Super Breaker issue is fixed with your custom version, however, I randomly flagged it while I was mining:
> 
> ![image](https://github.com/GrimAnticheat/Grim/assets/73846784/3d385933-716f-4682-bb7b-e287e1033051)
> 
> I was just mining a stone block in front of me while walking forward. It flags when it sometimes teleports me back when I mine the block.

I'll pull this later without the start breaking check (unless if I fix it)
