### ISSUE TITLE
BadPacketsW on Ender Dragon

### ISSUE THREAD

**Issue by Dbbtop** [GrimAnticheat/Grim#1514]
### Describe the false positive and how to replicate it

when hitting an ender dragon, the damage is canceled
![image](https://github.com/GrimAnticheat/Grim/assets/149936791/52472cec-cf95-435b-8683-943a4e01bca3)

### Grim version

2.3.64

### Server version

1.17.1

### Plugins

grim, PacketEvents

**Comment by SamB440** [comment]
#1496
