### ISSUE TITLE
Simulation w/ beds 1.7

### ISSUE THREAD

**Issue by ManInMyVan** [GrimAnticheat/Grim#1520]
### Describe the false positive and how to replicate it

walk into a bed

I think 1.7 player's step height is 0.5 instead of 0.6 (can someone with 1.7 src verify this?)

debug: https://streamable.com/pus8iv
no debug: https://streamable.com/rhe6g1
gl 98: https://paste.grim.ac/l8ictbi

### Grim version

d108355

### Server version

paper 1.8.8

### Plugins

spark, FastAsyncWorldEdit, ViaVersion, ViaBackwards, ProtocolLib, ViaRewind, LuckPerms, WorldEdit, Vault, WorldGuard, Essentials

**Comment by SamB440** [comment]
https://github.com/MCP-Decompiled/1.7.10-12/blob/1b1a78fd6857744146b485c8eb8651d04375ec20/src/minecraft/net/minecraft/entity/EntityLivingBase.java#L124

**Comment by SamB440** [comment]
https://github.com/GrimAnticheat/Grim/commit/b5060a64de6a3a504825528c5ebcb1cb8bf2296e
