### ISSUE TITLE
grim boat jump 

### ISSUE THREAD

**Issue by djw27921** [GrimAnticheat/Grim#1522]
### Describe the bypass and how to replicate it

video 
fdp client boatjump 
(mode matrix )(timer 1)
(2vl)
https://github.com/GrimAnticheat/Grim/assets/96292502/4e368e00-db69-43ea-bdff-73c90e6c96e0

### Grim version

loyisa's testserver

### Server version

1.8.9

### Plugins

grim ......

**Comment by ManInMyVan** [comment]
#1176?
