### ISSUE TITLE
Is this for Paper or Fabric?

### ISSUE THREAD

**Issue by Decme** [GrimAnticheat/Grim#1525]
### Feature description

I googled "fabric mc anticheat" and the rabbit hole led me here. I know Grim is for Paper, but I'm hoping a Fabric version exists as well.

**Comment by SamB440** [comment]
I think someone tried to make a fabric port but I don't know of any completed or active ones

**Comment by ManInMyVan** [comment]
You *might* be able to get it to work with [cardboard](https://cardboardpowered.org/), although I doubt you'll get much support.
