### ISSUE TITLE
speed

### ISSUE THREAD

**Issue by Dbbtop** [GrimAnticheat/Grim#1526]
### Describe the bypass and how to replicate it

private void handlePacketEvent(EventPacket e) {
        if (this.spdMode.is("RW")) {
            IPacket<IServerPlayNetHandler> p;
            IPacket iPacket = e.getPacket();
            if (iPacket instanceof CConfirmTransactionPacket) {
                p = (CConfirmTransactionPacket)iPacket;
                e.setCancel(true);
            }
            if ((iPacket = e.getPacket()) instanceof SPlayerPositionLookPacket) {
                p = (SPlayerPositionLookPacket)iPacket;
                SpeedFunction.mc.player.func_242277_a(new Vector3d(((SPlayerPositionLookPacket)p).getX(), ((SPlayerPositionLookPacket)p).getY(), ((SPlayerPositionLookPacket)p).getZ()));
                SpeedFunction.mc.player.setRawPosition(((SPlayerPositionLookPacket)p).getX(), ((SPlayerPositionLookPacket)p).getY(), ((SPlayerPositionLookPacket)p).getZ());
                this.toggle();
            }
        }
    }

    private void handleRWMode() {
        if (this.timerUtil.hasTimeElapsed(1150L)) {
            this.boosting = true;
        }
        if (this.timerUtil.hasTimeElapsed(7000L)) {
            this.boosting = false;
            this.timerUtil.reset();
        }
        if (this.boosting) {
            if (SpeedFunction.mc.player.isOnGround() && !SpeedFunction.mc.gameSettings.keyBindJump.pressed) {
                SpeedFunction.mc.player.jump();
            }
            SpeedFunction.mc.timer.timerSpeed = SpeedFunction.mc.player.ticksExisted % 2 == 0 ? 1.5f : 1.2f;
        } else {
            SpeedFunction.mc.timer.timerSpeed = 0.05f;
        }
    }

### Grim version

2.3.64

### Server version

1.17.1

### Plugins

grim, packetevents

**Comment by ghost** [comment]
send video

**Comment by Dbbtop** [comment]
> send video


https://github.com/GrimAnticheat/Grim/assets/149936791/c68a508f-59d6-4587-b5e0-950b37c2fcff

**Comment by SamB440** [comment]
This is just timer abuse
