### ISSUE TITLE
Incorrect Version Title on SpigotMC Website

### ISSUE THREAD

**Issue by Arthurmeade12** [GrimAnticheat/Grim#1532]
### Feature description

Correct me if I am wrong, but the major version on the spigot website is listed as 3.3.64 instead of 2.3.64. I would make a post on Spigot but I don't have a Spigot account.

Thanks!
![Screenshot_20240612_173843](https://github.com/GrimAnticheat/Grim/assets/71673838/eeed71ed-c984-47b6-b1ee-1f98842d5037)

**Comment by MWHunter** [comment]
grim 3 leak 100% real no virus

**Comment by Anthony01M** [comment]
fixed in latest release, please close this.
