### ISSUE TITLE
Better exempt player

### ISSUE THREAD

**Issue by toidicakhia** [GrimAnticheat/Grim#1533]
### Feature description

Exempt a player in real time without rejoin server

**Comment by Anthony01M** [comment]
Without killing server performance, I don't see a way to do so...
In other words: won't happen.

**Comment by SamB440** [comment]
What's your usecase?

**Comment by PaguroCavaliere** [comment]
Just rejoin the server, it will takes you 2 seconds in the worst scenario

**Comment by Anthony01M** [comment]
> What's your usecase?

> Just rejoin the server, it will takes you 2 seconds in the worst scenario

@toidicakhia

**Comment by ManInMyVan** [comment]
Luckperms has events, so we could use those, idk about contexts tho

**Comment by Anthony01M** [comment]
there's really absolutely no reason to do this, this is not what an
anti-cheat should handle imo, reconnecting should solve the issue which a
lot of plugins also require you to reconnect to be exempt, additional
features to grim like this might not actually be good for the AC itself.
