### ISSUE TITLE
OMG GRIM 3.3.64

### ISSUE THREAD

**Issue by YoSoyEse** [GrimAnticheat/Grim#1534]
### Describe the bypass and how to replicate it

OOOOOOOOOOOOOOOONG GRIM LATEST NEW GRIM  BEST MEGA UPDATE FR !!111!!!! 
![grim downs](https://github.com/GrimAnticheat/Grim/assets/144266886/1200c64b-cbe6-4452-b0e5-69b686135ab7)

### Grim version

3.3.64

### Server version

XD

### Plugins

XD

**Comment by Benhakx** [comment]
frfr

**Comment by Anthony01M** [comment]
Why is this under bypass?
also #1532
