### ISSUE TITLE
BadPacketsW PAINTING entity false

### ISSUE THREAD

**Issue by Ayouuuu** [GrimAnticheat/Grim#1536]
### Describe the false positive and how to replicate it

1. place a painting
2. attack or interact it

### Grim version

2.3.65

### Server version

Paper 1.20.4

### Plugins

None

**Comment by Anthony01M** [comment]
cannot reproduce;
Server: Purpur 1.20.4; Client: 1.20.6, 1.20.4, 1.20.1

**Comment by Ayouuuu** [comment]
> cannot reproduce; Server: Purpur 1.20.4; Client: 1.20.6, 1.20.4, 1.20.1

packet events fixed that problem
