### ISSUE TITLE
1.21 support

### ISSUE THREAD

**Issue by fucksophie** [GrimAnticheat/Grim#1537]
### Feature description

Support minecraft 1.21

**Comment by jonesdevelopment** [comment]
https://github.com/retrooper/packetevents/pull/732

**Comment by SamB440** [comment]
Have fun implementing whatever getPointPositions is.

https://github.com/GrimAnticheat/Grim/commit/c6abf493ae0431c8e0e05463d298527eed776b2c#diff-c50b448db26c85ed0958fa3f54077a5426641cd6505122999a4d71c3063afc01R184-R187

**Comment by mucookul** [comment]
Wait quick question: If I'm using 1.20.6 and ViaVersion, then will 1.21 players get flagged or will it work

**Comment by ManInMyVan** [comment]
> Wait quick question: If I'm using 1.20.6 and ViaVersion, then will 1.21 players get flagged or will it work

It should work as long as you use the latest commit

**Comment by xEcho1337** [comment]
@SamB440 should this issue be closed?
