### ISSUE TITLE
A strange warning that I happened to see

### ISSUE THREAD

**Issue by ChrisTVH** [GrimAnticheat/Grim#1538]
### Stack trace

https://mclo.gs/4IA3VCO

### How to replicate it if known

It just happens, that's all.

### Grim version

Grimac-2.3.64

### Server version

![image](https://github.com/GrimAnticheat/Grim/assets/58376852/72fae74a-01fa-46d7-9407-01e8883eff8c)

### Plugins

![image](https://github.com/GrimAnticheat/Grim/assets/58376852/912a55f0-cc33-44c4-97ae-5ca1adfae747)

**Comment by ChrisTVH** [comment]
I'm here reporting this, because maybe you might be interested to know what it is, just in case.

**Comment by ChrisTVH** [comment]
To be more specific, this is the version I use from grimac:  https://github.com/GrimAnticheat/Grim/pull/1494 and https://github.com/GrimAnticheat/Grim/pull/1488

**Comment by SamB440** [comment]
Try updating to the latest commit, there's a difference in packetevents versions since then

**Comment by ChrisTVH** [comment]
> Try updating to the latest commit, there's a difference in packetevents versions since then

I will do so.

**Comment by ChrisTVH** [comment]
By the way, where were the artifacts located?

**Comment by SamB440** [comment]
You mean these? https://github.com/GrimAnticheat/Grim/actions/runs/9528926240

**Comment by ChrisTVH** [comment]
> You mean these? https://github.com/GrimAnticheat/Grim/actions/runs/9528926240

Yes, that's right.

**Comment by Anthony01M** [comment]
@ChrisTVH does this still happen? If not please close this.

**Comment by ChrisTVH** [comment]
I thought they had already closed this and forgot about it, since then nothing has happened, it works very well.
