### ISSUE TITLE
Grim Velocity

### ISSUE THREAD

**Issue by Dbbtop** [GrimAnticheat/Grim#1542]
### Describe the bypass and how to replicate it

if (e.getPacket() instanceof EntityVelocityUpdateS2CPacket pac) {
            if (pac.getId() == mc.player.getId() && (!onlyAura.getValue() || ModuleManager.aura.isEnabled())) {
                switch (mode.getValue()) {case GrimNew -> {
                        e.cancel();
                        flag = true;
                    }
if (e.getPacket() instanceof ExplosionS2CPacket explosion && explosions.getValue()) {
 switch (mode.getValue()) {case GrimNew -> {
                    ((IExplosionS2CPacket) explosion).setMotionX(0);
                    ((IExplosionS2CPacket) explosion).setMotionY(0);
                    ((IExplosionS2CPacket) explosion).setMotionZ(0);
                    flag = true;
                }

### Grim version

latest commit

### Server version

1.17.1

### Plugins

grim. PacketEvents

**Comment by SamB440** [comment]
what? the code you sent doesn't make any sense

**Comment by Dbbtop** [comment]
> what? the code you sent doesn't make any sense

now I will send this whole velocity code 
[vel.txt](https://github.com/user-attachments/files/15858025/vel.txt)

**Comment by Dbbtop** [comment]
> what? the code you sent doesn't make any sense

maybe I'll send you the whole cheat and you fix all the bypasses for grim yourself?

**Comment by SamB440** [comment]
Oh, yeah, that's the important part:
```
            case GrimNew -> {
                if (flag) {
                    if(ccCooldown <= 0) {
                        sendPacket(new PlayerMoveC2SPacket.Full(mc.player.getX(), mc.player.getY(), mc.player.getZ(), mc.player.getYaw(), mc.player.getPitch(), mc.player.isOnGround()));
                        sendPacket(new PlayerActionC2SPacket(PlayerActionC2SPacket.Action.STOP_DESTROY_BLOCK, BlockPos.ofFloored(mc.player.getPos()), Direction.DOWN));
                    }
                    flag = false;
                }
            }
```

This has been reported before, I think some of the experimental checks that were added might flag this

**Comment by Dbbtop** [comment]
> Oh, yeah, that's the important part:

I've already turned on the experimental checks, and velocity is still working.

**Comment by SamB440** [comment]
It flags BadPacketsX in my testing. I used LiquidBounce which does the same thing. https://github.com/CCBlueX/LiquidBounce/blob/nextgen/src/main/kotlin/net/ccbluex/liquidbounce/features/module/modules/combat/ModuleVelocity.kt#L348

This also won't work at all after 1.21, due to the removal of the duplicate packet.

**Comment by ManInMyVan** [comment]
> This also won't work at all after 1.21, due to the removal of the duplicate packet.

This isn't true, I was able to implement this in a 1.8 client.

**Comment by ManInMyVan** [comment]
Duplicate of #1133

**Comment by SamB440** [comment]
> This isn't true, I was able to implement this in a 1.8 client.

Isn't it abusing the duplicate packet to clear the knockback list? How would you do this in 1.8?

**Comment by ManInMyVan** [comment]
> > This isn't true, I was able to implement this in a 1.8 client.
> 
> Isn't it abusing the duplicate packet to clear the knockback list? How would you do this in 1.8?

By sending a normal tick packet, (see [my implemention](https://github.com/ManInMyVan/SkidBounce/blob/main/src/main/java/net/ccbluex/liquidbounce/features/module/modules/combat/velocitymodes/grim/Grim.kt)) the duplicate just bypasses timer.

**Comment by Dbbtop** [comment]
Fixed (some issues on server)
