### ISSUE TITLE
Compile with Java 17 - drop Java 8, Java 11

### ISSUE THREAD

**Issue by Anthony01M** [GrimAnticheat/Grim#1548]
### Feature description

As of the latest versions of ViaVersion, Java 17 has been required to run Via.
I've tested things out to verify their claim in regards of 1.8 running on java 17 and I can confirm this works (what I used was: paper 1.8, pandaspigot 1.8 - recommended to use over paper).
I believe there's no need for us to support Java 8, Java 11 and only Java 17 and higher as of the next versions of Grim.
ViaVersion latest release: https://github.com/ViaVersion/ViaVersion/releases/tag/5.0.0

**Comment by SamB440** [comment]
I just know people are going to complain if we drop Java 8, but I think it's worth it

Edit: I went on Via Discord and saw someone complaining immediately

**Comment by Anthony01M** [comment]
> I just know people are going to complain if we drop Java 8, but I think it's worth it
> 
> Edit: I went on Via Discord and saw someone complaining immediately

Not like it's going to be reverted back, they can use old version without updates or fixes, I think it's worth it; or they could just update to a 1.8 version that supports java 17 like I did for my minigame servers.

**Comment by FirephoenixX02** [comment]
> > I just know people are going to complain if we drop Java 8, but I think it's worth it
> > 
> > Edit: I went on Via Discord and saw someone complaining immediately
> 
> Not like it's going to be reverted back, they can use old version without updates or fixes, I think it's worth it; or they could just update to a 1.8 version that supports java 17 like I did for my minigame servers.

Yeah I agree everyone should update their 1.8 servers to a fork which supports Java 17. I don't see a reason to not to, as basically all 1.8 servers are minigames/pvp servers, so Vanilla functionality doesn't really matter.

**Comment by rafi67000** [comment]
definitely you should update to at least java 17.

**Comment by SamB440** [comment]
My current plan is to warn about Java 17 migration in the next 1-2 updates, then actually upgrade after that.

Currently, 676 servers are below our target version: https://bstats.org/plugin/bukkit/Grim/12820#javaVersion

276 of those are on Java 16, which should be an easy bump.

**Comment by Anthony01M** [comment]
> My current plan is to warn about Java 17 migration in the next 1-2 updates, then actually upgrade after that.
> 
> Currently, 676 servers are below our target version: https://bstats.org/plugin/bukkit/Grim/12820#javaVersion
> 
> 276 of those are on Java 16, which should be an easy bump.

nvm, just noticed you actually added it.

**Comment by SamB440** [comment]
90.1% of servers are on Java 17+, this version will require java 17+

**Comment by ManInMyVan** [comment]
why is this still pinned?
