### ISSUE TITLE
Slime & Bed false

### ISSUE THREAD

**Issue by Dbbtop** [GrimAnticheat/Grim#1549]
### Describe the false positive and how to replicate it

A false positive occurs when a player simply climbs any block. And a few more false positives with beds and slime blocks at 1.20
video: https://youtu.be/bPyqtIgS6XU

### Grim version

latest commit

### Server version

1.20

### Plugins

grim

**Comment by SamB440** [comment]
Are you on 1.21

**Comment by PinoOG** [comment]
> ### Describe the false positive and how to replicate it
> 
> A false positive occurs when a player simply climbs any block. And a few more false positives with beds and slime blocks at 1.20 video: https://youtu.be/bPyqtIgS6XU
> ### Grim version
> 
> latest commit
> ### Server version
> 
> 1.20
> ### Plugins
> 
> grim

https://github.com/GrimAnticheat/Grim/issues/1550

Is this also happening to you?

**Comment by Dbbtop** [comment]
> > ### Describe the false positive and how to replicate it
> > A false positive occurs when a player simply climbs any block. And a few more false positives with beds and slime blocks at 1.20 video: https://youtu.be/bPyqtIgS6XU
> > ### Grim version
> > latest commit
> > ### Server version
> > 1.20
> > ### Plugins
> > grim
> 
> #1550
> 
> Is this also happening to you?

no

**Comment by Dbbtop** [comment]
> Are you on 1.21



> Are you on 1.21

bruh 
![image](https://github.com/GrimAnticheat/Grim/assets/149936791/9c11ca0b-fdf3-4bdb-b0c2-0e3f8daaf8d5)

**Comment by SamB440** [comment]
You could be using viaversion for all I know, this is why we require a /grim log.

**Comment by Dbbtop** [comment]
> You could be using viaversion for all I know, this is why we require a /grim log.
[f.txt](https://github.com/user-attachments/files/15885267/f.txt)

false on bed here

**Comment by Dbbtop** [comment]
> You could be using viaversion for all I know, this is why we require a /grim log.

slime block here
[f2.txt](https://github.com/user-attachments/files/15885367/f2.txt)

**Comment by SamB440** [comment]
I can't reproduce the false when colliding with a block. Make sure you are using a completely vanilla client (no tlauncher).

**Comment by Dbbtop** [comment]
> I can't reproduce the false when colliding with a block. Make sure you are using a completely vanilla client (no tlauncher).

why is the problem only in Tlauncher?

**Comment by SamB440** [comment]
Tlauncher has been known to cause falses in the past, particularly with things like NoSlow.

**Comment by Dbbtop** [comment]
I logged in with TL legacy and the problem disappeared, but how do I solve the problem on Tlauncher because 80% of people from my country use it

**Comment by SamB440** [comment]
You should complain to Tlauncher
