### ISSUE TITLE
[BUG] Freezing players and causing mass false flags

### ISSUE THREAD

**Issue by PinoOG** [GrimAnticheat/Grim#1550]
### Describe the bug and how to replicate it

1) Run latest GrimAC Version
2) Add a plugin that simply teleport you on death on spawn (this basically afflicts RespawnEvent)
3) Get on PvP and Jump while getting killed
4) After respawning, you will be stuck with Grim mass flagging NoSlowA and Simulation

Might be useful to know that instant respawn Gamerule is being used

### Grim version

2.3.64

### Server version

latest pufferfish 1.20.4

### Plugins

Not useful to share since this also happens without plugins, with just Grim and something teleporting you on Respawn

**Comment by SamB440** [comment]
Update to the latest commit.

**Comment by PinoOG** [comment]
> Update to the latest commit.

How?

**Comment by SamB440** [comment]
Go to actions, click on the latest one, scroll down, download the "artifact".

https://github.com/GrimAnticheat/Grim/actions/runs/9554679108

**Comment by PinoOG** [comment]
> Go to actions, click on the latest one, scroll down, download the "artifact".
> 
> https://github.com/GrimAnticheat/Grim/actions/runs/9554679108

thank you very much

**Comment by PinoOG** [comment]
> Go to actions, click on the latest one, scroll down, download the "artifact".
> 
> https://github.com/GrimAnticheat/Grim/actions/runs/9554679108


It was good but now its happening again even with that version

**Comment by SamB440** [comment]
Are you using any mods? Is your client completely vanilla (no tlauncher)?

**Comment by PinoOG** [comment]
> Are you using any mods? Is your client completely vanilla (no tlauncher)?

We run an online mode server, most players uses Lunar, Feather and Fabric.

In my case, yes I was using Classic Minecraft Launcher (1.20.1)

**Comment by SamB440** [comment]
I can't reproduce any falses with immediate respawn. Please find a way to reliably reproduce the problem otherwise I cannot fix any potential issues.

**Comment by PinoOG** [comment]
> I can't reproduce any falses with immediate respawn. Please find a way to reliably reproduce the problem otherwise I cannot fix any potential issues.

After a deeper check from today, it only happens to fabric players.

For reproducing you need two players, 1 must jump and the other must kill him while the player is still jumping.

After respawning he flags a lot and get stuck

**Comment by SamB440** [comment]
Jumping shouldn't affect this, I also tested using Fabric, it's likely those players are using a mod instead

**Comment by PinoOG** [comment]
> Jumping shouldn't affect this, I also tested using Fabric, it's likely those players are using a mod instead

Okay I did with a player having this problem too frequently, we tested with Modrinth and some mods he was using, and also with Lunar Client (No Fabri just Optifine Lunar)

This happened again and again

**Comment by PinoOG** [comment]
If you are on Discord of GrimAC, I can better help

**Comment by SamB440** [comment]
Check for any mods on lunar or fabric that could be related to sprinting

My Discord is cotander

**Comment by PinoOG** [comment]
> Check for any mods on lunar or fabric that could be related to sprinting
> 
> My Discord is cotander

A weird way I have temp fixxed the problem is with grim api, disabling all checks for player while dying, and enabling them after respawn but only 2-3 seconds later

**Comment by PinoOG** [comment]
> Check for any mods on lunar or fabric that could be related to sprinting
> 
> My Discord is cotander

He still does with mods off

**Comment by PinoOG** [comment]
the mass spamming flag is NoSlowA(Prediction)

**Comment by PinoOG** [comment]
```
NoSlowA:
  # How much of an offset is "cheating"
  # By default this is lower than other offs
  # Flags by 0.03-0.2 consistently with NoSlow on
  threshold: 0.02
  # Setback fast on the first item to remove any advantage NoSlow gives
  setbackvl: 5
  # Decay's when the player uses an item AND is slowed by it
  decay: 0.05
```
  
  What should I put here to give more "space"

**Comment by SamB440** [comment]
Does simulation flag at all?

**Comment by PinoOG** [comment]
> Does simulation flag at all?

After updating as you suggested, only NoSlowA

**Comment by SamB440** [comment]
Try the latest commit https://github.com/GrimAnticheat/Grim/actions/runs/9583325809
