### ISSUE TITLE
Baritone flags while fishing

### ISSUE THREAD

**Issue by codenameRika** [GrimAnticheat/Grim#1552]
### Describe the false positive and how to replicate it

1. Stand still
2. Don't look around
3. do fishing
4. Grim flags for baritone(but not always)

### Grim version

2.3.64

### Server version

This server is running Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)

### Plugins

Plugins (41): AdvancedReplay*, AntiCurse, AuctionHouse, AuraSkills, AuthMe, BanManager, BetterTeams, CustomDrops, CustomWhitelistMessage*, DiscordSRV, EconomyShopGUI, Essentials, EssentialsSpawn, GrimAC, GSit, InstantRestock, Logger, LuckPerms, NotTooExpensive, OnePlayerSleep, PlaceholderAPI, Playtimes*, ProtectionStones, ProtocolLib, PvPManager, RAntiBot*, RewardsLite, ShulkerRespawner, SkinsRestorer, Slimefun, SpigotPing, SuperVanish, TreeAssist, Vault, VeinMiner, ViaBackwards, ViaVersion, voicechat, VPNGuard*, WorldEdit, WorldGuard

**Comment by xEcho1337** [comment]
The baritone check is broken af
