### ISSUE TITLE
Add support for InfiniteParkour. False positive simulation check

### ISSUE THREAD

**Issue by buracion1** [GrimAnticheat/Grim#1555]
### Describe the false positive and how to replicate it

To produce the simulation error, you need to install the plugin called 'InfiniteParkour' and start doing parkour. After falling a few times, you will start getting a simulation error, and I believe after some time, it will kick you out.

LINK 1: https://www.spigotmc.org/resources/✅-infinite-parkour-▶-rewards-leaderboard-mysql.87226/
LINK 2: https://www.spigotmc.org/resources/✅-infinite-parkour-plus-▶-multiplayer-parkour-lobby-parkour-and-more.105019/

Pictures: https://cdn.discordapp.com/attachments/1132037476345716776/1253320123217870928/image.png?ex=66756cd2&is=66741b52&hm=56493e2017de19ead0ad76535e10a92365f512dba79be1735b52d4b70802af8a&

### Grim version

3.3.64

### Server version

1.17.1 purpur
![image](https://github.com/GrimAnticheat/Grim/assets/114614883/bb88ff0f-58d9-45af-acff-9e5945068166)

### Plugins

It's simply about adding support for infinite parkour; I don't see the need to provide you with a list of plugins.

**Comment by ManInMyVan** [comment]
Try with latest commit

**Comment by SamB440** [comment]
As mentioned on Discord and here, please try the latest commit which has fixes for world transfers / teleporting. https://github.com/GrimAnticheat/Grim/actions/runs/9619836062/artifacts/1626369266
