### ISSUE TITLE
BadPacketsX on kelp

### ISSUE THREAD

**Issue by Dbbtop** [GrimAnticheat/Grim#1563]
### Describe the false positive and how to replicate it

just break kelp in water

### Grim version

latest commit

### Server version

1.17.1

### Plugins

grim, packetevents, protocolLib, LP, viaversion

**Comment by jonesdevelopment** [comment]
https://github.com/GrimAnticheat/Grim/issues/1472

**Comment by Dbbtop** [comment]
> #1472

not this

**Comment by Anthony01M** [comment]
> > #1472
> 
> not this

referring to this I believe https://github.com/GrimAnticheat/Grim/issues/1472#issuecomment-2144039771
