### ISSUE TITLE
X-Ray 

### ISSUE THREAD

**Issue by dave9123** [GrimAnticheat/Grim#1569]
### Feature description

To make blocks around the player randomized into random ores and if the player's trying to mine that ore, the user might using x-ray. Something like this plugin [https://www.spigotmc.org/resources/orebfuscator-anti-x-ray.82710/](https://www.spigotmc.org/resources/orebfuscator-anti-x-ray.82710/)

**Comment by Souipi** [comment]
Use the anti x-ray mode of paper.

**Comment by Dbbtop** [comment]
> Use the anti x-ray mode of paper.

paper anti-xray bypass with usual Digg-Packets (RayTraceAntiXray also)
Grim does not prevent the use of this type of xray

**Comment by dave9123** [comment]
Easily bypassed with X-Ray Bruteforce

**Comment by Anthony01M** [comment]
orebfuscator uses too much resources to a point where even I'm thinking of removing it in favor of paper's anti-xray  so I don't think making something like orebfuscator will ever be in Grim, the max I can see is grim notifying you when someone mines ores and how many (I believe there's a plugin like that already somewhere) but not to a point where it would hide ores for you.

**Comment by MachineBreaker** [comment]
This is not something that should be added on Grim considering there are alternatives like the built-in anti-xray of Paper
