### ISSUE TITLE
False positive for Controlify Mod

### ISSUE THREAD

**Issue by mei1012** [GrimAnticheat/Grim#1573]
### Describe the false positive and how to replicate it

1. Connect controller using [controlify](https://modrinth.com/mod/controlify/versions)
2. Move around
3. Simulation false positive

### Grim version

2.3.64

### Server version

This server is running Paper version 1.20.6-138-master@906df69 (2024-06-10T06:32:15Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are 9 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-"812ccb9" (MC: 1.20.6)

### Plugins

Server Plugins (78):
Paper Plugins: AutoSellChests, EconomyShopGUI, Pl3xMapExtras

Bukkit Plugins: - AdvancedBan, AntiCombatLog, AntiCrystalPVP, AnvilUnlocker, Autoreplant, AxKills, AxSmithing, BetterTeams, BigSpender, ChestShop Chunky, ChunkyBorder, Citizens, ClientDetector, CraftEnhance, CrazyVouchers, CrisTreeCapitator, DamageDisplay, DeadChest, DiscordSRV
Disenchantments, DragonEggBuff, Drugs, Elevator, Essentials, EssentialsWarpGUI, ExpBottle, FancyPhysics, *FarmProtect, floodgate
Geyser-Spigot, GeyserHacks, GrimAC, HarvestEXP, HoloDropsX, InstantSmelt, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, ItemTracker LPC, LuckPerms, Maintenance, MarketPlace, MinecraftCustomMaps, MobsToEggs, MoneyFromMobs, NoteBlockAPI, OldCombatMechanics, Pl3xMap PlaceholderAPI, PlayerEconomy, PlayerWarps, PlugManX, ProtocolLib, QualityArmory, *RetainXP, SimpleScore, *SimpleSit, SimpleTpa Skript, sScreamer, TAB, Themis, TimeIsMoney, UnsafeEnchants, UpgradeableSpawners, Vault, Veinminer, ViaBackwards ViaRewind, ViaVersion, Vivecraft-Spigot-Extensions, WildRTP, WorldEdit

**Comment by ManInMyVan** [comment]
Enable Keyboard-like Movement in the settings of Controlify
