### ISSUE TITLE
Console spamming

### ISSUE THREAD

**Issue by Coariz** [GrimAnticheat/Grim#1577]
### Stack trace

https://pastes.dev/Gjv1Zq22I7

### How to replicate it if known

1. Install paper version 1f5db50
2. Install grim ac latest commit (d8a8468)
3. Start server then boom

Btw I have no clue what's going on, I'm just reporting this

### Grim version

d8a8468

### Server version

paper 1.21 build- 1f5db50

### Plugins

grimac and valhallammo

**Comment by SamB440** [comment]
Replicate without ValhallaMMO, TAB, and any of the "Ax" plugins

**Comment by Coariz** [comment]
Here https://pastes.dev/0pZ4OFEu0F

Freshly cooked server on minehut

**Comment by SamB440** [comment]
Try redownloading the latest commit

**Comment by Coariz** [comment]
Works good now without the "Ax" plugins and valhalla. But they still pop up when I install grimAC along with them

**Comment by SamB440** [comment]
Remove 1 by 1 to determine which is the troublesome plugin, then report it to the plugin author, I would suspect valhalla because it doesn't seem to be updated for 1.21.

**Comment by Coariz** [comment]
It is valhalla, I've addressed the author thanks :))
