### ISSUE TITLE
[1.20.4] "simulation failed" false positive SPAM

### ISSUE THREAD

**Issue by eltrevii** [GrimAnticheat/Grim#1579]
### Describe the false positive and how to replicate it

1. die and respawn (and possibly a lag spike?)
2. false positive spam starts
the issue is fixed after sprinting

### Grim version

3.3.64

### Server version

Current: git-Purpur-2176 (MC: 1.20.4)*
* You are running the latest version

### Plugins

Paper Plugins: (1):
 - AdvancedServerList
 
Bukkit Plugins: (24):
 - AntiCombatLog, AuctionHouse, BetterMessages, BetterRTP, CoreProtect, FastAsyncWorldEdit, GrimAC, InvSeePlusPlus, lightEconomy, LoginSecurity, LuckPerms, Multiverse-Core, Orebfuscator, PlaceholderAPI, ProtocolLib, Sit, spark, SuperVanish, TabTPS, UltimateHomes, Vault, ViaBackwards, ViaRewind, ViaVersion

**Comment by eltrevii** [comment]
video:

https://github.com/GrimAnticheat/Grim/assets/59333567/2801abd1-245c-493d-85af-d398e13f30f7

**Comment by eltrevii** [comment]
log (new error after video: `Grim » aritz331_ failed Simulation (x75) .028719 /gl 200`): https://paste.grim.ac/n2xq4rs

**Comment by ManInMyVan** [comment]
Try latest commit

**Comment by Anthony01M** [comment]
Consider trying with the latest commit; https://github.com/GrimAnticheat/Grim/actions/runs/9681468381/artifacts/1651569874

**Comment by eltrevii** [comment]
ok

**Comment by eltrevii** [comment]
it seems to be working fine, i will comment back if the issue persists. was there an important change or something?
