### ISSUE TITLE
False Positive: Fast Break Netherite Pickaxe EFF 5

### ISSUE THREAD

**Issue by Cartrigger** [GrimAnticheat/Grim#1590]
### Describe the false positive and how to replicate it

Create a Netherite Pickaxe with efficiency 5, mine stone.

### Grim version

2.3.65

### Server version

1.21-2264-bf63cfa

### Plugins

Grim Exempt Vivecraft V2, GrimAC, SilkTouchedSpawner, Spark, ViaBackwards, ViaVersion, Voicechat

**Comment by Cartrigger** [comment]
https://github.com/user-attachments/assets/96028a35-14e1-42b7-bb2d-30c69dfaa386

**Comment by ManInMyVan** [comment]
#1583
