### ISSUE TITLE
[BYPASS/BUG] There is no movement detection next to the boat

### ISSUE THREAD

**Issue by MatrixU5er** [GrimAnticheat/Grim#1593]
### Describe the bypass and how to replicate it

Approach a boat and activate flight

https://github.com/user-attachments/assets/4e9c1a7d-d20a-40b9-bd43-c0c8b2590c53

### Grim version

loyisa's grim (2.3.6.5) 

### Server version

1.8.8

### Plugins

grimac

**Comment by SamB440** [comment]
Not being fixed, boats are too buggy

**Comment by MatrixU5er** [comment]
sad ：（
