### ISSUE TITLE
[BYPASS] 1.9+viaversion to 1.8 Sword NoSlow Bypass

### ISSUE THREAD

**Issue by MatrixU5er** [GrimAnticheat/Grim#1594]
### Describe the bypass and how to replicate it

use Vanilla noslow on 1.9+ minecraft version(viaversion)

### Grim version

newest

### Server version

1.8.8

### Plugins

grimac

**Comment by SamB440** [comment]
idk what you mean by this or the title, are you saying that any noslow bypasses on a 1.8 server with 1.9+ client?

**Comment by MatrixU5er** [comment]
What I mean is that when using the 1.9+client version to enter the 1.8.8 version server (after installing viaversion on the 1.8.8 version server) and right clicking on the sword, a shield will appear instead of the sword's blocking, and there is no noslow check at this time

**Comment by SamB440** [comment]
iirc ViaVersion controls that shield, we have no idea about it. This can't be fixed.

**Comment by MatrixU5er** [comment]
Since that's the case, there's nothing more to say
