### ISSUE TITLE
[FALSE] AirLiquidPlace/PositionPlace false on stairs

### ISSUE THREAD

**Issue by MatrixU5er** [GrimAnticheat/Grim#1603]
### Describe the false positive and how to replicate it

watch the video

https://github.com/user-attachments/assets/b4557261-3b8a-435a-996f-3bf68b8b6c43

### Grim version

2.3.65 Loyisa

### Server version

Loyisa(1.8.8)

### Plugins

grimac

**Comment by SamB440** [comment]
How are you placing a block inside yourself?

**Comment by MatrixU5er** [comment]
I don't know why, but my client is indeed the original version. Just right click the lower part of this box and it will be like this in the video。You mean you can't put it?

**Comment by MachineBreaker** [comment]
I saw this once due to client<->server version differences, very annoying if you ask me

> How are you placing a block inside yourself?

**Comment by MatrixU5er** [comment]
> I saw this once due to client<->server version differences, very annoying if you ask me
> 
> > How are you placing a block inside yourself?
> 
> 

sorry for this error report, it is loyisa server issue
