### ISSUE TITLE
flagged when after respawn

### ISSUE THREAD

**Issue by Currypan1229** [GrimAnticheat/Grim#1606]
### Describe the false positive and how to replicate it

Step1. Die by any way
Step2. Move or jump
Step3. Setbacking without flags

### Grim version

[6fe2bf1](https://github.com/GrimAnticheat/Grim/commit/6fe2bf1d652b0963ad663d7e25a3ce1a55d72de7)

### Server version

git-Purpur-2176 (MC: 1.20.4)

### Plugins

GrimAC, PlugManX, spark

**Comment by SamB440** [comment]
Unable to reproduce. Provide more detailed reproduction steps.

**Comment by Currypan1229** [comment]
https://github.com/user-attachments/assets/15e9f30c-5b3d-48f8-837a-adceb1e83bb8

**Comment by SamB440** [comment]
As I said, I tried to reproduce doing that but it works fine for me. You haven't really provided any more details. Make sure you are using a 100% vanilla client.

**Comment by Currypan1229** [comment]
using fresh 100% 1.20.4 vanilla client
and default config except alert settings

**Comment by Currypan1229** [comment]
https://github.com/Currypan1229/fewfwfwe
Server template

**Comment by Currypan1229** [comment]
Use the artifact
https://github.com/GrimAnticheat/Grim/actions/runs/10021531660

**Comment by ManInMyVan** [comment]
Could not reproduce, even at 400ms

**Comment by Currypan1229** [comment]
It was happened in my friend server, but whyyyyyyy???????

**Comment by Anthony01M** [comment]
cannot reproduce;
Servers tested on:
1. git-Purpur-2176 (MC: 1.20.4)
2. git-Purpur-2155 (MC: 1.20.4)

Clients tested with:
1. Lunar 1.8.9 | Lunar 1.20.4 | Lunar 1.20.6
2. FeatherClient 1.20.4

**Comment by SamB440** [comment]
I think on Grim's end it's seeing the chunks as unloaded, that would most likely mean Grim isn't receiving a transaction response from your client. If you're behind a proxy, make sure via* is not installed on there. Though I have no idea what could cause such an issue.
