### ISSUE TITLE
Depth Strider & Dolphin's Grace Falses

### ISSUE THREAD

**Issue by overkidding** [GrimAnticheat/Grim#1607]
### Describe the false positive and how to replicate it

1. Put grim in your server
2. Get boots with depth strider or get near a dolphin to get the dolphins grace effect
3. Swim

[Video of depth strider false](https://youtu.be/GK7Dl8H7c6c)

not linking a video of dolphin cause i'm going to sleep

### Grim version

2.3.66

### Server version

1.21

### Plugins

ChatEmojis, Chunky, CrashFixer, *EdenSocials, Essentials, EssentialsChat, FastAsyncWorldEdit, IllegalStack, LuckPerms, NetherRoofLocker, PlaceholderAPI, ProtocolLib, randomSpawn, GrimAC, spark, TAB, Vault, ViaBackwards, ViaRewind, ViaVersion, Votifier, WorldGuard

**Comment by SamB440** [comment]
#1583
