### ISSUE TITLE
Bypass | NoSlow

### ISSUE THREAD

**Issue by MrWenter228** [GrimAnticheat/Grim#1608]
### Describe the bypass and how to replicate it

I recently found a bypass for noslow in your anti cheat using the Nursultan cheat, here is a video with the bypass.
Video: https://www.youtube.com/watch?v=9Ytn4VPpBDs

### Grim version

Grim version 2.3.65

### Server version

Patina 1.16.5

### Plugins

GrimAC, LuckPerms, Plugman

**Comment by SamB440** [comment]
Update to the latest commit

**Comment by MrWenter228** [comment]
> Update to the latest commit

I had the latest version of grimac

**Comment by SamB440** [comment]
commit != version, https://github.com/GrimAnticheat/Grim/commits/2.0/

Go to https://github.com/GrimAnticheat/Grim/actions

Select the latest, scroll down, download artifact.zip

**Comment by MatrixU5er** [comment]
At present, I can find similar noslow from this client。
https://gitee.com/chao-ying/MephistoClient-KevinPlus/blob/master/src/minecraft/kevin/module/modules/movement/NoSlow.kt
  if (packetMode equal "SpecialGrim") {
            if (isUsing || isBlocking|| aura.blockingStatus) {
                if (event.eventState == EventState.PRE) {
                    if (mc.thePlayer.heldItem.item is ItemSword) {
                        mc.netHandler.addToSendQueue(C09PacketHeldItemChange(mc.thePlayer.inventory.currentItem % 8 + 1))
                        mc.netHandler.addToSendQueue(C17PacketCustomPayload("Nothing", PacketBuffer(Unpooled.buffer())))
                        mc.netHandler.addToSendQueue(C09PacketHeldItemChange(mc.thePlayer.inventory.currentItem))

                    }
                    if (mc.thePlayer.heldItem.item is ItemBow) {
                        mc.netHandler.addToSendQueue(C09PacketHeldItemChange(mc.thePlayer.inventory.currentItem % 8 + 1))
                        mc.netHandler.addToSendQueue(C17PacketCustomPayload("Nothing", PacketBuffer(Unpooled.buffer())))
                        mc.netHandler.addToSendQueue(C09PacketHeldItemChange(mc.thePlayer.inventory.currentItem))
                    }
                }
                if (event.eventState == EventState.POST) {
                    if (mc.thePlayer.heldItem.item is ItemBow || mc.thePlayer.heldItem.item is ItemSword) {
                        mc.netHandler.networkManager.sendPacket(C08PacketPlayerBlockPlacement(mc.thePlayer.inventory.getCurrentItem()))
                    }
                }
                if (foodValue.get() && (mc.thePlayer.heldItem.item is ItemFood || mc.thePlayer.heldItem.item is ItemPotion || mc.thePlayer.heldItem.item is ItemBucketMilk)){
                    if (shouldSlow) {
                        consumeForwardMultiplier.set(0.2F)
                        consumeStrafeMultiplier.set(0.2F)
                    } else {
                        consumeForwardMultiplier.set(1F)
                        consumeStrafeMultiplier.set(1F)
                    }
                }
            }
This is its core code, and its execution behavior is basically the same as that shown in your video. You can try whether this is bypassing the latest build (I didn't test it)
But this code can run on Chinese minecraft's Huayuting server. (They use custom grimac)

**Comment by MrWenter228** [comment]
> commit != version, https://github.com/GrimAnticheat/Grim/commits/2.0/
> 
> Go to https://github.com/GrimAnticheat/Grim/actions
> 
> Select the latest, scroll down, download artifact.zip


The bypass still works, I just checked, 0 changes.

**Comment by ManInMyVan** [comment]
Does this work if you have a usable item in both hands?

**Comment by MrWenter228** [comment]
The bypass is an off hand. In addition, yesterday I found another bypass, where everything works in both hands.

> Does this work if you have a usable item in both hands?

**Comment by ManInMyVan** [comment]
> The bypass is an off hand. In addition, yesterday I found another bypass, where everything works in both hands.

I meant if it works if you use an item in one hand and have another item you could have used in the other hand (ie shield in mainhand and golden apple in offhand)

**Comment by MrWenter228** [comment]
> > The bypass is an off hand. In addition, yesterday I found another bypass, where everything works in both hands.
> 
> I meant if it works if you use an item in one hand and have another item you could have used in the other hand (ie shield in mainhand and golden apple in offhand)

So you cannot use 2 items at the same time.

**Comment by bbb908** [comment]
it could work cause of grim exempting noslow the first tick you're using an item for 1.8 compatibility cause for some reason 1.8 at the first tick of you using an item they have you able to go max speed and then only the next tick does it slow u down

**Comment by MahadRegent** [comment]
Its just switchitem bypass luqiudbounce (It's not fixed)

**Comment by ManInMyVan** [comment]
are you able to replicate this on #1623? ([pre-built jar](https://github.com/ManInMyVan/Grim/actions/runs/10153397633/artifacts/1753208952))
