### ISSUE TITLE
FastBreak

### ISSUE THREAD

**Issue by HAMPERHAMPS** [GrimAnticheat/Grim#1609]
### Describe the false positive and how to replicate it

Just use an efficiency II diamond axe and get wood.
Is there a way to turn off FastBreak?

### Grim version

2.3.65

### Server version

1.21

### Plugins

- AntiXRay (1.9.0), DeathCounter (1.3), Geyser-Spigot (2.4.0-SNAPSHOT), GrimAC (2.3.65), OnePlayerSleep (1.3), floodgate (2.2.3-SNAPSHOT (b109-49bd564)), voicechat (2.5.16)

**Comment by Anthony01M** [comment]
![image](https://github.com/user-attachments/assets/0743fd96-3e7a-4257-9579-a19f86a06b71)
consider checking #1587

**Comment by HAMPERHAMPS** [comment]
How do I disable FastBreak?

**Comment by Anthony01M** [comment]
> How do I disable FastBreak?

Go to punishments.yml
search for - "FastBreak" and simply add a ! before FastBreak; here's how it should look like:
\- "!FastBreak"

**Comment by HAMPERHAMPS** [comment]
Oh ok thx!

**Comment by Leoaxo098** [comment]
i cant find Fastbreak in punishments.yml
