### ISSUE TITLE
Understack item cause BadPacketsU

### ISSUE THREAD

**Issue by mckuhei** [GrimAnticheat/Grim#1611]
### Describe the false positive and how to replicate it

https://github.com/user-attachments/assets/0db109f8-99da-418d-a613-747b222f6f61

### Grim version

2.3.66

### Server version

1.8.9

### Plugins

idk

**Comment by mckuhei** [comment]
More information about understacked item: https://mcdf.wiki.gg/wiki/Java_Edition:Understacked_Items

**Comment by Anthony01M** [comment]
this might fix, but can't test rn; this basically exempts whatever is bellow 1 (isEmpty() and the understacked) for now.

```java
                // never sent when not holding anything
                final boolean failedItemCheck = packet.getItemStack().isPresent()
                        // ItemStack being understacked is causing the check to false
                        && packet.getItemStack().get().getAmount() < 1
                        // ViaVersion can sometimes cause this part of the check to false
                        && player.getClientVersion().isOlderThan(ClientVersion.V_1_9);

**Comment by ManInMyVan** [comment]
Are you able to replicate this on https://github.com/ManInMyVan/Grim/tree/fix/bpU-understacked

**Comment by mckuhei** [comment]
Can you give me a pre build patch?

**Comment by ManInMyVan** [comment]
> Can you give me a pre build patch?

https://github.com/ManInMyVan/Grim/actions/runs/10049560738/artifacts/1728092765

**Comment by mckuhei** [comment]
OK, It seems work
