### ISSUE TITLE
you need to click a block more than once to mine it looks like lag

### ISSUE THREAD

**Issue by nullr00tbyte** [GrimAnticheat/Grim#1613]
### Describe the bug and how to replicate it

Build
put in server paper https://api.papermc.io/v2/projects/paper/versions/1.21/builds/109/downloads/paper-1.21-109.jar
start 

https://github.com/user-attachments/assets/75f79163-604a-4af4-b31a-519ff35200f0

When I try to mine a block very quickly, it doesn't break until I do it at least 2 or 3 times.

### Grim version

grimac-2.3.66

### Server version

This server is running Paper version 1.21-109-master@5a5035b (2024-07-23T08:16:30Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### Plugins

![image](https://github.com/user-attachments/assets/622a2791-cf51-4268-b455-e0cb8807f284)

**Comment by ManInMyVan** [comment]
#1583
