### ISSUE TITLE
Speed bypasss

### ISSUE THREAD

**Issue by MahadRegent** [GrimAnticheat/Grim#1615]
### Describe the bypass and how to replicate it

1. Donwload LuqiudBounce
2. Set parametrs how on video
3.  Done

### Grim version

Latest Grim 2.3.66

### Server version

Purpur 1.20.6
And video is here -  https://youtu.be/O6xcFzt52Kg 
On video i forgot to add parametrs off function LuqiudBounce, its on screenshoot
And code of fix (Its in MovementTicker) ---> handleplayercolissions

 ITS ONLY HOTFIX, AND I DON'T ANSWERING ABOUT ANY FALSES IN THIS FIX!!! And etc. 

public static void handleEntityCollisions(GrimPlayer player) {
        // 1.7 and 1.8 do not have player collision
        if (player.getClientVersion().isOlderThan(ClientVersion.V_1_9)) return;

        int possibleCollidingEntities = 0;

        // Players in vehicles do not have collisions
        if (!player.compensatedEntities.getSelf().inVehicle()) {
            // Calculate the offset of the player to colliding other stuff
            SimpleCollisionBox playerBox = GetBoundingBox.getBoundingBoxFromPosAndSize(player, player.lastX, player.lastY, player.lastZ, 0.6f, 1.8f);
            SimpleCollisionBox expandedPlayerBox = playerBox.copy().expandToAbsoluteCoordinates(player.x, player.y, player.z).expand(1);

            for (PacketEntity entity : player.compensatedEntities.entityMap.values()) {
                if (!entity.isPushable())
                    continue;

                SimpleCollisionBox entityBox = entity.getPossibleCollisionBoxes();

                if (expandedPlayerBox.isCollided(entityBox))
                    possibleCollidingEntities++;
            }
        }
// fix hacking with colliding with entity
        double speedLimit = 0.42 + (possibleCollidingEntities * 0.01);

        if (player.isSneaking) {
            if (player.lastOnGround) {
                if (player.clientVelocity.lengthSquared() > speedLimit * speedLimit) {
                    player.clientVelocity = player.clientVelocity.normalize().multiply(speedLimit);
                }
            }
            if (player.isFlying && player.wasFlying) {
                {
                    return;
                }
            } else if (player.wasSneaking) {
                if (player.clientVelocity.lengthSquared() > speedLimit * speedLimit) {
                    player.clientVelocity = player.clientVelocity.normalize().multiply(speedLimit);
                }
            }

            if (player.isSprinting) {
                if (player.lastOnGround) {
                    if (player.clientVelocity.lengthSquared() > speedLimit * speedLimit) {
                        player.clientVelocity = player.clientVelocity.normalize().multiply(speedLimit);
                    }
                }
                if (player.isFlying && player.wasFlying) {
                    {
                        return;
                    }

                }
            } else if (player.lastSprinting) {
                if (player.clientVelocity.lengthSquared() > speedLimit * speedLimit) {
                    player.clientVelocity = player.clientVelocity.normalize().multiply(speedLimit);
                }
            }

            if (player.isGliding && possibleCollidingEntities > 0) {
                // Horizontal starting movement affects vertical movement with elytra, hack around this.
                // This can likely be reduced but whatever, I don't see this as too much of a problem
                player.uncertaintyHandler.yNegativeUncertainty -= 0.05;
                player.uncertaintyHandler.yPositiveUncertainty += 0.05;
            }

            player.uncertaintyHandler.collidingEntities.add(possibleCollidingEntities);
        }
    }
    
    ITS ONLY HOTFIX, AND I DON'T ANSWERING ABOUT ANY FALSES IN THIS FIX!!! And etc. 

### Plugins

[23:26:16 INFO]: Paper Plugins: (2):
[23:26:16 INFO]:  - BKCommonLib, FancyHolograms
[23:26:16 INFO]: Bukkit Plugins: (45):
[23:26:16 INFO]:  - AdvancedCrates, ajLeaderboards, AntiCheatAddition, BetterRTP, BetterStructures, Boss, Chatty, Chunky, Citizens, CMI
[23:26:16 INFO]:  CMILib, ConditionalCommands, ConditionalEvents, DecentHolograms, DeluxeMenus, ExecutableItems, FacilisCommon, GrimAC, Iris, LiteBans
[23:26:16 INFO]:  LPX, LuckPerms, Mars, MarsGenerator, MoonGenerator, MultiWorld, My_Worlds, packetevents, Pl-Hide-Pro, PlaceholderAPI
[23:26:16 INFO]:  PlasmoVoice, PlayerPoints, PlugManX, ProtectionStones, ProtocolLib, SCore, SpacePlugin, spark, TAB, Vault
[23:26:16 INFO]:  ViaBackwards, ViaVersion, W
![Снимок экрана_20240724_224827](https://github.com/user-attachments/assets/908912c1-e8aa-47da-bbb7-7d4d73d40548)
orldEdit, WorldGuard, WorldGuardExtraFlags

**Comment by ManInMyVan** [comment]
#1600

**Comment by MahadRegent** [comment]
Okay , just fix this bypass please

**Comment by MahadRegent** [comment]
bypass still working , after colission heavy core

**Comment by Anthony01M** [comment]
> bypass still working , after colission heavy core

test using this PR https://github.com/GrimAnticheat/Grim/pull/1600

**Comment by MahadRegent** [comment]
still not flagging IF you are not in box of entity , when you are in box of entity = flag. Check rec , this bypass is working out of box entity (You can jump up entity for example, you speed up without flag.

**Comment by SamB440** [comment]
> still not flagging IF you are not in box of entity , when you are in box of entity = flag. Check rec , this bypass is working out of box entity (You can jump up entity for example, you speed up without flag.

What? I literally tested the speed with LB, it doesn't bypass at all

**Comment by MahadRegent** [comment]
https://www.youtube.com/watch?v=1HP_dn76aaw&ab_channel=MahadRegent
check rec

**Comment by SamB440** [comment]
That's not on my branch.

**Comment by ManInMyVan** [comment]
> https://www.youtube.com/watch?v=1HP_dn76aaw&ab_channel=MahadRegent
> check rec

Use https://github.com/SamB440/Grim/actions/runs/10012009010/artifacts/1720045686

**Comment by MahadRegent** [comment]
this jar is working nice, thanks
