### ISSUE TITLE
Depth Strider cause Simulations flags

### ISSUE THREAD

**Issue by MojangBug** [GrimAnticheat/Grim#1617]
### Describe the bug and how to replicate it

Get the boot or legging Depth Strider and go into the water can cause flag Simulations

### Grim version

version 2.3.8

### Server version

![42AE604FA55FC0789AE8E1B87C38DA3F](https://github.com/user-attachments/assets/e8334b31-5895-4f40-ae3c-75e8e96c6f55)

### Plugins

![7CFAA14FC9999A15CFBA763AE4E61EED](https://github.com/user-attachments/assets/292787ac-91f3-41c7-bb25-d4d7d92922aa)

**Comment by MojangBug** [comment]
![0BF539088342D25DB35619EF71F45595](https://github.com/user-attachments/assets/9dc8be02-ae0d-4e75-9e4d-87143074523d)
![s](https://github.com/user-attachments/assets/7d0e1377-fda8-48a3-8997-fe0eb0d8b2ae)
It's for the bug describe.

**Comment by ManInMyVan** [comment]
#1583, 1.21 servers are not supported yet
