### ISSUE TITLE
Add a good autoclick detection

### ISSUE THREAD

**Issue by WarnDa** [GrimAnticheat/Grim#1620]
### Feature description

On PVE server (or skyblock server, servers with spawners) player can easily abuse with autoclick to click at the perfect interval (580ms) and get unfair advantage.

We tried to do a custom plugin to check each time between player click that is validated by the server, but it can't be really used as it's per tick, and even with autoclick we get up to 150ms difference, and a legit player can achieve the same difference of 150ms
![image](https://github.com/user-attachments/assets/8b7222b0-20fd-4c1b-b1bf-e11b5c1b95fe)

We saw that to make it better we would need to the player movement, but way more hard to do, as you need to play with packets, and require more knowledge.

If someone could add a perfect way to be 95% sure a player is autoclicking, I am willing to pay

**Comment by ManInMyVan** [comment]
https://github.com/GrimAnticheat/Grim/issues/1236#issuecomment-1844029545

**Comment by SamB440** [comment]
Are you talking about 1.9 attack interval being perfectly timed?

**Comment by WarnDa** [comment]
> Are you talking about 1.9 attack interval being perfectly timed?

Yes

**Comment by SamB440** [comment]
You can't detect that reliably because of missing idle tick, we don't know the progress of the player's attack cooldown, if Mojang readded idle movement tick this would be feasible.

Regardless, this doesn't belong in Grim.
