### ISSUE TITLE
Standing on the "heavy_core" can cause false alarms and prevent movement.

### ISSUE THREAD

**Issue by CatTeaA** [GrimAnticheat/Grim#1622]
### Describe the false positive and how to replicate it

Standing on the "[heavy_core](https://minecraft.wiki/w/Heavy_Core)" can cause false alarms and prevent movement.

### Grim version

grimac2.3.66
https://github.com/GrimAnticheat/Grim/actions/runs/10062651758
https://github.com/GrimAnticheat/Grim/actions/runs/10011478006

### Server version

This server is running Paper version 1.21-119-master@100d75a (2024-07-29T16:00:13Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version
Previous version: 1.21-111-66165f7 (MC: 1.21)

### Plugins

Only Grimac

**Comment by Anthony01M** [comment]
Please confirm if it still falses on this too: https://github.com/GrimAnticheat/Grim/pull/1587

**Comment by CatTeaA** [comment]
> Please confirm if it still falses on this too: #1587

The second link above includes the latest build version of attribute-rework, which still has false positives.

**Comment by Anthony01M** [comment]
> > Please confirm if it still falses on this too: #1587
> 
> The second link above includes the latest build version of attribute-rework, which still has false positives.

Ah yes, my bad, I more or less missed the branch name.
You might get asked for Client Version & a video on how to reproduce (which is basically standing so don't think you need that part) just the client would be enough ig since you didn't mention it anywhere

**Comment by SamB440** [comment]
Try the latest commit

**Comment by CatTeaA** [comment]
> > > Please confirm if it still falses on this too: #1587
> > 
> > 
> > The second link above includes the latest build version of attribute-rework, which still has false positives.
> 
> Ah yes, my bad, I more or less missed the branch name. You might get asked for Client Version & a video on how to reproduce (which is basically standing so don't think you need that part) just the client would be enough ig since you didn't mention it anywhere

Yes, just standing on it can reproduce the false alarm, Vanilla client.

**Comment by CatTeaA** [comment]
> Try the latest commit

There are still false positives.
![6cde87cf-e142-4b7b-afe8-b6516671506d](https://github.com/user-attachments/assets/c48b1090-1de3-4269-842a-b09f7e37ec1a)
https://github.com/GrimAnticheat/Grim/actions/runs/10151981829

**Comment by SamB440** [comment]
Try again

**Comment by CatBang** [comment]
> attribute-rework

https://github.com/GrimAnticheat/Grim/actions/runs/10161478590
The latest build version has resolved this issue after testing, can you sync the submission to 'attribute-rework'?

**Comment by CatTeaA** [comment]
> Try again

https://github.com/GrimAnticheat/Grim/actions/runs/10161478590
The latest build version has resolved this issue after testing, can you sync the submission to 'attribute-rework'?
