### ISSUE TITLE
False positives and occasional error

### ISSUE THREAD

**Issue by ChrisTVH** [GrimAnticheat/Grim#1633]
### Stack trace

https://mclo.gs/oxenYIc

### How to replicate it if known

- In the case of fastbreak, it happens even with tools that have efficiency 5, and I was told that with the soul speed enchantment a false positive also happens. (I saw that in a build they fixed it just now, so maybe it's discarded D:)
- As for the log I sent, it shows information about a bug that happens quite frequently.

### Grim version

![image](https://github.com/user-attachments/assets/24cb01e5-e328-46db-ada7-8ba07f7755e6)

### Server version

It also happened to me in purpur build 2280, but I switched to uspigot.
![image](https://github.com/user-attachments/assets/ba20af09-e654-44bb-8882-8bbc25f14e35)

### Plugins

![image](https://github.com/user-attachments/assets/050a87cb-373e-4431-a488-5c3350e4f5a6)

**Comment by SamB440** [comment]
2.3.65 is outdated, not the latest commit

**Comment by ChrisTVH** [comment]
> 2.3.65 is outdated, not the latest commit

I downloaded this build from the action section 2 days ago.

**Comment by SamB440** [comment]
The version has been 2.3.66 since Jul 1

**Comment by ChrisTVH** [comment]
> The version has been 2.3.66 since Jul 1

I will download it again then

**Comment by ChrisTVH** [comment]
It seems that what happened is that I confused my download folder with my local plugin folder, so I foolishly re-uploaded the old one.

Edit:
I will leave this open still and if I get bugs or any problems I will report it.
If this is not the case I will close it.

**Comment by ChrisTVH** [comment]
I waited patiently all day, and it came back out.
https://mclo.gs/V7W2wU5

Build: # 384
![image](https://github.com/user-attachments/assets/918d83eb-01e9-4542-b4fc-1f97af1a7144)

**Comment by SamB440** [comment]
That's a different error due to packetevents not supporting 1.21 fully yet, though if you're using the latest commit with the packetevents snapshot that error shouldn't appear

**Comment by ChrisTVH** [comment]
> That's a different error due to packetevents not supporting 1.21 fully yet, though if you're using the latest commit with the packetevents snapshot that error shouldn't appear

If it happens often enough.

**Comment by ChrisTVH** [comment]
I get reports of fastbreak with efficiency 5 on my server.

**Comment by ChrisTVH** [comment]
It also happens that if you have aquatic agility you cannot move in the water.

**Comment by ghost** [comment]
> It also happens that if you have aquatic agility you cannot move in the water.

its fixed in latest commit, download or build latest version
