### ISSUE TITLE
Standing on the "tuff_wall / polished_tuff_wall / tuff_brick_wall" can cause false alarms and prevent movement.

### ISSUE THREAD

**Issue by CatTeaA** [GrimAnticheat/Grim#1637]
### Describe the false positive and how to replicate it

stand on the wall    "1.21/1.21.1Vanilla Client"
![Zulu-21 Screenshot 2024 08 13 - 04 36 36 47](https://github.com/user-attachments/assets/7df87cad-2ca7-428b-9cb3-ad47e48b1aa6)

### Grim version

2.3.66
https://www.spigotmc.org/resources/grim-anticheat.99923/update?update=558198

### Server version

paper-1.21.1-40.jar

### Plugins

Grimac

**Comment by SamB440** [comment]
I don't know why they cause falses, I discovered this a while ago but they have the exact same collision box as normal walls, and Grim is correctly using that box.
