### ISSUE TITLE
reach falses on armadillos 

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1641]
### Describe the false positive and how to replicate it

Hit armadillo

Grim seems to hardcode hitbox sizes, can we maybe use NMS or something to get entity data more dynamically, like if you don't wanna have to add new cases for every new entity type.

### Grim version

1222db18064256183f35b13b8fdcd11dca282ea9

### Server version

1.21.1 paper latest

### Plugins

grim

**Comment by ghost** [comment]
Also if hitbox size isn't known for an entity type, the method should return null, reach check should ignore the entity and a warning should be put into console maybe.

**Comment by SamB440** [comment]
We need cross version support, using NMS is bad and would not work for this, we'd have to use reflection as well which is terrible for performance

**Comment by ghost** [comment]
> Also if hitbox size isn't known for an entity type, the method should return null, reach check should ignore the entity and a warning should be put into console maybe.

Also if hitbox size isn't known for an entity type, the method should return null, reach check should ignore the entity and a warning should be put into console maybe.

This is probably better, also reflection is slow relatively speaking yeah but using it as fallback wouldn't be the end of the world.
