### ISSUE TITLE
Walking through cobwebs

### ISSUE THREAD

**Issue by Barpadzik** [GrimAnticheat/Grim#1645]
### Describe the bypass and how to replicate it

From what I've heard, there is a new cheat client thunder hack that has a workaround and people can easily go through the cobwebs, is there any special build that fixes it? I would ask for a repair and tests.

Here is a link to the cheat client
https://github.com/Pan4ur/ThunderHack-Recode/releases

### Grim version

2.3.65

### Server version

paper1k 1.16.5 and up

### Plugins

Self Written idk

**Comment by Souipi** [comment]
> ### Describe the bypass and how to replicate it
> From what I've heard, there is a new cheat client thunder hack that has a workaround and people can easily go through the cobwebs, is there any special build that fixes it? I would ask for a repair and tests.
> 
> Here is a link to the cheat client https://github.com/Pan4ur/ThunderHack-Recode/releases
> 
> ### Grim version
> 2.3.65
> 
> ### Server version
> paper1k 1.16.5
> 
> ### Plugins
> Self Written idk

Can you go on eu.loyisa.cn and record a video to proof this please ?

**Comment by ManInMyVan** [comment]
enable experimental checks

**Comment by MahadRegent** [comment]
I have seen this bypass in lb, check luqiudbounce

**Comment by Barpadzik** [comment]
That's right, LiquidBounce in the latest version has a dedicated bypass that works perfectly, but I can bet that it also occurs on the Thunder client.

Regarding experimental checks, BadPacketsX flags it quite well, but does not block. Flagging by BadPacketsX also results in Simulation being flagged once in a while, but this does not change the fact that it is only a flag, not an undo, etc.

Regarding the Thunder Hack, he also has a workaround dedicated to grima in the latest release. On the experimental ones, everything is beautifully flagged and slightly blocked, but blocking and reverting needs to be refined.

Just like on LiquidBouce, having ThunderHack doesn't flag anything without experimental checks.

So the bypass is fixed by BadPacketsX, it would be best if the 2.3.66 update also came out with the official implementation of this check and with a tweaked set back. For now, I think that after saving this issue, you can close the issue and just push the update. Best regards

**Comment by Barpadzik** [comment]
> eu.loyisa.cn

I see that you already have a patch for it there, now just wait for it to be released on spigot
