### ISSUE TITLE
Ignore cancelled packets

### ISSUE THREAD

**Issue by LilyLefty69** [GrimAnticheat/Grim#1646]
### Feature description

Any cancelled packet wouldn't be processed server-side anyway, and should then also not be processed on grim, since it would instead lead to false flags from any other plugin that is cancelling packets.

**Comment by ManInMyVan** [comment]
~~Ok so falses -> more falses~~ nvm I misunderstood what you were saying

**Comment by SamB440** [comment]
I don't understand what this even means, what cancelled packets?

**Comment by LilyLefty69** [comment]
> I don't understand what this even means, what cancelled packets?

in packetevents, if e.getCancelled() it shouldn't be flagging it. since the server won't process this packet.

**Comment by ManInMyVan** [comment]
So if the server sends a packet, but another plugin cancels it, we ignore it?

**Comment by LilyLefty69** [comment]
Either ignore / exempt the packet, preferably. It causes issues with my plugin when another plugin cancels certain packets.

**Comment by ManInMyVan** [comment]
> Either ignore / exempt the packet, preferably. It causes issues with my plugin when another plugin cancels certain packets.

If you're using shaded packetevents, try adding grim to your plugin.yml `softdepend` list. If you're using unshaded packetevents, try adding "packetevents" to grim's plugin.yml `loadbefore` list. If you aren't using packetevents, try using packetevents.

**Comment by SamB440** [comment]
You are welcome to open a a PR, I don't understand what you're trying to achieve here, if a packet is cancelled, Grim won't see it, it's running on its own packetevents instance

**Comment by LilyLefty69** [comment]
> > Either ignore / exempt the packet, preferably. It causes issues with my plugin when another plugin cancels certain packets.
> 
> If you're using shaded packetevents, try adding grim to your plugin.yml `softdepend` list. If you're using unshaded packetevents, try adding "packetevents" to grim's plugin.yml `loadbefore` list. If you aren't using packetevents, try using packetevents.

i have a different packetevents instance running, and i have a disconnect command which causes all packets to not be sent nor received by the client, so they get timed out without knowing what happened.

whenever disconnected tho, grim for some reason makes every movement a flag and they become frozen as well which i dont want.

is there a way to disconnect without jsut cancelling packets, or?

edit: it seems that grim might be sending packets silently? this means my thing doesnt cancel it. hm. or something else idk.

**Comment by ManInMyVan** [comment]
> > > Either ignore / exempt the packet, preferably. It causes issues with my plugin when another plugin cancels certain packets.
> > 
> > If you're using shaded packetevents, try adding grim to your plugin.yml `softdepend` list. If you're using unshaded packetevents, try adding "packetevents" to grim's plugin.yml `loadbefore` list. If you aren't using packetevents, try using packetevents.
> 
> i have a different packetevents instance running, and i have a disconnect command which causes all packets to not be sent nor received by the client, so they get timed out without knowing what happened.
> 
> whenever disconnected tho, grim for some reason makes every movement a flag and they become frozen as well which i dont want.
> 
> is there a way to disconnect without jsut cancelling packets, or?
> 
> edit: it seems that grim might be sending packets silently? this means my thing doesnt cancel it. hm. or something else idk.

~~What loads first, grim or your plugin?~~ try softdepending on grim

**Comment by SamB440** [comment]
You should use the plugin packetevents instance instead of shading, as currently this means your plugin and grim's order in the pipeline is random

**Comment by LilyLefty69** [comment]
> You should use the plugin packetevents instance instead of shading, as currently this means your plugin and grim's order in the pipeline is random

Having to use a dependencies like that is really annoying. i'll probably just search for another way then.
