### ISSUE TITLE
Riptide still falsing on latest

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1648]
### Describe the false positive and how to replicate it

Riptide flags simulation consistently on latest. The offset in verbose is as if grim doesn't even know what riptide enchantment is.

### Grim version

e62323bab5088e2f452d17d5cd3ded8bb2f419af

### Server version

This server is running Paper version 1.21.1-DEV-master@7c9240f (2024-08-13T09:54:30Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21-DEV-042f15f (MC: 1.21)

### Plugins

grim

**Comment by DontNeedAName** [comment]
Are you using ViaVersion? This could be related to what I mentioned in the discord yesterday. For some reason if after a restart the first player to join is on a version below 1.21, grim fails to recognize any enchantments until you restart the server.

**Comment by CatTeaA** [comment]
It can be reproduced. According to the comments above, by using the version 1.21 client and joining the 1.21.1 server first, the issue can be reproduced.
It's interesting that the first player to enter the server will not receive false reports as long as the client version is 1.21.1 (it cannot be version 1.21, it must specifically be 1.21.1).

**Comment by ghost** [comment]
> It can be reproduced. According to the comments above, by using the version 1.21 client and joining the 1.21.1 server first, the issue can be reproduced. It's interesting that the first player to enter the server will not receive false reports as long as the client version is 1.21.1 (it cannot be version 1.21, it must specifically be 1.21.1).

1.21.1 and 1.21 have the exact same client version, I don't think this is related.

**Comment by ghost** [comment]
> Are you using ViaVersion? This could be related to what I mentioned in the discord yesterday. For some reason if after a restart the first player to join is on a version below 1.21, grim fails to recognize any enchantments until you restart the server.

No viaversion or any protocol hacks, just straight 1.21 paper and grim

**Comment by CatTeaA** [comment]
> > It can be reproduced. According to the comments above, by using the version 1.21 client and joining the 1.21.1 server first, the issue can be reproduced. It's interesting that the first player to enter the server will not receive false reports as long as the client version is 1.21.1 (it cannot be version 1.21, it must specifically be 1.21.1).
> 
> 1.21.1 and 1.21 have the exact same client version, I don't think this is related.

NO，The server installed with grimac must have the first player to enter using the game client version 1.21.1; if the client version 1.21 is used, false positives will still be triggered subsequently, at least that's the result of my tests

**Comment by SamB440** [comment]
I am unable to reproduce any false flags without using the client version bug

**Comment by ghost** [comment]
> I am unable to reproduce any false flags without using the client version bug

What is the client version bug? I still don't understand how that would even be a thing since protocol version for 1.21 and 1.21.1 are identical?

**Comment by SamB440** [comment]
Should be fixed by https://github.com/retrooper/packetevents/pull/950
