### ISSUE TITLE
FastBreak still broken

### ISSUE THREAD

**Issue by Incluuu** [GrimAnticheat/Grim#1650]
### Describe the false positive and how to replicate it

Hey!
FastBreak also still false flagging.
I'm running latest Grim commit.
![image](https://github.com/user-attachments/assets/5e66b892-6e02-4015-8d19-4e9d373cf77d)

### Grim version

grimac-2.3.66

### Server version

Current Purpur Version: 1.21-2284-4e55e26 (MC: 1.21)

### Plugins

grimac, protocollib, viaversion and viabackwards

**Comment by Incluuu** [comment]
![image](https://github.com/user-attachments/assets/0188ada7-f5c9-452c-8c12-e8917aa1870f)

**Comment by SamB440** [comment]
Please attempt to reproduce without via and viabackwards and on a completely vanilla client

**Comment by bbb908** [comment]
> Please attempt to reproduce without via and viabackwards and on a completely vanilla client

this is more common to happen with servers when the tps drops lower than 19.2ish if that helps

**Comment by bbb908** [comment]
idk if it'll do it without via but u can try

**Comment by Incluuu** [comment]
> Please attempt to reproduce without via and viabackwards and on a completely vanilla client

The error is on versions 1.20.x 1.19.x or lower (below version <1.21)

**Comment by SamB440** [comment]
What tool and block has the issue? There is also a packetevents bug right now when viabackwards is installed and the first client that joins is an older one, all enchants will be unable to be read. Please confirm first whether that is an issue.

**Comment by Incluuu** [comment]
The problem is when digging stone using pickaxes. Appears below version <1.21.
I joined first via minecraft version 1.21, then later 1.19.4, it didn't help.

step by step
1. Install paper 1.21
2. Install viabackwards, viaversion, grimac and protocollib
3. Join on minecraft 1.21 and 1.12.2 or 1.19.4 client version
4. Break stone on 1.19.4/1.12.2 version clinet

**Comment by SamB440** [comment]
I'm not able to reproduce this, please retry with the latest commit

**Comment by Incluuu** [comment]
https://github.com/user-attachments/assets/81d8d534-72ca-4867-a223-57b9dab424bc


pickaxe: iron_pickaxe with eff 2

I use latest commit [grimac-2.3.67 - today]

![image](https://github.com/user-attachments/assets/d01d52ce-7059-43cf-89fe-594107becc8c)

Current Purpur Version: 1.21.1-2289-201e928 (MC: 1.21.1)
I have to break the stone 2 times.

![image](https://github.com/user-attachments/assets/50dadf1e-489b-41dd-9989-8bbf93a2339e)

**Comment by SamB440** [comment]
Unfortunately I still can't reproduce this on a 1.21 server with a 1.16.5 and 1.19.4 client, with the exact same pickaxe you used on stone

**Comment by Incluuu** [comment]
> Unfortunately I still can't reproduce this on a 1.21 server with a 1.16.5 and 1.19.4 client, with the exact same pickaxe you used on stone

linux or windows?

**Comment by SamB440** [comment]
Windows, though I don't see the OS making a difference. Are you using Lunar client?

**Comment by Incluuu** [comment]
> Windows, though I don't see the OS making a difference. Are you using Lunar client?

Minecraft launcher with minecraft.net
