### ISSUE TITLE
Adding support for custom climbables.

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1651]
### Feature description

The amount of blocks that are climbable can be extended via a datapack in climbables.json. However this results in false simulation checks with Grim.

I have set chains to be climbable via a datapack, climbing the chain results in falses from Grim. The default vanilla climbables work fine.

I would like to see support for using more blocks as climbables. If this is not possible due to not being able to read what blocks are climbable, perhaps let the user define climbable blocks in the config?

**Comment by SamB440** [comment]
Please try the linked pr

**Comment by ghost** [comment]
> Please try the linked pr

Works 👍 thank you very much
