### ISSUE TITLE
Fastbreak with enchanted pickaxe false positive

### ISSUE THREAD

**Issue by NNickey** [GrimAnticheat/Grim#1656]
### Describe the false positive and how to replicate it

Enchanted diamond pickaxe with Efficiency IV and Unbreaking III.
Attempt to break stone blocks.
Grim logging FastBreak on console and preventing block breaking.

### Grim version

2.3.65

### Server version

1.21-130-master@b1b5d4c

### Plugins

Paper Plugins:
EconomyShopGUI

Bukkit Plugins:
BlockProt, BlueMap, connect, DecentHolograms, Essentials, EssentialsChat, EssentialsSpawn, ExcellentCrates, FastAsyncWorldEdit, floodgate, Geyser-Spigot, GrimAC, HeadBlocks, InfernalMobs, LuckPerms, MinePass, nightcore, PlayerAuctions, ProtocolLib, RandomTeleport, Towny, Vault, ViaVersion, WorldGuard

**Comment by lilnarco** [comment]
You are using an old version. Update to latest
