### ISSUE TITLE
GroundSpoof and Simulation false when dimension minY incorrect

### ISSUE THREAD

**Issue by Ayouuuu** [GrimAnticheat/Grim#1663]
### Describe the false positive and how to replicate it

1. Download this [paper 1.18.2 ](https://github.com/Ayouuuu/PaperServer/releases/tag/1.0)
3. Put `grim-2.3.67.jar` into plugins
4. Run server
5. Join Server
6. false...

### Grim version

[grim-2.3.67](https://github.com/GrimAnticheat/Grim/actions/runs/10454302359)

### Server version

Paper 1.18.2

### Plugins

GrimAC

**Comment by SamB440** [comment]
What do you mean 'dimension minY incorrect'? Grim already checks for world height, if the world height it gets is incorrect then report this issue to packetevents

**Comment by Ayouuuu** [comment]
But [setDimension()](https://github.com/GrimAnticheat/Grim/blob/2.0/src/main/java/ac/grim/grimac/utils/latency/CompensatedWorld.java#L678-L679) getMinY() and getHeight() method return static [DimensionTypes OVERWORLD](https://github.com/retrooper/packetevents/blob/f4bb1dd8fc92cc06be8bb223049e81f4b927e691/api/src/main/java/com/github/retrooper/packetevents/protocol/world/dimension/DimensionTypes.java#L42-L45) value, if you get the heights directly from the NBT like this [commit](https://github.com/GrimAnticheat/Grim/commit/b5c8558b571984baaa18f9d4592d8a98962a4864#diff-c3d055d1c19e013baa7ce61976a731b00253321970e9f503d65cbedca0ac850fL691-L692), it works fine.

#1659

**Comment by SamB440** [comment]
Can this be closed by the latest commit? idk if this is the same as the other 2

**Comment by Ayouuuu** [comment]
> Can this be closed by the latest commit? idk if this is the same as the other 2

I just tested it latest commit [artifact](https://github.com/GrimAnticheat/Grim/actions/runs/10510407271) still not work
I think that's the problem [here](https://github.com/GrimAnticheat/Grim/blob/2.0/src/main/java/ac/grim/grimac/utils/latency/CompensatedWorld.java#L678-L679)

**Comment by ChicknTurtle** [comment]
I have this issue with grim 2.3.66 on paper 1.21.1
I am using amplified nether + amplified nether height datapacks
I can't move on blocks above y256

**Comment by Ayouuuu** [comment]
[fixed](https://github.com/GrimAnticheat/Grim/actions/runs/10999156698)
