### ISSUE TITLE
join server in nether/end 

### ISSUE THREAD

**Issue by Dbbtop** [GrimAnticheat/Grim#1666]
### Describe the false positive and how to replicate it

When a player joins a server in nether or ender world, he can't move, but verbose doesn't show anything. If you run the server without grim, then this bug disappears. This is accompanied by a lot of errors in the console

### Grim version

latest commit

### Server version

purpur 1.19.4

### Client version

vanilla 1.19.4

### Plugins

packetevents, grim

**Comment by ManInMyVan** [comment]
> a lot of errors

make an error report

**Comment by Dbbtop** [comment]
> > a lot of errors
> 
> make an error report

https://pastebin.com/0jVnhBuF
