### ISSUE TITLE
Frequently breaking 'Coral_Fans' can cause false alerts

### ISSUE THREAD

**Issue by CatTeaA** [GrimAnticheat/Grim#1672]
### Describe the false positive and how to replicate it

https://github.com/user-attachments/assets/759fc2ed-f104-4653-8aba-8118b354a7df

### Grim version

Grimac2.3.66
https://www.spigotmc.org/resources/grim-anticheat.99923/update?update=558198

### Server version

paper-1.21.1-40.jar

### Client version

1.21 & Vanilla1.21.1

### Plugins

Grimac，FastAsyncWorldEdit

**Comment by Axionize** [comment]
This has been fixed for a very long time... why is this issue still open?
