### ISSUE TITLE
trident on low durability

### ISSUE THREAD

**Issue by Dbbtop** [GrimAnticheat/Grim#1675]
### Describe the false positive and how to replicate it

1) Try to throw a trident with 1 durability
2) noslow false
video - https://mega.nz/file/i3gEhR4b#WOLCeI0LWyr6kYkqH-L04STpO1InJJoY7EQTBUO1EwY

### Grim version

latest commit

### Server version

purpur 1.19.4

### Client version

vanilla 1.19.4

### Plugins

packetevents, grim

**Comment by SamB440** [comment]
https://github.com/GrimAnticheat/Grim/commit/24a51d9584c6d4234cea0d19b83fc4d326c140c3
