### ISSUE TITLE
world generation datapack incompatibility

### ISSUE THREAD

**Issue by Dbbtop** [GrimAnticheat/Grim#1676]
### Describe the bug and how to replicate it

when using the Terralith datapack, players who have connected to the game in nether or the end cannot move from their place (there was no such error in grim 2.3.65)

### Grim version

latest commit

### Server version

1.19.4

### Plugins

grim

**Comment by Ayouuuu** [comment]
#1659  
#1663

**Comment by Dbbtop** [comment]
> #1659 #1663

Shouldn't it be fixed?

**Comment by Aurimous29317** [comment]
хуйня фиксите

**Comment by Aurimous29317** [comment]
если не зафиксите будет фистинг :D

**Comment by SamB440** [comment]
Can you retry on the latest commit again, I made it redownload dependencies

I tested the current code and packetevents is correctly grabbing the world height on my server with a height datapack

**Comment by Dbbtop** [comment]
> Can you retry on the latest commit again, I made it redownload dependencies
> 
> I tested the current code and packetevents is correctly grabbing the world height on my server with a height datapack

nothing changed, i still can't move if join server in nether

**Comment by Dbbtop** [comment]
> Can you retry on the latest commit again, I made it redownload dependencies
> 
> I tested the current code and packetevents is correctly grabbing the world height on my server with a height datapack

try to test terralith

**Comment by SamB440** [comment]
It doesn't seem to be a world height / dimension issue, that's being read correctly, it seems to be something else in packetevents

**Comment by SamB440** [comment]
Try on the new commit

**Comment by Dbbtop** [comment]
it seems to be fixed

**Comment by Dbbtop** [comment]
now can you check my trident false ?

**Comment by Dbbtop** [comment]
when fix it ?

**Comment by SamB440** [comment]
https://github.com/retrooper/packetevents/issues/962

**Comment by Dbbtop** [comment]
How much longer to wait?

**Comment by SamB440** [comment]
Please try on the latest commit (packetevents 2.5.1)

**Comment by Dbbtop** [comment]
fixed, thanks
