### ISSUE TITLE
can't move (again)

### ISSUE THREAD

**Issue by Dbbtop** [GrimAnticheat/Grim#1677]
### Describe the bug and how to replicate it

#1676 fixed, but now i can't move when teleport in nether or the end

### Grim version

latest commit

### Server version

1.19.4

### Plugins

grim

**Comment by SamB440** [comment]
Unable to reproduce

**Comment by Dbbtop** [comment]
> Unable to reproduce

Tomorrow I will sent a video

**Comment by SamB440** [comment]
Seems to happen on 1.19.4 clients, but not modern ones

**Comment by Dbbtop** [comment]
did you install terralith datapack on 1.19.4 server?

**Comment by Dbbtop** [comment]
> did you install terralith datapack on 1.19.4 server?

this is mandatory

**Comment by MichaelKozlovOfficial** [comment]
how would he know what to install

**Comment by Dbbtop** [comment]
> how would he know what to install

Я русский перепиши сообщение

**Comment by SamB440** [comment]
The problem is because the respawn dimension type is latency compensated, whilst the packetevents user was not

I am closing this and reverting the fix I made previously, this needs to be fixed on packetevent's end instead
