### ISSUE TITLE
New input packet

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1702]
### Feature description

Latest snapshot 24w36a just added a keyboard input packet.
```java
Client:
@Override
public void tick() {
if (this.getWorld().isPosLoaded(this.getBlockX(), this.getBlockZ())) {
	super.tick();
	this.sendSneakingPacket();
	if (!this.field_54156.equals(this.input.field_54155)) {
		this.networkHandler.sendPacket(new PlayerInputC2SPacket(this.input.field_54155));
		this.field_54156 = this.input.field_54155;
	}
```
```java
@Override
	public void onPlayerInput(PlayerInputC2SPacket packet) {
		NetworkThreadUtils.forceMainThread(packet, this, this.player.getServerWorld());
		this.player.method_63561(packet.input());
	}
```

```java
	public record class_10185(boolean forward, boolean backward, boolean left, boolean right, boolean jump, boolean shift, boolean sprint) {
```

This opens up the possibility for a huge amount of cool new checks.

**Comment by SamB440** [comment]
No it doesn't give us cool new checks, we already have this information from the prediction engine, it's useful to heavily improve performance though. Client also sends an END_TICK packet now too, so idle tick is back.

**Comment by ghost** [comment]
> No it doesn't give us cool new checks, we already have this information from the prediction engine, it's useful to heavily improve performance though. Client also sends an END_TICK packet now too, so idle tick is back.

already having the information from the prediction engine is exactly why this is cool, we can compare them for discrepancies, synthetic movement likely wouldn't have the corresponding input in the packet, can also validate sprinting, jumping and sneaking

**Comment by SamB440** [comment]
That's already what the prediction engine does, validates inputs. All that's changed is we no longer need to bruteforce the possible inputs.

**Comment by overkidding** [comment]
> No it doesn't give us cool new checks

It could be a good way to check if a client sent a sprinting or smt packet without an input packet or am i wrong

**Comment by ManInMyVan** [comment]
> > No it doesn't give us cool new checks
> 
> It could be a good way to check if a client sent a sprinting or smt packet without an input packet or am i wrong

Using toggle sprint would flag if we checked for this

**Comment by overkidding** [comment]
> Using toggle sprint would flag if we checked for this

Then if a player is moving but not pressing any key? (Could actually fix auto walk duh now that i think about it)

**Comment by ManInMyVan** [comment]
> Then if a player is moving but not pressing any key?

Yes, we will probably use the client input instead of bruteforcing it

> Could actually fix auto walk duh now that i think about it

No, the client can modify this.

**Comment by overkidding** [comment]
> No, the client can modify this.

I know but trash ass clients wouldn't know that the packet exists so it will just start walking without any input

**Comment by FirephoenixX02** [comment]
> > No, the client can modify this.
> 
> I know but trash ass clients wouldn't know that the packet exists so it will just start walking without any input

Everyone just sets the walking keybind pressed state to true, its one line, and the client handles all the movement correctly like usual. Don't see a reason why this wouldn't behave the same with the new snapshot.
