### ISSUE TITLE
Error when logging in players when starting the server

### ISSUE THREAD

**Issue by vladyaso** [GrimAnticheat/Grim#1703]
### Stack trace

https://paste.gg/p/anonymous/58e4e1f109c5475db8c0203a18ae007b/revisions

### How to replicate it if known

1. Start the server
2. Log in to it server

### Grim version

2.3.66

### Plugins

The crossed out plugins are plugins that we wrote.

**Comment by ManInMyVan** [comment]
one of your plugins is sending an invalid team name or something

**Comment by vladyaso** [comment]
How can I find out which plugin?

**Comment by ManInMyVan** [comment]
> How can I find out which plugin?

You could remove them one by one

**Comment by vladyaso** [comment]
![image](https://github.com/user-attachments/assets/c2d1ae5c-7cc0-4e79-a496-fb65a53e6af5)
what it this?

**Comment by SamB440** [comment]
Grim is disconnecting players because they aren’t responding to transaction packets
