### ISSUE TITLE
Packetevents error spam

### ISSUE THREAD

**Issue by Flaame7** [GrimAnticheat/Grim#1708]
### Stack trace

https://pastebin.com/raw/EfysppqL

### How to replicate it if known

This error happens only when a player join my server in 1.21 and spams this in console
every second.

### Grim version

2.3.66

### Server version

1.8.8

### Plugins

Grim, Vulcan, LPX, CoreProtect, PAPI, ProtocolLIB, TAB, Citizens, ViaVersion, Spark

**Comment by SamB440** [comment]
Your server is sending a team name longer than permitted for that server version. most likely TAB. See https://github.com/retrooper/packetevents/issues/960
