### ISSUE TITLE
kelp underwater

### ISSUE THREAD

**Issue by Dbbtop** [GrimAnticheat/Grim#1712]
### Describe the false positive and how to replicate it

video: https://mega.nz/file/uiRQxQrY#WKDRC9Jo1DMMnZCwZ-ZGf4e-3D8qI8kDVNR_mhcO5rI

### Grim version

latest commit

### Server version

1.19.4

### Client version

vanilla 1.19.4

### Plugins

grim, viaversion, LP

**Comment by Axionize** [comment]
Fixed https://github.com/GrimAnticheat/Grim/pull/1817
