### ISSUE TITLE
Bypass on some worlds or players

### ISSUE THREAD

**Issue by ceres-dev** [GrimAnticheat/Grim#1716]
### Feature description

I have a problem, on my server I have anarchic and other modes. The idea is that the anarchic and grim are disabled but in other modes they are enabled. Does anyone know which method or class I would have to modify?

**Comment by ManInMyVan** [comment]
You could probably use the API and cancel any flags where the player is in the anarchy world. You could also update the player's permissions on world change (should be possible with API) and give them grim.exempt in the anarchy server (possible with contexts in luckperms)
