### ISSUE TITLE
Unplayable from y=320 and above with increased height limit datapack

### ISSUE THREAD

**Issue by Learting** [GrimAnticheat/Grim#1717]
### Describe the false positive and how to replicate it

1. install an increased height limit datapack to world save (I’ve attached the one that I used.)
2. becomes unplayable, unable to stand / move / climb etc., from y=320 and above
[higherheightlimitomega.zip](https://github.com/user-attachments/files/16992197/higherheightlimitomega.zip)

### Grim Log

https://paste.grim.ac/r12k9e3

### Server version

> version
[17:53:28 INFO]: Checking version, please wait...
[17:53:29 INFO]: Current Purpur Version: 1.21.1-2305-fdfc12e (MC: 1.21.1)*
* You are running the latest version

### Client version

1.21.1

### Plugins

> plugins
[17:53:41 INFO]: Paper Plugins: (0):
[17:53:41 INFO]: Bukkit Plugins: (2):
[17:53:41 INFO]:  - GrimAC, WorldEdit

**Comment by SamB440** [comment]
See #1676, packetevents issuue

**Comment by SamB440** [comment]
You can also try updating to 2.3.67 to see if packetevents fixed the issue somehow. Don't use spigot it's outdated. Use modrinth or hangar.
