### ISSUE TITLE
After respawn, the player is lagging state from the perspective of other players

### ISSUE THREAD

**Issue by Dg32z** [GrimAnticheat/Grim#1722]
### Describe the bug and how to replicate it

https://github.com/user-attachments/assets/84b978e4-540b-488d-b4bf-eedf9ddbbc3f

### Grim version

2.3.68

### Server version

ver
[23:07:38 INFO]: This server is running Paper version 1.21.1-41-master@fcedb49 (2024-08-24T09:02:10Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are 36 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21.1-13-7c9240f (MC: 1.21.1)
> 

### Plugins

[23:07:47 INFO]: Server Plugins (11):
[23:07:47 INFO]: Bukkit Plugins:
[23:07:47 INFO]:  - FastAsyncWorldEdit, FastCrystal, GrimAC, LiteBans, LuckPerms, PlaceholderAPI, ProtocolLib, pvp
[23:07:47 INFO]:  Vault, ViaBackwards, ViaVersion

**Comment by SamB440** [comment]
Provide a valid reproduction method

**Comment by Dg32z** [comment]
> Provide a valid reproduction method

This is the code used to implement death
[1.txt](https://github.com/user-attachments/files/17006345/1.txt)

**Comment by Dg32z** [comment]
This problem often occurs on my server ):

**Comment by Dg32z** [comment]
solved

**Comment by SamB440** [comment]
What was the cause?

**Comment by Dg32z** [comment]
> What was the cause?

            if (player.compensatedEntities.getSelf().isDead) {
                event.setCancelled(true);
from SetBackBlocker.java

**Comment by SamB440** [comment]
If grim thinks the player is dead when it’s not then you have a bigger issue there

**Comment by Dg32z** [comment]
> If grim thinks the player is dead when it’s not then you have a bigger issue there

but player.bukkitPlayer.isDead() return false

**Comment by Axionize** [comment]
I'm willing to bet you have a plugin that is setting the bukkitPlayer's dead state incorrectly. Probably whatever plugin is handling your minigame and respawning the player.
