### ISSUE TITLE
Server Registration Bug

### ISSUE THREAD

**Issue by Doggy7331** [GrimAnticheat/Grim#1731]
### Describe the bug and how to replicate it

I created a TXT record on my domain's DNS settings as it is in the Server Registration instruction and after 3 days I still have ,,missing" in ,,record found" section. My server's domain is ,,bagmc.pl" and I have more than 50 legal players.

### Grim version

2.3.65

### Server version

Paper version git-Paper_409 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

### Plugins

![obraz_2024-09-21_112659934](https://github.com/user-attachments/assets/2e9f4b5a-81c8-433c-885b-9c1eb74a9d4d)

**Comment by SamB440** [comment]
Please contact aoelite on discord, this issue tracker is not for 3.0 related issues
