### ISSUE TITLE
0.03 allows excessive movement in cobweb

### ISSUE THREAD

**Issue by 6ex9one** [GrimAnticheat/Grim#1734]
### Describe the bypass and how to replicate it

Players have found a workaround for flying on elytra, all they can do is put on elytra and fly straight up in the Y direction. Please fix this

### Grim version

2.3.67

### Server version

1.16.5

### Plugins

***

**Comment by SamB440** [comment]
Provide a debug log

**Comment by 6ex9one** [comment]
> Provide a debug log

As soon as I meet the player again, I will try to write down the debug code. But you can check this yourself using any cheat.

**Comment by SamB440** [comment]
What is your max-firework-boost-ping set to in the config

**Comment by SamB440** [comment]
>  But you can check this yourself using any cheat.

Also no I can't, it flags me.

**Comment by Bruhdows** [comment]
I've had a bit of Turkish users abusing this on my server. I can provide more info myself soon.

**Comment by SamB440** [comment]
Any update?

**Comment by Bruhdows** [comment]
Really weird bypass, can't really reproduce it.

**Comment by SamB440** [comment]
Could be a config issue

**Comment by Bruhdows** [comment]
Found it, you can use Y Elytra Flight in Cobwebs. It completely does not flag anything. You just need to overlap with the Cobwebs Bounding Box.

https://github.com/user-attachments/assets/4664d0cb-b20f-4aba-a097-fb5710dd1598

**Comment by SamB440** [comment]
Oh then it’s not a big issue then. Likely 0.03 gets triggered since you’re moving so slow

**Comment by Bruhdows** [comment]
Um, also when the speed is low enough you can easily travel thru cobwebs horizontally. Probably the same issue.


https://github.com/user-attachments/assets/2242759e-f185-4c92-969b-cd2e51ced1d1

**Comment by Bruhdows** [comment]
I would try coding a fix for that. I don't know where to start tho, should I check out the current checks or create a new one just for that?

**Comment by SamB440** [comment]
Can you provide a grim log, by triggering a flag when you exit the cobweb in the first video, as it will include the movement before that

**Comment by Bruhdows** [comment]
It was uploading and uploaded, but the provided link redirects to Not found page.

**Comment by SamB440** [comment]
Try reloading or just sending it here or trying again, cloudflare cache messes it up

**Comment by SamB440** [comment]
Superseded by #1786
