### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by heper651** [GrimAnticheat/Grim#1738]
### Describe the bypass and how to replicate it

Hello people, I encountered a problem when using GrimAC: if you stand on a block of the path, it visually disappears but remains in place, can this be fixed somehow? (GrimAC is to blame)

### Grim version

2.3.67

### Server version

1.16.5 paper

### Plugins

![image](https://github.com/user-attachments/assets/b5239d6b-4ba4-4505-b740-304169bc34ef)

**Comment by SamB440** [comment]
This is not a bypass, and see #1733
