### ISSUE TITLE
Right-Click false positive

### ISSUE THREAD

**Issue by KinczeK** [GrimAnticheat/Grim#1743]
### Describe the false positive and how to replicate it

1. Be in a cobweb or any block that slows you down
2. Attack other players
3. Hold right mouse click and then attack
Example video: https://medal.tv/games/minecraft/clips/iIWvMvyxiS8XFVntb/d1337Y0viwDp?invite=cr-MSxYVjYsMjQwMDU2NDAxLA (banned for hitboxes/reach)

### Grim version

2.3.67 (latest)

### Server version

paper 1.16.5

### Client version

Feather Client, Lunar Client 1.16.5-1.20.4 (might be working for all versions)

### Plugins

Chunky, Citizens, DecentHolograms, FastAsyncWorldEdit, GrimAC, LPX, PlugManX, Shopkeepers, TradePlus, Vault, ViaBackwards, ViaVersion, Vulcan, WorldGuard

**Comment by SamB440** [comment]
Feather client and Lunar client are not vanilla.

Please try and reproduce this issue yourself on a vanilla client.
