### ISSUE TITLE
Fix check please

### ISSUE THREAD

**Issue by rejomy** [GrimAnticheat/Grim#1752]
### Describe the bug and how to replicate it

https://github.com/GrimAnticheat/Grim/blob/2.0/src/main/java/ac/grim/grimac/checks/impl/aim/AimModulo360.java
this commit break logic of this check
https://github.com/GrimAnticheat/Grim/commit/843840c3205188272bd8f811f6aba5e387ada74c
by the way if its can false, its heuristics check?

lastDeltaYaw = rotationUpdate.getDeltaXRot();
        if (player.packetStateData.lastPacketWasTeleport) return;
        if (player.xRot < 360 && player.xRot > -360 && Math.abs(rotationUpdate.getDeltaXRot()) > 320 && Math.abs(lastDeltaYaw) < 30) {

code:

Math.abs(rotationUpdate.getDeltaXRot()) > 320 && Math.abs(lastDeltaYaw) < 30

but lastDeltaYaw already equals rotationUpdate.getDeltaXRot(), so your code:

Math.abs(x) > 320 && Math.abs(x) < 30

### Grim version

666

### Server version

666

### Plugins

FlightA check that cache 99% of hackers

**Comment by Souipi** [comment]
No an heuristic check, it's when you're using magic values.

**Comment by Souipi** [comment]
Btw this is a big troll issue...

**Comment by rejomy** [comment]
> Btw this is a big troll issue...

why? I talking about broken check if u not agree with me, say why?

**Comment by rejomy** [comment]
> No an heuristic check, it's when you're using magic values.

but this use "magic" numbers too
