### ISSUE TITLE
"Unknown nbt type id 20" with items using new 1.20.5+ Components

### ISSUE THREAD

**Issue by JRGrim** [GrimAnticheat/Grim#1761]
### Stack trace

https://paste.sparked.host/ewonusuhed.php

### How to replicate it if known

Step 1. Make an Oraxen item using Components like food (in my case)https://docs.oraxen.com/configuration/items-advanced#1205-specific-properties (My item config: https://paste.sparked.host/emozayuden.yaml)
Step 2. /o reload all to add the item to the server.
Step 3. /o inv to open the inventory in a GUI.

### Grim version

![Screenshot_3693](https://github.com/user-attachments/assets/25b5eb3a-3613-4b3f-9fe4-6705769b2433)

### Server version

![Screenshot_3692](https://github.com/user-attachments/assets/698bb961-864e-45df-a22c-e7c69a44bfba)

### Plugins

![Screenshot_3694](https://github.com/user-attachments/assets/845a8677-0fbe-4a20-8919-a8a62458d35c)

**Comment by SamB440** [comment]
That's a packetevents issue that was likely fixed in https://github.com/retrooper/packetevents/commit/487bcc3461ab42ecfb5df83a02788cc33d9850ad
