### ISSUE TITLE
Shields breaking isn't recognized

### ISSUE THREAD

**Issue by DontNeedAName** [GrimAnticheat/Grim#1766]
### Describe the false positive and how to replicate it

https://github.com/user-attachments/assets/58c2c2b3-17c0-429f-b788-8d58b838a1a8

### Grim version

2.3.67

### Server version

This server is running Paper version 1.21.1-119-master@7cd4f2c (2024-10-03T15:19:34Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### Client version

1.21.1

### Plugins

AntiHealthIndicator, floodgate, Geyser-Spigot, GrimAC, OpenInv, ProtocolLib, SMPPlugin

**Comment by DanilGnedin** [comment]
Um you can bugging this if you change shield of first and second hands and fast clicking.just Catch timing )

**Comment by DontNeedAName** [comment]
> Um you can bugging this if you change shield of first and second hands and fast clicking.just Catch timing )

<img width="340" alt="621" src="https://github.com/user-attachments/assets/2749ca50-0e13-49ce-ac16-c480e2924488">
