### ISSUE TITLE
morecarry/xcarry bypass on liquidebounce

### ISSUE THREAD

**Issue by realduziy** [GrimAnticheat/Grim#1768]
### Describe the bypass and how to replicate it

![image](https://github.com/user-attachments/assets/7ad35cc2-ad51-4c1c-a150-6d4362d662ef)
![image](https://github.com/user-attachments/assets/7ecaeab0-98d3-4686-a2cc-d73446487950)

### Grim version

2.3.68

### Server version

1.21.1

### Plugins

just grimac

**Comment by SamB440** [comment]
There's no proper way to fix this.

**Comment by realduziy** [comment]
I see, Was not sure if there was or not

**Comment by ManInMyVan** [comment]
#995

**Comment by Axionize** [comment]
Fixed in my fork https://modrinth.com/plugin/lightning-grim-anticheat
