### ISSUE TITLE
BADPACKETSE false for 1.21.2+ clients

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1769]
### Describe the false positive and how to replicate it

Ride any vehicle in 1.21.2 (using viaversion, not a viaversion issue though, I think they made clients send flying packets while riding in 1.21.2+, or changed how steer vehicle packets are sent, idk)

### Grim version

b0cd32622e0dbaa1d6bded568e4db80d1ec21d6d a bit out of date but im pretty sure same issue happens on latest grim

### Server version

This server is running Paper version 1.21.1-DEV-master@14a48cd (2024-10-21T13:11:50Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21.1-DEV-7cd4f2c (MC: 1.21.1)

### Client version

1.21.3

### Plugins

Grim

**Comment by SamB440** [comment]
ViaVersion has decided it’s a great idea to send steer vehicle packets when a player is not in a vehicle.

We are done trying to fix via issues. We will be making a packetevents fork and bypassing via for certain listeners.

**Comment by SamB440** [comment]
As a temporary fix we can see if they are in a vehicle server side

**Comment by ghost** [comment]
> As a temporary fix we can see if they are in a vehicle server side

turns out it also falses even with vehicle check im pretty sure, maybe they just left vehicle but idk, im not using grims lag compenated vehicle check just player.isInVehicle()

**Comment by SamB440** [comment]
Bukkit player? Try the compensatedEntities.serverPlayerVehicle or whatever it was called.

**Comment by ghost** [comment]
> Bukkit player? Try the compensatedEntities.serverPlayerVehicle or whatever it was called.

well currently I just have it disabled for now until i can get rid of viaversion

**Comment by ManInMyVan** [comment]
> for certain listeners

why not all of them?
