### ISSUE TITLE
False positive when walking on snow (1.8 server with 1.13 + client)

### ISSUE THREAD

**Issue by toluam17** [GrimAnticheat/Grim#1770]
### Describe the false positive and how to replicate it

make a whole block of snow with snow, add another snow. Jump on and you will false simulation

### Grim Log

https://paste.grim.ac/ss5j5oy

### Server version

1.8.8 paper based, 

### Client version

1.13 + clients

### Plugins

Viaversion, Grim

**Comment by ManInMyVan** [comment]
[this](https://github.com/GrimAnticheat/Grim/blob/2.0/src/main/java/ac/grim/grimac/utils/collisions/CollisionData.java#L552) is somehow broken

**Comment by Axionize** [comment]
Are you sure this issue still exists? I can't reproduce.

Also WTF does Farmland have to do with this issue? I'm guessing you linked the right thing but it changed over time @ManInMyVan ? What commit corresponds to release 2.6.67?

**Comment by ManInMyVan** [comment]
> Are you sure this issue still exists? I can't reproduce.

last I checked this still existed

> Also WTF does Farmland have to do with this issue? I'm guessing you linked the right thing but it changed over time @ManInMyVan ?

fixed now

> What commit corresponds to release 2.6.67?

2.6.67 never existed

**Comment by ManInMyVan** [comment]
now that I think of it, shouldn't the layers be set to 0 if snow collisions aren't being fixed?

**Comment by ManInMyVan** [comment]
>  I can't reproduce.

on pre-1.13 server and post-1.13 client: place a single snow layer on the ground and walk on it. You may need to change snow collision fix in your via config

**Comment by Axionize** [comment]
I have snow-collision-fix set to off (which is the default) and everything is working. Can't reproduce.
