### ISSUE TITLE
Grim Premium 

### ISSUE THREAD

**Issue by Briiqn** [GrimAnticheat/Grim#1774]
Hello, I am seeking clarification regarding how Grim Premium operates. My understanding is that Grim AntiCheat is licensed under the GPLv3, which requires that the source code be made accessible under all circumstances. Additionally, the configuration file explicitly states:

> "# Modified binaries, or plugins with copied Grim code, must be private,  
> or with full source code available to buyers at no additional cost."

The configuration file can be viewed here: [config](https://github.com/GrimAnticheat/Grim/blob/2.0/src/main/resources/config/en.yml).

If I purchase Grim Premium, will I be provided access to the modified source code?

**Comment by AoElite** [comment]
@Briiqn Grim Premium is considered a separate project and would fall under a separate license. Also this project is going to probably be changing to MIT or something.

**Comment by SamB440** [comment]
2.0 is GPLv3, 3.0 is not

**Comment by Briiqn** [comment]
Thank you for the clarification regarding Grim Premium's licensing. To make sure I understand correctly: Since the current version of Grim Premium is based on the community Grim project, would all previous versions of Grim Premium (prior to any license change) still fall under the GPL license requirements?

**Comment by SamB440** [comment]
Grim premium is not based on 2.0 and is a complete recode

**Comment by NoboKik** [comment]
> Grim premium / 3.0 is not based on 2.0 and is a complete recode

![image](https://github.com/user-attachments/assets/5e328c5f-fbd2-4757-a7e8-9f64fc885f93)
what about this?

**Comment by NoboKik** [comment]
Grim 3.0 config also looks around the same as 2.0's config, so it probably uses the same base (and also seems to include all the same checks as 2.0)

<details>
<summary>1</summary>

![image](https://github.com/user-attachments/assets/0efab178-80f6-4069-9c65-595aeb0cc8ce)

![image](https://github.com/user-attachments/assets/cbda13b3-5d94-471c-b990-e441cad5d9ec)
</details>

<details>
<summary>2</summary>

![image](https://github.com/user-attachments/assets/85f70efa-e86f-4e63-bf8b-b1baf6926a81)

![image](https://github.com/user-attachments/assets/1a4a5b1d-be5d-4664-a4d7-bb275fa236a2)
</details>

**Comment by NoboKik** [comment]
Some other code from 2.0 that is in premium / 3.0 (which clearly breaks GPL)
<details>
<summary>code</summary>

![image](https://github.com/user-attachments/assets/3b0ffad8-3a13-43bb-8fdd-8f0c86407c8d)

![image](https://github.com/user-attachments/assets/b46e8f2f-b6e9-4b37-9172-77f36af685f3)
</details>

**Comment by SamB440** [comment]
DefineOutside owns that code and can do what he wants with it. As for the prs, those have to be adapted to the 3.0 codebase. No one cares if an if statement is the same.
