### ISSUE TITLE
Grim Premium

### ISSUE THREAD

**Issue by Briiqn** [GrimAnticheat/Grim#1775]
Hello, why was my issue removed?

It raised a valid question in which your customers should know before buying 3.0

If Grim 3.0 is based on 2.0 it should be under GPL otherwise what's the point of essentially buying a proprietary grim 2.0 fork with no source availability?

**Comment by AoElite** [comment]
@Briiqn Grim Premium isn't based on 2.0

**Comment by Briiqn** [comment]
Thank you for the response. However, I would appreciate evidence to verify this claim. This could be demonstrated through:

1. A comparison of snippets of code (e.g the simulation engine)

2. Grim 3.0's project file structure demonstrating a separate codebase

**Comment by SamB440** [comment]
You have the obfuscated source, go look yourself.
