### ISSUE TITLE
BadPackets for riding Minecon

### ISSUE THREAD

**Issue by nootserp** [GrimAnticheat/Grim#1796]
### Describe the false positive and how to replicate it

Play on the 1.21 Feather Fabric on the server version 1.21 and ride Minecon

### Grim version

2.3.67

### Server version

This server is running Paper version 1.21-130-master@b1b5d4c (2024-08-10T10:02:42Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
You are running the latest version

### Client version

1.21 Feather Fabric

### Plugins

AuthMe, AutoMessage, BetterRTP, Essentials, getClan, GriefPrevention, GrimAC, LuckPerms, PlaceholderAPI, SkinsRestorer, Sonar, TAB, UltimateAntiBot, Vault, ViaBackwards, ViaVersion

**Comment by SamB440** [comment]
what is a minecon, also feather fabric is not supported
