### ISSUE TITLE
Vape V4 KeepSprint bypasses when using 1.0 retain factor

### ISSUE THREAD

**Issue by AbdisKiosk** [GrimAnticheat/Grim#1844]
### Describe the bypass and how to replicate it

Step 1. Enable keepsprint on vape with retain factor set to 1.00
Step 2. Use keepsprint to keep sprinting when attacking players

Keepsprint allows the attacker to attack players while running at full speed.

I have a video here:
https://github.com/user-attachments/assets/37de7a37-5559-4dc1-a7d9-b167e2783c68

### Grim version

Latest commit at this time, [7737337](https://github.com/GrimAnticheat/Grim/commit/7737337a86f60fe954cb7cafb05e506f505b67af)

### Server version

1.8.8

### Plugins

Grim, ZNPCsPlus, LuckPerms, PlaceholderAPI

**Comment by ManInMyVan** [comment]
#1155
