### ISSUE TITLE
on player join

### ISSUE THREAD

**Issue by yooojules** [GrimAnticheat/Grim#1845]
### Stack trace

https://paste.learnspigot.com/lepafojaze.php

### How to replicate it if known

Put in the plugin jar (latest version: 2.3.67), restarted, joined

### Grim version

2.3.67

### Server version

Pufferfish version 1.21.3-23-HEAD@784d72f

### Plugins

![image](https://github.com/user-attachments/assets/751c5cf7-f9eb-4929-be52-ad074e3fe435)

**Comment by SamB440** [comment]
1.21.2+ is currently not supported. Use the latest commit from the update/1.21.3 branch.
