### ISSUE TITLE
We track painting now?

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1849]
### Describe the bug and how to replicate it

https://github.com/GrimAnticheat/Grim/blob/fde99a7cbfa1aa7354643600d65954e8d8755c1c/src/main/java/ac/grim/grimac/checks/impl/combat/Reach.java#L79 does this need updated since now we do track paintings? https://github.com/GrimAnticheat/Grim/commit/954eb8b51c19af5c73d01c9aa2aeb1b04e46f997

**Comment by SamB440** [comment]
There are entities other than paintings.
