### ISSUE TITLE
FastAsyncWorldEdit Placing blocks will hinder movement

### ISSUE THREAD

**Issue by ZhiBuMiao** [GrimAnticheat/Grim#1858]
### Describe the bug and how to replicate it

1. Make FastAsyncWorldEdit automatically place blocks for easy testing
2. Walk, run or jump near where FastAsyncWorldEdit places blocks

I'm trying to make some dungeon rooms, where I need to place blocks to make some mechanisms, or a platform jumping game. But the setback every time I place blocks really affects the gaming experience

### Grim version

grimac-2.3.67

### Server version

This server is running Paper version 1.20.6-151-ver/1.20.6@a4f0f5c (2024-10-30T19:13:22Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version

### Plugins

FastAsyncWorldEdit-Bukkit-2.12.1-SNAPSHOT-959
grimac-2.3.67
packetevents-spigot-2.6.0
ProtocolLib
PlaceholderAPI-2.11.6
Vault-1.7.4
LuckPerms-Bukkit-5.4.145
LibsDisguises
ViaBackwards-5.1.1
ViaRewind-4.0.3
ViaVersion-5.1.1

**Comment by AoElite** [comment]
@ZhiBuMiao Update to latest commit
