### ISSUE TITLE
Not compatible with Iris world generator

### ISSUE THREAD

**Issue by EazyPaw** [GrimAnticheat/Grim#1866]
### Describe the bug and how to replicate it

1. Install Iris world generator
2. Install Grim Anticheat
3. Enter the nether or the end
4. The players (without premission grim.exempt) will be setback from time to time

log from Girm: https://paste.grim.ac/shzvdgp

The Dev form Iris says that's probably on Grim, so if you don't think so, please contact them.

### Grim version

2.3.66 and above.

### Server version

This server is running Leaf version 1.21.1-DEV-ver/1.21.1@8a96160 (2024-12-01T02:11:43Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
* You are 2 version(s) behind
Download the new version at: https://github.com/Winds-Studio/Leaf
Previous: 1.21.1-68-b33c46c (MC: 1.21.1)

### Plugins

Paper Plugins: (0):
Bukkit Plugins: (2):
 - GrimAC, Iris

**Comment by SamB440** [comment]
"setback from time to time" tells us nothing, you will have to do your own research for premium plugins

**Comment by EazyPaw** [comment]
But when I checked Grim's logs, I found that it seems that Grim thinks the player is in another dimension and gives the wrong simulation.

**Comment by EazyPaw** [comment]
Or think that the player is in the wrong place in another place, when in fact the player is not there

**Comment by EazyPaw** [comment]
ok, its
