### ISSUE TITLE
[packetevents] Disconnected null due to invalid packet!

### ISSUE THREAD

**Issue by TenriaProjects** [GrimAnticheat/Grim#1888]
### Describe the bug and how to replicate it

All I did was install Grim into my server, and whenever I joined, I get disconnected with the message "[packetevents] Disconnected null due to invalid packet!". I am uncertain whether this only applies to me, and I will edit/add a new message when I find out.

### Grim version

2.3.67

### Server version

Paper 1.21.3 (Build 81)

### Plugins

AdvancedBan, AdvancedSpyInventory, AxiomPaper, CoreProtect, DiscordSRV, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, spark, TabTPS, WorldEdit, WorldEditSUI, Grim.

**Comment by ManInMyVan** [comment]
update to the latest commit

**Comment by TenriaProjects** [comment]
uh how do I install the GitHub version? im confused.

**Comment by Anthony01M** [comment]
> uh how do I install the GitHub version? im confused.

https://github.com/GrimAnticheat/Grim/actions/runs/12362983993/artifacts/2329076428

**Comment by TenriaProjects** [comment]
> > uh how do I install the GitHub version? im confused.
> 
> https://github.com/GrimAnticheat/Grim/actions/runs/12362983993/artifacts/2329076428

That lead to a 404?

Edit : Now it works but it didn’t earlier.

**Comment by ManInMyVan** [comment]
this issue is fixed now right?
