### ISSUE TITLE
1.21.4 timer + simuation false positive

### ISSUE THREAD

**Issue by ghywk** [GrimAnticheat/Grim#1890]
### Describe the false positive and how to replicate it

1.  Open your 1.21.4 fabric client (without any mods)
2.  Join a server (mc.loyisa.cn) 
3.  Hold a block in your hand and right-click on it towards the sky
4.  Flag (simulation + timer)

### Grim version

2.3.68

### Server version

1.8 (mc.loyisa.cn)

### Client version

1.21.4

### Plugins

Grim ,ProtocolLib...(mc.loyisa.cn)

**Comment by ManInMyVan** [comment]
loyisa's viaversion is setup wrong (to fix this on your own server, disable "fix-1_21-placement-rotation" in your viaversion config)
