### ISSUE TITLE
timer falses when you lag now

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#1898]
### Describe the false positive and how to replicate it

my shitternet can lag connection where no packets are sent for like 10+ seconds, then when u im back I spam timer A flags all at once, this is only a 1.21.4 thing, timer didnt use to be this unstable with bad internet im pretty sure

https://github.com/GrimAnticheat/Grim/commit/5fd8230884db404b4cebd6b6bd6c1e8bbbc3734b to blame maybe? idk

### Grim version

6ca375ff610f676657176c387c318c160fbc98d8

### Server version

This server is running Paper version 1.21.4-DEV-master@71a367e (2024-12-08T13:59:53Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are 10 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: 1.21.3-DEV-c2294d7 (MC: 1.21.3)

### Client version

1.21.4 vanilla

### Plugins

Grim

**Comment by SamB440** [comment]
Intentional to prevent lag abuse and will not be fixed. Increase max ping abuse limit.

**Comment by ghost** [comment]
> Intentional to prevent lag abuse and will not be fixed. Increase max ping abuse limit.

I thought grim was "beyond vanilla" checks only, why should players be punished for lagging?

**Comment by SamB440** [comment]
We already have other lag abuse mitigations such as using fireworks with greater than a second lag advantage. The lag is just unrealistic and the tradeoff is worth it: a very small minority of players may be mitigated vs countless hackers gaining up to 30 second lag advantage over legit players.
