### ISSUE TITLE
Fabric port?

### ISSUE THREAD

**Issue by Grandev-0** [GrimAnticheat/Grim#1905]
### Feature description

I was wondering if this plugin could ever get a fabric port?

**Comment by SamB440** [comment]
No and it would be pointless because packetevents doesn't support modded block or items

**Comment by Weigurde** [comment]
except it wouldn't be because a lot of people host on fabric for significant performance improvements and the many mods that make it easier for technical players to do things

**Comment by Grandev-0** [comment]
> No and it would be pointless because packetevents doesn't support modded block or items

This would purely be for a vanilla server and not have any mods except the optimization ones such as: lithium, chunky, c2m, etc.

**Comment by SamB440** [comment]
You are welcome to do it yourself or pay someone to do so, for a multiplatform Grim I would expect at least £200

**Comment by EzequielDM** [comment]
@SamB440 £200 sounds like way underpay if anything, although I'd really enjoy having it on Fabric
