### ISSUE TITLE
1.21.4 Paper Movement False Positive

### ISSUE THREAD

**Issue by iam-best** [GrimAnticheat/Grim#1911]
### Describe the false positive and how to replicate it

1. Use 1.21.4 Paper and the latest Grim Anti-Cheat 
2. Simply play and walk a little bit
3. It will say randomly that someone failed simulation

### Grim Log

Unable to send Log and I'm getting the 500 Error

### Server version

1.21.4

### Client version

1.21.4 Vanilla Minecraft

### Plugins

AdvancedServ [21:56:30 INFO]: erList, EconomyShopGUI, FancyNpc s, Minepacks [21:56:30 INFO]: Bukkit Plugins: [21:56:30 INFO]: AdvancedAchi evements, AdvancedBan, AFK-Kicke r, AuctionHouse, AuraSkills, Bad ventsDisabler-remake, BedWars, B etterRTP, Chunky, CMILib [21:56:30 INFO]: CommandPanels, CoreProtect, CraftingStore, CSk yFreeze, CustomJoinMessages, Dam ageIndicator, DecentHolograms, D eluxeHub, DiscordSRV, Essentials [21:56:30 INFO]: EssentialsChat floodgate, Geyser-Spigot, GMus ic, GravesX, GriefPrevention, Gr imAC, HomeSpawn, IridiumSkyblock , ItemJoin [21:56:30 INFO]: s, Maintenance, Multiverse-Core, Jobs, LuckPerm Multiverse-Inventories, Multive rse-Portals, MyPetDownloader, NB TAPI, NDailyRewards, PerWorldCom, PlaceholderAPI, [21:56:30 INFO]: PerWorldPlugin *PlayerCheck, PlayerKits2, Prot ocolLib, PvPToggle, SBA, SCore, SimpleScore [21:56:30 INFO]: SkinsRestorer, StackMob, StayPut, TerraformGen erator, TigerReports, TradeSyste m, Vault, ViaBackwards, ViaVersi on, VoidGen [21:56:30 INFO]: VotingPlugin, WarpSystem, WorldEdit, WorldGuard, PictureLogin

**Comment by SamB440** [comment]
“Simply play and walk a little bit”

Closing this as “can’t reproduce”

**Comment by iam-best** [comment]
I can send you the Server IP if that helps

**Comment by iam-best** [comment]
UPDATE: Happens only on Java Edition with a Controlled Mod. Please close this I make a new issue for this!

**Comment by ghost** [comment]
> UPDATE: Happens only on Java Edition with a Controlled Mod. Please close this I make a new issue for this!

It is almost certainly the controller mods fault, disable "analog movement" duplicate of #1912
