### ISSUE TITLE
Controller Mod False Positive

### ISSUE THREAD

**Issue by iam-best** [GrimAnticheat/Grim#1912]
### Describe the false positive and how to replicate it

1. Install this Mod: https://modrinth.com/mod/controlify
2. Connect your Controller (In My Case, Steam Deck)
3. Walk and play
4. The Issues happens in my testing

### Grim Log

Unable to send Log and I'm getting the 500 Error

### Server version

1.21.4 Paper (latest)

### Client version

1.21.4 Vanilla Minecraft

### Plugins

The Plugins don't affect this Issue.

**Comment by ManInMyVan** [comment]
analog movement mods are not supported, if the mod has a setting like "Analog Movement" or "Keyboard-like Movement", please toggle it

**Comment by iam-best** [comment]
Is there any way I can allow Controller Players without them needing to change this?

**Comment by ManInMyVan** [comment]
> Is there any way I can allow Controller Players without them needing to change this?

unfortunately no, I have made [an issue](https://github.com/isXander/Controlify/issues/366) about allowing the server to force this option, but it hasn't been implemented yet
