### ISSUE TITLE
building on ghostblocks

### ISSUE THREAD

**Issue by marszak** [GrimAnticheat/Grim#1913]
### Describe the false positive and how to replicate it

https://streamable.com/ckjzcm

### Grim Log

[GrimAC] Returned response code 500: Internal Server Error

### Server version

Paper Spigot 1.8.8-R0.1-SNAPSHOT

### Client version

1.8.8 vanilla

### Plugins

grimac-2.3.69, worldedit-bukkit-6.1, worldguard-6.2

**Comment by SamB440** [comment]
I tested ghost blocks on loyisa asia with 400 ping earlier today and had no falses, so that looks specific to your environment, if you have ghost block mitigation enabled then this is by design

**Comment by marszak** [comment]
@SamB440 Have you even seen the video that is at the top?, I have a stable internet connection and I don't think it would be something on my end
