### ISSUE TITLE
teleporting and running back into 0.03 fails to send an updated position, falsing grim

### ISSUE THREAD

**Issue by cupiditys** [GrimAnticheat/Grim#420]
**Describe the bug**
running into ladder at a certain angle falses?

**To Reproduce**
https://www.youtube.com/watch?v=965IYDcn2TE
on vanilla 1.8.9

**Comment by MWHunter** [comment]
Thanks for reporting bug #420

Seems to be caused by vanilla anticheat teleporting the player for trying to climb a ladder with a 1.8 client on a 1.18 server.  Even without grim vanilla 1.9+ does this to 1.8 players.  I'll try to look at why the teleports are causing issues with grim.

**Comment by cupiditys** [comment]
i didnt even realize it was 420 thats amazing
