### ISSUE TITLE
Elytra false positive

### ISSUE THREAD

**Issue by Pantera07** [GrimAnticheat/Grim#504]
**Describe the bug**
Elytra false positive
Wear the elytra by right-clicking.

**To Reproduce**
1.18.2 Vanilla
1: https://youtu.be/dViWnjBhGs4
2: https://youtu.be/5OtMXeSZgwk

**Server Version:**
GrimAC Official Server (2022-05-22)

**Grim Version (Git commit or the version in the jar's name)**
GrimAC Official Server (2022-05-22)

**Relevant plugins**
GrimAC Official Server (2022-05-22)

**Comment by MWHunter** [comment]
Fixed by https://github.com/GrimAnticheat/Grim/commit/4c175e6f98d2543e60e2aeee1ac16e64dcf11b5d
