### ISSUE TITLE
Ground Spoof bug

### ISSUE THREAD

**Issue by 05678sg** [GrimAnticheat/Grim#538]
**Describe the bug**
The player jumped from a high place to a wet spot on the deepslate level and signaled the anticheat with Ground Spoof.

**Server Version:**
- 1.18.2 (but using ProtocolLib & ViaVersion & ViaBackwards)
- The player joined in 1.16.4

**Grim Version (Git commit or the version in the jar's name)**
- 2.2.14

https://user-images.githubusercontent.com/107126959/172636913-e9e882b5-2746-4473-b1b5-e69df4c669c6.mp4

**Comment by MWHunter** [comment]
This is not really fixable unless grim is in front of ViaVersion.  Pre-1.17 players on 1.17+ servers aren't really supported.

**Comment by MWHunter** [comment]
Fixed by some recent commit
