### ISSUE TITLE
prediction large false when placing water near lava

### ISSUE THREAD

**Issue by alec-jensen** [GrimAnticheat/Grim#540]
**Describe the bug**
When placing water near lava (creating a portal in the form speedrunners do it), grim will keep falsing prediction large. It can sometimes be fixed by removing the water, its about 50 50 though.

**To Reproduce**
[Video showing how to reproduce](https://medal.tv/games/minecraft/clips/nSZjbwzDcHPod/d1337TBFdHvS?invite=cr-MSxtcG8sMjcwNjQ0NjUs)

**Server Version:**
Current: git-Purpur-1632 (MC: 1.18.2)*
Previous: git-Purpur-1586 (MC: 1.18.2)
* You are running the latest version

**Grim Version (Git commit or the version in the jar's name)**
2.3.0

**Relevant plugins**
![image](https://user-images.githubusercontent.com/59067840/172945033-f6851da5-2521-4f0d-bbdc-74b78f6b2b27.png)

**Comment by MWHunter** [comment]
Unable to reproduce
