### ISSUE TITLE
Simulation & Rotation Place false positives when riding entities

### ISSUE THREAD

**Issue by iFlamingoz** [GrimAnticheat/Grim#544]
**Describe the bug**
Simulation falses when ejecting from entities.
Rotation Place falses whilst on entities.
Timer and Reach (missed hitboxes) can also false.

**To Reproduce:** https://youtu.be/WOqFjaRpu2k

**Server Version:** 1.8.8 WindSpigot

**Grim Version (Git commit or the version in the jar's name):** 83e262d3fd8d6f1c44b55d022326908a80c3da79

**Comment by haxvzje** [comment]
reach 3.0 cant detect btw

**Comment by MWHunter** [comment]
I give up with scaffolding checks with vehicles https://github.com/GrimAnticheat/Grim/commit/ba1b247114d0e64d5c8cc11d602766396eb7c6c3
