### ISSUE TITLE
Send STOP_USE_ITEM on behalf of the player to stop a bypass with using items

### ISSUE THREAD

**Issue by iFlamingoz** [GrimAnticheat/Grim#564]
**Describe the bug**
Spam switching slots causing NoSlow and BadPacketM false positives.

**To Reproduce**
https://youtu.be/Kjn66s5FJr0

**Server Version:** 1.8.8

**Grim Version (Git commit or the version in the jar's name)** f1cc31ca4eb107b0bec179f8e190957e99e81caa

**Relevant plugins**
Or all plugins if you are unsure

**Comment by MWHunter** [comment]
I don't understand how the vanilla client could be sending two item held status's in a single tick...

**Comment by MWHunter** [comment]
Removing the check for 1.8 players but it leaves a bypass so I'll just convert the issue to fixing the bypass, which relies on https://github.com/retrooper/packetevents/issues/436 being fixed

**Comment by MWHunter** [comment]
436 was finally fixed, this issue is now resolved.
