### ISSUE TITLE
Grim (maybe packetevents related) bug

### ISSUE THREAD

**Issue by freaky767** [GrimAnticheat/Grim#604]
https://paste.gg/p/freaky/c777092534654ff2b18a73b24b5a2250

This error happens when a player joins the server, but it does not let anyone join the server

1.8.8 server (spigot fork)

Relevant plugins:
ViaVersion (4.3.1)
ViaRewind
BungeeGuard

**Comment by NoJokeFNA** [comment]
Did you reload the server? I know this exception from NachoSpigot after reloading the server. Which fork are you using? And make sure to always restart the server and don't replace running jars

**Comment by freaky767** [comment]
i never reloaded the server and my spigot is a custom fork, i made sure i installed the anticheat correctly

**Comment by NoJokeFNA** [comment]
Can you probs reproduce it with normal spigot?

**Comment by MWHunter** [comment]
What spigot fork specifically?

The netty version is important with these injection issues

**Comment by freaky767** [comment]
its a custom fork with no netty updates whatsoever, its running the same netty version as tacospigot 1.8.8 (which is where the fork is based off)

**Comment by MWHunter** [comment]
Can you reproduce this with another fork such as tacospigot?

**Comment by MWHunter** [comment]
Closing due to insufficient reproduction steps
