### ISSUE TITLE
nosetback permission doesent work fully

### ISSUE THREAD

**Issue by Tizooo** [GrimAnticheat/Grim#605]
**Describe the bug**
nosetback permission wont reset antikb

**To Reproduce**
Video: https://cdn.discordapp.com/attachments/811396971059085364/991308763359359067/Minecraft__1.19_-_Mehrspieler_Drittanbieter-Server_2022-06-28_13-42-42_Trim_Trim.mp4

**Server Version: git-Purpur-1684 (MC: 1.19)***

**Grim Version 2.3.9**

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/a0306ef0066344d9d01e406f1e199f322c56d6a2
