### ISSUE TITLE
Attacking players with items with high knockback will cause Simulation to misjudge

### ISSUE THREAD

**Issue by misss520** [GrimAnticheat/Grim#606]
After testing, if you use a sword with knockback 2 to attack the player in the corner, it will cause Simulation to falsely report. In addition, I hope to add the management bypass function.

**Comment by misss520** [comment]
After testing, I found that if it is just an ordinary attack, it will also generate false positives after a long time. This problem is more serious, and it is recommended to fix it as soon as possible.

**Comment by MWHunter** [comment]
Test latest commit, there is a bug fix related to velocity not yet released.

**Comment by misss520** [comment]
I'm amazed at how fast you guys can fix it, it's great
