### ISSUE TITLE
Failed Simulations on 1.8 Client

### ISSUE THREAD

**Issue by Rollczi** [GrimAnticheat/Grim#610]
**Describe the bug**
![image](https://user-images.githubusercontent.com/49173834/177018536-e48d9d33-35f9-4dd8-8aaa-d3696a358638.png)
**To Reproduce**
Server 1.19
Client 1.8.x
failed Simulations in normal walking/jumping

**Server Version:**
![image](https://user-images.githubusercontent.com/49173834/177018450-4751de69-b532-4b69-afcc-475fd2c04125.png)

**Grim Version (Git commit or the version in the jar's name)**
Grimac v2.3.7.jar
**Relevant plugins**
ViaBackwards, ViaRewind, ViaVersion, ProtocolLib

**Comment by MWHunter** [comment]
The client is likely using a custom version of fastmath which changes the player's movement mechanics enough to flag grim... this is NOT a false, the player is moving those values differently than what a vanilla player would.

This was "fixed" in 2.3.9 by setting flagging offset to 0.001 which doesn't flag players who modify their own movement in an attempt to speed up their game... this is not a false... the player is actually moving these values incorrectly and grim is flagging them for it.
