### ISSUE TITLE
Mining down and taking fall damage falses AntiKB and Post

### ISSUE THREAD

**Issue by booky10** [GrimAnticheat/Grim#613]
**Describe the bug**
If you mine down blocks with 3 blocks air in between (taking fall damage between block breaking) AntiKB and Post are getting false flagged. Client version is 1.19.

**To Reproduce**
[https://youtu.be/-psIz_uGxqo (slabs)](https://youtu.be/-psIz_uGxqo)
[https://youtu.be/gcoByi9NEGk (full blocks)](https://youtu.be/gcoByi9NEGk)

**Server Version:**
`test.grim.ac`

**Grim Version (Git commit or the version in the jar's name)**
`test.grim.ac`

**Relevant plugins**
`test.grim.ac`

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/2d89c047c9f005775f61004d541de207793c9269
