### ISSUE TITLE
BadPacketL falses on 1.7

### ISSUE THREAD

**Issue by FlamWy** [GrimAnticheat/Grim#616]
**Describe the bug**
BadPacketL falses on 1.7.

**To Reproduce**
Get on a 1.7 client and use an item (block with a sword for example).

**Server Version:** 1.8.8

**Grim Version (Git commit or the version in the jar's name)** 4bd569ea5671e55abaeb8c81c11280f7f59f90b6

**Relevant plugins**
Or all plugins if you are unsure

**Comment by MWHunter** [comment]
https://github.com/MWHunter/Grim/commit/2c3a6acc4ebad00a91bce18a77542b1e7af39fba
