### ISSUE TITLE
Sensitivity detection is off

### ISSUE THREAD

**Issue by FlamWy** [GrimAnticheat/Grim#617]
**Describe the bug**
The displayed sensitivity in the profiles of players is not correct.
I use a sensitivity of 18.
![image](https://user-images.githubusercontent.com/35672743/177317461-ccbfe4a1-2096-43a8-b720-6b7ee272dd9c.png)
With cinematic camera:
![image](https://user-images.githubusercontent.com/35672743/177317972-ba934eef-82b1-4ea1-b8c8-cdcdd0ba0456.png)

**To Reproduce**

**Server Version:** 1.8.8

**Grim Version (Git commit or the version in the jar's name)** https://github.com/MWHunter/Grim/commit/4bd569ea5671e55abaeb8c81c11280f7f59f90b6

**Relevant plugins**
Or all plugins if you are unsure

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/0fd3e66e9d2f4261a23aa74a19490bde122f7696
