### ISSUE TITLE
Console exception

### ISSUE THREAD

**Issue by ytnoos** [GrimAnticheat/Grim#620]
https://www.toptal.com/developers/hastebin/damozecebi.properties

**Server Version:** 1.8

**Grim Version (Git commit or the version in the jar's name)** 2.3.10

**Comment by MWHunter** [comment]
error is harmless but I'll fix it whenever I refactor that code

**Comment by MWHunter** [comment]
Fixed by https://github.com/GrimAnticheat/Grim/commit/5aaa4d61838d512ee550c548c2d0b7628d117400
