### ISSUE TITLE
Invalid placeholder

### ISSUE THREAD

**Issue by nuym** [GrimAnticheat/Grim#621]
**Describe the bug**
When the server loads anti-cheat, its placeholder is disabled, but if you reload it, the placeholder works.
![1Q3B}1Q$CM % GBTT@ZC18O](https://user-images.githubusercontent.com/102905510/177682875-cc8738be-b521-4c3d-953d-cf2ddaba3ed9.png)
![QAP9C VS I8P6 68_ S2`LO](https://user-images.githubusercontent.com/102905510/177682877-88c7e03d-adf6-431c-a3ef-706ac129a704.png)
**Server Version:**
PaperSpigot 1.8.8
**Grim Version (Git commit or the version in the jar's name)**
[2ea48ff](https://github.com/MWHunter/Grim/commit/2ea48ff7fdc57c037e487362935450b648c0ec49) commit 0fd3e66e9d2f4261a23aa74a19490bde122f7696
**Relevant plugins**
Protocollib5.0

**Comment by AoElite** [comment]
Potentially fixed by https://github.com/MWHunter/Grim/commit/5485650989a1294ce502766643997f25e07d8e74

**Comment by nuym** [comment]
Thank you
