### ISSUE TITLE
Changing worlds without changing rotation false flags Simulation

### ISSUE THREAD

**Issue by FlamWy** [GrimAnticheat/Grim#625]
**Describe the bug**
![image](https://user-images.githubusercontent.com/35672743/178084904-0f3e3737-276a-4ef2-8e7b-1610cd2757ca.png)

**Server Version:** 1.8.8

**Grim Version (Git commit or the version in the jar's name)** 2.3.11

**Relevant plugins**
Or all plugins if you are unsure

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/49fe98256f10397d5c3e76d506ef71df06d511a3
