### ISSUE TITLE
SuperDebug error and missing config option

### ISSUE THREAD

**Issue by FlamWy** [GrimAnticheat/Grim#626]
**Describe the bug**
Unless I am blind and cannot find it, there does not seem to be a "super-debug-webhook" option in the config.

https://pastebin.com/VNMqLyzS

**Server Version:** 1.8.8

**Grim Version (Git commit or the version in the jar's name)** b7e1418a7848169e00adfe1282ea078e5e28a283

**Relevant plugins**
Or all plugins if you are unsure

**Comment by MWHunter** [comment]
Yes, because it's a developer option that's meant to be hidden for people who can read code.

**Comment by FlamWy** [comment]
> Yes, because it's a developer option that's meant to be hidden for people who can read code.

Ah, I see.
The error still exists on the latest release with the default config.
https://pastebin.com/VNMqLyzS
