### ISSUE TITLE
AntiKB

### ISSUE THREAD

**Issue by Abel156** [GrimAnticheat/Grim#627]
**Describe the bug**
The antikb detection seems to be less sensitive than before 2.3.11 compared with 2.3.10, the antikb of 2.3.10 will be more sensitive

**To Reproduce**
Tested with vape v4
95% velocity
Knockback:
   threshold: 0.001
   setbackvl: -1
2.3.10 will be more sensitive to detect than 2.3.11, while 2.3.11 seems to be unable to detect, or very slow

**Server Version:**
foxspigot

**Grim Version (Git commit or the version in the jar's name)**
2.3.11

**Relevant plugins**
none

**Comment by MWHunter** [comment]
Reverted knockback change in https://github.com/MWHunter/Grim/commit/b7594b8d8519182c6c3ea5b2a505da676d781059
