### ISSUE TITLE
TpBack when placing froglight

### ISSUE THREAD

**Issue by SissioMisio** [GrimAnticheat/Grim#628]
If I fall and I place a Froglight under my feet (or just spam froglight) I get tp-backed. [GroundSpoof / Simulation]

Video: https://mega.nz/file/8ZF0lDRK#wv-X5OWtSrkVxKMGF21RN-cvQ1UEAwqrMUQCsWwrXm8
Screenshot of /grim debug: ![Screenshot 2022-07-09 115225](https://user-images.githubusercontent.com/40896232/178100909-8e2bed35-f2e6-4dcd-992b-c9ddd163e44d.png)

Server Version: 1.19 
(git-Purpur-1708 (MC: 1.19))

Grim Version: 2.3.11
(from grim.ac discord server)

I tested it in another server with only ProtocolLib and Grim and it still does that.

**Comment by MWHunter** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/3fd2b883de5b69c9f9c89b756dd5fdd235941418
