### ISSUE TITLE
Tp-back spamming sword

### ISSUE THREAD

**Issue by SissioMisio** [GrimAnticheat/Grim#629]
If I spam a sword on the terrain (creative mode) I get tp-backed 

Video: https://mega.nz/file/pVNU3JIC#jJnVgHifw5R-ry-B39J2zzfhk-qc8DGELdlXoCj_8WM
Screenshot of /grim debug: ![Screenshot 2022-07-09 123114](https://user-images.githubusercontent.com/40896232/178101982-811f5c7e-cbe7-472a-ae9a-09c04aaf1957.png)

Server Version: Paper 1.19 

Grim Version: 2.3.11
(from grim.ac discord server)

I tested it in another server with only ProtocolLib and Grim and it still does that.

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/df66bd622d627de623e6693adff3f217bb4fd6bf
