### ISSUE TITLE
[False] Spamming Sprint False

### ISSUE THREAD

**Issue by getxd-dev** [GrimAnticheat/Grim#630]
**Describe the bug**
Spamming Sprint while in Water flags Simulation. I don't know if this is another Sprint Desync issue.

**To Reproduce**
https://streamable.com/p0hck4

**Server Version:**
1.19

**Grim Version (Git commit or the version in the jar's name)**
2.3.10

**Relevant plugins**
None

**Comment by MWHunter** [comment]
I can't reproduce this, can you update then send the first flag with /grim verbose.  Keep going for around two seconds after flagging, mentally noting the first flag id, then using /grim log [id] to get the flag debug and paste the link here.
