### ISSUE TITLE
Dead players flag reach

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#634]
**Describe the bug**
If you are attacking an entity a lot and then you get killed by someone else and get teleported to the spawn, it will false reach

**To Reproduce**
Alone:
- Setup autoclicker on 1 account to hit entity
- Open another mc and kill the other account with a powerful sword
- false
With friends:
- Attack an entity
- Have your friend kill you
- false

**Server Version:**
1.18.2

**Grim Version (Git commit or the version in the jar's name)**
2.3.10-all

**Relevant plugins**
Or all plugins if you are unsure

**Comment by MWHunter** [comment]
which player falses?  The dead or the alive player?

**Comment by ghost** [comment]
dead player

**Comment by MWHunter** [comment]
Caused by player.lastXYZ variables being set on teleport, probably affects other checks too

**Comment by MWHunter** [comment]
Fixed https://github.com/MWHunter/Grim/commit/c796ef4be409d5129f8f580aeb29605a035febbc
