### ISSUE TITLE
AntiKB is too insensitive

### ISSUE THREAD

**Issue by Abel156** [GrimAnticheat/Grim#635]
**Describe the bug**
AntiKB is too insensitive
Tested with vape v4, compared to 2.3.10, default configuration
2.3.10 Accurately detect 99% Velocity
But in version 938e79e51f2c2836778f7066578003eb9341a7d6, I can use Horizontal90%, which is hard to be caught by anti-cheat antikb

**To Reproduce**
Tested with vape v4, compared to 2.3.10, default configuration
2.3.10 Accurately detect 99% Velocity
But in version 938e79e51f2c2836778f7066578003eb9341a7d6, I can use Horizontal90%, which is hard to be caught by anti-cheat antikb

**Server Version:**
foxspigot

**Grim Version (Git commit or the version in the jar's name)**
938e79e51f2c2836778f7066578003eb9341a7d6

**Relevant plugins**
none

**Comment by infinitesm** [comment]
Vape knockback is placebo in the 90-100% range, it only starts working at 90%

**Comment by MWHunter** [comment]
I thought it was placebo starting at ${CURRENT_DETECTION_LEVEL - 1}

**Comment by Abel156** [comment]
> I thought it was placebo starting at ${CURRENT_DETECTION_LEVEL - 1}

sorry i didn't get your point...but can you give it a shot
Use 90%~99% velocity (vapev4)
2.3.10 is very quick to check but 938e79e51f2c2836778f7066578003eb9341a7d6 is almost impossible to check

**Comment by jtJava** [comment]
His point is that you are not actually receiving reduced knockback. You will also not receive reduced knockback if you have resistance 9999, afaik.

**Comment by Abel156** [comment]
> His point is that you are not actually receiving reduced knockback. You will also not receive reduced knockback if you have resistance 9999, afaik.

I think I have the velocity effect which reduces the knockback
I just tested with vape v4, 90% of my servers are not detected (using 938e79e51f2c2836778f7066578003eb9341a7d6), and I think the velocity effect is obvious
But this is well detected on 2.3.10

**Comment by infinitesm** [comment]
> 

My bad, on V4 it's not placebo, I'm able to flag 99% velocity with it. On V3 the velocity only applies below 90% though.

**Comment by MWHunter** [comment]
Yeah the bug is only that couldSkipTick isn't resetting correctly on 1.8 as I think it has the 1.9+ logic.

**Comment by MWHunter** [comment]
Just the fun of writing a 13 version anticheat

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/3ccd60cc26e2cd7f09d2d9d69d89b1342b3357c9
