### ISSUE TITLE
Minecart riding position isn't tracked correctly

### ISSUE THREAD

**Issue by FusselTV** [GrimAnticheat/Grim#637]
**Describe the bug**
When you right-click on the bottom of a moving minecart you get falsed for rotation place

**To Reproduce**
https://user-images.githubusercontent.com/89834718/178374877-100bd9bd-dba4-4685-b65c-94a37139c705.mp4

**Server Version:**
paper-1.19-58.jar

**Grim Version (Git commit or the version in the jar's name)**
grimac-2.3.12.jar

**Comment by MWHunter** [comment]
https://github.com/GrimAnticheat/Grim/commit/ba1b247114d0e64d5c8cc11d602766396eb7c6c3
