### ISSUE TITLE
False flag AntiKB

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#638]
**Describe the bug**
A false on AntiKB

**To Reproduce**
- Go to the corner between 2 walls
- place water bucket where you are standing
- sneak
- get hit
- false

**Server Version:**
1.18.2

**Grim Version (Git commit or the version in the jar's name)**
2.3.10

**Relevant plugins**
Or all plugins if you are unsure

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/f5e0da4e6767c96b7b8e0cf9c003a41c4788b4b6
