### ISSUE TITLE
Simulation false from breaking block below you

### ISSUE THREAD

**Issue by jtJava** [GrimAnticheat/Grim#640]
**Describe the bug**
Simulation flags when breaking a slab below you

**To Reproduce**
https://youtu.be/wjs0RNirt_4
Break a slab below you with diamond pickaxe efficiency 5

**Server Version:**
1.8.8 server and client

**Grim Version (Git commit or the version in the jar's name)**
https://github.com/MWHunter/Grim/commit/938e79e51f2c2836778f7066578003eb9341a7d6

**Relevant plugins**
None that would interfere.

**Comment by MWHunter** [comment]
https://github.com/MWHunter/Grim/commit/2c499d22b7ab5ea290dd21af0186440a7ce50f4d
