### ISSUE TITLE
Simulation false breaking the block above you and jumping

### ISSUE THREAD

**Issue by jtJava** [GrimAnticheat/Grim#641]
**Describe the bug**
Breaking quartz stair above you with efficiency 5 and jumping falses simulation

**To Reproduce**
https://youtu.be/QKr6vl0g9-Q

**Server Version:**
1.8.8 client and server

**Grim Version (Git commit or the version in the jar's name)**
https://github.com/MWHunter/Grim/commit/938e79e51f2c2836778f7066578003eb9341a7d6

**Relevant plugins**
None that would interfere

**Comment by MWHunter** [comment]
https://github.com/MWHunter/Grim/commit/2c499d22b7ab5ea290dd21af0186440a7ce50f4d
