### ISSUE TITLE
FastBreak false breaking the block below you

### ISSUE THREAD

**Issue by jtJava** [GrimAnticheat/Grim#642]
**Describe the bug**
Break an iron block below you with diamond pickaxe efficiency 5. I assume its due to grim thinking you have the wrong ground state for a tick and so youre breaking it faster than you should.

**To Reproduce**
https://youtu.be/-g2TQX6lC4Q

**Server Version:**
1.8.8 client and server

**Grim Version (Git commit or the version in the jar's name)**
https://github.com/MWHunter/Grim/commit/938e79e51f2c2836778f7066578003eb9341a7d6

**Relevant plugins**
None that would interfere

**Comment by MWHunter** [comment]
https://github.com/MWHunter/Grim/commit/2c499d22b7ab5ea290dd21af0186440a7ce50f4d
