### ISSUE TITLE
Simulation false with teleport without lag

### ISSUE THREAD

**Issue by jtJava** [GrimAnticheat/Grim#644]
**Describe the bug**
Simulation flag on teleport

**To Reproduce**
https://youtu.be/GzkKh-2VQaA
https://paste.grim.ac/JgXfQ

**Server Version:**
1.8.8 client and server

**Grim Version (Git commit or the version in the jar's name)**
https://github.com/MWHunter/Grim/commit/938e79e51f2c2836778f7066578003eb9341a7d6

**Relevant plugins**

**Comment by misss520** [comment]
bad, right, man
Although I have encountered false positives like yours, but few
This bug can be easily reproduced at higher latency
The only solution is to raise the threshold
This bug was made a long time ago, and I'm not sure that your commit will have a good answer
good luck man

**Comment by MWHunter** [comment]
https://github.com/MWHunter/Grim/commit/d1bab6e56a8104e5556a3e1f8b33b2b0b65795b3
