### ISSUE TITLE
[False] Slow falling Simulation false C1.12.2 -> S1.19

### ISSUE THREAD

**Issue by VidTu** [GrimAnticheat/Grim#645]
**Describe the bug**
Falling with slow falling potion from 1.12.2 client on the 1.19 server falses Simulation.

**To Reproduce**
1. Join the 1.19 (Paper) server with the 1.12.2 (Vanilla) client.
2. Use `/effect give @s minecraft:slow_falling 1000000`.
3. Fall from high place.
4. See Simulation flags.

https://www.youtube.com/watch?v=duF0crjEs2Q
`/gl 40` from video: https://paste.grim.ac/AH2in

**Server Version:**
1.19 (Paper)

**Grim Version (Git commit or the version in the jar's name)**
2c499d2

**Relevant plugins**
ViaVersion, ViaBackwards

**Comment by MWHunter** [comment]
https://github.com/MWHunter/Grim/commit/adea8b6356c956955b8700fb1f9932d49a3f8d2c
