### ISSUE TITLE
Piston simulation false positive

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#647]
**Describe the bug**
Piston pushing you up will false flag on test.grim.ac (1.8.8 client)
**To Reproduce**
Go to 10 5 -36 in the test server and use that piston
https://paste.grim.ac/M7Ep2

**Server Version:**
test.grim.ac (1.19 afaik)
**Grim Version (Git commit or the version in the jar's name)**
test.grim.ac version (?)
**Relevant plugins**
Or all plugins if you are unsure

**Comment by Lolwe1** [comment]
Video Link for above ^
https://streamable.com/hnw8cq

**Comment by MWHunter** [comment]
Duplicate
