### ISSUE TITLE
Web simulation false positive

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#649]
**Describe the bug**
Jumping in a web false flags Simulation and GroundSpoof on 1.8.8
https://paste.grim.ac/lnscl
**To Reproduce**
Jump in a web (1.8.8)

**Server Version:**
test.grim.ac (1.19 afaik)
**Grim Version (Git commit or the version in the jar's name)**
test.grim.ac (latest afaik)
**Relevant plugins**
Or all plugins if you are unsure

**Comment by Lolwe1** [comment]
Video for above ^
https://streamable.com/tzmacc

**Comment by MWHunter** [comment]
Duplicate https://github.com/MWHunter/Grim/issues/596
