### ISSUE TITLE
[False] Clicking in inventory while sitting in vehicle falses Post (C1.14.4 -> S1.19)

### ISSUE THREAD

**Issue by VidTu** [GrimAnticheat/Grim#651]
**Describe the bug**
Clicking on any slot in inventory (survival mode) from 1.14.4 client on 1.19 server while sitting in vehicle falses Post check.

**To Reproduce**
1. Join a 1.19 (Paper) server with the 1.14.4 (Vanilla) client.
2. Sit in any vehicle. (e.g. Minecart)
3. Open inventory and click on any slot.
4. Grim falses with Post.

https://www.youtube.com/watch?v=MQvJSxnIfug

**Server Version:**
1.19 (Paper)

**Grim Version (Git commit or the version in the jar's name)**
fdc0e88

**Relevant plugins**
ViaVersion, VIaBackwards

**Comment by MWHunter** [comment]
Fixed https://github.com/MWHunter/Grim/commit/0ae88e65ab74764240b43b752590e27b96cf69e1
