### ISSUE TITLE
[Bypass] Flagged ElytraFly bypass with Meteor (acceleration upwards with flags)

### ISSUE THREAD

**Issue by VidTu** [GrimAnticheat/Grim#653]
**Describe the bug**
After getting enough vanilla momentum to fly upwards with elytra you can use ElytraFly module from Meteor (or any other hacked client with ElytraFly) to preserve that momentum.

**To Reproduce**
1. Download [Meteor](https://meteorclient.com/) 0.4.9 for 1.18.2 (Fabric) and join the 1.19 (Paper) server.
2. Bind ElytraFly to whatever key you like. (Using `.bind elytra-fly` and then pressing any key)
3. Accelerate enough to fly upwards without hacks.
4. Enable ElytraFly.
5. Grim continues to push you upwards, but flags Simulation.
Video is always useful. /grim log is required for reporting simulation falses.  Use /grim verbose and /grim log to get the debug information.  For non-simulation falses, a minimally reproducable description is best.

https://www.youtube.com/watch?v=LQ65tVYfIXA
https://paste.grim.ac/NFHhD (Not sure if it's log from the video, but it should be from testing this issue)

**Server Version:**
1.19 (Paper)

**Grim Version (Git commit or the version in the jar's name)**
fdc0e88

**Relevant plugins**
(None)

Additional context: I tested it earlier with Impact (with Elytra+) and it appears that any hacked client that can flag Simulation while flying on elytra bypasses this, because it's the Grim continues pushing (teleporting) the player.

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/4b902b240069127d8676a790305629ef9640f31f
