### ISSUE TITLE
False flag 1.7.10

### ISSUE THREAD

**Issue by Resoomerr** [GrimAnticheat/Grim#655]
**Describe the bug**

1.7 client flags Reach invalid hitbox every time an Hologram is attacked

**To Reproduce**
Video is always useful. /grim log is required for reporting simulation falses.  Use /grim verbose and /grim log to get the debug information.  For non-simulation falses, a minimally reproducable description is best.

https://imgur.com/a/X8zWLMD

**Server Version:**

NachoSpigot 1.8.8

**Grim Version (Git commit or the version in the jar's name)**

2.3.12

**Relevant plugins**
Or all plugins if you are unsure

viaversion viarewind lpx holographicdisplays

**Comment by Tofaa2** [comment]
Grim is 1.8-1.19 I don't see any way you would get your false flag fixed

**Comment by AoElite** [comment]
Fixed b6cd28da42d40216b5ee74230506ce1929cf00c0
