### ISSUE TITLE
Not able to get out of water

### ISSUE THREAD

**Issue by tomtomat0** [GrimAnticheat/Grim#656]
**Describe the bug**
getting set back when trying to move in flowing water

**To Reproduce**
[Video Link](https://mega.nz/file/bolnAJqT#dB41-mJFeVZT1OjUrogDcJOI5Y0mhHm_2zstBWyLaX0) 
/grim log: https://pastebin.com/HWrw1Cyf

**Server Version:**
PaperMC 1.19

**Grim Version (Git commit or the version in the jar's name)**
2.3.12

**Relevant plugins**
none

**Comment by MWHunter** [comment]
Did you have depth strider boots?

**Comment by tomtomat0** [comment]
yes

**Comment by MWHunter** [comment]
Based on your grim debug, grim wasn't seeing your depth strider boots then.  Weird, is this behavior consistent?

**Comment by tomtomat0** [comment]
yes always when i try to get out of flowing water

**Comment by MWHunter** [comment]
Anything special about the boots? Unable to reproduce.

**Comment by tomtomat0** [comment]
no

**Comment by MWHunter** [comment]
closing due to inventory handling rewrite
