### ISSUE TITLE
Bugs,bypassed

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#658]
This is bypass: https://disk.yandex.ru/d/tZnXu2X9lBzl6A
This is errors: : [09:49:31 WARN]: [ac.grim.grimac.shaded.com.github.retrooper.packetevents.PacketEventsAPI] Default state for pumpkin is null. Returning AIR + shulker, 1.12.2
And grimac fantom blocks on 1.12.2 created visual.

**Comment by MWHunter** [comment]
Potentially fixed by https://github.com/MWHunter/Grim/commit/4b902b240069127d8676a790305629ef9640f31f
