### ISSUE TITLE
BYPASS!!! TELEPORT!!!! NEW!!!

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#659]
Video (Yandex) https://disk.yandex.com.ge/d/wI9bEeIY_aVIjQ
Or veed.io: https://www.veed.io/view/a2322f03-91cb-4abd-a990-649895765134?sharingWidget=true

**Comment by 11pz** [comment]
goodluck fixing it <3

**Comment by ghost** [comment]
You fixed it but the bypass works

**Comment by ghost** [comment]
2.3.13 buid bypass

**Comment by VidTu** [comment]
YES MORE CAPS!

**Comment by MWHunter** [comment]
Fixed https://github.com/MWHunter/Grim/commit/fc92bf08179a4fd641734c2b445f975a207ed6f9
