### ISSUE TITLE
Water hit slowdown false

### ISSUE THREAD

**Issue by jtJava** [GrimAnticheat/Grim#660]
**Describe the bug**
Hit someone while sprinting and moving around in water and you will false simulation

**To Reproduce**
[Video is always useful. /grim log is required for reporting simulation falses.  Use /grim verbose and /grim log to get the debug information.  For non-simulation falses, a minimally reproducable description is best.](https://paste.grim.ac/4aPqv)

**Server Version:**
1.8.8 server/client

**Grim Version (Git commit or the version in the jar's name)**
latest
**Relevant plugins**
Or all plugins if you are unsure

**Comment by MWHunter** [comment]
> * 0.6 horizontal attack slowdown
Jump
Simulated: 0.09754789649521504,-0.14885951718082158,0.060300832374369145
Actually:  0.10302066820512579,-0.14885951718082424,0.05891875067916885
Offset Vector: 0.005472771709910743,-2.6645352591003757E-15,-0.0013820816952002934
Offset: 0.005644588559054332
Location:  x: 30.95571285770994 y: 38.414244869397095 z: 87.28010839294095 xRot: -27.370287 yRot: 15.256855 world: world
Initial velocity: 0.14758006054978406,-0.1888595162867519,0.0715051590768339
Water vel addition: 0.013545535097295577,0.0,-0.003538146255870965
Client input:    -0.0338156633079052,0.0,-0.03167250007390976 length: 0.046331914981850464
Simulated input: -0.03931501880288124,0.0,-0.03296029195189476 length: 0.051303523748618324

look at these beautiful logs

**Comment by MWHunter** [comment]
Fixed https://github.com/MWHunter/Grim/commit/19d01ec5d0e7135fbe88b95f9b39ec3e1c2b6f6f
