### ISSUE TITLE
Simulation's Setback made player time out

### ISSUE THREAD

**Issue by DFQY** [GrimAnticheat/Grim#662]
When a player setback by Simulation check, the player's game will time out and disconnect
And in logs or console, it just display "Player lost connection: Disconnected"
I tried to test without other plugins, only use grim. But it couldn't be solved, until I change grim version to 2.3.12
How can I fix my server? I want to use all new versions in future, instead of still use 2.3.12
(I'm sorry for my poor English)

Server Version: 1.8

Grim Version : 2.3.13 & 2.3.14

**Comment by MWHunter** [comment]
unable to reproduce, please provide a video showing that the server is running on 1.8 and that you are being timed out after flagging prediction.

**Comment by MWHunter** [comment]
fixed on latest git anyways... I think there's another plugin interfering with grim here
