### ISSUE TITLE
grim water false

### ISSUE THREAD

**Issue by Abel156** [GrimAnticheat/Grim#664]
**Describe the bug**
https://youtu.be/vUbnZp19Nfs
Press to find the video to do, very simple answer can be reproduced
(May require forced sprinting, cheatbreaker is used in the video)

**To Reproduce**
Video is always useful. /grim log is required for reporting simulation falses.  Use /grim verbose and /grim log to get the debug information.  For non-simulation falses, a minimally reproducable description is best.
https://youtu.be/vUbnZp19Nfs
Press to find the video to do, very simple answer can be reproduced
(May require forced sprinting, cheatbreaker is used in the video)

**Server Version:**
foxspigot

**Grim Version (Git commit or the version in the jar's name)**
19d01ec5d0e7135fbe88b95f9b39ec3e1c2b6f6f

**Relevant plugins**
Or all plugins if you are unsure
none

**Comment by MWHunter** [comment]
Duplicate
