### ISSUE TITLE
[False] Forcing client to swing falses Post (C1.12.2 -> S1.19)

### ISSUE THREAD

**Issue by VidTu** [GrimAnticheat/Grim#665]
**Describe the bug**
Forcing 1.12.2 client to swing via `Player.swingMainHand()` on right-click interaction while walking on 1.19 server falses Post.

**To Reproduce**
1. Install some plugin that forces client to swing on right click. (e.g. code from below)
2. Join a 1.19 (Paper) server with 1.12.2 (Vanilla) client.
3. Start walking and right-click on blocks. (or click on air with any item)
4. See Post falses.

https://www.youtube.com/watch?v=hkGz2_se1wU

**Server Version:**
1.19 (Paper)

**Grim Version (Git commit or the version in the jar's name)**
19d01ec

**Relevant plugins**
ViaVersion, ViaBackwards + Test plugin:
(Paper 1.19 API)
```java
package tst;

import org.bukkit.Bukkit;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerInteractEvent;
import org.bukkit.plugin.java.JavaPlugin;

public class Tst extends JavaPlugin implements Listener {
    @Override
    public void onEnable() {
        Bukkit.getPluginManager().registerEvents(this, this);
    }

    @EventHandler
    public void onInteract(PlayerInteractEvent event) {
        if (event.getAction().isRightClick()) event.getPlayer().swingMainHand();
    }
}
```

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/e7529e1a783da324d16ca1746d94c60a262583bf
