### ISSUE TITLE
[Fast Scaffold bypass] Use FDPClient bypass GrimAC2.3.16 Scaffold

### ISSUE THREAD

**Issue by MatrixU5er** [GrimAnticheat/Grim#668]
**Describe the bug**
Using fdpclient to bypass scaffold detection in their own grimac test clothes （ GrimAC2.3.16）

**To Reproduce**
Video is always useful. /grim log is required for reporting simulation falses.  Use /grim verbose and /grim log to get the debug information.  For non-simulation falses, a

https://user-images.githubusercontent.com/89892616/179924300-ba309205-463c-4418-b0b5-3285002dcda9.mp4

 minimally reproducable description is best.

**Server Version: paper1.8.8**

**Grim Version (Git commit or the version in the jar's name)**
GrimAC2.3.16

**Relevant plugins**
Or all plugins if you are unsure
![ICPLNV9 1VN2Y6JYX1EC1J0](https://user-images.githubusercontent.com/89892616/179924533-dfb124ed-fcd9-4f15-9a28-dcd9335fbfde.png)
FDPClient scaffold Config
      }
    },
    "Scaffold": {
      "state": false,
      "keybind": 34,
      "array": true,
      "autodisable": "NONE",
      "trigger": "TOGGLE",
      "values": {
        "PlaceableDelay": "Normal",
        "MaxDelay": 0,
        "MinDelay": 0,
        "AutoBlock": "Spoof",
        "Sprint": "OFF",
        "Swing": "Normal",
        "Search": true,
        "Down": false,
        "PlaceTiming": "Pre",
        "Eagle": "OFF",
        "BlocksToEagle": 0,
        "ExpandLength": 1,
        "Rotations": "AAC",
        "TowerRotations": "AAC",
        "AACYawOffset": 0,
        "CustomYaw": -145,
        "CustomPitch": 79,
        "CustomTowerYaw": -145,
        "CustomTowerPitch": 79,
        "SilentRotation": true,
        "MinRotationSpeed": 180,
        "MaxRotationSpeed": 180,
        "KeepRotationTick": 0,
        "ZitterMode": "OFF",
        "ZitterSpeed": 0.13,
        "ZitterStrength": 0.072,
        "Timer": 1.0,
        "MotionSpeedSet": false,
        "MotionSpeed": 0.28,
        "SpeedModifier": 1.0,
        "TowerMode": "Jump",
        "StopTowerWhenBlockAbove": true,
        "TowerFakeJump": true,
        "TowerActivation": "NoMove",
        "TowerTimer": 1.0,
        "SameY": "Simple",
        "SafeWalk": "OFF",
        "HitableCheck": "Simple",
        "ExtraClick": "OFF",
        "ExtraClickMaxDelay": 100,
        "ExtraClickMinDelay": 50,
        "TowerJumpMotion": 0.42,
        "TowerJumpDelay": 0,
        "TowerStableMotion": 0.42,
        "TowerPlusMotion": 0.1,
        "TowerPlusMaxMotion": 0.8,
        "TowerConstantMotion": 0.42,
        "TowerConstantMotionJumpGround": 0.79,
        "TowerTeleportHeight": 1.15,
        "TowerTeleportDelay": 0,
        "TowerTeleportGround": true,
        "TowerTeleportNoMotion": false,
        "Counter": true,
        "Mark": true
      }
    },

**Comment by MatrixU5er** [comment]
对没能保密我很抱歉，因为我来自中国，我的网络条件不允许我访问discord 并接受短信验证码
I'm sorry for not being able to keep it secret, because I'm from China and my network conditions don't allow me to visit discord and accept SMS verification code

**Comment by misss520** [comment]
Good bypass, your work amazes me, I can't imagine there is a bypass on anti-cheat like this

**Comment by ghost** [comment]
大牛子

**Comment by MatrixU5er** [comment]
GrimAC2.3.17 bypass

**Comment by ghost** [comment]
Grim latest version still bypass
@AoElite @MWHunter

**Comment by MWHunter** [comment]
Feel free to PR a fix

**Comment by AoElite** [comment]
I've added a experimental check to detect this scaffold in ee0eef26f9e715ff3290000ee1ccc1a63d47cab8
