### ISSUE TITLE
Ground spoof + simulation false positives when standing on minecraft:mud_brick_wall

### ISSUE THREAD

**Issue by Jaren8r** [GrimAnticheat/Grim#670]
https://paste.grim.ac/ENLCJ

https://user-images.githubusercontent.com/8620569/180067998-ce91fff0-7fb8-41a2-b4b8-96fc3651c7c7.mp4

**Server Version:**
git-PufferfishPlus-13 (MC: 1.19)

**Grim Version (Git commit or the version in the jar's name)**
2.3.16

**Comment by Jaren8r** [comment]
Plugins:

![image](https://user-images.githubusercontent.com/8620569/180069451-97fd8424-9280-47ef-b5d6-b1d962e1c1cb.png)

**Comment by MWHunter** [comment]
Fixed by https://github.com/retrooper/packetevents/commit/6efb6aebdff2f495ae239eb3aaad77af5dbf5c53
