### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#672]
**Describe the bug**
Error: https://pastebin.com/03yLx4mG

Versions:
4.4.0-1.19.1-pre4-SNAPSHOT
ProtocolLib v5.0.0-SNAPSHOT-b575
Latest build github today on: 8:33 am (my 9:51 time)

**Comment by ghost** [comment]
Server version 1.12.2. Core: https://github.com/nopjmp/Dionysus/releases/tag/v0.1.15

**Comment by AoElite** [comment]
Fixed f1c1af77b6dc371f1ca43d4ba528fceb92312c88
