### ISSUE TITLE
Bugged hex

### ISSUE THREAD

**Issue by NotroDev** [GrimAnticheat/Grim#675]
**Describe the bug**
Hex colors are breaking sometimes
Alerts info (good prefix)
![obraz](https://user-images.githubusercontent.com/77281214/180459486-3fe263b1-fd35-43d9-97cf-4ede634df7fc.png)
spectate return:
![obraz](https://user-images.githubusercontent.com/77281214/180459525-2c8daf1a-aaf7-4927-a415-974cede8af8a.png)
prefix: `&8[&x&5&a&f&c&9&3E&x&5&9&f&c&a&2a&x&5&7&f&c&b&1s&x&5&6&f&c&c&0t&x&5&4&f&b&d&0C&x&5&3&f&b&d&fo&x&5&1&f&b&e&er&x&5&0&f&b&f&de&8]`

**Server Version:**
![obraz](https://user-images.githubusercontent.com/77281214/180459777-c7e8545d-2ade-42cc-b403-506992531edd.png)

**Grim Version (Git commit or the version in the jar's name)**
2.3.17

**Comment by AoElite** [comment]
Fixed by ef5a21b99e38c12f658fc311d4c67572b2f7dd81
