### ISSUE TITLE
Boat bug

### ISSUE THREAD

**Issue by Animationking11** [GrimAnticheat/Grim#677]
**Describe the bug**
You get kicked out of a boat when clutching
**To Reproduce**
In my video, it shows a player performing it
https://youtu.be/MXsyzzrFJGw

**Server Version:**
1.19
**Grim Version (Git commit or the version in the jar's name)**
2.3.9
**Relevant plugins**
Or all plugins if you are unsure

**Comment by Animationking11** [comment]
Ok better explnation: It kicks you out of a boat when falling for over 2 sec

**Comment by Animationking11** [comment]
Fix when?!?!?!?

**Comment by MWHunter** [comment]
when i feel like it or when someone else feels like it, and no sooner

**Comment by MWHunter** [comment]
Unable to reproduce
