### ISSUE TITLE
Plugin messaging bug

### ISSUE THREAD

**Issue by CayeOficial** [GrimAnticheat/Grim#680]
### Describe the bug and how to replicate it

After updating from 2.3.9 to 2.3.17 final, all plugin channels (generally plugin messaging) is not working.
Therefore, PlaceholderAPI's Bungee Expasion shows incorrect data as it works with plugin messaging and also NuVotifier forwards votes from the proxy to the backend via plugin messaging but the backend doesn't detect it as plugin channels are like broken.
Then i went back again to 2.3.9 version and it works again, unsure which versions between 2.3.9 and 2.3.17 have the bug 🤔

### Grim version

2.3.17

### Server version

This server is running Airplane version git-Airplane-"5e8ac76" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Previous version: git-Purpur-1171 (MC: 1.16.5)

### Plugins

I'm not publishing my plugins in a public issue sorry, contact me at discord if you need it `zCayeOficial#0001`

**Comment by MWHunter** [comment]
Airplane 1.16.5 is vulnerable to log4j

**Comment by CayeOficial** [comment]
I've a custom build which is not

**Comment by MWHunter** [comment]
Closing because if grim actually did break plugin messaging, then I'd receive more than one report of it.  You may reopen the ticket with a minimal reproduction of this issue.
