### ISSUE TITLE
[False] Resetting velocity (server-side) falses Simulation

### ISSUE THREAD

**Issue by VidTu** [GrimAnticheat/Grim#681]
### Describe the false positive and how to replicate it

https://www.youtube.com/watch?v=YMvnWki6sj4
https://paste.grim.ac/ifpvp

### Grim version

e8b3a84

### Server version

This server is running Paper version git-Paper-77 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 44b6869)
You are running the latest version
Previous version: git-Paper-66 (MC: 1.19)

### Plugins

Plugins (4): GrimAC, Tst, ViaBackwards, ViaVersion
Tst plugin src:
```java
package tst;

import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerInteractEvent;
import org.bukkit.plugin.java.JavaPlugin;
import org.bukkit.util.Vector;

public class Tst extends JavaPlugin implements Listener {
    @Override
    public void onEnable() {
        Bukkit.getPluginManager().registerEvents(this, this);
    }

    @EventHandler
    public void onInteract(PlayerInteractEvent event) {
        if (event.getMaterial() == Material.PRISMARINE_CRYSTALS) {
            event.setCancelled(true);
            event.getPlayer().setVelocity(new Vector(2, 2, 2));
            event.getPlayer().sendActionBar(Component.text("LAUNCH!", NamedTextColor.GOLD));
            Bukkit.getScheduler().runTaskLater(this, () -> {
                event.getPlayer().sendActionBar(Component.text("STOP!", NamedTextColor.RED));
                event.getPlayer().setVelocity(new Vector());
            }, 10L);
        }
    }
}
```

**Comment by MWHunter** [comment]
Thanks for the easy reproduction instructions, fixed in https://github.com/MWHunter/Grim/commit/ae3ed1d638b4ab56d7f6a861b7b68dc72ed157b1

**Comment by VidTu** [comment]
(Oh I forgot...)

**Comment by MWHunter** [comment]
Wasn't meant to be sarcastic, I copied and pasted the code into a plugin and I reproduced the bug the first try.

**Comment by VidTu** [comment]
I thought you're about reproduction steps like
1. Do this.
2. Do that.
3. See false.
