### ISSUE TITLE
Simulation false with pearls on the edge of a block

### ISSUE THREAD

**Issue by Jyguy** [GrimAnticheat/Grim#683]
### Describe the false positive and how to replicate it

Logs: https://paste.grim.ac/dWS2f
Video: https://youtu.be/XXuu8d9kqog

### Grim version

79b940f8c4e97666a2e1c0b272b68237f13103a7

### Server version

This server is running Paper version git-Paper-411 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6625db3 on ver/1.17.1)

### Plugins

Plugins (1): GrimAC

**Comment by MWHunter** [comment]
Duplicate https://github.com/MWHunter/Grim/issues/390
