### ISSUE TITLE
Simulation false when towering with an explosion below player quickly

### ISSUE THREAD

**Issue by Jyguy** [GrimAnticheat/Grim#685]
### Describe the false positive and how to replicate it

When a player places a respawn anchor below them, puts a glowstone in, and rapidly clicks another block right below, Simulation will false if the first block of the tower is placed fast enough. Testing was done on a local server. It may be easier to reproduce if an autoclicker with high CPS is used instead. In the video, I was probably clicking 11-12 CPS.
Video: https://youtu.be/bkvS9Jb2J8Y
Log: https://paste.grim.ac/3fxme

### Grim version

5f69fe10

### Server version

This server is running Paper version git-Paper-411 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6625db3 on ver/1.17.1)

### Plugins

Plugins (1): GrimAC

**Comment by MWHunter** [comment]
likely fixed by 2.3.20

**Comment by Jyguy** [comment]
> likely fixed by 2.3.20

I am still able to reproduce this on caf742d3614dd14e891bd3fa7c93bb6702e1170c on 1.19 as well. This time a 15 CPS autoclicker was used to make this easier.

Video: https://youtu.be/yGDzqH_FeTA
Log: https://paste.grim.ac/YXB5q
Server version: This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)
