### ISSUE TITLE
Creative mode block replace false

### ISSUE THREAD

**Issue by DontNeedAName** [GrimAnticheat/Grim#686]
### Describe the false positive and how to replicate it

Since 1.14 (i think) creative mode has this weird mechanic where if you press left and right click at the same time while looking at a block, it replaces that block with the block you have in your hand, even if that block is in midair and theres no block to place against. Currently grim blocks that placement causing the block to only be destroyed and not replaced. It's hard to show what i mean on video. You just have to compare singleplayer to a server with grim installed.

### Grim version

2.3.17

### Server version

3498-Spigot-b081915-10ba1be (MC: 1.18.2)

### Plugins

Tested this without any plugins.

**Comment by jtJava** [comment]
You press left, and then right click. I tested, I think best solution is to exempt creative since I was unable to do this in survival when I tested.

**Comment by AoElite** [comment]
Fixed by 674b491a92de7d29f775e9b8a65d08ec795ae9fb
