### ISSUE TITLE
AntiExplosion, Simulation, GroundSpoof, Phase false positives with tnt

### ISSUE THREAD

**Issue by FlamWy** [GrimAnticheat/Grim#687]
### Describe the false positive and how to replicate it

GroundSpoof, Simulation & Phase false positive: https://youtu.be/9GgxNEVaFbo
AntiExplosion, Simulation false positive: https://youtu.be/cbJf9QO21NU

### Grim version

b85c2d0f46bf59df90da7ed6f134155f8e63a60a

### Server version

1.8.8 WindSpigot

### Plugins

GrimAC

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/611129a26d476837d3146725d96dc36870c30adf

**Comment by MWHunter** [comment]
more than 1 issue here

**Comment by MWHunter** [comment]
should be fixed now
