### ISSUE TITLE
Lagbacks

### ISSUE THREAD

**Issue by Symmettry** [GrimAnticheat/Grim#688]
### Feature description

Make the anticheat lagbacks potentially push you downwards a bit more. If someone cheats and flags, they can still jump up more than vanilla and up 1 block + stairs which can break certain maps!

**Comment by kropt** [comment]
Especially on slime blocks.

**Comment by MWHunter** [comment]
Video?  This may be something different than just setbacks as I wasn't able to jump past 1.25 blocks on a 1.8 client.

**Comment by MWHunter** [comment]
Invalid bug report without reproduction steps
