### ISSUE TITLE
SnowShoe by Wurst

### ISSUE THREAD

**Issue by noramibu** [GrimAnticheat/Grim#689]
### Describe the bypass and how to replicate it

When I use SnowShow from Wurst, I'm able to 50% walk on snow powder and I can easily climb to snow powder.

### Grim version

2.3.17

<img width="1512" alt="Screen Shot 2022-07-24 at 22 02 00" src="https://user-images.githubusercontent.com/50046813/180662020-ea4c4644-c448-4156-919e-468d9256b8c7.png">
<img width="1512" alt="Screen Shot 2022-07-24 at 22 02 32" src="https://user-images.githubusercontent.com/50046813/180662045-2dbe48bb-db51-4019-b221-be177d4c4163.png">

### Server version

Mirai-3 1.19

### Plugins

TAB, EssentialsX, KingdomsX, PlaceholderAPI, CombatLogX, SirBlobmanCore, AutoShulker, ProtocolLib, ToolKit

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/f8f5045ce1eba0220a9f556fd864642547c1483f
