### ISSUE TITLE
pvp false

### ISSUE THREAD

**Issue by unlegit1234** [GrimAnticheat/Grim#697]
### Describe the false positive and how to replicate it

there are many unreproducible false when players are in pvp
1. find two players to fight
2. use various tricks like side pearl/wtap
3. ez get false

### Grim version

5061df3de62ee1c80e9347992f7b9f19095a1330

### Server version

1.8

### Plugins

none

**Comment by Tofaa2** [comment]
"Unreproducable" yet you still describe you to reproduce them

**Comment by AoElite** [comment]
Not enough information provided.
