### ISSUE TITLE
console spam water bug

### ISSUE THREAD

**Issue by M3bular** [GrimAnticheat/Grim#698]
### Describe the false positive and how to replicate it

when a player without op swims in water the console spams a bunch of random crap like in the video attatched

https://user-images.githubusercontent.com/66199306/181005425-82bc9398-c369-40c0-8616-3889c4db07ec.mp4

https://user-images.githubusercontent.com/66199306/181005574-be19b662-aeb3-4d1d-9de8-0f8f1558e8f1.mp4

### Grim version

2.3.17

### Server version

Paper version git-Paper-"86f87ba" (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)

### Plugins

coolprotection, essentials, grimac, luckperms, openinv

**Comment by AoElite** [comment]
Can you paste the entire error? Also you should update to latest grim.

**Comment by M3bular** [comment]
i cant paste the entirety of it but i can paste a bit of it 

https://pastebin.com/D7faFwL1

**Comment by M3bular** [comment]
where do i get the latest version if i may ask?

**Comment by MWHunter** [comment]
Your jar is corrupted.

**Comment by M3bular** [comment]
are u 100% sure cause i installed a brand new paper jar on my server just a few hours ago on my pebblehost server

**Comment by MWHunter** [comment]
Yes, either your jar is corrupted or you have two duplicate grim
