### ISSUE TITLE
Fix ender_eye

### ISSUE THREAD

**Issue by SourceOVH** [GrimAnticheat/Grim#699]
### Describe the false positive and how to replicate it

logs: https://paste.grim.ac/ajW79 
text: 
![image](https://user-images.githubusercontent.com/104106085/181073249-b55ce866-c88e-4327-88b5-aed4930df8d9.png)
![image](https://user-images.githubusercontent.com/104106085/181073281-3ec30df2-6b17-4807-8b73-8cb7402aad0c.png)
if you quickly press PKM with   Ender eye detect AH

### Grim version

last version

### Server version

![image](https://user-images.githubusercontent.com/104106085/181073064-221ab84d-0922-425c-8f9f-365853c6229f.png)

### Plugins

![image](https://user-images.githubusercontent.com/104106085/181073085-e013b0b8-b240-4610-a853-d9d9ec2520f7.png)

**Comment by SourceOVH** [comment]
I forgot to add, to make it work you need to look at the block and run and throw the ender eye

**Comment by MWHunter** [comment]
Unable to reproduce, works fine for me
