### ISSUE TITLE
Water spam obby trap?

### ISSUE THREAD

**Issue by GustavsGglitcher** [GrimAnticheat/Grim#700]
### Describe the false positive and how to replicate it

Step1: Obby trap yourself
Step2: Make sure your in a 1x1 
Step3: Spam a water bucket

https://imgur.com/mjuMXJ

https://user-images.githubusercontent.com/81566027/181093546-d9d133c2-ced2-461d-be9e-aa4a21077572.mp4

### Grim version

grimac-2.3.19.jar

### Server version

This server is running Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2)
[26.07 21:19:16] [Server] You are running the latest version
[26.07 21:19:16] [Server] Previous versiongit-Paper-386 (MC: 1.18.2)

### Plugins

[INFO] Plugins (29): AFK-Kick*, BeyondPvP, BisectHosting, CoinSystem*, CoreProtect, CustomBansPlus, CustomWhitelistMessage*, DecentHolograms, F3Name, FastAsyncVoxelSniper, FastAsyncWorldEdit (WorldEdit), Fly, GrimAC, ImageOnMap, LPC, LuckPerms, Multiverse-Core, OpenInv, PL-Hide, PlugMan, PowerBoard, ProtocolLib, ShieldBreakSound*, StaffChatLite, SuperVanish, ViaBackwards, ViaVersion, VoidGen, WorldGuard

**Comment by MWHunter** [comment]
Duplicate https://github.com/MWHunter/Grim/issues/578
