### ISSUE TITLE
Various falses while spam clicking pearls

### ISSUE THREAD

**Issue by Jyguy** [GrimAnticheat/Grim#701]
### Describe the false positive and how to replicate it

Spamming pearls at a high CPS (in the video, ~12 CPS) causes falses in Simulation, Timer, GroundSpoof, AimDuplicateLook, and AntiKB.

Video: https://youtu.be/JbxeEyW1S7I
Logs (for Simulation): https://paste.grim.ac/4VDnn

### Grim version

7fc6486290de27fc42795bb8e2a334db497f81ff

### Server version

This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)

### Plugins

Plugins (1): GrimAC

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/e01a30a066c28bc09b7c7e210eb95dd387aaad89
