### ISSUE TITLE
Random Simulation False

### ISSUE THREAD

**Issue by IceWaffles** [GrimAnticheat/Grim#702]
### Describe the false positive and how to replicate it

No idea how to replicate, but I'll upload logs here to show some examples of people I know aren't hacking. They're only on sodium if fabric shows. 

https://paste.grim.ac/yC9L

I shall also attach some screenshots below of said random false. They aren't a concern as there's like 1-2 for a player a day only - this is more for you to look at.

<img width="412" alt="Screenshot 2022-07-27 at 9 03 03 AM" src="https://user-images.githubusercontent.com/865991
<img width="417" alt="Screenshot 2022-07-27 at 9 02 56 AM" src="https://user-images.githubusercontent.com/86599175/181194756-2843b0d1-c4cd-469e-82bf-b64f90a830ca.png">

### Grim version

2.3.19

### Server version

git-PufferfishPlus-7 (MC: 1.19)

### Plugins

Gsit, EssentialsX, EssentialsXSpawn, Grim, WorldEdit, WorldGuard

(It is a test server)

**Comment by ghost** [comment]
The paste expired

**Comment by MWHunter** [comment]
Pastes are 5 characters not 4

**Comment by MWHunter** [comment]
invalid bug report without a grim paste
