### ISSUE TITLE
Weather desync

### ISSUE THREAD

**Issue by AVuTuVA** [GrimAnticheat/Grim#703]
### Describe the false positive and how to replicate it

https://youtu.be/FvjHWXeX21E

### Grim version

latest discord

### Server version

1.19

**Comment by MWHunter** [comment]
How did the player get into this state?  I only see one way for the server to tell the player that it has begun raining which grim handles.

**Comment by AVuTuVA** [comment]
It just took and happened, me and the player don't know the reason

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/e030a824420363244af672f8af69d5ef27ed23c1
