### ISSUE TITLE
Elytra False Flag

### ISSUE THREAD

**Issue by amnoah** [GrimAnticheat/Grim#704]
### Describe the false positive and how to replicate it

https://youtu.be/YvUGPJbMxYI

1: Crouch stand under a slab with air to the side, a slime block on the ground next to the block you're standing on, and an elytra on.
2: Spam jump and move slightly back/forward.
3: False flag Ground Spoof.

### Grim version

Test Server (2.3.20)

### Server version

Test Server (This server is running Paper version git-Paper-18 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 17c1c6c))

### Plugins

Test Server

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/162170a7b0d817018202fd62a6d7a9b4bd549918
