### ISSUE TITLE
Scaffold Raytrace Bypass

### ISSUE THREAD

**Issue by amnoah** [GrimAnticheat/Grim#705]
### Describe the bypass and how to replicate it

https://youtu.be/MCBXkDkrnrc

Grim is failing to catch people using scaffolds which fail to raycast block places on the test server.

### Grim version

Test Server (2.3.20)

### Server version

Test Server (This server is running Paper version git-Paper-18 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 17c1c6c))

### Plugins

Test Server

**Comment by MWHunter** [comment]
This isn't enough information, RotationPlace seems to be flagging for me.

**Comment by DontNeedAName** [comment]
Was about to report this as well. Try using these settings in meteor client. (Basically you just have to disable rotate.) This even allows you to practically fly when the blocks are cancelled.
![Screenshot 2022-07-28 125946](https://user-images.githubusercontent.com/50169271/181489872-efcb2f88-421e-459f-971e-4c32f2d5f941.png)

**Comment by amnoah** [comment]
In the clip recorded meteor client scaffold was used with the only setting being enabled being "air place" and "swing".

**Comment by DontNeedAName** [comment]
> In the clip recorded meteor client scaffold was used with the only setting being enabled being "air place" and "swing".

Yeah you can also place blocks midair. It seems like all of the place checks are broken.

**Comment by MWHunter** [comment]
was issue with test server from outdated punishments config
