### ISSUE TITLE
Timer Elytra False Flag

### ISSUE THREAD

**Issue by amnoah** [GrimAnticheat/Grim#706]
### Describe the false positive and how to replicate it

https://youtu.be/0qljjT9P-Lw

1: Equip an elytra and position yourself similarly to issue #704 
2: Look up and start repeating the same process, but spamming firework rockets
3: False flag ground spoof and timer

### Grim version

Test Server (2.3.20)

### Server version

Test Server (This server is running Paper version git-Paper-18 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 17c1c6c))

### Plugins

Test Server

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/162170a7b0d817018202fd62a6d7a9b4bd549918

Timer fixed by https://github.com/MWHunter/Grim/commit/e01a30a066c28bc09b7c7e210eb95dd387aaad89
