### ISSUE TITLE
Simulation/GroundSpoof Falses when teleporting inside of blocks

### ISSUE THREAD

**Issue by amnoah** [GrimAnticheat/Grim#707]
### Describe the false positive and how to replicate it

https://youtu.be/9OjFNs4sl6g

Step 1: Get some enderpearls
Step 2: Throw them into stairs/slabs in a way that you'll be teleported inside of blocks
Step 3: Try to move, flagging Simulation/GroundSpoof

### Grim version

Test Server (2.3.20)

### Server version

Test Server (This server is running Paper version git-Paper-18 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 17c1c6c))

### Plugins

Test Server

**Comment by MWHunter** [comment]
Should be resolved by https://github.com/MWHunter/Grim/commit/54c88f1df8523c190b5d41052b537faa75322238 and https://github.com/MWHunter/Grim/commit/cd701713f33ed2c9c6c3fdf8308dd44bbb967f20
