### ISSUE TITLE
GrimAC and packetevents are not compatible.

### ISSUE THREAD

**Issue by MinecraftUserHAN1110** [GrimAnticheat/Grim#709]
### Describe the bug and how to replicate it

1: Apply GrimAC 2.3.17 and PacketEvents 1.8.4 to the plugin.
2: start the server
3: When I run the /pl command, GrimAC is displayed in red in the plug-in list.

### Grim version

GrimAC 2.3.17
Packet Events 1.8.4

### Server version

This server is running Paper version git-Paper-324 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 8c9d98e)
You are 63 version(s) behind
Download the new version at: https://papermc.io/downloads

### Plugins

ABC, AntiCheatReloaded, Citizens, Essentials, EssentialsChat, EssentialsSpawn, GrimAC, HolographicDisplays, LuckPerms, Matrix, Multiverse-Core, Negativity, NoCheatPlus, packetevents*, ProtocolLib, ProtocolSupport, SkQuery, skRayFall, Skript, skUtilities*, SoaromaSAC, Themis, VoidGen, WorldEdit, WorldGuard

Note: ABC stands for Advanced Anticheat, GrimAC and ABC are shown in red.

**Comment by ghost** [comment]
Use PacketEvents 2.0

**Comment by MWHunter** [comment]
Console log of exception?  PE 2.0 and 1.8 should be compatible.

**Comment by MWHunter** [comment]
resolved by shading correctly
