### ISSUE TITLE
Destroying blocks using autoclicker trigger FastBreak

### ISSUE THREAD

**Issue by BD9a** [GrimAnticheat/Grim#713]
### Describe the false positive and how to replicate it

Place a bunch of Sticky Pistons
Destroy them using any autoclicker (I used SpeedAutoClicker and [this](https://i.imgur.com/sDro9AF_d.webp?maxwidth=760&fidelity=grand) config)

### Grim version

Grim Version 2.3.21

### Server version

Paper 1.8.8

### Plugins

Just Grim without any plugins

**Comment by MWHunter** [comment]
Fixed by https://github.com/GrimAnticheat/Grim/commit/e2f6771bfc51b1bfb9299226a3939a8f9df695f5
