### ISSUE TITLE
[False] Experimental Crash false with "Russian Pre-revolution" language

### ISSUE THREAD

**Issue by VidTu** [GrimAnticheat/Grim#716]
### Describe the false positive and how to replicate it

1. Enable experimental checks.
2. Set the locale to "Russian Pre-revolution" (internally `rpr.json`).
3. See Crash false.

This language looks like this in the language selector: ![image](https://user-images.githubusercontent.com/60929459/181831815-96e2e2cd-045b-4728-ae97-da7ed32a5b07.png)

### Grim version

2.3.21

### Server version

1.19 (Paper)

### Plugins

GrimAC (my own test server)

**Comment by AoElite** [comment]
Thanks for reporting this and using experimental checks. Fixed by 624b502c951eb588586ebc8378927387639fe66f.

**Comment by VidTu** [comment]
IIRC you can add any language with any ID using resource packs, please check this
