### ISSUE TITLE
Cannot invoke "String.length()" because "string" is null

### ISSUE THREAD

**Issue by kixmc** [GrimAnticheat/Grim#717]
### Stack trace

https://paste.gg/p/anonymous/76fd8ac52450400d9dffb16bba6d0275

Everybody was kicked for `Internal Exception: io.netty.handler.codec.EncoderException: java.lang.reflect.InvocationTargetException`

### How to replicate it if known

N/A, seems to have randomly occured

### Grim version

2.3.14

### Server version

Purpur-1715 1.19

### Plugins

Viaversion, protocolib, nametagedit, nothing else touching packets

**Comment by probablynotkai** [comment]
It looks as though the error is a result of an API call to ViaVersion. I noticed that you're using Panilla.jar as well, after a bit of research, I saw that user ds58 distributed a JAR called **panilla-nopacketdecompress.zip**, this may help to resolve your issue.
