### ISSUE TITLE
Velocity falses when flying

### ISSUE THREAD

**Issue by FlamWy** [GrimAnticheat/Grim#720]
### Describe the false positive and how to replicate it

https://user-images.githubusercontent.com/35672743/181879645-b64e0bf4-96f8-4643-8ead-62b3968ed8a3.mp4

### Grim version

0c502c157a39d74d97a07363647d5525efae9506

### Server version

1.8.8 WindSpigot

### Plugins

GrimAC

**Comment by MWHunter** [comment]
Duplicate #714
