### ISSUE TITLE
player cant join

### ISSUE THREAD

**Issue by Abel156** [GrimAnticheat/Grim#724]
### Stack trace

_Player lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NoClassDefFoundError: Could not initialize class ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.entity.data.EntityDataTypes_
player join will show these
18b5ea868a45f07068ce77c1cb8fbc497157efc3 - grim version
server version - This server is running GoatSpigot version 1.8.8-R0.1-SNAPSHOT (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
client version - 1.7.10 cheatbreaker 
Plugins (4): ViaVersion, PlaceholderAPI, ViaRewind, GrimAC

### How to replicate it if known

1. join server

### Grim version

18b5ea868a45f07068ce77c1cb8fbc497157efc3

### Server version

server version - This server is running GoatSpigot version 1.8.8-R0.1-SNAPSHOT (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### Plugins

Plugins (4): ViaVersion, PlaceholderAPI, ViaRewind, GrimAC

**Comment by MWHunter** [comment]
NoClassDefFoundError means there's a helpful error in console to debug this, without it the issue can't be fixed.

**Comment by Abel156** [comment]
> NoClassDefFoundError means there's a helpful error in console to debug this, without it the issue can't be fixed.

[GrimAC] Enabling GrimAC v2.3.21
[GrimAC] Registering singular bukkit event... (PistonEvent)
[GrimAC] Registering packets...
[GrimAC] Checking ViaBackwards Compatibility...
[GrimAC] Registering tick schedulers...
Finished loading the server in 0.844s...
Timings Reset
[ViaVersion] ViaVersion detected server version: 1.8.x (47)
[ViaVersion] This version of Minecraft is extremely outdated and support for it has reached its end of life. You will still be able to run Via on this Minecraft version, but we are unlikely to provide any further fixes or help with problems specific to legacy Minecraft versions. Please consider updating to give your players a better experience and to avoid issues that have long been fixed.
[ViaVersion] You are running an outdated Java version, please consider updating it to at least Java 17 (your version is 1.8.0_301). At some point in the future, ViaVersion will no longer be compatible with this version of Java.
[ViaVersion] Finished mapping loading, shutting down loader executor!
UUID of player PLAYER1 is NOOONONO
PLAYER1[/IP:12128] logged in with entity id 4 at ([world]-515.8968990763146, 4.0, 2.3105917788034174)
[ViaVersion] You are running a development version of the plugin, please report any bugs to GitHub.
PLAYER1 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.ExceptionInInitializerError
PLAYER1 left the game.
UUID of player PLAYER1 is NOOONONO
PLAYER1[/IP:12135] logged in with entity id 5 at ([world]-515.8968990763146, 4.0, 2.3105917788034174)
PLAYER1 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NoClassDefFoundError: Could not initialize class ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.entity.data.EntityDataTypes
PLAYER1 left the game.
UUID of player PLAYER1 is NOOONONO
PLAYER1[/IP:12138] logged in with entity id 6 at ([world]-515.8968990763146, 4.0, 2.3105917788034174)
PLAYER1 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NoClassDefFoundError: Could not initialize class ac.grim.grimac.shaded.com.github.retrooper.packetevents.protocol.entity.data.EntityDataTypes
PLAYER1 left the game.

**Comment by caoli5288** [comment]
May you should update your viaversion

**Comment by Abel156** [comment]
> May you should update your viaversion

https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/
https://ci.viaversion.com/job/ViaVersion/631/

same

**Comment by Abel156** [comment]
This problem seems to have been fixed, but new problems have arisen
https://github.com/GrimAnticheat/Grim/issues/731

**Comment by Abel156** [comment]
This problem seems to have been fixed, but new problems have arisen
https://github.com/GrimAnticheat/Grim/issues/731
