### ISSUE TITLE
Bypass,false positives

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#725]
### Describe the bypass and how to replicate it

https://www.youtube.com/watch?v=DAOjicsERbY
https://www.youtube.com/watch?v=hw_DeKavjMs

### Grim version

http://130.61.49.173/job/GrimAC/73/

### Server version

1.8/1.19

### Plugins

.

**Comment by AoElite** [comment]
Already has been reported. A lot of these issues have already been fixed.
