### ISSUE TITLE
Simulation false on air (Specific block)

### ISSUE THREAD

**Issue by zNoah-1** [GrimAnticheat/Grim#730]
What the title says

**Video demonstration:** 
https://youtu.be/D4ocfDIg2JU

**"/gl" related to the issue:** 
https://paste.grim.ac/5K4r9

**Info:**
Server: Purpur 1.19.1 1748
Client: Fabric 1.19 with Sodium
Grim Version: 2.3.21
Plugins (42): AsyncWorldEdit, BlockLocker, ChatManager, Chunky, CoreProtect, DeluxeTags, DiceFurniture, DiscordSRV, DragonDropElytra, dynmap, Dynmap-SimpleClans*, Dynmap-WorldGuard*, EntityDetection, Essentials, EssentialsSpawn, FurnitureLib, GrimAC, GSit, HolographicDisplays, Images, LuckPerms, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, OnePlayerSleep*, PlaceholderAPI, PlayerKits, PlugMan, ProtectionStones, ProtocolLib, Randomtp, SimpleClans, spark, SternalBoard, TAB, Vault, ViaBackwards, ViaVersion, ViewDistanceTweaks, WorldEdit, WorldGuard

**Comment by MWHunter** [comment]
don't know what the error is or how to fix it, my guess would be something broke in the 1.19 block prediction logic

**Comment by MWHunter** [comment]
this is impossible to debug
