### ISSUE TITLE
License/GPL considerations

### ISSUE THREAD

**Issue by danthe1st** [GrimAnticheat/Grim#732]
I have noticed this sentence in the README:
> It will eventually become paid and/or will include offer additionally subscription based paid checks.

Note that GPL requires to publish the source code under the GPL license as long as you provide binaries (selling them counts as well!).

While GPL doesn't forbid selling licenses, it does forbid selling selling binaries while not giving away the source code under GPL (and everyone the source code is given to is allowed to publish and change it under GPL).

Also note that the maintainers are not the only copyright holders (every contributor is a copyright holder) resulting in the maintainers being bound to GPL as well.

Currently, this is no problem but it should probably be considered when
> It will eventually become paid and/or will include offer additionally subscription based paid checks.

Disclaimer:
> I am not a lawyer and I have also not used/tested the Anticheat by myself. I just found it and wanted to make sure that the maintainers know about the issue.

**Comment by MWHunter** [comment]
Fuck off, you just want free stuff.

**Comment by danthe1st** [comment]
I don't want free stuff, I don't even maintain any Minecraft server. I was just warning you that this might happen as GNU GPL uses strong copyleft.

In fact, I have no problem with you wanting to make money with your anticheat but you _might_ not be able to do so by selling closed-source binaries containing GPL-licensed code.

**Comment by MWHunter** [comment]
The premium checks will likely be cloud based anyways as GPL doesn't apply there, plus piracy in this community is ridiculous with pirated downloads sometimes having twice as many downloads as the legit source.

Fun fact - bukkit is GPL meaning all plugins on SpigotMC should be GPL, but a significant potion aren't.  Sadly GPL isn't enforced in this community.

**Comment by danthe1st** [comment]
As long as the project stays Open Source under GPL, it should be fine.
Regarding piracy and enforcement of the GPL in that Community, I have no idea about it as I cannot consider myself part of it. I just wanted to make sure you are informed about it and the fact that outside contributors are copyright holders providing their code under GPL as well.

Regarding Bukkit being GPL, it might be the case that GPL only applies to providing bukkit binaries as I think that Minecraft Plugins don't bundle Bukkit itself.

However, as said earlier, I am neither a lawyer nor a Minecraft Plugin Developer so take it with a grain of salt.
