### ISSUE TITLE
Error being spammed on console after shutdown

### ISSUE THREAD

**Issue by CayeOficial** [GrimAnticheat/Grim#733]
### Stack trace

https://pastebin.cayeoficial.com/wokejapufu.log

### Grim version

2.3.17

### Server version

This server is running Pufferfish version git-Pufferfish-22 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 42ef3dc on HEAD)

### Plugins

Come MD on discord if you need this `zCayeOficial#0001`

**Comment by AoElite** [comment]
Outdated grim version
