### ISSUE TITLE
Reach FP with goats

### ISSUE THREAD

**Issue by Jaren8r** [GrimAnticheat/Grim#737]
### Describe the false positive and how to replicate it

https://user-images.githubusercontent.com/8620569/183201925-1060ecf7-b53c-4738-a8ab-cb4527e8d90c.mp4

### Grim version

2.3.21

### Server version

Pufferfish+ version git-PufferfishPlus-18 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: 2f07a0d on HEAD)

### Plugins

ViaVersion (4.2.2-SNAPSHOT), ViaBackwards (4.2.2-SNAPSHOT)

**Comment by AoElite** [comment]
Fixed by 627374f4c612a5265f23881a0c43fdd793f18095
