### ISSUE TITLE
Exception when a player joins a 1.16.5 server

### ISSUE THREAD

**Issue by Jyguy** [GrimAnticheat/Grim#742]
### Stack trace

https://paste.gg/p/anonymous/23b1bca4310b44f8b46b0a60a7a4f3e1

### How to replicate it if known

1. Start a 1.16.5 Paper server
2. Join the server

### Grim version

3d42504fdb4858b3c1ab13a5ed2841efc5453ede

### Server version

This server is running Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Plugins

Plugins (1): GrimAC

**Comment by MWHunter** [comment]
old
Class<?> COMPONENT_SERIALIZER = Class.forName("net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl");

with shading
final Class<?> COMPONENT_SERIALIZER = Class.forName("ac.grim.grimac.shaded.kyori.adventure.text.serializer.gson.ComponentSerializerImpl");

Recompile grim for updated gson shading
