### ISSUE TITLE
Error while using ModelEngine

### ISSUE THREAD

**Issue by SuggarHidden** [GrimAnticheat/Grim#747]
### Describe the bug and how to replicate it

First, download [ModelEngine](https://github.com/Ticxo/Model-Engine-Wiki/tree/master/demo) you can use the [free trial](https://github.com/Ticxo/Model-Engine-Wiki/tree/master/demo), I am using the paid one, but it is the same.
Second, use the command /meg disguise "model" or you can also create a model using the citizens integration, you can try it with any model, there are some free ones by the plugin. 
Third, read [many errors](https://pastebin.com/raw/ByGZZBYS) in the console. 

### Grim version

grimac-2.3.23

### Server version

git-Purpur-1632 (MC: 1.18.2)*

### Plugins

ajLeaderboards, AnnouncerPlus, AntiRaidFarm, BetterRTP, BottledExp, BuycraftX, ChatFilter, Chunky, Citizens, CMI, CMILib, CommandWhitelist, CoreProtect, CrazyAuctions, CustomAdvancements, CyberLevels, DenyTravel, DiceFurniture, DisableRecipe, DisplayShops, Elevators, EnderVaults, FarmControl, FastAsyncWorldEdit (WorldEdit), ForcePack, FurnitureLib, GrimAC, HungerGames, Insights, LibsDisguises, LoneLibs, LuckPerms, LumberJack, MMOItems, ModelEngine, Multiverse-Core, Multiverse-Inventories, MyPet, MythicLib, MythicMobs, OfflineGrowthPro, OldCombatMechanics, PlaceholderAPI, PlayerParticles, PlayerWarps, PocketMobs, ProtectionLib, ProtectionStones, ProtocolLib, PvPManager, Quests, SCore, Shopkeepers, spark, SpawnerMeta, SpecializedCrates, StopNetherTrap, TAB, TradeSystem, TrMenu, UltimateClans, UpgradeableHoppers, Vault, ViaBackwards, ViaVersion, VoxelSniper, WorldGuard, WorldGuardExtraFlags

**Comment by AoElite** [comment]
Link to the error no longer works.

**Comment by SuggarHidden** [comment]
> Link to the error no longer works.
[errors1.txt](https://github.com/GrimAnticheat/Grim/files/9747838/message.txt)
[errors2.txt](https://github.com/GrimAnticheat/Grim/files/9747840/message.1.txt)

**Comment by MWHunter** [comment]
Can you reproduce on the latest grim?  This seems like a PacketEvents issue and packetevents was updated in the last release

**Comment by MWHunter** [comment]
closing all injector related bugs due to rewritten injector
