### ISSUE TITLE
BadPacketsM false positive

### ISSUE THREAD

**Issue by jonesdevelopment** [GrimAnticheat/Grim#753]
### Describe the false positive and how to replicate it

Step 1: Get blocks
Step 2: Go to a building area
Step 3: Hot key to an empty slot and to your block slot really quickly while spamming right click

Minecraft version: 1.19 vanilla

[screenshot](https://media.discordapp.net/attachments/896568458559500289/1008307839741202522/unknown.png)

### Grim version

Test server (2.3.21)

### Server version

Paper-1.19-R0.1-17c1c6c

### Plugins

This was tested on the official Grim test server. (test.grim.ac)

**Comment by MWHunter** [comment]
this check isn't fixable.

removed in https://github.com/GrimAnticheat/Grim/commit/08d3392b0f0ed21b23aeb7cf35e683e50a7d7166
