### ISSUE TITLE
So I've been using grimac and I recently updated to 2.3.23.

### ISSUE THREAD

**Issue by cjhickson647** [GrimAnticheat/Grim#754]
All of a sudden, I get this from Windows Defender.
![image](https://user-images.githubusercontent.com/77416223/184545878-b937aa77-a524-4a17-b0e2-daa9cd91954d.png)
Why did this happen?

**Comment by cjhickson647** [comment]
I was able to recover the jar from windows and upload it into google drive.

**Comment by ghost** [comment]
Heh, typical Windows Defender. For some reason anti-viruses often trigger on .jar files.
