### ISSUE TITLE
Breaking pistons falses FastBreak

### ISSUE THREAD

**Issue by SelfMadeSystem** [GrimAnticheat/Grim#757]
### Describe the false positive and how to replicate it

I break pistons on official test server with 100% vanilla 1.12.2 minecraft client (no forge, optifine, etc.) and it falses. Doesn't matter if it's the head or the body of the piston. It falses. It doesn't seem to false for the other blocks.

https://youtu.be/ZkHD9dgzCSg

### Grim version

idk i'm on official test server

### Server version

idk i'm on official test server

### Plugins

idk i'm on official test server

**Comment by MWHunter** [comment]
Duplicate https://github.com/GrimAnticheat/Grim/issues/713

**Comment by SelfMadeSystem** [comment]
I wasn't using autoclicker but ok
