### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by deestt** [GrimAnticheat/Grim#762]
C:\Users\onlyb\Desktop\Grim>gradlew shadowJar

> Task :compileJava
C:\Users\onlyb\Desktop\Grim\src\main\java\ac\grim\grimac\utils\data\TrackerData.java:9: warning: @NonNull is meaningless on a primitive.
@RequiredArgsConstructor
^
C:\Users\onlyb\Desktop\Grim\src\main\java\ac\grim\grimac\utils\data\TrackerData.java:9: warning: @NonNull is meaningless on a primitive.
@RequiredArgsConstructor
^
C:\Users\onlyb\Desktop\Grim\src\main\java\ac\grim\grimac\utils\data\TrackerData.java:9: warning: @NonNull is meaningless on a primitive.
@RequiredArgsConstructor
^
C:\Users\onlyb\Desktop\Grim\src\main\java\ac\grim\grimac\utils\latency\CompensatedEntities.java:20: error: cannot find symbol
import com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityProperties;
                                                            ^
  symbol:   class WrapperPlayServerEntityProperties
  location: package com.github.retrooper.packetevents.wrapper.play.server
C:\Users\onlyb\Desktop\Grim\src\main\java\ac\grim\grimac\utils\data\packetentity\PacketEntitySelf.java:7: error: cannot find symbol
import com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityProperties;
                                                            ^
  symbol:   class WrapperPlayServerEntityProperties
  location: package com.github.retrooper.packetevents.wrapper.play.server
C:\Users\onlyb\Desktop\Grim\src\main\java\ac\grim\grimac\utils\latency\CompensatedEntities.java:100: error: package WrapperPlayServerEntityProperties does not exist
    public void updateAttributes(int entityID, List<WrapperPlayServerEntityProperties.Property> objects) {
                                                                                     ^
C:\Users\onlyb\Desktop\Grim\src\main\java\ac\grim\grimac\utils\latency\CompensatedEntities.java:144: error: package WrapperPlayServerEntityProperties does not exist
    private double calculateAttribute(WrapperPlayServerEntityProperties.Property snapshotWrapper, double minValue, double maxValue) {
                                                                       ^
C:\Users\onlyb\Desktop\Grim\src\main\java\ac\grim\grimac\utils\data\packetentity\PacketEntitySelf.java:14: error: package WrapperPlayServerEntityProperties does not exist
    public WrapperPlayServerEntityProperties.Property playerSpeed = new WrapperPlayServerEntityProperties.Property("MOVEMENT_SPEED", 0.1f, new ArrayList<>());
                                            ^
C:\Users\onlyb\Desktop\Grim\src\main\java\ac\grim\grimac\predictionengine\PlayerBaseTick.java:14: error: cannot find symbol
import com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerEntityProperties;
                                                            ^
  symbol:   class WrapperPlayServerEntityProperties
  location: package com.github.retrooper.packetevents.wrapper.play.server
6 errors
3 warnings

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
1 actionable task: 1 executed

**Comment by jonesdevelopment** [comment]
> build.gradle:

```
// repository for PacketEvents
maven {
    name = 'codemc-snapshots'
    url = 'https://repo.codemc.io/repository/maven-snapshots/'
} // PacketEvents
```

```
// dependencies
implementation 'com.github.retrooper.packetevents:spigot:2.0.0-SNAPSHOT'

// make sure to add lombok as a annotation processor and not as an implementation
annotationProcessor 'org.projectlombok:lombok:1.18.24'

// don't compile lombok
testCompileOnly 'org.projectlombok:lombok:1.18.24'
testAnnotationProcessor 'org.projectlombok:lombok:1.18.24'
```

This is working fine for me.
If this isn't working, please send your build.gradle or download/use the one from the repository.
