### ISSUE TITLE
BadPacketE

### ISSUE THREAD

**Issue by Souipi** [GrimAnticheat/Grim#767]
### Describe the false positive and how to replicate it

increase or decrease the general sounds of MineCraft
MineCraft client version : 1.8.9

### Grim version

2.3.23

### Server version

1.8.9

### Plugins

GrimAC, protocolib 2.5.0, FAWE, WD, WG, Viaversion, Luckperms and spark.

**Comment by MWHunter** [comment]
Caused by a packet limiting plugin interfering with grim.  Increasing/decreasing sound spams packets, and some packet limiter is blocking normal flying packets due to packet spam.  Not the fault of grim.
