### ISSUE TITLE
Simulation

### ISSUE THREAD

**Issue by NMDx86** [GrimAnticheat/Grim#775]
### Describe the false positive and how to replicate it

Step 1 : Swim ( I am using a depthstrider 3 boot, idk if that will affect it )
Step 2 : Break lots of kelp while swimming

### Grim version

2.3.23

### Server version

Purpur 1.19.2

### Plugins

Plugins (89): AdvancedBan, AdvancedReplay*, AntiChunkCrash, ArmorStand-Limiter, AuctionHouse, AureliumSkills, Aurora, BeastWithdraw, BetterRTP, BetterTeams, BetterTridents, BlueMap, BlueSlimeCore (SirBlobmanAPI, SirBlobmanCore, XSeries), BountySeekers, ChestSort, Chunky, ClaimChunk, CombatLogX, CooldownsX, CoreProtect, CrackShot, Craftconomy3*, DailyRewards, DeadChest, DecentHolograms, DeluxeCoinflip, DiscordSRV, DoorsReloaded, DualWield, FarmControl, floodgate, Geyser-Spigot, GrimAC, GSit, Hat, HealthBar, ImageOnMap, InteractionVisualizer, InteractiveChat, InteractiveChatDiscordSrvAddon, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, ItemNameTags, LevelledMobs, LightAPI, LightN*, LoginSecurity*, LPC, LuckPerms, MineTweaks, MoneyHunters, MoreOres, NexEngine, NoChunkLag, PixelMOTD*, PlaceholderAPI, Plan, PlayerKits, PlayerNPC, PlayerWarps, ProtocolLib, PunishGUI, QuickShop-Hikari, RealisticSurvival, RealScoreboard, RedstoneDetector*, ShulkerPackX, SimpleTpa*, SkinsRestorer, spark, StackMob, StaffChatX, SuperVanish, TabList, Themis, TradeSystem, TreeAssist, TroddenPath, UltimateHomes, VanillaTweaks, Vault, VeinMiner, ViaBackwards, ViaVersion, Vouchers, Vulcan, WorldEdit, WorldGuard

**Comment by MWHunter** [comment]
Caused by 1.19 changing logic when block breaking, so air isn't always replaced when a block is broken

**Comment by NMDx86** [comment]
> lock is br
Anyway to fix it or i need to wait for 3.0

**Comment by captainion2119** [comment]
Same problem.

**Comment by MWHunter** [comment]
https://github.com/GrimAnticheat/Grim/commit/9b99115ec162f5e8112aa52f338440957e633f93
