### ISSUE TITLE
Jumping plus mashing W every now and then 

### ISSUE THREAD

**Issue by TheTawnyYT** [GrimAnticheat/Grim#777]
### Describe the false positive and how to replicate it

lunarclient jumping around players or NPC‘s and matching W every now and then false flags, Grim log doesn’t wanna work there’s no Errors, Plus soul sand plus Fence

### Grim version

Latest

### Server version

1.8

### Plugins

World edit, World guard, essentials, Grim.

**Comment by AoElite** [comment]
Not enough information
