### ISSUE TITLE
Simulation | Breaking kelp leads to false positive

### ISSUE THREAD

**Issue by glitchring** [GrimAnticheat/Grim#778]
### Describe the false positive and how to replicate it

Literally kelp can achieve false 100+
Video: https://drive.google.com/file/d/1pd4eSVZVZ23pZbl-DGSq2gDqHowpL4Pp/view

### Grim version

Latest (Compiled version)

### Server version

Airplane version git-Airplane-11 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Plugins

Grim, ProtocolLib

**Comment by vytskalt** [comment]
Probably duplicate of #775

**Comment by glitchring** [comment]
> Probably duplicate of #775

Oh, funny. I'm sorry, I didn't notice

**Comment by MWHunter** [comment]
https://github.com/GrimAnticheat/Grim/commit/9b99115ec162f5e8112aa52f338440957e633f93
