### ISSUE TITLE
Full disabler

### ISSUE THREAD

**Issue by Comiclyy** [GrimAnticheat/Grim#780]
### Describe the bypass and how to replicate it

Hi, I just thought i would let this be known to anyone using this anticheat on any server with people acctualy playing on it. Litterly anyone could make a full disabler or anything for this server. If you dont know what OPEN SOURCE means, it litterly means anyone can see the code of the anticheat, therefor making it very easy to make bypasses. For example if i went to look at the reach checks for this anticheat, then went to my client and coded a disabler that makes that check not be able to notice that i am using 8 block reach. this is so easy to do because i can see all of the code for the anticheat and can see what i need to do to make a disabler/ bypass

### Grim version

latest

### Server version

cba

### Plugins

cba

**Comment by vytskalt** [comment]
is this a joke

**Comment by AoElite** [comment]
It's clear that you didn't look at the source or even read the readme.

**Comment by sadcenter** [comment]
xd
