### ISSUE TITLE
Simulation falses when switching between dimensions/worlds

### ISSUE THREAD

**Issue by c0dingnoobi** [GrimAnticheat/Grim#787]
### Describe the false positive and how to replicate it

Behaviour reproduceable on every world manager plugin and vanilla dimensions.
Video: https://youtu.be/5d2dH2BeRHo

1. Load GrimAC default config
2. Have multitple worlds (either vanilla dimensions or world manager worlds)
3. Switch between dimensions and move directly after switching

Super debug of latest alert: https://paste.grim.ac/BJvHp (/gl 144)

Also falses occasionally on server join events. Might also be related to this topic.

### Grim version

- GrimAC 2.3.24 (Spigot Version)

### Server version

- Spigot 1.8.8

### Plugins

- GrimAC
- Multiverse-Core (2.5)

**Comment by ghost** [comment]
Can confirm this

**Comment by MWHunter** [comment]
Analysis to figure out the significant numbers in this debug:

First offset is 0.007134399644708633

Tick one:
(0.2 movement speed * 0.98 input multiplier at direction of 0)
0.0,0.0,0.019600000232458115


Friction different from ground vs air
0.019600000232458115 * 0.91 * (1.0 - 0.6) = 0.00713440008

First offset flag provided in grim debug: 0.007134399644708633

The ground status of the player is wrong when teleporting cross world, the player's ground is being set to air when they should be on the ground.  Maybe 1.8 doesn't reset the ground status when teleporting cross dimension.

**Comment by SamB440** [comment]
Should be fixed by #1494 and related commits, hopefully
