### ISSUE TITLE
Fastswim works on 1.12.2

### ISSUE THREAD

**Issue by vixtordev** [GrimAnticheat/Grim#790]
### Describe the bypass and how to replicate it

1. Open liquidbounce
2. Turn on FastSwim
Now if the player walks in water they go faster than normal.

### Grim version

2.3.23

### Server version

Paper 1.12.2 git-Paper-1620

### Plugins

![image](https://user-images.githubusercontent.com/108889461/197390535-7993b868-583f-4e74-9cdf-19b86c49d970.png)
Ignore skelett and watchdog

**Comment by MWHunter** [comment]
WaterSpeed on liquidbounce (can't find FastSwim) flags for me at 1.1x, the minimum setting allowed.
