### ISSUE TITLE
Issue when players joining on Purpur 1.19.2 with this plugin.

### ISSUE THREAD

**Issue by Crsuh2er0** [GrimAnticheat/Grim#792]
### Stack trace

Console:
`[13:01:26] [User Authenticator #0/INFO]: UUID of player MC_June is a1d75625-a085-3b13-bddb-df92a82a8fec
[13:01:26] [Server thread/INFO]: MC_June lost connection: Internal Exception: io.netty.handler.codec.EncoderException: ac.grim.grimac.shaded.com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 107 to a PacketType constant. Bound: CLIENT, Connection state: PLAY, Server version: 1.19`

Client side:
`NativeIoexception: readaddress(...) failed: Connection reset by peer`

### How to replicate it if known

1.Use this plugin on Purpur 1.19.2.
2.Join the server.

### Grim version

GrimAC v2.3.12

### Server version

Purpur version git-Purpur-1832 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 0d5fd50 on HEAD)

### Plugins

![680B47C4-381C-43dc-A748-2DD5746FFB16](https://user-images.githubusercontent.com/93849805/198507235-e8d9183a-cded-46b1-b308-1ccc143dec6d.png)

**Comment by c0dingnoobi** [comment]
Would say try updating ur grim. 
Also what client version u used to join

**Comment by Crsuh2er0** [comment]
But now I find it's all right. I didnt even do anything

**Comment by Crsuh2er0** [comment]
I updated my GrimAC and now it's all right.
I used 1.19 to join.
