### ISSUE TITLE
Bedrock Players Get Flagged

### ISSUE THREAD

**Issue by BobtheBob123456** [GrimAnticheat/Grim#797]
### Describe the bug and how to replicate it

So when I started using Grim there were no issues, but once I installed GeyserMC bedrock players started to get flagged.

I looked at the Grim Spigot page and it said you had to install GeyserMC on a backend server but I don't know what that is.

(I also use aternos)

### Grim version

2.3.24

### Server version

This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)

### Plugins

AdvancedTeleport, DeathCoordinates, EntityClearer, floodgate, Geyser-Spigot, GrimAC, JoinCommands, Logger, LuckPerms, Multiverse-Core, Multiverse-Portals, PvPManager, ViaVersion, WorldEdit, WorldGuard

**Comment by hinoobers** [comment]
Backend server means the actual spigot server itself, not the proxy.

**Comment by MWHunter** [comment]
09:58:02 INFO]: [floodgate] Floodgate player logged in as .Define_Outside joined (UUID: 00000000-0000-0000-0009-01f7ed6f3737)
[09:58:03 INFO]: .Define_Outside joined the game
[09:58:03 INFO]: .Define_Outside[/123.456.789.123:0] logged in with entity id 128 at ([world]-2.5, 101.0, 3.5)
[09:58:20 INFO]: This player is exempt from all checks!
[09:58:20 INFO]: User connection state: PLAY

Works for me on aternos
