### ISSUE TITLE
Anti Baritone doesnt work

### ISSUE THREAD

**Issue by xXCooBloyXx** [GrimAnticheat/Grim#798]
### Describe the bypass and how to replicate it

Anti baritone doesnt detect anything

### Grim version

2.3.24

### Server version

This server is running Paper version git-Paper-188 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 6d14093)
You are 73 version(s) behind

### Plugins

Plugins (40): Citizens, CommandWhitelist, DiSky, Essentials, GrimAC, GSit, iControlU*, InventoryRollbackPlus, ItemEdit, LibsDisguises, LPC, LuckPerms, MineResetLite, MorkazSk, OpenInv, PlaceholderAPI, PlayerKits, PlugManX (PlugMan), ProtocolLib, PvPManager, Sentinel, Shopkeepers, SkBee, Skellett, SkinsRestorer, SkQuery, skRayFall, Skript, skript-reflect, Skungee, spark, SuperVanish, TAB, TradeSystem, Vault, ViaBackwards, ViaVersion, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Comment by MWHunter** [comment]
That's intentional, I can't open source my updated baritone check.

**Comment by caoli5288** [comment]
> That's intentional, I can't open source my updated baritone check.

When can I pay for Grim3?
