### ISSUE TITLE
Massive console spam

### ISSUE THREAD

**Issue by Xayanix** [GrimAnticheat/Grim#805]
### Stack trace

https://paste.gg/p/anonymous/324519e30c4044dbb70c897bb8e1dd4b

and

![image](https://user-images.githubusercontent.com/12672902/202706817-bc9cfb60-a006-4998-a31d-77224b93ebd1.png)

### How to replicate it if known

Just install grimac and let players play

### Grim version

2.3.24

### Server version

1.8.8

### Plugins

![image](https://user-images.githubusercontent.com/12672902/202706742-0fa515ea-f065-419a-8163-289acdddfd60.png)

**Comment by MWHunter** [comment]
-1 isn't a valid value here according to the protocol wiki, but I'll see what the client is doing with this invalid -1 value

**Comment by MWHunter** [comment]
Fixed by https://github.com/GrimAnticheat/Grim/commit/378939cfb03a0a6c139243be0774af59ea69aa12

**Comment by Xayanix** [comment]
Recent GrimAC update fixed all exceptions in console log, thanks.
