### ISSUE TITLE
NegativeTimer false positive

### ISSUE THREAD

**Issue by ghost** [GrimAnticheat/Grim#819]
### Describe the false positive and how to replicate it

Step 1. Use Optifine 1.8 client
Step 2. Be idle
Step 3. False positive

![image](https://user-images.githubusercontent.com/72635645/206305963-31ce04fd-8052-41ec-9da8-1ef08a1ba8de.png)

Seems to happen only with optifine

### Grim version

[f7e6e99](https://github.com/GrimAnticheat/Grim/commit/f7e6e992ce730f091e3fe2f6a55d3526e553a27f)

### Server version

Paper 1.8.8

### Plugins

-

**Comment by MWHunter** [comment]
use the spigot release, I haven't tested 1.8 with NegativeTimer

**Comment by MWHunter** [comment]
Should have been fixed by https://github.com/GrimAnticheat/Grim/commit/bfe3d8c57e783e023bd4eac89c33d9060df81cac

This treats 1.8 players more like they are 1.9 players - and I've stress tested 1.9 to be fine except the rare false positive when server clock is screwed up by a huge lag spike.
