### ISSUE TITLE
Simulation and Groundspoof falses when opening iron trapdoor on 1.7 Client

### ISSUE THREAD

**Issue by c0dingnoobi** [GrimAnticheat/Grim#820]
### Describe the false positive and how to replicate it

This behaviour has nothing to do with the recent updates. It was reproduceable since 2.3.23.
Might just get labelled with Viaversion since the cause is Viaversions worldmapping.

1. Place iron trapdoor
2. Get online with 1.7
3. Open trapdoor while standing above on it (will be wood)

Video: https://www.youtube.com/watch?v=qdNtET7xwEI
Last super debug: https://paste.grim.ac/3hCLU

### Grim version

- 2.3.26 (Spigot)

### Server version

- Spigot 1.8.8

### Plugins

- GrimAC 2.3.26
- ViaVersion 4.5
- ViaRewind 
- Warpsystem (should not be related to this behaviour)

**Comment by MWHunter** [comment]
https://github.com/GrimAnticheat/Grim/commit/26a9e3f3c731b9bed66bd0d75cd8d50b0ef24d47
