### ISSUE TITLE
Fences false positive

### ISSUE THREAD

**Issue by B4rCodee** [GrimAnticheat/Grim#821]
### Describe the false positive and how to replicate it

Step 1. Place a fence next to a block that the fence cant connect to
Step 2. Jump on the block and start running on the fence

### Grim version

2.3.26

### Server version

Light spigot lite version based on paper spigot 1.8.8

### Plugins

CoreProtect, LunarClient-API, WOrldEdit, Skript, PlaceholderAPI, SkQuery, Kits, Multiverse-Core, OpGuard, ViaVersion, LuckPerms, PlugMan, ProtocolLib, Grim, Vault, Lazarus, VortexPearls

**Comment by FlamWy** [comment]
What block specifically? I am unable to reproduce this with glass, leaves & piston blocks

**Comment by B4rCodee** [comment]
i have been using leaves and fences placed next to eachother and got spammed for simulation while walking overthem

**Comment by MWHunter** [comment]
Invalid bug report, leaves and fences work fine on my machine.  Most likely the client's version got misidentified due to 2.3.26 having a bug where an exception would silently throw so grim would miss the player's handshake version.

**Comment by B4rCodee** [comment]
Van you direct me to the commit wyre the bug was fixed please? I cant find it

**Comment by MWHunter** [comment]
injector fix that affected client versioning: https://github.com/retrooper/packetevents/commit/7927c89ba2003d5ce8bbca0391dc7c705f5d6f3c
