### ISSUE TITLE
1.19.3: Toggling sprint whilst in vehicle flags Post

### ISSUE THREAD

**Issue by SamB440** [GrimAnticheat/Grim#824]
### Describe the false positive and how to replicate it

1. Get on a tamed horse with a saddle, or a boat
2. Toggle sprint whilst riding it

The server is 1.19.2 using ViaVersion whilst the client is 1.19.3 vanilla. This does not happen with 1.19.2 clients.

Is it possible this bug fix in 1.19.3 is the cause? https://bugs.mojang.com/browse/MC-30403?filter=27487

![image](https://user-images.githubusercontent.com/11319274/206786497-5f831993-1dc3-41e4-b692-e71694054805.png)

### Grim version

2.3.26

### Server version

This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version
Previous version: git-Paper-310 (MC: 1.19.3)

### Plugins

GrimAC, ViaVersion

**Comment by MWHunter** [comment]
At least this is simple to fix

https://github.com/GrimAnticheat/Grim/commit/a39639b4f9ebcd21b7d06ba9563dc342ffa91409
