### ISSUE TITLE
Simulation flag while running through fern

### ISSUE THREAD

**Issue by SquareCodeFX** [GrimAnticheat/Grim#826]
### Describe the false positive and how to replicate it

Just run into fern
https://paste.grim.ac/a1uVE
![image](https://user-images.githubusercontent.com/37747818/206851866-f58f8761-0fe5-42ae-915c-cb940080e585.png)

### Grim version

latest

### Server version

1.19

### Plugins

Just grim

**Comment by MWHunter** [comment]
Caused by via
