### ISSUE TITLE
Simulation error while running on coco beans

### ISSUE THREAD

**Issue by SquareCodeFX** [GrimAnticheat/Grim#827]
### Describe the false positive and how to replicate it

https://paste.grim.ac/pqfFN
Just run over it
![image](https://user-images.githubusercontent.com/37747818/206851981-b1102ece-edf8-4e41-8855-792659a10b54.png)

### Grim version

latest

### Server version

1.19

### Plugins

just grim

**Comment by MWHunter** [comment]
Those aren't cocoa beans, caused by viaversion

Duplicate https://github.com/GrimAnticheat/Grim/issues/758
