### ISSUE TITLE
Players are blocked in motion when throwing EnderPearls

### ISSUE THREAD

**Issue by sm1leclock** [GrimAnticheat/Grim#828]
### Stack trace

Players get stuck in the block because of ender pearls
Please note that this happened after the updates of this plugin! Before that, there was no such thing and the players were not blocked.

### How to replicate it if known

This video is an indicator of that: https://youtu.be/ouRxGcr1zxg

### Grim version

2.3.27

### Server version

1.16.5

**Comment by MWHunter** [comment]
Duplicate #718
