### ISSUE TITLE
Check for cheats and Bedrock players

### ISSUE THREAD

**Issue by DimaSergeew** [GrimAnticheat/Grim#833]
### Feature description

I have a big server Java & & Bedrock, and we began to notice that more and more players with Bedrock use cheats, as GeyserMC evolved and cheats on this platform began to develop fairly quickly, at the moment very few Anti-Cheats that somehow can fight cheats on the phone, it would be cool to have an anticheat does not ignore the players BEdrock and checks them on a simplified scheme

**Comment by c0dingnoobi** [comment]
out of scope of grim

**Comment by MWHunter** [comment]
Grim's scope is already too large, I can't take on writing checks for an entirely new game.  I'm not doing it unless I can find a large crossplay server willing to sponsor the work (thousands of players) - which I haven't been able to.
