### ISSUE TITLE
Picking Water

### ISSUE THREAD

**Issue by tbrnEXEL** [GrimAnticheat/Grim#841]
### Describe the false positive and how to replicate it

picking water in new version kicks me out, like a hole is little bit up i swam and went to top and picked the water, it kicks me for that i have made punishment config saying "Cheating" it once kicked me, and when i tried to join it kicks me out again and again after a server restart it was fixed

### Grim version

2.3.29

### Server version

1.19.3 paper

### Plugins

GrimAc, coreprotect, essentialsX, Skript, SkRayfall (skript addon)

**Comment by c0dingnoobi** [comment]
Describe clearer for which check you are being kicked. If it is "Simulation" provide debug using `/gl <id>`. A video showing how to reproduce would also help.

**Comment by MWHunter** [comment]
invalid bug report, follow the format
