### ISSUE TITLE
Stops the player when receiving critical damage

### ISSUE THREAD

**Issue by DimaSergeew** [GrimAnticheat/Grim#842]
### Describe the false positive and how to replicate it

When a player in pvp receives crit damage, anti-cheat stops him, this problem is observed in all players

### Grim version

13.12.2022 lastet in Spigot

### Server version

![Screenshot_3](https://user-images.githubusercontent.com/75163645/207309161-89a63900-5ed4-45de-a914-c3f25b5d2fd5.png)

### Plugins

![Screenshot_2](https://user-images.githubusercontent.com/75163645/207309056-c795d06e-fc80-4748-8900-181518f9d96a.png)

**Comment by MWHunter** [comment]
Unable to reproduce - crits work for me, tested on a 1.8 and 1.19.3 client on a 1.19.3 server

Minimally reproduce this or use /grim verbose to find a false positive that would cause this, but I don't believe grim is causing this issue.
