### ISSUE TITLE
Grim cause switch item cannot cancel pulling bow

### ISSUE THREAD

**Issue by caoli5288** [GrimAnticheat/Grim#849]
### Describe the bug and how to replicate it

1. Install grimac
2. Pulling bow
3. Switch item by number key or mouse
4. Arrow launched

### Grim version

2.3.30

### Server version

This server is running CraftBukkit version git-PaperSpigot-9385e24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### Plugins

Plugins (1): GrimAC

**Comment by caoli5288** [comment]
I upgrade from 2.3.24 which the old one has no bug

**Comment by MWHunter** [comment]
Fixed by https://github.com/GrimAnticheat/Grim/commit/3e740a3afbef64c6db8e8f8fa0e2d82ca9ec6481

**Comment by caoli5288** [comment]
@MWHunter Still bugy with paperspigot-1.8.8 and ViaVersion-4.5.1
