### ISSUE TITLE
Criticals bypass

### ISSUE THREAD

**Issue by tbrnEXEL** [GrimAnticheat/Grim#853]
### Describe the bypass and how to replicate it

1) install flux b13 client
2) open clickgui
3) turn on criticals in hypixel mode by clicking the arrow beside it
![2022-12-15_20 46 13](https://user-images.githubusercontent.com/105154404/207897661-b8b6cd99-2bb0-4004-902e-0b3f00536c99.png)

### Grim version

2.3.30

### Server version

idk it's grim testing server

### Plugins

idk it's grim testing server

**Comment by c0dingnoobi** [comment]
tested, doesnt actually deal critical damage. probably doesnt do anything or needs an additional module enabled in order to make the client do anything.
