### ISSUE TITLE
Toggling Sprint Falses

### ISSUE THREAD

**Issue by tbrnEXEL** [GrimAnticheat/Grim#854]
### Describe the false positive and how to replicate it

1) Open version 1.8.9 in lunar client
2) Enable toggle sprinting
3) Run for 3 minutes

### Grim version

2.3.30

### Server version

idk it's grim testing server

### Plugins

idk it's grim testing server

**Comment by MWHunter** [comment]
invalid bug report

**Comment by c0dingnoobi** [comment]
unable to reproduce either
prob client issue since he used [custom](https://www.youtube.com/watch?v=LxO7tEpDNS8) one
