### ISSUE TITLE
False positive with spawner stacking plugin (rosestacker)

### ISSUE THREAD

**Issue by Hermelijn15** [GrimAnticheat/Grim#859]
### Describe the false positive and how to replicate it

Get the plugin rosestacker
get a bunch of spawners
spam stack place them
walk through the block

https://youtu.be/RmkvbT44z2I

### Grim version

2.3.27

### Server version

1.19.2

### Plugins

 CustomAdvancements, Essentials, EssentialsChat, EssentialsSpawn, Factions, FactionsBridge, FactionsTop, FastAsyncWorldEdit (WorldEdit), GrimAC, LuckPerms, Multiverse-Core, OldCombatMechanics, PlaceholderAPI, RoseLoot, RoseStacker, TAB, Vault, ViaBackwards, ViaVersion, VoidGen, VotingPlugin, WorldGuard

**Comment by MWHunter** [comment]
Closing due to outdated grim
