### ISSUE TITLE
Reach flagging due to XP bottles

### ISSUE THREAD

**Issue by VRXDev2** [GrimAnticheat/Grim#863]
### Describe the false positive and how to replicate it

The false positive is related to throwing XP bottles at others from outside the normal player reach. (flags as Reach)

To replicate you need 2 players and follow these steps:
1. get XP bottles
2. 1 player has to throw the XP bottles at the 2nd player from outside the 3/4 block reach in a way so it hits the character
3. it should false flag after throwing a few bottles

### Grim version

Grim 2.3.30

### Server version

Current: git-Purpur-"dc4a29b" (MC: 1.18.2)*
Previous: git-Paper-"fc9ee65" (MC: 1.18.2)
* You are running the latest version

Players are using versions from 1.18.1 to 1.19.2

### Plugins

Plugins (53): ajLeaderboards, AuctionHouse, AuthMe, Brewery, BuycraftX, ChatManager, Chunky, Citizens, CommandTimer, CraftingStore, DecentHolograms, DiscordSRV, Drugs, EconomyShopGUI, Essentials, EssentialsSpawn, ExcellentCrates, FastAsyncWorldEdit (WorldEdit), GrimAC, GSit, InteractiveChat, InventoryRollbackPlus, ItemEdit, LagAssist, LibsDisguises, LiteBans, LPC, LuckPerms, MOTD, Multiverse-Core, MythicMobs, NexEngine, OnePlayerSleep, Orebfuscator, PL-Hide, PlaceholderAPI, PlayerKits, PremiumVanish, ProtocolLib, PvPManager, SimpleStaffChat2*, SkinsRestorer, spark, TAB, UltimateAutoRestart, Vault, ViaBackwards, ViaRewind, ViaVersion, WildTP*, WorldEditSUI, WorldGuard

**Comment by c0dingnoobi** [comment]
can you show a video how to exactly reproduce 
unable to reproduce with the current given steps

**Comment by MWHunter** [comment]
Unable to reproduce
