### ISSUE TITLE
Simulation false when riding strider

### ISSUE THREAD

**Issue by IceWaffles** [GrimAnticheat/Grim#872]
### Describe the false positive and how to replicate it

1. Go to nether, get a strider and put a saddle on it
2. Ride it and go around with warped fungus on stick for a while (I just went in straight line ahead) 
4. Should give simulation false

Note: was tested while I was in creative; unsure if this flags for survival

PICTURE:
<img width="1094" alt="Screenshot 2022-12-22 at 1 47 59 PM" src="https://user-images.githubusercontent.com/86599175/209149109-50673683-8e4f-4d79-800b-63739ecb7a67.png">

### Grim version

2.3.31

### Server version

git-PufferfishPlus-14 (MC: 1.19.2)*

### Plugins

Grim, Essentials, LuckPerms, ChatManager

**Comment by c0dingnoobi** [comment]
Can't reproduce
server 1.19.2 pufferfish 
client 1.19.2
grim c071582a58c9cd1f321d7ec43389820eafada407
Tested using creative and survival

**Comment by IceWaffles** [comment]
I'm on Purpur version of pufferfish+, maybe try that? but I'm not sure what to say...

**Comment by c0dingnoobi** [comment]
Pufferfish+ is only available for customers of pufferfish. It is not a public fork as Pufferfish

**Comment by IceWaffles** [comment]
I should have worded it better; I meant to say just test with Purpur

**Comment by c0dingnoobi** [comment]
I will try to, 
meanwhile it would be helpful if u also try to reproduce this with paper

**Comment by c0dingnoobi** [comment]
> I meant to say just test with Purpur

not reproduceable even when using purpur

**Comment by MWHunter** [comment]
unable to reproduce
