### ISSUE TITLE
Slot switch with charged bow

### ISSUE THREAD

**Issue by c0dingnoobi** [GrimAnticheat/Grim#874]
### Describe the bug and how to replicate it

3e740a3afbef64c6db8e8f8fa0e2d82ca9ec6481 was an attempt to fix weird behaviour on charged bows.
Switching slots when having a charged bow still causes the arrow to be shot.
I have also noticed that switching to a rod causes an arrow to be shot without removing the arrow from inventory.

1. Charge bow 
2. Switch to another slot --> causes arrow shooting
----------------------
1. Charge bow
2. Switch to rod --> causes shooting arrow without removing arrow from inventory

### Grim version

- c071582a58c9cd1f321d7ec43389820eafada407

### Server version

- Spigot 1.8.8

### Plugins

- GrimAC

**Comment by caoli5288** [comment]
dup https://github.com/GrimAnticheat/Grim/issues/849

**Comment by MWHunter** [comment]
I don't know how to fix this.  Vanilla 1.8 doesn't check if the player switched their slot on complete use item, and this is needed so that a player can't just switch slots twice to break vanilla's logic and use NoSlow.  There's nothing in bukkit to cancel a use item.

**Comment by caoli5288** [comment]
> I don't know how to fix this. Vanilla 1.8 doesn't check if the player switched their slot on complete use item, and this is needed so that a player can't just switch slots twice to break vanilla's logic and use NoSlow. There's nothing in bukkit to cancel a use item.

Maybe delayed it?

**Comment by c0dingnoobi** [comment]
resolved in 209d90ad3abf396bf16986e8fde89f3b4cfc20c9 ig
