### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by BobtheBob123456** [GrimAnticheat/Grim#876]
### Stack trace

This is the full log: https://mclo.gs/sThSox8

And below is a screenshot of part of the error:
![Screenshot_20221224-085537_Chrome](https://user-images.githubusercontent.com/101293758/209439179-05867360-d7b2-4ffa-b665-8de65d712afc.jpg)

### How to replicate it if known

I don't know how to. (Just happened)

### Grim version

2.3.31

### Server version

Paper 1.19.3

### Plugins

ViaVersion (4.5.1)
ViaBackwards (4.5.1)
GeyserMC
Floodgate
AdvancedTeleport
EntityClearer
Worldedit
WorldGuard
Pvpmanager Lite
Multiverse Core

**Comment by Avenred** [comment]
I'm having the same error spam my console, as well as another very similar looking error: https://pastes.dev/fSJMpig3h5

**Comment by RAINRAINRAINRAINRAINRAINRAINRAINRAIN** [comment]
SAME

**Comment by MWHunter** [comment]
PacketEvents issue

**Comment by RAINRAINRAINRAINRAINRAINRAINRAINRAIN** [comment]
> PacketEvents issue

and how to fix that ?

**Comment by c0dingnoobi** [comment]
> and how to fix that ?

we wait for packetevents dev to fix it

**Comment by MWHunter** [comment]
or just download latest action (or compile from source) where I disabled that check

**Comment by MWHunter** [comment]
Removing this check, probably won't add it back even when https://github.com/retrooper/packetevents/issues/503 is fixed
