### ISSUE TITLE
末地传送门与铁栅栏 Terminal Portal and Iron Fence | Move Incorrect detection

### ISSUE THREAD

**Issue by MatrixU5er** [GrimAnticheat/Grim#879]
### Describe the false positive and how to replicate it

![QB_Y$Z({~TJ8A8SZFRLHB_G](https://user-images.githubusercontent.com/89892616/209463281-1623efb2-a3ad-45ec-b03a-6d549a530146.png)
![% 6PJ1Y}2DLX$35U5GQQ_13](https://user-images.githubusercontent.com/89892616/209463308-e2a53ea4-f1f6-4ed3-8c37-ebc2019541ee.png)
It will check when you walk from the iron fence to the terminal portal or from the terminal portal to the iron fence

### Grim version

GrimAC 2.3.31

### Server version

Paper 1.8.8

### Plugins

我认为不需要

**Comment by c0dingnoobi** [comment]
Which client version?

**Comment by DeltaLimit** [comment]
> Which client version?

looks like 1.8.9 forge

**Comment by c0dingnoobi** [comment]
if its 1.8, it has to be a client issue since iron gates neither do connect to end portal frames nor to glass. 
op should try to use vanilla and see if it happens.

not reproduceable on 1.8 with 1.8 client

**Comment by MWHunter** [comment]
Not reproducible on vanilla.
