### ISSUE TITLE
Console Error Spam

### ISSUE THREAD

**Issue by RAINRAINRAINRAINRAINRAINRAINRAINRAIN** [GrimAnticheat/Grim#880]
### Stack trace

https://mclo.gs/TCN90J7
these are errors that just appear in console nonstop making logs up to 100 MB
it really makes it difficult to see command outputs or follow the console.
question is, are these fixed in the 2.3.31 version of grim ?

### Grim version

2.3.30

### Server version

git-PufferfishPlusPurpur-16 (MC: 1.19.3)*

**Comment by BobtheBob123456** [comment]
I have the same error.

**Comment by MWHunter** [comment]
Outdated grim

**Comment by BobtheBob123456** [comment]
Except I am experiencing the same issue on 2.3.31, the latest version.

#871

**Comment by BobtheBob123456** [comment]
Sorry. Actually #876
