### ISSUE TITLE
Outdated grim

### ISSUE THREAD

**Issue by RAINRAINRAINRAINRAINRAINRAINRAINRAIN** [GrimAnticheat/Grim#883]
Outdated grim

_Originally posted by @MWHunter in https://github.com/GrimAnticheat/Grim/issues/880#issuecomment-1364694315_
      

Updating grim didn't help.
It actually broke something, I use grim + vulcan and after I updated it (grim), it (vulcan) started kicking players on inventory slot switching

**Comment by MWHunter** [comment]
I don't support proprietary software.

**Comment by RAINRAINRAINRAINRAINRAINRAINRAINRAIN** [comment]
> I don't support proprietary software.

wdym ? you said that I have an outdated version, I updated but error spam did not stop.
