### ISSUE TITLE
Simulation false positive

### ISSUE THREAD

**Issue by niemogewejsc** [GrimAnticheat/Grim#885]
### Describe the false positive and how to replicate it

https://streamable.com/wnoaym
https://paste.grim.ac/bQiy1
sprint while teleport (better to repeat in creative mode as the teleportation is instant)

### Grim version

2.3.31

### Server version

git-Paper-363
1.19.3

### Plugins

Plugins (16): AureliumSkills, Chunky, Citizens, CommandWhitelist, CustomBansPlus, Essentials, EssentialsChat, EssentialsSpawn, GrimAC, LuckPerms, MiniMOTD, PlaceholderAPI, PrivateMessages, Skript, Vulcan, WorldEdit

**Comment by c0dingnoobi** [comment]
Maybe related to #787 but can not say for sure since define thinks this is related to 1.8 (which would not be the case for you)

**Comment by MWHunter** [comment]
rejecting because not a vanilla client

**Comment by Huge-mistake** [comment]
This problem still exists
1.20.1  
plugins：Ancient Gates，grimac 2.3.46
sprint while teleport，False positives
