### ISSUE TITLE
When you have the golden apple in your secondary hand, and you change slots it resets your apple

### ISSUE THREAD

**Issue by VictimOfPing** [GrimAnticheat/Grim#889]
### Describe the bug and how to replicate it

Step 1. Metto una mela d'oro nella mano secondaria
Step 2. I start eating
Step 3. As I eat, I change slots

### Grim version

grimac-2.3.31.jar

### Server version

![Immagine 2022-12-30 201627](https://user-images.githubusercontent.com/120317607/210105007-14a1138d-f2b5-4425-aee5-57fd57aea25d.png)

### Plugins

![Immagine 2022-12-30 201709](https://user-images.githubusercontent.com/120317607/210105030-90baf17b-6091-419c-a021-3b01792b3920.png)

**Comment by BerryThDev** [comment]
Are you able to send a video? I wasn't able to recreate it.
I put the golden apple into my offhand and started eating it, and it worked fine.

**Comment by VictimOfPing** [comment]
> Are you able to send a video? I wasn't able to recreate it. I put the golden apple into my offhand and started eating it, and it worked fine.

you have to change the number of slots with the other hand

**Comment by BerryThDev** [comment]
Are you able to show it in a video?

**Comment by VictimOfPing** [comment]
> Are you able to show it in a video?

https://user-images.githubusercontent.com/120317607/210118165-0ef5b7c8-7de3-47c1-8cc0-0ea6c3752ed1.mp4

**Comment by VictimOfPing** [comment]
> 

With anticheat this happens, when I go to remove it it doesn't happen anymore

**Comment by Monkeyfog** [comment]
Yes this still isnt fixed.
