### ISSUE TITLE
Doesn't make people eat the apple

### ISSUE THREAD

**Issue by VictimOfPing** [GrimAnticheat/Grim#894]
### Describe the bug and how to replicate it

Step 1. Put a golden apple in the second hand 
Step 2. Start eating, and as you eat change slots, and it doesn't make people eat the apple

https://user-images.githubusercontent.com/120317607/210175688-475007e3-f030-44fa-a23a-a854fd64b9d1.mp4

### Grim version

GrimAC version 2.3.32

### Server version

![image](https://user-images.githubusercontent.com/120317607/210175660-868a4c06-402e-43da-b694-5109fa7faf96.png)

### Plugins

![image](https://user-images.githubusercontent.com/120317607/210175680-b8f998a6-1d31-4bee-a018-e96a6ec7a8dc.png)

**Comment by c0dingnoobi** [comment]
?? duplicate of same author #889

**Comment by VictimOfPing** [comment]
> ?? duplicate of same author #889

Yes, they don't answer me anymore

**Comment by c0dingnoobi** [comment]
#889 most likely has been seen
there is no guarantee when it will be fixed.
for now just wait instead of creating more issues about this
