### ISSUE TITLE
Can't hit any mob

### ISSUE THREAD

**Issue by shark01d** [GrimAnticheat/Grim#896]
### Describe the false positive and how to replicate it

Step 1. Start 1.9.4 server with latest versions of GrimAC and ProtocolLib
Step 2. Connect with any 1.9.3/1.9.4 Minecraft client
Step 3. Hit any mob

![Screenshot_260](https://user-images.githubusercontent.com/94995123/210188736-b914ce8c-6ae3-43fb-9260-226ac50f9579.png)

### Grim version

v2.3.32

### Server version

![Screenshot_258](https://user-images.githubusercontent.com/94995123/210188586-cfb9825d-091d-49cc-86bd-7250d1286438.png)

### Plugins

![Screenshot_259](https://user-images.githubusercontent.com/94995123/210188593-9498a7bb-62e9-45d0-b89d-6e5a286a35f7.png)

**Comment by MWHunter** [comment]
Why are you using 1.9?

**Comment by MWHunter** [comment]
I'm not supporting 1.9.4 - if you want this fixed you will have to do it yourself.

**Comment by shark01d** [comment]
i thought 1.9 is supported because of "1.8-1.19.3 support" on spigotmc
