### ISSUE TITLE
Aristois

### ISSUE THREAD

**Issue by Monkeyfog** [GrimAnticheat/Grim#897]
### Describe the bypass and how to replicate it

Aristois client Bhop module up to 5,0-6,0

### Grim version

grimac-2.3.32.jar

### Server version

1.18.2 paper

### Plugins

AdvancedPlHide*, ArmorStandTools, BeyondPvP, BisectHosting, BuycraftX, ChatFilter, CoinSystem*, CoreProtect, CustomBansPlus, CustomWhitelistMessage*, DecentHolograms, DiscordSRV-Staff-Chat, Exyron-FastCrystals, F3Name, FastAsyncVoxelSniper, FastAsyncWorldEdit (WorldEdit), GrimAC, ImageMaps, LPC, LuckPerms, MessageAnnouncer, Msg*, Multiverse-Core, NexEngine, OpenInv, PlaceholderAPI, Plan, PlugManX (PlugMan), PowerBoard, ProtocolLib, ShieldBreakSound*, SuperVanish, TrollBoss, Vault, ViaBackwards, ViaVersion, VoidGen, Votifier, VotingPlugin, WorldGuard

**Comment by c0dingnoobi** [comment]
highly doubt that ur able to bhop if everything is properly setup

**Comment by BerryThDev** [comment]
Packet events isn't listed in your plugins which is required by Grim to run and it will also not run if you have the wrong version of Protocol Lib installed. You should check that startup log on your server for more detail, but I would think it has something to do with Grim never starting in the first place.

**Comment by MWHunter** [comment]
do it on the test server

**Comment by Monkeyfog** [comment]
It works here the config isnt really changed idk.

**Comment by c0dingnoobi** [comment]
you probably have bypass permissions on your server since you r operator 
see [wiki page ](https://github.com/GrimAnticheat/Grim/wiki/Permissions) for permission managment
