### ISSUE TITLE
grim plugin require update to protocolLib 5.x development builds, but it may cannot be used under this condition

### ISSUE THREAD

**Issue by xyHank** [GrimAnticheat/Grim#898]
### Describe the bug and how to replicate it

protocolLib development builds is not supported minecraft 1.8-1.18, it means grim can only run on minecraft 1.19.
how to solve this problem?

### Grim version

latest

### Server version

paper 1.16.5

### Plugins

ProtocoLib 5.0(latest)
Grimac 2.3.32(latest)
Viaversion 4.5.1(latest)
Viabackwards 4.5.1(latest)

**Comment by caoli5288** [comment]
Just delete ProtocolLib

**Comment by c0dingnoobi** [comment]
I am running protocllib 5.0 on 1.8 without any problems. 
if u dont have any other plugin which needs protocllib you can also delete it as caoli suggested
