### ISSUE TITLE
IndexOutOfBoundsException v2.3.32

### ISSUE THREAD

**Issue by ItsSynchro** [GrimAnticheat/Grim#902]
### Stack trace

https://paste.gg/p/anonymous/fb110dd120ec4a9192b86a5b43ff0d71

### Grim version

grimac-2.3.32

### Server version

PaperMC 1.19.2

### Plugins

GrimAC

**Comment by MWHunter** [comment]
https://github.com/GrimAnticheat/Grim/commit/5c9a58957f9373c894cbf61d7a9880adab7d4b1b
