### ISSUE TITLE
RotationPlace/FarPlace with GSit

### ISSUE THREAD

**Issue by MATRIX-feather** [GrimAnticheat/Grim#905]
### Describe the bug and how to replicate it

1. Install [GSit](https://github.com/Gecolay/GSit)
2. Sit on someone
3. Place or click something
4. Triggers RotationPlace/FarPlace

https://user-images.githubusercontent.com/55654482/211118210-e28721ea-5c3e-4695-a4fa-211b63d52215.mp4

### Grim version

33ed774

### Server version

Paper 1.19.3

### Plugins

GrimAC, GSit, ProtocolLib

**Comment by MWHunter** [comment]
https://github.com/GrimAnticheat/Grim/commit/ba1b247114d0e64d5c8cc11d602766396eb7c6c3
