### ISSUE TITLE
Spigot 1.8.8 /profile command

### ISSUE THREAD

**Issue by FairGames** [GrimAnticheat/Grim#906]
### Stack trace

https://gyazo.com/842707905cc9f6a610f998f2c7350288

### How to replicate it if known

https://gyazo.com/842707905cc9f6a610f998f2c7350288

### Grim version

https://gyazo.com/842707905cc9f6a610f998f2c7350288

### Server version

https://gyazo.com/842707905cc9f6a610f998f2c7350288

### Plugins

https://gyazo.com/842707905cc9f6a610f998f2c7350288

**Comment by c0dingnoobi** [comment]
not a valid report at all imo

but stll, just use higher java version instead of java 8

**Comment by FairGames** [comment]
Oh, so it won't work on Java 8 ? :( (I'm afraid to change the version, most plugins are compiled in 8 )
All other things are working

**Comment by c0dingnoobi** [comment]
Seems like something is compiled with a newer java version (idk if intended) but yes right now it wont work on java 8
Java has backwards compatibility, plugins wont break after updating java version

**Comment by FairGames** [comment]
so there is no advantage to run on old java 8? Every pvp server is sticking to the java 8, but idk why :D 
So you recommend me to use latest version of java?

**Comment by c0dingnoobi** [comment]
there is not an advantage as long as you are not on linux 
if you are on linux and use spigot 1.8.8 without java 8 it wont use native-transport which is benefitial for networking performance. 
there are some spigot forks (such as pandaspigot/windspigot/titanium) which implemented patches to make native-transport also work on higher java versions such as like 17

**Comment by FairGames** [comment]
Oh, thank you so much for the explanation
+rep

**Comment by FairGames** [comment]
My server isn't loading up at java 17, but java 11 is ok, but i have same problem there :(

**Comment by vytskalt** [comment]
Send console logs

**Comment by FairGames** [comment]
sure, i am going for it
i am using windows 10 now btw

**Comment by FairGames** [comment]
[latest.log](https://github.com/GrimAnticheat/Grim/files/10367340/latest.log)
why are there so much spaces there now?, with java 11

**Comment by c0dingnoobi** [comment]
> My server isn't loading up at java 17 

we would need the startup log when loading it with java 17

**Comment by FairGames** [comment]
I mean from main server, It is cuz other plugins are not compatible with java 17 i think (errors).
With java 11 just old Votifier plugin didn't load up. So it's ok.
At 17 it's just cuz my core plugin is not compatible so server goes off

**Comment by c0dingnoobi** [comment]
Yea to help you we would need the console startup logs to see whats causing them -.-

**Comment by FairGames** [comment]
I know the reason there :/ My core plugin crash server

**Comment by FairGames** [comment]
Anyway, why are there so much spaces in Error logs with java 11 ? 
With 8 it was normal i think

**Comment by c0dingnoobi** [comment]
Happens when using unsupported java version on spigot.

**Comment by MWHunter** [comment]
Should be fixed on latest commit, I'll just avoid loading this class for pre-1.18 servers
