### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16

### ISSUE THREAD

**Issue by DimaSergeew** [GrimAnticheat/Grim#911]
### Stack trace

https://paste.gg/p/anonymous/757b665ba17f4b83a06713d2fb52003b

### How to replicate it if known

-

### Grim version

Grim Anticheat 2.3.32

### Server version

PurPur 1.19.3

### Plugins

![Screenshot_1](https://user-images.githubusercontent.com/75163645/211280567-2db362b4-d539-4021-82a9-4dbe98ee727c.png)

**Comment by ghost** [comment]
Is there any fix for this? I have the same issue

**Comment by SamB440** [comment]
Is this still a problem on the latest Grim?
