### ISSUE TITLE
Sprinting in a flowing water false positive

### ISSUE THREAD

**Issue by FairGames** [GrimAnticheat/Grim#912]
### Describe the false positive and how to replicate it

Hitting while sprinting in a water false flag

### Grim version

2.3.32

### Server version

1.8.8
LiteLightSPigot

### Plugins

All is on video https://gyazo.com/774869788e5148f6ad9c6eae12a0d662

**Comment by c0dingnoobi** [comment]
dup #785

**Comment by c0dingnoobi** [comment]
you should not kick for 20 violations for simulation
you should not kick at all for simulation

**Comment by FairGames** [comment]
> you should not kick for 20 violations for simulation you should not kick at all for simulation

Walking was fine for me, only while sprinting.

Do you have some balanced config?
Ye, I know. I will turn off punishment for simulation. So i can turn on the punishments for the other checks?

**Comment by c0dingnoobi** [comment]
gimme ur dc so we can write instead of filling issues with something like that
issue is safe to close imo

**Comment by FairGames** [comment]
Ok, thanks.

**Comment by FairGames** [comment]
Added
