### ISSUE TITLE
Crosspearls aren't working with Grim

### ISSUE THREAD

**Issue by FairGames** [GrimAnticheat/Grim#914]
### Feature description

https://gyazo.com/67136959a86b38fc0e8320a71a3d6088

**Comment by c0dingnoobi** [comment]
can confirm, happens mostly on 1.8.8  spigots which do support "crosspearls/taliban pearls" (such as LightLiteSpigot and TitaniumMC) these pearling mechanic do work without grim. 
with grim it prevents them. whilst failing phase simulation. player's grim debug is greyed out. probably somehow related to #718.

**Comment by FairGames** [comment]
> can confirm, happens mostly on 1.8.8 spigots which do support "crosspearls/taliban perls" (such as LightLiteSpigot and TitaniumMC) these pearling mechanic do work without grim. with grim it prevents them. whilst failing phase simulation. player's grim debug is greyed out. probably somehow related to #718.

you are very precise 👍

**Comment by MWHunter** [comment]
Duplicate https://github.com/GrimAnticheat/Grim/issues/718
