### ISSUE TITLE
Redstone wire NullPointerException

### ISSUE THREAD

**Issue by scarfacered** [GrimAnticheat/Grim#915]
### Stack trace

https://pastebin.com/raw/R0Bv0NvX

### Grim version

grimac-2.3.32.jar

### Server version

Latest Paper 1.19.3

### Plugins

ViaVersion, ViaBackwards

**Comment by c0dingnoobi** [comment]
~~totally invalid~~
~~either~~ provide steps to reproduce or a video.

**Comment by scarfacered** [comment]
> totally invalid,
> either provide steps to reproduce or a video.

Thank you, but you're not the one who determines validity. It clearly states "How to replicate it *if known*". I trust Define knows his codebase and can read a stacktrace. A brief code analysis shows it occurs when retrieving the raw power near a redstone wire. Define would know more. All the data I have on this error is provided.

**Comment by c0dingnoobi** [comment]
> but you're not the one who determines validity

no doubt, the way how i stated it might have been wrong mb. purpose was just to make it easier for further investigation on this specific error since only stacktrace was provided

**Comment by MachineBreaker** [comment]
We don't have the stacktrace anymore due to the paste being expired, paste a new one or close this please

**Comment by MWHunter** [comment]
I remember fixing it
