### ISSUE TITLE
Blink+Scaffold=FakeFly Bypass

### ISSUE THREAD

**Issue by caoli5288** [GrimAnticheat/Grim#921]
### Describe the bypass and how to replicate it

1. Open Blink
2. Building bridge with scaffold
3. Close Blink
4. Then cheaters can still see the block placed when blink and walk on it, looks in flight

### Grim version

2.3.32

### Server version

This server is running CraftBukkit version git-PaperSpigot-b5fdf39 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### Plugins

GrimAC, ViaVersion

**Comment by MWHunter** [comment]
this isn't cheating
