### ISSUE TITLE
scaffold! (ghost kinda)

### ISSUE THREAD

**Issue by honey-sk** [GrimAnticheat/Grim#925]
### Describe the bypass and how to replicate it

step 1: launch vape
step 2: use scaffold godbridge mode
step 3: use it :)

### Grim version

What ever the test server was on 

### Server version

![image](https://user-images.githubusercontent.com/68305098/212367283-57bafc69-3263-4b09-8a08-993b9b6f8a7e.png)

### Plugins

what ever your test server has on.

**Comment by honey-sk** [comment]
works with legit to but tbf no anticheat detects that

**Comment by c0dingnoobi** [comment]
#877

**Comment by MWHunter** [comment]
I don't care.  Grim only has basic scaffolding checks.  This is a feature request not a bug.
