### ISSUE TITLE
Incorrect cobblestone wall collision for new client versions on old server

### ISSUE THREAD

**Issue by ruViolence** [GrimAnticheat/Grim#928]
### Describe the false positive and how to replicate it

Wall collision for clients with version 1.13 or above is calculated incorrectly if the server version is 1.12 or below.

Video: [https://www.youtube.com/watch?v=RVA4bJj_MtU](https://www.youtube.com/watch?v=RVA4bJj_MtU)

### Grim version

9ba732b8fdbcacbd9787a4923bb86f8120ff1a8f

### Server version

Paper 1.12.2

### Plugins

GrimAC

**Comment by MWHunter** [comment]
You sure this isn't a via bug?

**Comment by ruViolence** [comment]
> You sure this isn't a via bug?

Without Grim, I can go into connected walls like this.
![image](https://user-images.githubusercontent.com/78062896/212529439-bd39ffef-74e6-42b9-82b8-2507ecf5ce28.png)

Except for the corner ones like this, the collision is really different there on the new versions.
![image](https://user-images.githubusercontent.com/78062896/212529533-5ba7c82d-a0ee-4dfa-b2a4-747473ab0164.png)

I temporarily fixed it for myself by disabling that "if" but don't know how many other problems it caused 🤪:
https://github.com/GrimAnticheat/Grim/blob/9ba732b8fdbcacbd9787a4923bb86f8120ff1a8f/src/main/java/ac/grim/grimac/utils/collisions/blocks/connecting/DynamicWall.java#L51

**Comment by MachineBreaker** [comment]
Could you try add an statement to that check?
`PacketEvents.getAPI().getServerManager().getVersion().isNewerThan(ServerVersion.V_1_12_2) && version.isNewerThanOrEquals(ClientVersion.V_1_13)`

**Comment by ruViolence** [comment]
> Could you try add an statement to that check? `PacketEvents.getAPI().getServerManager().getVersion().isNewerThan(ServerVersion.V_1_12_2) && version.isNewerThanOrEquals(ClientVersion.V_1_13)`

This is the same as turning off this check completely. In both cases it results that walls collision for players from newer versions is handled incorrectly. In addition, the server core gets in the way here, which also has its own collision check. If we fix anticheat, the server will handle collision in its own way and will setback the player.

**Comment by Axionize** [comment]
Should be fixed by https://github.com/GrimAnticheat/Grim/pull/1824
