### ISSUE TITLE
use grim i can get the Ghost block

### ISSUE THREAD

**Issue by RegotlyLong** [GrimAnticheat/Grim#934]
### Describe the false positive and how to replicate it

I don't know if this is a result of sending packets, but when I used WorldGuard, the player stood on the edge of the block, dug out the block and moved forward, the player would get stuck in the block, and after a while, the player would teleportate to the block below, get stuck, and get the ghost block

### Grim version

2.3.32

### Server version

1.8.8

### Plugins

vulcan+grim

**Comment by MWHunter** [comment]
ghost blocks aren't cheating

**Comment by RegotlyLong** [comment]
But grim seems to create a ghost block, and then the player will get stuck on it, I don't know what the reason is, the logs will not report, if we delete grim there is no problem, it may be related to the player's movement or packet sending
