### ISSUE TITLE
bypass

### ISSUE THREAD

**Issue by RegotlyLong** [GrimAnticheat/Grim#938]
### Describe the bypass and how to replicate it

1.use FDPClient mod
2.open Velocity event ,use mods: HYTNEW.

3.you can get bypass

4.FDPClinet Velocity bypass: https://github.com/SkidderMC/FDPClient/blob/main/src/main/java/net/ccbluex/liquidbounce/features/module/modules/combat/velocitys/other/HYTNewVelocity.kt

5.FDPClient mods download:https://github.com/SkidderMC/FDPClient/releases

### Grim version

2.3.32

### Server version

Checking version, please wait... 
This server is running CraftBukkit version git-Spigot-21fe707-741a1bd (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) 

### Plugins

grim

**Comment by c0dingnoobi** [comment]
![image](https://user-images.githubusercontent.com/97745777/213781461-4c10dc0e-fb47-4b4a-898c-88802b732b8d.png)
flags for me with default configuration

if tested player has op make sure he has `grim.exempt` permission set to false

**Comment by RegotlyLong** [comment]
Regotly
***@***.***



&nbsp;


or



As long as you don't change the bottom, the top number can be adjusted




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GrimAnticheat/Grim"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月21日(星期六) 凌晨2:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GrimAnticheat/Grim] bypass (Issue #938)





 

 flags for me with default configuration

**Comment by RegotlyLong** [comment]
Switch this cheat and you can see the obvious difference









Regotly
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GrimAnticheat/Grim"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月21日(星期六) 凌晨2:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GrimAnticheat/Grim] bypass (Issue #938)





 

 flags for me with default configuration

**Comment by RegotlyLong** [comment]
> 

![image](https://user-images.githubusercontent.com/32794892/213787305-afb31182-db86-46ce-a61e-bec195bf7a83.png)

**Comment by RegotlyLong** [comment]
Wait found another solution, using Simulation can solve this problem：xd
but So much the better if you can resolve the check item at Knockback

**Comment by c0dingnoobi** [comment]
well its not a bypass then since it is flagging 
and flagging simulation with high offsets (which it should with these settings) will correct ur movement
so its not rlly necessary to flag velocity here

**Comment by RegotlyLong** [comment]
I'm sorry to bother you.





Regotly
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GrimAnticheat/Grim"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月21日(星期六) 凌晨4:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GrimAnticheat/Grim] bypass (Issue #938)





 
well its not a bypass then since it is flagging
 and flagging simulation with these offsets (which it should with these settings) will correct ur movement
 so its not rlly necessary to flag velocity here

**Comment by RegotlyLong** [comment]
bye
