### ISSUE TITLE
Error when mounting an animal

### ISSUE THREAD

**Issue by Grafnus** [GrimAnticheat/Grim#939]
### Describe the bug and how to replicate it

Step 1: Have grimac installed
Step 2: Mount a horse/lama/etc.
Step 3: Player gets kicked from the server and cannot connect again.

Error message: `20:44:43 [WARNING] [DstroyTheCreeble] <-> DownstreamBridge <-> [Survival] - could not decode packet! java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledSlicedByteBuf(ridx: 1, widx: 1, cap: 1/1, unwrapped: PooledUnsafeDirectByteBuf(ridx: 324, widx: 441, cap: 16384))`

### Grim version

Tested it with 2.3.32 and 2.3.33

### Server version

git-Purpur-1894 (MC: 1.19.3)

### Plugins

- ArmorStandAdjustor
- BungeeGuard
- BungeeTabListPlus
- CoreProtect
- FancyWaystones
- HeadDrop
- helper
- HuskHomes
- LuckPerms
- Pipes
- PlaceholderAPI
- PortalShard
- ProtocolLib
- sleep-most
- spark
- UltimateAutoRestart
- Vault
- VentureChat
- WorldEdit
- WorldGuard
- xaero-map-spigot

**Comment by MWHunter** [comment]
This isn't enough information to reproduce the issue.  I would need a minimum reproduction to fix this issue.

**Comment by MWHunter** [comment]
unable to reproduce

**Comment by Grafnus** [comment]
@MWHunter 
Sry for the late answer, had other issues to fix.

I am not quite sure what you mean by `This isn't enough information to reproduce the issue.`, but I try my best to give a clear picture of the server and the environment.

GrimAC was installed on a single server in a BungeeCord-Server-Cluster (BCSC). It worked perfectly and 1000000x better than every other AC plugin I could find. The server in the BCSC is the main server. The only other server is a Creative server to prebuild stuff. The survival server was running 1.19 until a few days ago. The plugins running on that server are listed above. We had some configuration changed but only related to "bug fixes" paper build into the server or performance enhancements. If there is interest in the configuration, I can provide it on request.

Then follows the upgrade to 1.19.3. We updated all plugins to the required version and resolved some minor issues. All worked until a player mounted a lama he had in his home. He got the above stated error message while getting kicked every time he tried to join the server. Removing the player data from the worlds folder granted him access to the server again, but removing all he had from the world.

There was no error in the mc server logs and only the above stated error displayed in the BungeeCord server logs.

I spotted Grim AC as the source of this issue by disabling all plugins and reactivating them one by one.

Current state is that as soon as I drop the newest GrimAC jar into the servers plugin folder, the issue occurs again.

I hope this gives a more defined image of the server and help reproduce it.

**Comment by Samridhya75** [comment]
I had this exact issue. It only happens when the server is connected through bungeecord. No errors on the survival server only shows on the bungeecord server console.
Any player mounted on a horse/llama gets kicked out and unable to enter at all.

**Comment by MWHunter** [comment]
fixed in some version
