### ISSUE TITLE
1.12.2 Viaversion Noslow Bypass

### ISSUE THREAD

**Issue by MatrixU5er** [GrimAnticheat/Grim#942]
### Describe the bypass and how to replicate it

Use FDPClient with noslow mode matrix, get viaforge to 1.12.2 . join a 1.8.8/1.8.9 viaversion server 
or 
Use 1.12.2 Hacked client with noslow mode matrix join 1.8.8/1.8.9 viaversion server 

### Grim version

Grim 2.3.33

### Server version

1.8.8 paper

### Plugins

Viaversion Grimac and some lib

**Comment by MWHunter** [comment]
unable to reproduce
