### ISSUE TITLE
AntiKB falses

### ISSUE THREAD

**Issue by Endrjuu** [GrimAnticheat/Grim#968]
### Describe the false positive and how to replicate it

https://www.youtube.com/watch?v=5IR7nIimwr4

https://medal.tv/games/minecraft/clips/WbOIWzzNtr349/CN3idnr75vVI?invite=cr-MSwxTUYsMTU3MDUyNTQzLA

### Grim version

2.3.35

### Server version

1.8.8

### Plugins

Mine and grim

**Comment by c0dingnoobi** [comment]
#967 duplicate
