### ISSUE TITLE
False positives when jump-sprinting

### ISSUE THREAD

**Issue by FatildaIV** [GrimAnticheat/Grim#975]
### Describe the false positive and how to replicate it

Step 1: Jump up
Step 2: Enter sprinting mode while midair (with Ctrl)
Step 3: Go forward while midair

https://paste.grim.ac/WsMR9

### Grim version

2.3.36

### Server version

This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version
Previous version: git-Paper-18 (MC: 1.19)

### Plugins

Plugins (16): ACUtils, AnimeBoard, AntiDisconnectSpam, ClearLag, Essentials, EssentialsChat, EssentialsSpawn, GrimAC, LightPerms, MyCommand, PlaceholderAPI, ViaBackwards, ViaRewind, ViaVersion, WorldEdit, WorldGuard

**Comment by SamB440** [comment]
> Client Version: 1.19.1

This doesn't seem right, the offset is 0.005 as well, this was the behaviour I saw with 1.19.4 clients prior to the sprinting fix.

Can't reproduce on the Grim test server either on pre-1.19.4 or 1.19.4 clients.

**Comment by FatildaIV** [comment]
> > Client Version: 1.19.1
> 
> This doesn't seem right, the offset is 0.005 as well, this was the behaviour I saw with 1.19.4 clients prior to the sprinting fix.
> 
> Can't reproduce on the Grim test server either on pre-1.19.4 or 1.19.4 clients.

Indeed, after closer inspection this was caused by ViaFabric 1.19.1/2 setting on 1.19.4 client, closing.
