### ISSUE TITLE
Support for PlacehodersAPI

### ISSUE THREAD

**Issue by MrTokyo12345** [GrimAnticheat/Grim#977]
### Feature description

Hi, add placehodersapi support? I need it because I created a telegram reporting system based on the various placehoders, or if it is possible to add in the punishments.yml config, the placeholders %server_tps_one%, %player_ping%

**Comment by MachineBreaker** [comment]
I could try adding support but you will need to compile from my fork, however you could listen to the CommandExecuteEvent and parse your placeholders
