### ISSUE TITLE
Players will be reported wrong if they walk through the snow blanket normally。

### ISSUE THREAD

**Issue by polang233** [GrimAnticheat/Grim#979]
### Describe the false positive and how to replicate it

Players will be pulled back and report an error if they walk through the snow blanket normally。
I tried a square wool carpet of the same size as the snow carpet, and the wool carpet will not be a problem. And only one layer of snow blanket can report errors. A little thicker, such as more layers of snow, will not report errors。

### Grim version

2.3.35、2.3.36，Both appear

### Server version

1.12.2 paper   jdk8

### Plugins

We have tried to leave only the grimac plug-in, but it still appears

**Comment by c0dingnoobi** [comment]
which version did client have?

**Comment by polang233** [comment]
> 

Sorry, I forgot to consider whether ViaVersion is useful. The client version is 1.19.3 (there will be problems after trying 1.18.2). ViaVersion used

**Comment by c0dingnoobi** [comment]
as define labeled
thats a viaversion issue cuz of their world mapping of blocks 
not much grim can do about it for now
consider upgrading to latest spigot or limit clients to 1.12

**Comment by polang233** [comment]
thank you

**Comment by MWHunter** [comment]
There is a way to change this in the viaversion config.  I can't add this mapping because it depends on the viaversion config.

**Comment by polang233** [comment]
> There is a way to change this in the viaversion config. I can't add this mapping because it depends on the viaversion config.

Could you please tell me which option is in the configuration file?
I can adjust the settings myself, and if someone encounters this problem in the future, I can also inform them. Your plug-in is very well received in China

**Comment by MWHunter** [comment]
# For 1.13 clients the smallest (1 layer) snow doesn't have collision, this will send these as 2 snowlayers for 1.13+ clients to prevent them bugging through them
fix-low-snow-collision: false

**Comment by polang233** [comment]
> # For 1.13 clients the smallest (1 layer) snow doesn't have collision, this will send these as 2 snowlayers for 1.13+ clients to prevent them bugging through them
> fix-low-snow-collision: false

thank you! Effectively solved this problem

**Comment by MachineBreaker** [comment]
Close this if resolved

**Comment by MWHunter** [comment]
it might be possible to grab this config in the future so if can't false with either setting

**Comment by Valyrox** [comment]
```Java
SNOW((player, version, data, x, y, z) -> {
        if (data.getLayers() == 1 && version.isNewerThanOrEquals(ClientVersion.V_1_13)) {
            // Via doesn't touch this
            if (PacketEvents.getAPI().getServerManager().getVersion().isNewerThanOrEquals(ServerVersion.V_1_13)
                    || !Via.getConfig().isSnowCollisionFix()) {
                return NoCollisionBox.INSTANCE;
            }

            // Handle viaversion mapping
            data = data.clone();
            data.setLayers(2);
        }

        return new SimpleCollisionBox(0, 0, 0, 1, (data.getLayers() - 1) * 0.125, 1);
    }, StateTypes.SNOW),
```
CollisionData.java

**Comment by MachineBreaker** [comment]
What if we don't have ViaVersion? it would throw an exception

> ```java
> SNOW((player, version, data, x, y, z) -> {
>         if (data.getLayers() == 1 && version.isNewerThanOrEquals(ClientVersion.V_1_13)) {
>             // Via doesn't touch this
>             if (PacketEvents.getAPI().getServerManager().getVersion().isNewerThanOrEquals(ServerVersion.V_1_13)
>                     || !Via.getConfig().isSnowCollisionFix()) {
>                 return NoCollisionBox.INSTANCE;
>             }
> 
>             // Handle viaversion mapping
>             data = data.clone();
>             data.setLayers(2);
>         }
> 
>         return new SimpleCollisionBox(0, 0, 0, 1, (data.getLayers() - 1) * 0.125, 1);
>     }, StateTypes.SNOW),
> ```
> 
> CollisionData.java

**Comment by MachineBreaker** [comment]
> > # For 1.13 clients the smallest (1 layer) snow doesn't have collision, this will send these as 2 snowlayers for 1.13+ clients to prevent them bugging through them
> > fix-low-snow-collision: false
> 
> thank you! Effectively solved this problem

If possible, can you test my PR to see if this still happens with both config options off/on?
https://github.com/GrimAnticheat/Grim/pull/994

**Comment by polang233** [comment]
> 



> > > # For 1.13 clients the smallest (1 layer) snow doesn't have collision, this will send these as 2 snowlayers for 1.13+ clients to prevent them bugging through them
> > > fix-low-snow-collision: false
> > 
> > 
> > thank you! Effectively solved this problem
> 
> If possible, can you test my PR to see if this still happens with both config options off/on? #994

Do you want to use a 1.8.8 client to access clients above 1.13? I can help you test

**Comment by MachineBreaker** [comment]
> > 
> 
> > > > # For 1.13 clients the smallest (1 layer) snow doesn't have collision, this will send these as 2 snowlayers for 1.13+ clients to prevent them bugging through them
> > > > fix-low-snow-collision: false
> > > 
> > > 
> > > thank you! Effectively solved this problem
> > 
> > 
> > If possible, can you test my PR to see if this still happens with both config options off/on? #994
> 
> Do you want to use a 1.8.8 client to access clients above 1.13? I can help you test

Already fixed the snow collision entirely, thanks tho
