### ISSUE TITLE
Blink is working

### ISSUE THREAD

**Issue by SkyplayYT** [GrimAnticheat/Grim#980]
### Describe the bypass and how to replicate it

1. Donwload Liquidbounde
2. Install Forge 1.8
3. Put Liquidbounce-x.y.z.jar in Mods Folder
4. Join a Server
5. Bind blink
6. Press you're bind and walk a while
7. Press you're bind again and you got you're Teleport

### Grim version

grimac-2.3.35

### Server version

Spigot-21fe707-741a1bd 1.8.8

### Plugins

GrimAC, ProtocolLibs

**Comment by SamB440** [comment]
https://www.youtube.com/watch?v=N54mYvftFoM

**Comment by MWHunter** [comment]
Blink isn't a cheat
