### ISSUE TITLE
Pressing W and S simultaneously in boat on ice falses Simulation

### ISSUE THREAD

**Issue by VidTu** [GrimAnticheat/Grim#981]
### Describe the false positive and how to replicate it

1. Join via 1.19.3 client.
2. Place a boat onto ice.
3. Ride it.
4. Press W and S at the same time.
5. Simulation falses and you get kicked out of the boat.

https://paste.grim.ac/tWJoj

### Grim version

050eb72

### Server version

This server is running Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)
You are running the latest version

### Plugins

ViaVersion, ViaBackwards, GrimAC

(Via is not active here, client and server versions match)

#### Edit
Works **in water**, not on ice only.

**Comment by 0-x-2-2** [comment]
Still happens in 1.20.x, #1166, maybe https://github.com/UserNugget/Grim/commit/2bc7ade66342ee46d9d37647cd52be43c75ce95e could be merged into upstream if it fixes the issue correctly?
