### ISSUE TITLE
Wall climb bypass

### ISSUE THREAD

**Issue by caoli5288** [GrimAnticheat/Grim#983]
### Describe the bypass and how to replicate it

1. build wall use ***Slime*** blocks
2. Climb with motion less than 0.4

### Grim version

2.3.36

### Server version

tested both 1.8.8 and higher

### Plugins

GrimAC

**Comment by MachineBreaker** [comment]
Slime blocks aren't totally handled on the actual Prediction Engine afaik, would require an Motion check instead

**Comment by MWHunter** [comment]
I don't care.  No one can really abuse this on a real server
