### ISSUE TITLE
Sneaking and walking sometimes leads to take no knockback

### ISSUE THREAD

**Issue by ytnoos** [GrimAnticheat/Grim#984]
### Describe the false positive and how to replicate it

Replicate the videos

https://www.youtube.com/watch?v=ENipGzKYr2o
https://www.youtube.com/watch?v=7V_K5-ifRWo

### Grim version

512d4322f02c2a0d737ba33583f12e55178209cc

### Server version

1.8.8 PaperSpigot

### Plugins

Nothing relevant to apply the false

**Comment by c0dingnoobi** [comment]
should be dup of #612
