### ISSUE TITLE
Error console

### ISSUE THREAD

**Issue by MrTokyo12345** [GrimAnticheat/Grim#987]
### Describe the bug and how to replicate it

Sometimes the plugin for no reason spam these errors:
https://pastebin.com/qZtKaie8

### Grim version

2.3.36

### Server version

[17:23:50 INFO]: This server is running Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Plugins

ajLeaderboards, BuycraftX, ChatControlRed, DecentHolograms, Essentials, EssentialsSpawn, ExtraSpecialItems, FastAsyncWorldEdit, floodgate, Gen-Splitter, GrimAC, HeroxVote, HeroxWar_Report, LuckPerms, MBedwars, MBedwars-Cosmetics, MBedwars_SelectShopDesign, MBedWarsKits, MBedwarsSpectateAddon, MBedwarsSpectatorSettingsAddon, MBedwarsTweaks, OldCombatMechanics, PlaceholderAPI, PlugMan, ProtocolLib, Skript, SlimeWorldManager, TAB, Vault, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion, VoidTeleport, WorldEdit, WorldGuard

**Comment by MachineBreaker** [comment]
https://github.com/MachineBreaker/Grim/commit/c5dafc7bb9848d8ab73b4393d344006513ddee80
Compile this branch and test if it happens
