### ISSUE TITLE
My server periodically writes a WARN in the console (not even during a reboot)

### ISSUE THREAD

**Issue by sm1leclock** [GrimAnticheat/Grim#997]
### Stack trace
https://pastebin.com/aHbi58vX

### How to replicate it if known

I start the server and the players are playing there - for some reason, such a terrible spam is being written WARN

### Grim version

Grim Anticheat 2.3.38

### Server version

This server is running Paper version git-Paper-8359863 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by MachineBreaker** [comment]
Upload your stracktrace in pastebin or other website please

**Comment by sm1leclock** [comment]
> Upload your stracktrace in pastebin or other website please

I'm sorry I didn't do it right away. I changed it.

**Comment by MachineBreaker** [comment]
I can reproduce this, use creative mode, drop any item of the creative tab and you get the stack trace, i'm trying to fix this

**Comment by sm1leclock** [comment]
I found an error - it appears when I try to throw something out of the creative mod (video provided)

**Comment by MachineBreaker** [comment]
Resolved by #996

**Comment by sm1leclock** [comment]
> Решено [# 996](https://github.com/GrimAnticheat/Grim/pull/996)

what should I do with this code? or how do I fix this error myself now?

**Comment by MachineBreaker** [comment]
> > Решено [# 996](https://github.com/GrimAnticheat/Grim/pull/996)
> 
> what should I do with this code? or how do I fix this error myself now?

Clone that branch, compile it and use the final jar in your server, or just wait the update in discord

**Comment by sm1leclock** [comment]
Thank, i'm wait...

**Comment by sm1leclock** [comment]
and in which class to insert? and in which line?

> > > Решено [# 996](https://github.com/GrimAnticheat/Grim/pull/996)
> > 
> > 
> > what should I do with this code? or how do I fix this error myself now?
> 
> Clone that branch, compile it and use the final jar in your server, or just wait the update in discord

**Comment by MachineBreaker** [comment]
> and in which class to insert? and in which line?
> 
> > > > Решено [# 996](https://github.com/GrimAnticheat/Grim/pull/996)
> > > 
> > > 
> > > what should I do with this code? or how do I fix this error myself now?
> > 
> > 
> > Clone that branch, compile it and use the final jar in your server, or just wait the update in discord

Well, you have the commit, it shows everything
